### ISSUE TITLE
Can't select czech language for vanced instalation

### ISSUE THREAD

**Issue by radimous** [YTVanced/VancedManager#100]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: Samsung
- Operating System: One UI 2
- Android Version: 10
- Vanced Manager Version: 1.1.0

**Please describe the problem you are having in as much detail as possible:** Can't select czech language for vanced instalation

**Steps to reproduce:**

**Further details:**
![3JEoe7n](https://user-images.githubusercontent.com/56518192/89111720-8498b680-d459-11ea-99e6-58921e9f0839.jpg)

**Comment by X1nto** [comment]
Czech wasn't translated on https://translate.vanced.app
