### ISSUE TITLE
Request a feedback of the started download on the button

### ISSUE THREAD

**Issue by FeaXR** [YTVanced/VancedManager#101]
In the vanced manager there is no feedback if the download is started after the press of the button, except for the notification. It would be great if you could grey out the button while downloading and change the text to "Downloading" or something like that. A few times I pressed the button again, and restarted the download because of this, because the intuitive way to show that the download has started, is to show it on the button.

**Comment by X1nto** [comment]
Added in 71eb1c19d8f9f85d654ce128590be72223440f2c
