### ISSUE TITLE
Install gets stuck

### ISSUE THREAD

**Issue by Walker43241** [YTVanced/VancedManager#102]
**Phone Specifications:**
- Brand: Samsung Galaxy A11
- Operating System: Android 
- Android Version: 10
- Vanced Manager Version: 1.1.0 (Big Sur)

YouTube Vanced installation from Vanced Manager gets stuck whenever I try it, I've been waiting for so long yet it still doesn't work.

**Steps to reproduce:** idk

**Further details:** It says "Installing Vanced" in the notification, but it doesn't actually do it.

**Comment by lucknaumann** [comment]
Try going to App Info and turn on Allow to Install Unknown Apps (or something similar). I just tried it and it finally updated Vanced YouTube.

**Comment by X1nto** [comment]
Don't exit app when installing vanced/microg
