### ISSUE TITLE
Does not request root from Magisk

### ISSUE THREAD

**Issue by Legion495** [YTVanced/VancedManager#106]
**Please only report your issue here, if all points below are true**

**Phone Specifications:**
- Brand:Blackview
- Operating System: Android 9
- Android Version: ^
- Vanced Manager Version: 1.1.0 (Big Slur)

**Please describe the problem you are having in as much detail as possible:**
Well simple. The manager does not request root access unlike other root apps I know. 
Very frustrating as I have Magisk installed and am greeted by "no root access".

**Steps to reproduce:**
I mean nothing to produce to be frank.
Literally hit root should make the request imo. :)
But it doesn't. I am on the latest Magisk 20.4 and Manager 7.5.1

Obviously not a programmer. If there is a way to force the prompt let me know.

**Comment by X1nto** [comment]
Just tested on magisk 20.4, works fine. Could you send a logcat?

**Comment by Mattis6666** [comment]
`Magisk Manager > Superuser > Switch toggle to on for Manager`

You most likely denied the initial prompt on accident.

**Comment by X1nto** [comment]
Btw you may have set "deny" as default answer on superuser prompt in magisk manager

**Comment by Legion495** [comment]
Well I checked the log it said denied. WTF. 
I reinstalled it. Hit root and now it actually asked me... 

I do not know how. I don't get it.
