### ISSUE TITLE
Downloading sucks

### ISSUE THREAD

**Issue by hisudhakar** [YTVanced/VancedManager#108]
Installed micro-g easily and vanced was downloading, but it's not installing and showing notification 'installing vanced' no in app Notification/pop. Clicking install on vanced in app starts downloading again. Tried 3 times

**Comment by X1nto** [comment]
You probably out app in he background and your OS killed the service, try again without exiting the app

**Comment by hisudhakar** [comment]
I tried staying in the app.... Keeping display on all the time and it
wasn't installing. So i had to download those apk and compress all into
.apks zip file and install via SAI.
