### ISSUE TITLE
Vanced manager crashes instantly after update

### ISSUE THREAD

**Issue by warmos** [YTVanced/VancedManager#112]
Hi,
- I've installed the App from [vanced.app](https://vanced.app)
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- I'm not MIUI user. I've got rid of it
- I have disabled apk Signature Verification

**Phone Specifications:**
- Brand: Xiaomi redmi note 8T
- Operating System: Lineage OS 10
- Android Version:  10
- Vanced Manager Version: 1.2.0

**Problem decription:**
While opening the manager app, it crashes instantly. Had no problem with 1.1.0, but since developers updated it to new version, im unable to use at least the 1.1.0 version, it says "Error downloading file". 
Would give you more information, but the app instantly crashes and i don't see any log output. Could you guys please at least make work the 1.1.0 version? Thanks

**Steps to reproduce:**
Install app from vanced.app, launch

**Comment by X1nto** [comment]
There's no reason 1.1.0 would've stopped working as we didn't change anything on server. Could you send a logcat for 1.2.0?

**Comment by warmos** [comment]
Okay, i will close the issue. It seems, that my android have broke in some way and if I install any new app, it just crashes. Downloaded original youtube app from play store and it crashes immediatedly. Sorry for false alert.
