### ISSUE TITLE
Default preferred speed feature is not working

### ISSUE THREAD

**Issue by rajatpundir** [YTVanced/VancedManager#114]
I am using the latest version of app on a OnePlus6 device with latest Android version.

Change preferred video speed under Vanced settings from 1x to something else, say 1.5x.

Now try playing a few videos, some videos are played at preferred speed but it keeps reseting to Normal speed and you have to manually change the preferred speed.

Also, the preferred speed dialog gets stuck on screen 90% of the time when you are changing speed manually, I have tried this mostly for offline videos. In this case, I have to lock and unlock the phone to make the dialog disappear.

**Comment by Oizaro** [comment]
This is not a section where reporting Vanced bugs.

Only Manager.
