### ISSUE TITLE
Orbot incompatibility

### ISSUE THREAD

**Issue by Rikj000** [YTVanced/VancedManager#117]
Hi really cool and good looking app.

However when my Orbot Always-on VPN is turned on (which forces all trafic through the Tor network) all vanced versions show up as unavailable.

They reappear however when I turn off my VPN and Orbot, but this is not a thing you'd like to do often.

**Comment by KevinX8** [comment]
This means orbot can't resolve vanced.app for some reason, check what nodes you're using or use a different DNS
