### ISSUE TITLE
Please provide a tracker-free APK

### ISSUE THREAD

**Issue by IzzySoft** [YTVanced/VancedManager#118]
Could you please provide an APK that comes without Crashlytics, Firebase etc – as it was until v1.1.0? Thanks in ad-vance(d) :wink:

**Comment by KevinX8** [comment]
We use firebase to provide push notifications and track crashes + performance issues. You can build your own firebase free version if you wish, but in order for us to continue improving the app we will continue to provide public builds that have it ( you can also just use a tracker blocker like adaway and block analytics.google.com)

**Comment by KevinX8** [comment]
Also as an aside, YouTube Vanced itself still contains firebase from Google themselves so it is a strange request to ask for.

**Comment by IzzySoft** [comment]
First, thanks for your fast reply!

End users are rarely able to build their own APKs. And proprietary tracking-code inside root-enabled apps always is a bad idea (you can never be sure what that code really does: it has access to everything your code has access to, as it becomes part of your app).

I agree YouTube is a bad idea in this context, too; I've banned that from all my devices. But what about people who just want to use your installer to get microG set up? Considering that, my request should not sound strange at all. Of course I accept a "no" – I'm not using the app myself, I just [added it to my repo](https://apt.izzysoft.de/fdroid/index/apk/com.vanced.manager) on another user's request. For now I've removed v1.2.0 (takes effect with the next sync in about 12h) to wait your response; if it stays at "no", I'll probably have to remove the app again at some point when it becomes outdated, as you certainly wouldn't support older versions should issues arise.

**Comment by X1nto** [comment]
We are considering adding a switch in settings that will let you turn off firebase services

**Comment by KevinX8** [comment]
> First, thanks for your fast reply!
> 
> End users are rarely able to build their own APKs. And proprietary tracking-code inside root-enabled apps always is a bad idea (you can never be sure what that code really does: it has access to everything your code has access to, as it becomes part of your app).
> 
> I agree YouTube is a bad idea in this context, too; I've banned that from all my devices. But what about people who just want to use your installer to get microG set up? Considering that, my request should not sound strange at all. Of course I accept a "no" – I'm not using the app myself, I just [added it to my repo](https://apt.izzysoft.de/fdroid/index/apk/com.vanced.manager) on another user's request. For now I've removed v1.2.0 (takes effect with the next sync in about 12h) to wait your response; if it stays at "no", I'll probably have to remove the app again at some point when it becomes outdated, as you certainly wouldn't support older versions should issues arise.

To the root point, if you're afraid of what Google can do then why are you using Google play services/microg (which is a requirement for vanced root version). You don't need Vanced installer to install vanced microg, you can just get it from our repo. The main purpose of vanced manager is to make installation easy for people who don't know how to do things manually themselves, most of these people also do not know how to provide logcats etc. For crashes.
In the next release we will add a toggle for analytics so you don't have to manually block it.

**Comment by IzzySoft** [comment]
First: thanks for considering! And yes, I know (actually, I use "LineageOS for microG", so it even comes pre-installed for me).

The idea was to support an app that makes it easier for inexperienced users as you describe. With the update to 1.2.0, my scanner threw warnings as it detected all those libs (GMS, Crashlytics, Firebase). As long as they are present (toggle in the app or not), it will scream – as I wrote, with proprietary code you cannot be sure if you really disabled it or what it will still be doing in the background, so its presence is already the trigger here. I usually close an eye or two in most cases, but some combinations are blockers (like apps with root powers or apps targeted at children must **not** have any such). Hence I raised this issue in the hope for a "full FOSS build" (e.g. established via a build flavor, if you otherwise feel the need for those libs).

Why I am using microG? Only for UnifiedNlp (location services). FCM etc I leave disabled. I could also say: because of I am afraid what Google can do. And I know Marvin would NOT do. And because of developers not providing "full FOSS" apps which then refuse to work as they don't see GServices (which µG fakes so they accept them). There's no contacting Google from µG unless you explicitly enable it. But root access can work around that and directly contact whatever it wants – hence root-apps should not have such code.

Just to clarify: no blaming, just explaining! Though I don't use your app myself: thanks for providing non-tech-savvy users with an easy way to get µG onto their devices!

**Comment by KevinX8** [comment]
I really don't see the point in making vanced manager fully Foss friendly when Vanced itself isn't and never will be, and as you just mentioned that you refuse to use vanced yourself for this reason what is the point of making a manager that Foss people will install but refuse to use?

**Comment by KevinX8** [comment]
>thanks for providing non-tech-savvy users with an easy way to get µG onto their devices!
I think there's been a major misunderstanding, this is not what vanced manager is for, the microg it installs is only for YouTube Vanced, it is not designed as a play services replacement like the main microg, it is just used to bypass play services signature checks on unrooted devices. I repeat the microg it installs should not be confused with the one on microg.org and should not be and cannot be used as a drop in replacement.

**Comment by IzzySoft** [comment]
Looks like I wasn't clear enough in one point (my bad): The restriction (root/child apps must not have any trackers) is a rule for my repo – some users of my repo might feel different. And yes, you're correct: I completely misunderstood the microG part.

OK, no big deal for me: if there's no tracker-free version anymore, I can keep v1.1.0 around a little longer and then will have to drop the app (or drop it right away) as it makes no sense providing unsupported/outdated versions. I understand your point towards "100% FOSS" (and to a degree even share it in this context). Thanks for taking the time of explaining things, nevertheless!

PS: for reference, [here's the original request](https://github.com/YTVanced/VancedManager/issues/118). Be welcome should you want any app listed with my repo later!

**Comment by KevinX8** [comment]
> Looks like I wasn't clear enough in one point (my bad): The restriction (root/child apps must not have any trackers) is a rule for my repo – some users of my repo might feel different. And yes, you're correct: I completely misunderstood the microG part.
> 
> OK, no big deal for me: if there's no tracker-free version anymore, I can keep v1.1.0 around a little longer and then will have to drop the app (or drop it right away) as it makes no sense providing unsupported/outdated versions. I understand your point towards "100% FOSS" (and to a degree even share it in this context). Thanks for taking the time of explaining things, nevertheless!
> 
> PS: for reference, [here's the original request](https://github.com/YTVanced/VancedManager/issues/118). Be welcome should you want any app listed with my repo later!

If your repo is similar to fdroid then I do not recommend providing this app on it unless you are happy to trust vanced itself, which is proprietary, even without firebase included.

**Comment by IzzySoft** [comment]
It's close (a bit more "permissive" but not by much). So yes, I'll remove your app again.

PS: copy-paste error above, the URL to the original request is https://gitlab.com/IzzyOnDroid/repo/-/issues/125

Thanks again!
