### ISSUE TITLE
[Enhancement] Make root vs. non-root more obvious

### ISSUE THREAD

**Issue by TheFeelTrain** [YTVanced/VancedManager#123]
Right now in the UI it is extremely confusing, as the uncolored button is the active one when you would expect it to be the other way around. It might even make more sense to make them actual tabs just to make it super obvious.

It was on the non-root page by default so I went through the whole process of lmgtfy > reading the article > getting Lucky Patcher > disabling signature verification > rebooting, only to find it was unnecessary since I have root.

Turns out I am not the only one who thinks this:
https://old.reddit.com/r/Vanced/comments/ib85wk/question_vanced_manager_non_root_install/

Besides this I am loving the manager, the jump from v14 to v15 was painful and this manager makes it so much nicer.

**Comment by X1nto** [comment]
I have an explanation to this: all the *clickable* buttons in the app are filled, thus button variant that user can switch to is also filled, because it's clickable

**Comment by 1nikolas** [comment]
I agree. I think with tabs and fragments it will be more obvious. Now you don't know what's checked. I have to click a clicked button to make sure 😅

**Comment by X1nto** [comment]
Currently working on it, added some base stuff in 3a3624e1beb17784d058f7bc6a554b9d84dddf4c but layout is currently not working at all:
![Screenshot_2020-08-29-15-47-04-376_com.vanced.manager.jpg](https://user-images.githubusercontent.com/48173186/91654626-702cf580-eabb-11ea-8804-23e653165cfc.jpg)

**Comment by X1nto** [comment]
Update: we got it to work![Screenshot_2020-09-03-12-46-33-906_com.vanced.manager.jpg](https://user-images.githubusercontent.com/48173186/92092786-91575400-ede3-11ea-90b0-dda65658e58a.jpg)

**Comment by TheFeelTrain** [comment]
Very nice. It's a small thing in the grand scheme but I think it helps a lot with quality-of-life.

**Comment by X1nto** [comment]
https://github.com/YTVanced/VancedManager/releases/tag/1.3.0b
