### ISSUE TITLE
An error has occured when downloading Vanced

### ISSUE THREAD

**Issue by VuHongQuang-VN** [YTVanced/VancedManager#128]
After download, it didnt install but showed a nofication:"An error has occured when downloading Vanced"
Device name: Samsung Galaxy A20/ SM-A205F/DS
Root: Yes
Logcat: https://drive.google.com/file/d/15ureSKRM6__6CjmmS7xAHM6r8jzqeHYc/view
![Screenshot_20200825-183853_Vanced Manager](https://user-images.githubusercontent.com/67698443/91170882-be30aa80-e703-11ea-9303-640faec249ae.jpg)

**Comment by X1nto** [comment]
Go to manager settings > chose installation values > reset, then download again

**Comment by VuHongQuang-VN** [comment]
Thanks, It's working
