### ISSUE TITLE
Allow youtube vanced on external storage

### ISSUE THREAD

**Issue by egscodes** [YTVanced/VancedManager#129]
So the vanced app by default does not go in the sd.

When they decided to use SAI the app did store it on the external storage. 

But now that we use vanced manager not only installs it back to the phone, but it also deletes the apps settings (i.e. playback feeds, auto play, etc.) 

so maybe have a option like sai that installs it on external storage? (or make it so vanced allows it by default)

(dou i will say if you do decide to implement the install on external make it so microg does not install cause if you restart the phone it will make you so you have to log in again...)

**Comment by KevinX8** [comment]
We're not going to change any stock youtube options
