### ISSUE TITLE
Question about signature spoofing included in some ROM

### ISSUE THREAD

**Issue by siffreinsg** [YTVanced/VancedManager#130]
Hi,
Some ROMs provide a way to disable signature spoofing and adds an android permission apps can request.
Could it be used by Vanced Manager or is it unrelated ? Lucky Patcher is great but runs in background and doesn't inspire trust at first glance... (and adds another dependency : watching YouTube requires 3 apps instead of just one)

Thanks

**Comment by X1nto** [comment]
Signature verification != Signature spoofing

**Comment by siffreinsg** [comment]
> Signature verification != Signature spoofing

Okay so it is unrelated. Thanks! Then I'll stick with LP
