### ISSUE TITLE
Vanced download not successful

### ISSUE THREAD

**Issue by kanehu** [YTVanced/VancedManager#131]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: lg v30
- Operating System:android
- Android Version:9
- Vanced Manager Version:1.2.0

**Please describe the problem you are having in as much detail as possible:**
I try to reinstall vanced. Downloading splitconfig something, then dark.apk. Before finishing download it says download not successful. Not installing anything.

**Steps to reproduce:**

**Further details:**
I downloaded apkm from a different location. So I have now the latest version.

**Comment by X1nto** [comment]
#128

**Comment by kanehu** [comment]
Thank you. Working.

**Comment by kanehu** [comment]
Thank you.
