### ISSUE TITLE
Swipe control not working in new update

### ISSUE THREAD

**Issue by shipoxx** [YTVanced/VancedManager#132]
**Hey guys in new update i can't use swipe control it doesn't work especially wheb I'm offline after download a video!**

**Phone Specifications:**
- Brand: sony
- Operating System: android
- Android Version: 6.0.1
- Vanced Manager Version:15.33.34

**Comment by shipoxx** [comment]
@X1nto

**Comment by Oizaro** [comment]
Manager Bug  --->  Report on Manager github page

MicroG Bug  --->  Report on MicroG github page

Do you see Vanced writed somewhere here?

**Comment by X1nto** [comment]
First of all, this is not a manager issue. Second, you don't have to mention me in order to take my attention. I'm closing this issue
