### ISSUE TITLE
Problem in Picture-in-picture mode

### ISSUE THREAD

**Issue by droidteamoficial** [YTVanced/VancedManager#136]
After the last update when I enter a direct link because it does not work in Picture-in-picture mode (even if it is activated), it starts to work only in the background.

[Projeto_08-31(4)_SD.zip](https://github.com/YTVanced/VancedManager/files/5152228/Projeto_08-31.4._SD.zip)

**Comment by X1nto** [comment]
I swear if anyone else reports Vanced issues on manager GitHub, I'll close issues without even explaining

**Comment by droidteamoficial** [comment]
Onde posso relatar?

Em seg, 31 de ago de 2020 16:37, Tornike Khintibidze <
notifications@github.com> escreveu:
