### ISSUE TITLE
Auto-resume downloads or updates after network interruptions

### ISSUE THREAD

**Issue by CrimsonBloodfang** [YTVanced/VancedManager#140]
I couldn't completely download and update YouTube Vanced through Vanced Manager because the downloads won't resume whenever the internet connection gets interrupted or unstable. 

My internet connection is unstable and disconnects every minute. So I also have it set to auto-reconnect the internet every minute using MacroDroid or Automate. 

I tried to download the YouTube Vanced apk using the mediafire mirror link posted on xda or in the official website, but either the latest apk wasn't uploaded or only Vanced Manager can be downloaded.

I hope auto-resume feature could be added since not everyone has a solid internet connection. Or if you could also include a separate download link for the YouTube Vanced apk on the website, for those wanting to install using SAI or is in the same situation as me. I'll have to wait until then.

**Comment by kmashao** [comment]
Clearing the downloads in settings allowed me to download after my internet got interrupted

**Comment by CrimsonBloodfang** [comment]
> Clearing the downloads in settings allowed me to download after my internet got interrupted

Yeah, I can also download back whenever my internet connection gets interrupted too. Problem is, my internet isn't fast enough to complete the download within a minute. It's exactly a minute before internet gets disconnected and then reconnected using a task app. For me, I just click update button again. Did tried clearing the downloads.

**Comment by KevinX8** [comment]
added in https://github.com/YTVanced/VancedManager/releases/tag/1.3.0
