### ISSUE TITLE
Error downloading Vanced

### ISSUE THREAD

**Issue by Saibamen** [YTVanced/VancedManager#141]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

All good for above.

**Phone Specifications:**
- Brand: Huawei P20 Pro
- Operating System: ?? Android lol
- Android Version: 10
- Vanced Manager Version: 1.2.0

**Please describe the problem you are having in as much detail as possible:**
I can not install latest Vanced.
After downloading `split_config.en.apk` I got toast error:  `Error downloading Vanced`

**Steps to reproduce:**
Uninstall Vanced, install again

**Further details:**
I do "Clear downloaded files"  and I reset `feed URL` but it doesn't help

**Comment by X1nto** [comment]
#128

**Comment by Saibamen** [comment]
Ok, working, but IMO will be good to add info about it in toast

**Comment by X1nto** [comment]
Next version will skip language split download if it doesn't exist in server
