### ISSUE TITLE
Swiping for volume and brightness dont work

### ISSUE THREAD

**Issue by juckendesAuge** [YTVanced/VancedManager#145]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: Huawei mediapad m3
- Operating System:
- Android Version: 9
- Vanced Manager Version: 1.20 Nico

**Please describe the problem you are having in as much detail as possible:**

**Steps to reproduce:**
Enable IT, in the vanced options. Dont work

**Further details:**
Swiping for volume and brightness dont work

**Comment by X1nto** [comment]
Look at this screenshot carefully![IMG_20200910_223040.jpg](https://user-images.githubusercontent.com/48173186/92781581-4f1aad80-f3b5-11ea-9609-cb54cfc2673c.jpg)
