### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by iain80** [YTVanced/VancedManager#146]
Vanced Manager crashes on start up Google Pixel 4 running Android 11.

**Comment by X1nto** [comment]
Duplicate of #115. Just wait for an update

**Comment by X1nto** [comment]
https://github.com/YTVanced/VancedManager/releases/tag/1.3.0b

**Comment by benefacto** [comment]
> 
> 
> https://github.com/YTVanced/VancedManager/releases/tag/1.3.0b

This link is a 404--the latest publicly visible release is 1.2.0.

**Comment by Merwenus** [comment]
Any link for the 1.3 beta version? 1.2 crashes on Mi 10 with weekly xiaomi.eu firmware.

**Comment by X1nto** [comment]
https://github.com/YTVanced/VancedManager/releases/tag/1.3.0
