### ISSUE TITLE
Error Downloading microG

### ISSUE THREAD

**Issue by truefriend-cz** [YTVanced/VancedManager#148]
Hello. I have problem in Vanced Manager on Android 5.1 (ARMv7).
After tap Install microG show this message: "Error Downloading microG".
How i can fix it? This bug is many month.

Steps:
Download Vanced Manager from https://vanced.app/
I am running App and tap on "Install" button at microG section. Then show popup error "Error Downloading microG". And microG not installed.

**Comment by DroidSFT** [comment]
Should be fixed in this PR https://github.com/YTVanced/VancedManager/pull/207

**Comment by truefriend-cz** [comment]
v.2.0
App now killed after running on Android 5.1.

Great job, the next version could launch a Russian missile straight away.
