### ISSUE TITLE
Help to ytv

### ISSUE THREAD

**Issue by Martydk85** [YTVanced/VancedManager#151]
**Phone Specifications:**
- Brand: Samsung a50
- Operating System: android
- Android Version: latest
- Vanced Manager Version: latest update 

So now I can't use my ytv it says I have no connection, even though I'm home on my wifi,
Im used to use it when I'm at work, watching videos.
But it says I have no connection what so ever.
I have tried deleting it 2 times and reinstalling it.
Tried the playstore version to,
But with that one I can't connect to my YouTube channel and se my videos or my subscriptions and how far a got in my channel watching..
What could it be, pls help I'm addicted to this app without ads

**Comment by X1nto** [comment]
I already told you, use https://github.com/YTVanced/Vanced for Vanced related issues
