### ISSUE TITLE
Android 11: Manager doesn't seem able to detect YouTube Vanced or microG

### ISSUE THREAD

**Issue by JLJTGR** [YTVanced/VancedManager#153]
**Phone Specifications:**
- Brand: Google
- Operating System: Stock Google Android?
- Android Version: 11 (RP1A200720.009)
- Vanced Manager Version: 1.2.0

**Please describe the problem you are having in as much detail as possible:**
Cannot use the manager to install YouTube Vanced because it cannot detect microG and insists on installing it.  After installation, it still cannot detect microG and blocks installing YouTube Vanced.

**Steps to reproduce:**
Open the app and notice the "installed" version for each component.  Try to install either component.  Status remains "Unavailable".

**Further details:**
![Screenshot_20200914-165704](https://user-images.githubusercontent.com/5780236/93139336-8b4c5780-f6ae-11ea-89d0-a44a55a04ed6.png)
Disabling XPrivacyLua didn't help.  Wasn't an issue for Android 10.

**Comment by JLJTGR** [comment]
Since the other topics were crash topics, I thought this was a different issue, but I guess it's still a known issue as it is referenced here: https://github.com/YTVanced/VancedManager/issues/115#issuecomment-674076587
I suppose you can close this if you think it's a duplicate, but others might also overlook the crash issues and repost this.

**Comment by X1nto** [comment]
Try this one: https://github.com/YTVanced/VancedManager/releases/tag/1.3.0b

**Comment by JLJTGR** [comment]
Works for me.

**Comment by JLJTGR** [comment]
Hmm, I started pointing people to this pre-release version but it's gone now.
