### ISSUE TITLE
I can't open vanced manager...

### ISSUE THREAD

**Issue by gustasmor** [YTVanced/VancedManager#156]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: Xiaomi redmi note 8 (ginkgo)
- Operating System: android (ion os custom rom)
- Android Version: 10 (Q)
- Vanced Manager Version: 1.0.2 (niko)

so when I download youtube vanced manager, it can't be opened, like, there is no way to open it, there is no choice to open it from settings either, it just offers to uninstall or force stop vaned manager. (like with substratum overlays)
![Screenshot_Settings_20200915-180000](https://user-images.githubusercontent.com/71335873/93228414-1cd6ca80-f77e-11ea-851d-2a7c4f38658c.jpg)

**Comment by X1nto** [comment]
Issue with your ROM, not manager. Try reinstalling it

**Comment by agtpirrone** [comment]
> Issue with your ROM, not manager. Try reinstalling it

Not working on stock Android 11 on pixel 4 either. I don't think is ROM related.

**Comment by veselysps** [comment]
Isn't working on android 11 for me either

**Comment by goofy1988** [comment]
It was also not working for me on 11 and Pixel an 4XL. I found out a workaround. Use the app App Cloner and activate that the app will not close when it crashes. After that i was able to use the cloned vanced manager apk as normal.

**Comment by gustasmor** [comment]
> It was also not working for me on 11 and Pixel an 4XL. I found out a workaround. Use the app App Cloner and activate that the app will not close when it crashes. After that i was able to use the cloned vanced manager apk as normal.

Which one did you use

**Comment by gustasmor** [comment]
> It was also not working for me on 11 and Pixel an 4XL. I found out a workaround. Use the app App Cloner and activate that the app will not close when it crashes. After that i was able to use the cloned vanced manager apk as normal.
Which one did you use?

**Comment by elliotnash** [comment]
Not working on Oneplus 8 android 11 ob1

**Comment by ginotonny** [comment]
I solved it by installing an older version of Vanced Manager.

**Comment by gustasmor** [comment]
> I solved it by installing an older version of Vanced Manager. 

I'm trying to make 14.21.54 rooted work

**Comment by boonhapus** [comment]
+1 on Pixel 4 XL, Android 11, v1.2.0 Niko

**Comment by NatoBoram** [comment]
@agtpirrone @veselysps @elliotnash @boonhapus you're looking for #115.

**Comment by incIined** [comment]
To everyone above, you are having a completely separate issue than OP. The issue has to do with A11, OP’s bug does not.

**Comment by X1nto** [comment]
Try out this one: https://github.com/YTVanced/VancedManager/releases/tag/1.3.0b

**Comment by MrSnowball-dev** [comment]
> Try out this one: https://github.com/YTVanced/VancedManager/releases/tag/1.3.0b

link doesn't work

**Comment by agtpirrone** [comment]
> Try out this one: https://github.com/YTVanced/VancedManager/releases/tag/1.3.0b

Worked for me. Also could fix the fullscreen problem on Android11 by updating YT Vanced

**Comment by CiriousJoker** [comment]
Pixel 4xl with Android 11 here, just like the rest

**Comment by Cabbo** [comment]
VancedManager v1.1.0 Big Sur worked for me on Android 11 too

**Comment by CiriousJoker** [comment]
Big sur worked for me as well

**Comment by X1nto** [comment]
https://github.com/YTVanced/VancedManager/releases/tag/1.3.0
