### ISSUE TITLE
[removed from reddit so posting here]How does Vance take access to my Google Account

### ISSUE THREAD

**Issue by codingonsteroid** [YTVanced/VancedManager#177]
I really liked the product. Also, the code is on Github. I mindlessly since my main Google account in Vance. All my bank accounts are linked with my primary Google account. I have created a secondary account for Vance and would like to pull my main account out of Vance's access

I logged out my G-account from Vance. Removed Vance account from my Android device's Accounts section. Also checked if Vance took access via Google signed-in apps. I didn't Vance in my Google Signed in Apps. I just don't want my main Google account to be compromised. Any idea if Vance is still accessing my main primary GMAIL account?

If yes how do I pull all permission back from Vance?

**Comment by codingonsteroid** [comment]
<img width="792" alt="Screenshot 2020-10-02 at 2 55 20 AM" src="https://user-images.githubusercontent.com/69804298/94865146-ba0e5000-045a-11eb-9ff3-a1ba604c27d3.png">

I downloaded vance from vanced.app

**Comment by X1nto** [comment]
Vanced had no access to your account whatsoever, Login is done via microg or play services (if you're on root version), vanced does not and will NEVER store your accounts/personal data on the servers/somewhere else. I'd you're concerned about your safety, you can stop using vanced anytime

**Comment by codingonsteroid** [comment]
Thanks took lot of strees of my head ❤️🌶️
Naah I'm not Uninstalling this. It's like my current favourite app along with Blokada and Brave Browser 

I can watch video in 2k and 4k when youtube is restricted it to 480p during lockdown. 

Such a cool app. I even have youtube music from Vance now. Good work guys 🤠
