### ISSUE TITLE
Error Downloading dark.apk

### ISSUE THREAD

**Issue by patterned** [YTVanced/VancedManager#179]
**Phone Specifications:**
- Brand: Motorola
- Operating System: 
- Android Version: 10
- Vanced Manager Version: 1.3.0

**Please describe the problem you are having in as much detail as possible:**
After installing MicroG, attempting to install Vanced errors in "Error Downloading dark.apk".
Reset theme settings, changed theme preference on install, error still exists.

**Steps to reproduce:**
Install vanced manager, install microg, install vanced

**Comment by X1nto** [comment]
Server had some problems, try if it works now

**Comment by myhrmans** [comment]
Same issue here. OnePlus 7 pro

**Comment by RobbieTemanevry** [comment]
Same issue on my Huawei MediaPad T5

**Comment by AskMeCode** [comment]
same issue Samsung galaxy S6 android 7

**Comment by dustojnikhummer** [comment]
Also happens on my Poco F1, MIUI11 with Optimizations disabled.

**Comment by DJRysiek** [comment]
Same here. Samsung Galaxy S7 android 8.0.0.

**Comment by anonymix007** [comment]
I am also unable to download YT Music. I guess it's the same issue

**Comment by dushtusozzy** [comment]
yeah same issue here... on S8 Plus rooted

**Comment by catbreast** [comment]
https://vanced.app/api/v1 Redirected 127.0.0.1
I deleted all hosts，The problem is still。
Maybe there are other api addresses

**Comment by TBSniller** [comment]
Same here, /api also redirecting to localhost. Using direct IP is blocked by CloudFlare.

**Comment by chino-chan1** [comment]
same here with samsung a20 android 10

**Comment by Vic470** [comment]
Same here with One Plus 6 Android 10

**Comment by SnizelDev** [comment]
Same with YT Music when trying to download on Vanced Manger, on OnePlus 7t Pro.

**Comment by I-Go-By-M** [comment]
Same problem on my Galaxy Note 9. Guess we wait for the West coast to wake up?

**Comment by dustojnikhummer** [comment]
According to guys on Discord, this is an issue on Cloudflare's end, nothing they can do about it. Please be patient.

**Comment by oxk4r01** [comment]
She is issue here. Fix this please, nothing is working right now.

**Comment by rajarshiamity** [comment]
Same problem in Nokia 6.1, Android 10

**Comment by Vic470** [comment]
Problem solved, thank you very much to those involved !!

**Comment by AinzTheSupremeOne** [comment]
Have you guys tried using a VPN when downloading apps from Manager?

**Comment by TheDarkTron** [comment]
Error still exists on OnePlus 6

**Comment by Demetryi** [comment]
the problem came back again.
nonroot.

**Comment by X1nto** [comment]
website is down

**Comment by kasteckis** [comment]
Global Vanced notification destroyed the server. Lol

**Comment by hyunki** [comment]
Ah server is gone

**Comment by nerex127** [comment]
I think it's fixed now

**Comment by InzemamZahidi** [comment]
Mine too , suddenly showing this error, I was tinkering things in Lucky patcher, spent half an hour to understand that it was really the server and not my system.

**Comment by MRishiK99** [comment]
Issue fixed??

**Comment by NimeshJohari02** [comment]
Nah Still There for the root version

**Comment by Shoxx98** [comment]
not fixed yet for me

**Comment by p6002** [comment]
Same here, still not fixed. 
The worst part is that it cannot be given 1 star.

**Comment by travisterrell** [comment]
Yeah, I'm surprised this still hasn't been fixed--particularly given I was just given an notification telling me to download the latest updates! Hopefully they reopen the issue and actually address it. (Blaming AWS is not sufficient--even the cheapest plans still have 99%+ uptime!)

**Comment by loworbitmoonsun** [comment]
A manager app is nice and all but if you cant actually manage to provide downloads through it then it might be better to just go old school and provide a simple download on your website...issue still persists.

**Comment by tomXGames** [comment]
Same thing here... Neither YT or Music, nor MicroG can be downloaded... I also can't access the changelog. I assume it's a cdn problem.

**Comment by FARES-ESAM** [comment]
clear the vanced manager cache. it worked for me

**Comment by viveksinghmehta** [comment]
> clear the vanced manager cache. it worked for me

The issue still persist

**Comment by FARES-ESAM** [comment]
really then your bad luck🤭.i cleared cache the it instantly downloaded. maybe they are pushing the update to number of users because of server.

**Comment by AidanTheTurtle** [comment]
Restarting my device fixed any files not downloading in the manager.

**Comment by g34rn1nja** [comment]
I had this issue now and managed to fix it, thought it was the hosts like other, but it turns out that it was already installed as it said from the start, it was saying "reinstall". All I had to do was to uninstall the original YouTube app, it appeared in its place after. Hope this helps someone

**Comment by abhivr** [comment]
Updated my Vanced manager and now facing this issue. Not able to install YouTube Vanced at all. Using OnePlus 6

**Comment by travisterrell** [comment]
Have you attempted any of the techniques described here to fix it? Though that'd actually be my second course of action. My first would actually be to just wait several hours and try again! Mine have always begun working within 24 hours all on their own, independently of my extensive troubleshooting and failed attempts to fix it.

**Comment by DrSaad77** [comment]
> clear the vanced manager cache. it worked for me

Thx, easy solution, but it worked.
Close totally Vanced Manager > Clean Data + Cache, then Reboot the phone.
And hope it is enable to download latest Vanced version.
Thx :)

**Comment by darthnithin** [comment]
> > clear the vanced manager cache. it worked for me
> 
> Thx, easy solution, but it worked.
> Close totally Vanced Manager > Clean Data + Cache, then Reboot the phone.
> And hope it is enable to download latest Vanced version.
> Thx :)

I did this and it's still not working 

🤔I wonder what the issue is

for some reason only microg.apk is working... not even ytmc is working

**Comment by MeXaN1cK** [comment]
> > > clear the vanced manager cache. it worked for me
> > 
> > 
> > Thx, easy solution, but it worked.
> > Close totally Vanced Manager > Clean Data + Cache, then Reboot the phone.
> > And hope it is enable to download latest Vanced version.
> > Thx :)
> 
> I did this and it's still not working
> 
> 🤔I wonder what the issue is
> 
> for some reason only microg.apk is working... not even ytmc is working

Same problem on my Xiaomi Mi Pad 4.

**Comment by Nanofari** [comment]
> > > > очистить кеш расширенного менеджера. это сработало для меня
> > > 
> > > 
> > > Спасибо, простое решение, но оно сработало. 
> > > Полностью закройте Vanced Manager> Clean Data + Cache, затем перезагрузите телефон. 
> > > И надеюсь, что это позволит загрузить последнюю версию Vanced. 
> > > Спасибо :)
> > 
> > 
> > Я сделал это, но все еще не работает
> > 🤔Интересно, в чем проблема
> > почему то работает только microg.apk ... даже ytmc не работает
> 
> Такая же проблема на моем Xiaomi Mi Pad 4.

Тоже проблема такая же (dark.apk) Samsung A52
