### ISSUE TITLE
Error updating or uninstalling Root YT Vanced and Error downloading microG

### ISSUE THREAD

**Issue by Kritior** [YTVanced/VancedManager#180]
**Phone Specifications:**
- Brand: Moto
- Operating System:
- Android Version: 9.0
- Vanced Manager Version:  1.3.0

The Manager app is showing version 14.18.56 [root] as installed and i cannot update it (error downloading dark.apk and trying to uninstall it does nothing) even tho i uninstalled both microG and Vanced and cant find it in android settings. I also cannot install microG (my phone isn't actually rooted i probably mistakenly tried to install the root version before) with error downloading microG

I dont actually know how to reproduce it but i assume I have an earlier bugged version because I installed vanced wrong previously, that somehow cant be uninstalled. 
Also this started because I couldn't remove my google account in vanced even after removing it from my phone restarting and everything so I decided to just completely reinstall everything.

Here are two screenshots of the Manager app for me: 
[
![image](https://user-images.githubusercontent.com/49076498/94994418-c21fda00-0597-11eb-8654-3b870a4e0d01.png)
](url)

![image](https://user-images.githubusercontent.com/49076498/94994450-f2677880-0597-11eb-8710-76a301c635e5.png)

edits are me adding the images and making my writing more coherent...

**Comment by dustojnikhummer** [comment]
Duplicate [#179](https://github.com/YTVanced/VancedManager/issues/179)

**Comment by Kritior** [comment]
well only half of this is a duplicate of #179 also since the newest update the install worked for me even tho the root version still says it's installed when it's not
