### ISSUE TITLE
yt music not install

### ISSUE THREAD

**Issue by dmiltondas** [YTVanced/VancedManager#181]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand:Nokia
- Operating System: Android
- Android Version:10
- Vanced Manager Version:1.3.0

**Please describe the problem you are having in as much detail as possible:** when i try to install it's show download error.

**Steps to reproduce: 

**Further details:**

**Comment by abun880007** [comment]
I am having the same issue since the new Music 3.86.51 version was added

**Comment by Kratoris** [comment]
I am having the same issue too since the new Music 3.86.51 version was added. Xiaomi MI A3 4G LTE on Android 10 running latest Vanced Manager.
