### ISSUE TITLE
Retain already downloaded files

### ISSUE THREAD

**Issue by wereii** [YTVanced/VancedManager#185]
This is just an idea that popped into my mind because I have forgot I had the update running for Vanced and cleared my cache (killing the app). After getting back and doing it again it seems the apks and stuff gets re-downloaded.

So a some kind of "multi-step" installation process - download (if not already found) > verify (always) > install, would be nice.

**Comment by DraconicNEO** [comment]
Maybe there should be an option to download the apk and apks files to local storage to use them in a different installer, If you wanted to.
