### ISSUE TITLE
Lastest release broken all

### ISSUE THREAD

**Issue by darhanger** [YTVanced/VancedManager#186]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: lg g8 thinq
- Operating System: android
- Android Version: 10
- Vanced Manager Version: lastest

**Please describe the problem you are having in as much detail as possible:**
After update all stop working. Music, microg and youtube. 

**Steps to reproduce:**
Update to lastest version

**Further details:**
Reinstall and reboot device not help

**Comment by DarkSiider77** [comment]
I encountered the same issue with a mi mix 2s with android 10 (evolutionX not miui)

**Comment by Virtualtrax** [comment]
Exactly the same problem for me with a Xiaomi mi mix using with linalgeOs 17.1. It has begin to crash YouTube Vanced but the problem seem to come from vanced manager as I can't reinstall anything on it

**Comment by cibic89** [comment]
Having problems here too. Cannot install or update anything with latest app version. It asks for no permissions and it says "error downloading xxx. Apk"
Uninstalling apps works. Tried reinstalling manager app and rebooting phone but no change

**Comment by DefaultSimon** [comment]
Same issue here on rooted Huawei P10 Lite. It downloads the apk files, but gets stuck on the spinner animation.

**Comment by Cipheriax** [comment]
can't reproduce.
Had manager installed before, updated to 1.3.1 using the update button (not redownloading from vanced.app), and updated YT Vanced after that, as well as installed YT Music. 

Galaxy Tab S6 LTE (SM-T865), Android 10, no root

**Comment by sachindanav** [comment]
I tried to update but now i have official youtube, vanced not installing what can i do i tried reinstalling more then 20 times

**Comment by Cipheriax** [comment]
@sachindanav Disable the original Youtube app.
For further assistance, you can join the Vanced Discord server https://discord.com/invite/TUVd7rd

**Comment by sachindanav** [comment]
> Youtube

Are you serious i already have vanced youtube install 15.5 when updating with vanced manager it removes vanced youtube and install official one

**Comment by X1nto** [comment]
> > Youtube
> 
> Are you serious i already have vanced youtube install 15.5 when updating with vanced manager it removes vanced youtube and install official one

That's not how it works lmao
