### ISSUE TITLE
Vanced music doesn't appear on ROOT tab.

### ISSUE THREAD

**Issue by hsinankirdar** [YTVanced/VancedManager#188]
- Brand: Samsung Galaxy Note 8
- Operating System: Android
- Android Version: 10
- Vanced Manager Version: 1.3.1

The issue about Vanced Music.
 I am on latest version of vanced manager app, i am already a user of youtube vanced with root. But vanced music option doesn't appear at root tab. 

I can see it on non root tab, but when i click to install it, it want microg. Do i have to install vanced music with non root option?

**Comment by KevinX8** [comment]
where does it say vanced music has a root version? it asks you to install microg because there is only a nonroot version.

**Comment by hsinankirdar** [comment]
OK. Don't be angry :). I just thought, should be opposite and it may be a bug. MB
