### ISSUE TITLE
[BUG] Chinese Traditional as system language shows as Chinese Simplified

### ISSUE THREAD

**Issue by RobotHanzo** [YTVanced/VancedManager#191]
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: Samsung
- Operating System: OneUI 2.1 + Magisk 20.04
- Android Version: 10
- Vanced Manager Version: 1.3.1

**Steps to reproduce:**
1. Change your system language to Chinese Traditional 
2. Go into Vanced manager and choose system default as language
3. You get Chinese Simplified

**Further details:**
- Despite the Vanced app only having one type of Chinese (zh), it works perfectly to convert between Tradtional and Simplifed Chinese
- It only happens after updating to 1.3.1

**Comment by X1nto** [comment]
Weird, Language is grabbed directly from system, probably has something to do with the different types of one language, will look into that
