### ISSUE TITLE
I can't install in tablet

### ISSUE THREAD

**Issue by wernser412** [YTVanced/VancedManager#193]
I can't install in tablet

![Screenshot_2020-10-04-08-42-07](https://user-images.githubusercontent.com/53667212/95017283-05249080-061e-11eb-96b4-804088637c70.jpeg)

**Comment by X1nto** [comment]
Install what

**Comment by wernser412** [comment]
> Install what

Vanced Manager 1.3.1.apk

**Comment by ikamaru** [comment]
which model is this?

**Comment by wernser412** [comment]
the app was for android 5+ and not for android 4+, that was the problem, I can only install old vanced YouTube for android 4+

**Comment by X1nto** [comment]
Manager supports Android 5 and up

**Comment by TrianguloY** [comment]
Is it possible to download the apks manually without the manager to be able to install it? (I assume the apks are installable on android 4, normal YouTube is, while the manager isn't) 
Is there a list of links somewhere?

**Comment by X1nto** [comment]
Vanced doesn't support android 4, manager doesn't support it either and no, there are no direct links

**Comment by TrianguloY** [comment]
Oh, I still have an old version (14.05.56) on an android 4.2.2 tablet. It works fine, but lacks the newest features from latest versions. I wanted to update, but from your words I assume you dropped the compatibility (not sure why).

Thanks for the reply anyway. In any case a way to download the apks directly would be beneficial (but I guess you have already received that petition).
