### ISSUE TITLE
Mobile Data downloads (YT Music)

### ISSUE THREAD

**Issue by mosope02** [YTVanced/VancedManager#195]
**Can't download songs with mobile data (YT music)**
- I am using the latest version of the app

- Non-root user

**Phone Specifications:**
- Brand: Tecno Canon X (CA7)
- Operating System: Android 
- Android Version: 8.1.0
- Vanced Manager Version: 1.3.1

It would be nice if I could download songs to be able to play offline with mobile data.
The latest version supports only Downloads with WiFi.

**Comment by X1nto** [comment]
Not a manager related issue
