### ISSUE TITLE
Regular Youtube Music gets installed instead of Vanced Music

### ISSUE THREAD

**Issue by Taewan-P** [YTVanced/VancedManager#198]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: Pixel 3 XL
- Operating System: Android pure, no root
- Android Version: 11
- Vanced Manager Version: 1.3.1

**Please describe the problem you are having in as much detail as possible:**
Installing Vanced Music would install Regular Youtube Music. No difference 
The premium features are blocked and cannot even load main page. (Since YT music is available to premium members in my country)

**Steps to reproduce:**
Install Vanced Music from Vanced Manager

**Further details:**
How can you tell the difference between Vanced Music and Regular YT Music? So far, there was no difference with YT Music and Vanced Music in my device. Features are all blocked due to premium, icons are the same, and etc...

**Comment by X1nto** [comment]
Only icons are the same. Music vanced does not allow downloads, otherwise it's just like premium music with background download

**Comment by Taewan-P** [comment]
Well, still my YT music does not load at all saying, "YT music is available to premium members in your country".

**Comment by dna1982** [comment]
Vanced Music can only let you listen music in background, it can't automatic make you a Premium member.

**Comment by X1nto** [comment]
basically this ^

I'm closing this issue now
