### ISSUE TITLE
Vanced Manager doesn't install the apk if the manager is not in foreground

### ISSUE THREAD

**Issue by fawazahmed0** [YTVanced/VancedManager#200]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server : Yes
- I am using the latest version : Yes
- This is an issue in the Vanced Manager app (NOT Youtube Vanced) : Yes
- This issue keeps re-occurring every time I try : Yes
- For MIUI users: I disabled MIUI optimisation : Yes
- For root users: I disabled apk Signature Verification : N/A

**Phone Specifications:**
- Brand: Mi Redmi 9A
- Operating System: 10
- Android Version: 10
- Vanced Manager Version: 1.3.1

**Please describe the problem you are having in as much detail as possible:**
When I try to install the vanced app or microG from manager, it doesn't get installed if the phone goes to sleep  due to lock screen timeout or when the manager is not in foreground. The Install dialog will never appear.

To fix the issue, the app screen should be on/visible  during the time when apk download completes, because that is the time when the Install dialog will appear

**Steps to reproduce:**
1. Press on Install for youtube vanced. 
2. Make the phone sleep by pressing power button.
3. Wait for sometime like 10mins etc and unlock the phone and try seeing the vanced manager screen.
Actual:
You will see no install dialog
Expected:
we should see install dialog, so we can install the downloaded apk by vanced manager

Thanks

**Comment by X1nto** [comment]
I assume you didn't read README, closing this issue
