### ISSUE TITLE
Option to disable the Miui warnings

### ISSUE THREAD

**Issue by DraconicNEO** [YTVanced/VancedManager#206]
Hello This is a suggestion for a feature, there should be a way to disable the Miui warnings in Vanced Manager. Installs worked fine before the last update, and they worked up until I cleared the Manager's data so don't tell me they never have worked (I'm not that stupid).

**Comment by X1nto** [comment]
There are people who forget to turn off miui optimisations, which is why the app is showing warnings. We really don't want to have 100 new issues just because people FORGOT to disable miui optimisations

**Comment by DraconicNEO** [comment]
I don't see how allowing users to disable warnings in settings is too much to ask. Also what did you change about Vanced Manager to make it not working on newer versions after clearing data? Does it just refuse to download if it detects the Miui optimizations settings? (It worked before So I know it was caused by something in one of the new updates.)

**Comment by X1nto** [comment]
> Does it just refuse to download if it detects the Miui optimizations settings? (It worked before So I know it was caused by something in one of the new updates.)

No? Not sure why you even ask that. there's only one dialog, nothing else.

**Comment by DraconicNEO** [comment]
Because of this, "In order to install Vanced, you MUST disable MIUI Optimisations in the developer settings."
Seems intentional, especially since it was working before I updated Vanced Manager.

**Comment by X1nto** [comment]
> Because of this, "In order to install Vanced, you MUST disable MIUI Optimisations in the developer settings."
> Seems intentional, especially since it was working before I updated Vanced Manager.

You MUST disable it in order for installation to work (MemeUI moment), otherwise it will just error out, unless you're on xiaomi.eu 20.0.2 or higher

**Comment by DraconicNEO** [comment]
Then why did it work before I updated to the new version of vanced manager?

**Comment by X1nto** [comment]
> Then why did it work before I updated to the new version of vanced manager?

How am I supposed to know?

**Comment by X1nto** [comment]
Send a logcat or something, I'm not all-seeing

**Comment by DraconicNEO** [comment]
Here is the logcat, I hope it's any good. (I used MatLog Libre) [logcat.txt](https://pastebin.com/LZqbjLHc)

**Comment by X1nto** [comment]
`MIUILOG- Install Reject uid: 10231 pkg : com.vanced.manager`

Now you understand why you should disable miui optimisations?

**Comment by DraconicNEO** [comment]
But it worked fine in the previous version, before the latest update, what's different between now and then?

**Comment by X1nto** [comment]
> But it worked fine in the previous version, before the latest update, what's different between now and then? 
> 
> Is there a way I get just get the split files from the cache and use SAI, it doesn't have this same issue.

Nothing, it's literally MIUI's fault. There were no changes in installer code

**Comment by DraconicNEO** [comment]
How can I manually download and install them with a different app (SAI does work on Miui).

**Comment by X1nto** [comment]
> How can I manually download and install them with a different app (SAI does work on Miui).

For god's sake SAI also requires you to disable MIUI optimizations unless you're on xiaomi.eu 20.0.2 ROM or higher

**Comment by DraconicNEO** [comment]
> > How can I manually download and install them with a different app (SAI does work on Miui).
> 
> For god's sake SAI also requires you to disable MIUI optimizations unless you're on xiaomi.eu 20.0.2 ROM or higher

But it's working on my device

**Comment by Crescendo-BLYAT** [comment]
@X1nto Since SAI (root mode) can install all the apks from non-root method of Vanced Manager just fine in MIUI without disabling **MIUI Optimization**.

How about offer root-mode installation of all apps in non-root menu ala SAI root-mode?

For some reason Youtube root installation always gone after reboot on Redmi Note 8 Pro - MIUI 12 - Android 10 & Poco F1 - MIUI 11 - Android 9.

**Comment by Crescendo-BLYAT** [comment]
> How can I manually download and install them with a different app (SAI does work on Miui).

SAI root mode?
I can confirm this, mine is MIUI 12.0.2.0 Global - Android 10, rooted using Magisk 20.4, SAI is working in **root mode**.

SAI normal mode **require disabling** MIUI Optimization like @X1nto said.

**Comment by X1nto** [comment]
> > How can I manually download and install them with a different app (SAI does work on Miui).
> 
> SAI root mode?
> I can confirm this, mine is MIUI 12.0.2.0 Global - Android 10, rooted using Magisk 20.4, SAI is working in **root mode**.
> 
> SAI normal mode **require disabling** MIUI Optimization like @X1nto said.

It doesn't require disabling Miui optimisations for Miui 12.0.2 and up, of we follow what SAI says, same for manager.

**Comment by Crescendo-BLYAT** [comment]
> > > How can I manually download and install them with a different app (SAI does work on Miui).
> > 
> > 
> > SAI root mode?
> > I can confirm this, mine is MIUI 12.0.2.0 Global - Android 10, rooted using Magisk 20.4, SAI is working in **root mode**.
> > SAI normal mode **require disabling** MIUI Optimization like @X1nto said.
> 
> It doesn't require disabling Miui optimisations for Miui 12.0.2 and up, of we follow what SAI says, same for manager.

Then maybe the possibility to install the non-root version with root?
Coz the root version that overwrite the factory one always gone on reboot.

Also I already disabled the app signature verification using Lucky Patcher.

**Comment by X1nto** [comment]
> > > > How can I manually download and install them with a different app (SAI does work on Miui).
> > > 
> > > 
> > > SAI root mode?
> > > I can confirm this, mine is MIUI 12.0.2.0 Global - Android 10, rooted using Magisk 20.4, SAI is working in **root mode**.
> > > SAI normal mode **require disabling** MIUI Optimization like @X1nto said.
> > 
> > It doesn't require disabling Miui optimisations for Miui 12.0.2 and up, of we follow what SAI says, same for manager.
> 
> Then maybe the possibility to install the non-root version with root?
> Coz the root version that overwrite the factory one always gone on reboot.
> 
> Also I already disabled the app signature verification using Lucky Patcher.

It's not possible due to the way root installer works
