### ISSUE TITLE
No way to switch to black.apk after downloading dark.apk

### ISSUE THREAD

**Issue by AndreiMiculita** [YTVanced/VancedManager#210]
**Phone Specifications:**
- Brand: Samsung Galaxy S9
- Operating System: Android
- Android Version: 10
- Vanced Manager Version: 0.2.12.203316

**Please describe the problem you are having in as much detail as possible:**
I downloaded and installed the dark.apk version of Vanced through the manager by mistake. I uninstalled it, and there is no way to switch to the black.apk version.

**Steps to reproduce:**
Tapping the "Install" button simply downloads the dark.apk version again.

**Further details:**
I've tried it multiple times.

**Comment by X1nto** [comment]
Settings > chosen installation values > reset > install vanced.

**Comment by AndreiMiculita** [comment]
Thank you!
