### ISSUE TITLE
App crashes when installing root Vanced

### ISSUE THREAD

**Issue by tgp1994** [YTVanced/VancedManager#211]
Using manager 1.3.1 on Phh Treble Android 9 (NOOK Tablet). When I try to install the root version, permission is granted and the downloads begin. After about 5 files download, the app just crashes back to my homescreen without any messages.

Edit: The non-root version installs just fine. Only the root version seems to be an issue.

**Comment by X1nto** [comment]
You're probably using a root binary that came with phh, only magisk is supported by manager's so consider patching boot.img with magisk

**Comment by tgp1994** [comment]
That is true, I don't use Magisk. I've looked into patching my boot.img several times but I don't believe that's an option for my device. It is unfortunate that Vanced Manager cannot work with other root solutions. Is there any particular reason it can't?

**Comment by X1nto** [comment]
> That is true, I don't use Magisk. I've looked into patching my boot.img several times but I don't believe that's an option for my device. It is unfortunate that Vanced Manager cannot work with other root solutions. Is there any particular reason it can't? 

Main reason is because other root solutions don't support running service.d scripts, which are required for root vanced to work properly

**Comment by tgp1994** [comment]
Understood, thank you for explaining it.
