### ISSUE TITLE
Non root with Lion-DPM in Qin 2 / Pro installation

### ISSUE THREAD

**Issue by hooddy** [YTVanced/VancedManager#213]
**Phone Specifications:**
- Brand: Qin 2 / Pro
- Operating System: Android 
- Android Version: 9
- Vanced Manager Version: 1.3.1 

**Please describe the problem you are having in as much detail as possible:**
My Qin 2 Pro with original non rooted fw have limits to install apk up to 12 (for common Qin 2 up to 6 apks). To avoid it I use Lion-DPM
https://github.com/dadaewq/Install-Lion-DPM
And its works well except Vanced Manager. Its dosnt detect Lion-DPM and trying to install microg and other related thing with default package installer even if Lion-DPM set as default. Please fix this issue.

**Steps to reproduce:**
Open Vance Manager and trying to install microg or Vanced.

**Further details:**
As workaround it would be fine to config download folder so I can install downloaded packages manually from it with Lion-DPM. And it would nice option to have in any way.

**Comment by X1nto** [comment]
We can't do anything about that, manager is installing packages using system's package manager, we won't and don't want to add support for another sketchy package manager
