### ISSUE TITLE
[Enhancement] Zoom to fill on any screen aspect ratios? 

### ISSUE THREAD

**Issue by Lord-Mendoza** [YTVanced/VancedManager#215]
For foldable phones or tablets with 4:3 aspect ratios the screen can't zoom in with a finger gesture, but works on other aspect ratios (ex. 16:9 with samsung phones).

I would be willing to look in the code to trying to implement this, but wanted to know if it's something that I **can** find in the code, or is this something Youtube turns on from the server-side?

**Comment by X1nto** [comment]
Not manager related
