### ISSUE TITLE
Missing language in the list of vanced download 

### ISSUE THREAD

**Issue by SiriosDev** [YTVanced/VancedManager#216]
**Phone Specifications:**
- Brand: Xiaomi
- Operating System: Miui 12
- Android Version: 10
- Vanced Manager Version: 1.3.1

**Please describe the problem you are having in as much detail as possible:**
In the list of languages for the download of ytvanced, Italian is missing, although on crowdin it is 100% complete

**Comment by X1nto** [comment]
Italian is not on the website, devs asked people who want their language to be added in the upcoming release, no one wanting italian showed up
