### ISSUE TITLE
Where is music apk url?

### ISSUE THREAD

**Issue by o700** [YTVanced/VancedManager#226]
I found Youtube vanced apks download url from sourcecode.
So I will share them.You can install them to zipping them and use SAI.
--Vanced--
https://vancedapp.com/api/v1/apks/v$vancedVersion/$variant/Arch/split_config.$arch.apk

https://vancedapp.com/api/v1/apks/v$vancedVersion/$variant/Language/split_config.$lang.apk

https://vancedapp.com/api/v1/apks/v$vancedVersion/$variant/$theme.apk
https://vancedapp.com/api/v1/apks/v$vancedVersion/$variant/stock.apk
https://vancedapp.com/api/v1/apks/v$vancedVersion/$variant/dpi.apk

arch:
x86
arm64_v8a

vancedVersion:
https://vancedapp.com/api/v1/versions.json

variant:
root
nonroot

lang:
https://vancedapp.com/api/v1/latest.json

theme:
dark
black

--MicroG--
https://github.com/YTVanced/VancedMicroG/releases/latest/download/microg.apk

After that i tried to extract music apk url from here. 
https://github.com/YTVanced/VancedManager/blob/dev/app/src/main/java/com/vanced/manager/core/downloader/MusicDownloader.kt
I thought it is in:
https://vancedapp.com/api/v1/music/stock/v$version/$arch.apk
and
https://vancedapp.com/api/v1/music/$variant/v$version.apk

,but server returns notfound.what does it wrong??

**Comment by X1nto** [comment]
Did you really think those are complete URLs? They're just template strings. For example `$variant` in the URL gets replaced with either root or nonroot depending on what user chose, `$arch` gets replaced with device architecture. I assume you blindly digged into code without knowing what any of those do.

**Comment by o700** [comment]
I know that ofcource.
https://vancedapp.com/api/v1/music/stock/v3.86.51/arm64_v8a.apk
It return 404 too.

**Comment by gghhkm** [comment]
> I know that ofcource.
> https://vancedapp.com/api/v1/music/stock/v3.86.51/arm64_v8a.apk
> It return 404 too.

That's because only the manager is allowed to access it 😐

**Comment by o700** [comment]
I think user is using vanced manager is using VancedManager or not isn't reason.
https://vancedapp.com/api/v1/apks/v15.43.32/nonroot/Arch/split_config.arm64_v8a.apk
Because that is accesible now and i can't find any code of setting useragent.
