### ISSUE TITLE
[#226 REOPENED]Where is music apk url?

### ISSUE THREAD

**Issue by o700** [YTVanced/VancedManager#227]
#226 My issue closed so I re opened.

**Comment by Ridley8819** [comment]
I can confirm this. Download fails (MicroG works fine) but installing music non root isn't possible. YT vanced download in root version worked fine too. There is no option to download Music in root version and non root version fails.

**Comment by gghhkm** [comment]
> I can confirm this. Download fails (MicroG works fine) but installing music non root isn't possible. YT vanced download in root version worked fine too. There is no option to download Music in root version and non root version fails.
> 
> ![Screenshot_20201109-162417__01](https://user-images.githubusercontent.com/6527637/98561278-0134ff80-22a9-11eb-92e1-8677ce7844f6.jpg)

That's a different issue.

**Comment by gghhkm** [comment]
> #226 My issue closed so I re opened.

https://vancedapp.com/api/v1/music/v4.02.51/nonroot.apk

**Comment by o700** [comment]
> > #226 My issue closed so I re opened.
> 
> https://vancedapp.com/api/v1/music/v4.02.51/nonroot.apk

Thanks so much!
