### ISSUE TITLE
Can't Download Vanced Music

### ISSUE THREAD

**Issue by NicTech-1989** [YTVanced/VancedManager#228]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: Samsung
- Operating System: Android
- Android Version: 7
- Vanced Manager Version: 1.3.1

**Please describe the problem you are having in as much detail as possible:**

Error Downloading Music when install is pressed

**Steps to reproduce:**

Same as above

**Further details:**

None

**Comment by MikMikYT** [comment]
I have the same issue as well, tried on sister's new Alcatel 1S 2020.
It does have YT Music preinstalled tho, so I thought maybe that is an issue.

**Comment by gghhkm** [comment]
The new website is https://vancedapp.com/

And here :
https://vancedapp.com/api/v1/music/v4.02.51/nonroot.apk

**Comment by X1nto** [comment]
please use the link posted by @gghhkm until issue is resolved

**Comment by alexis-evelyn** [comment]
Yep, the reason for it is the vanced.app website is gone. Not even the dns exists. From looking around the code, it appears that the update information was pulled from vanced.app. So, all that needs to happen is to just change the url to vancedapp.com for the future release of the app.

**Comment by abhishekabk5** [comment]
I have a question, if the issue is that the website was changed and now the metadata can't be pulled, then why isn't an issue for youtube vanced or microg installation?

**Comment by X1nto** [comment]
> I have a question, if the issue is that the website was changed and now the metadata can't be pulled, then why this isn't an issue for youtube vanced or microg installation?
> 

Because I fucked up the music url getter xD

**Comment by amritkrs** [comment]
Any idea by when this is going to be fixed?

**Comment by X1nto** [comment]
> Any idea by when this is going to be fixed?

We have some tiny bugs to fix until we release a new manager, can't give any ETAs but won't take too long

**Comment by mersimersi33** [comment]
@gghhkm Thank you TR

**Comment by mersimersi33** [comment]
> Yeni web sitesi https://vancedapp.com/
> 
> Ve burada:
> https://vancedapp.com/api/v1/music/v4.02.51/nonroot.apk

Thank you TR

**Comment by sunqb** [comment]
> > Yeni web sitesi https://vancedapp.com/
> > Ve burada:
> > https://vancedapp.com/api/v1/music/v4.02.51/nonroot.apk
> 
> Thank you TR

Thank you .

**Comment by amirulasyraf88** [comment]
Hi why still can't be download?

**Comment by sunqb** [comment]
> Hi why still can't be download?

https://vancedapp.com/api/v1/music/v4.02.51/nonroot.apk

**Comment by anburocky3** [comment]
Latest update?
