### ISSUE TITLE
Questions about READMEME.md

### ISSUE THREAD

**Issue by danthe1st** [YTVanced/VancedManager#23]
From the file `READMEME.MD`:
> Main Menu screenshot taken from tablet screenshot [![](https://camo.githubusercontent.com/1d4c0fc8809b1182b7c3096606b5e1be0082a097/68747470733a2f2f692e696d6775722e636f6d2f72326a6971374a2e706e67)](https://camo.githubusercontent.com/1d4c0fc8809b1182b7c3096606b5e1be0082a097/68747470733a2f2f692e696d6775722e636f6d2f72326a6971374a2e706e67)

It sais that the image is not available. Should it be removed or replaced with a new, available image?

> Ladies and gentlemen, I'm very proud to introduce the new **Vancad Manger 1.0.0™** (typo is intentional)

It sais that the typo is intentional but I cannot find the same typo anywhere else. Why is it nowhere else?

**Comment by X1nto** [comment]
M8 you need to work on your sense of humor
1. Actually image was there but it got deleted so I thought why not leave it as meme
2. Seriously?
