### ISSUE TITLE
v2.0.0 won't launch

### ISSUE THREAD

**Issue by unknownsoldierx** [YTVanced/VancedManager#238]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: Amazon Fire HD10 (suez)
- Operating System: FireOS
- Android Version: 5.6.8.0 (Android 5.1.1, API 22)
- Vanced Manager Version: 2.0.0

**Please describe the problem you are having in as much detail as possible:**
App won't start. Crashes when I tap the icon. Previous version worked.

**Comment by TRI99ERED** [comment]
Same.

**Comment by TheArgentinian** [comment]
Crashes as soon as I open the app. Android Marshmallow, Yoga Tab 3

**Comment by Lukasz-egg** [comment]
Crashes when trying to change theme of YouTube vanced, installing dont work, cant change vanced language, list is empty..... Cant change version, I installed version 2.0 beta (old beta) and works better....

**Comment by uncensoredtr** [comment]
Same problem vanced manager crashes during startup. I was using old version, got an update message and proceed to update.

**Comment by BennoMP** [comment]
Same issue, using Samsung Galaxy TabPRO 8.4 (SM-T320) on LineageOS 13 update 11-2018

**Comment by EL-S** [comment]
> Crashes when trying to change theme of YouTube vanced, installing dont work, cant change vanced language, list is empty..... Cant change version, I installed version 2.0 beta (old beta) and works better....

This is the exact same as what I experienced, I simply downgraded back to 1.3 for now.

**Comment by X1nto** [comment]
We found it it's caused by the layout file, sorry we didn't test it properly. A shot fix should be available soon

**Comment by truefriend-cz** [comment]
v.2.0
App now killed after running on Android 5.1.

Great job, the next version could launch a Russian missile straight away.
#148

**Comment by Cee123** [comment]
Same issue here, Android QBox running Android version 5.1.1. Just crashes upon launch.

**Comment by truongdaklak49** [comment]
App won't start. Crashes when I tap the icon. Previous version worked.
Brand: Oppo Neo 5
Operating System: Color OS
Android Version: 5.0
Vanced Manager Version: 2.0.0

**Comment by AdityaAdi1103** [comment]
Same here on android 6.0 1

**Comment by DanteKG** [comment]
@X1nto no rush, just asking: any approximate ETA of hotfix?

**Comment by X1nto** [comment]
> @X1nto no rush, just asking: any approximate ETA of hotfix?

It'll be released either today or tomorrow at max
