### ISSUE TITLE
Vanced Manager 2.0 crashes when trying to change version or theme

### ISSUE THREAD

**Issue by Itox001** [YTVanced/VancedManager#239]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: Samsung S10
- Operating System: Android
- Android Version: 10
- Vanced Manager Version: 2

**Please describe the problem you are having in as much detail as possible:**

Was messing around with the new manager when I saw the changelog that you could select versions, so I tried to do so.

I tapped the reinstall button for YT Vanced since I already have the latest version, and a menu to select theme, version and language showed up. Tapping on the arrow to expand version or theme instantly crashes the app. The language arrow works fine, but opens an empty list so nothing can be selected.

I also found that the vancedapp.com page is giving 502, so perhaps it's related.

Good job otherwise, the new manager looks nice :)

**Comment by X1nto** [comment]
Yeah it indeed is related with site being downz should be fixed in a short time

**Comment by X1nto** [comment]
Should be fixed now

**Comment by Itox001** [comment]
@X1nto you are correct, it is working as expected now. Perhaps handling for non-responding server is in order :)

**Comment by X1nto** [comment]
I'll close this now, feel free to reopen if this issue occurs to you again
