### ISSUE TITLE
New Vanced Manager Update

### ISSUE THREAD

**Issue by keatit71** [YTVanced/VancedManager#240]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: Samsung S8
- Operating System: Android
- Android Version: 9
- Vanced Manager Version: 2.0.0

**Please describe the problem you are having in as much detail as possible:**
Trying to change the options when reinstalling Youtube Vanced trying to change the theme crashes the app, trying to change version does nothing and just closes the installation dialogue and the language option shows blank dialogue. YouTube music doesn't crash the app when reinstalling but trying to change the version does nothing. Trying to reinstall microg just gives an error downloading it

**EDIT**
Seems like giving the app time to get working seems to have fixed the theme and language options but version does nothing still and updates and app versions are working now but either taking a long time or not downloading as its stuck on installing YouTube music now

**Steps to reproduce:**
- Open vanced manager
- try to reinstall any of the available apps
- try changing an option in the installation dialogue

**Further details:**
For every app available it just says Latest: Unavailable and is not detecting updates since in the old manager there was an update available for youtube music but nothing now.

**Comment by X1nto** [comment]
Should be fixed now
