### ISSUE TITLE
Version 2.0.0 does not retrieve latest version

### ISSUE THREAD

**Issue by TiberiumFusion** [YTVanced/VancedManager#242]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: Motorola Moto Z2 Force
- Operating System: Android
- Android Version: 7.1.1
- Vanced Manager Version: 2.0.0

**Please describe the problem you are having in as much detail as possible:**
The app does not display the latest version for Vanced and MicroG and instead says "Latest: Unavailable". This also occurrs in 1.3.1. Reading other issues here led me to believe it was due to the vanced.app -> vancedapp.com migration, which seemed like a dead simple fix that would be in 2.0.0, but alas the issue prevails. Swiping down to refresh brings up the refresh indicator, but it churns forever and doesn't seem to successfully refresh anything.
![Screenshot_20201113-133342](https://user-images.githubusercontent.com/6332277/99110027-ba504e00-25b7-11eb-9343-223963f330f4.png)

**Steps to reproduce:**
* Install 2.0.0 over 1.3.1
* Choose non-root mode during introducing wizard
* Start Vanced Manager
* Notice the "Latest: Unavailable" messages.
* Swipe down to refresh
* Notice the refresh indicator spins endlessly and nothing changes
* Restart Vanced Manager several times and get the same results

**Further details:**
Also of note, the landscape layout of the introduction wizard has problems. 
![Screenshot_20201113-133142](https://user-images.githubusercontent.com/6332277/99110064-c9cf9700-25b7-11eb-8632-1f5ca9b1ec08.png)
(also there's a typo in there, should be "fulfills")
Additionally, fwiw said introducing wizard is confusing for users with existing Vanced installs, since it does not explain what checking the boxes actually does and does not allow the user to continue without checking anything. I was worried it would blindly attempt to reinstall vanced without checking my current installation - and maybe it did indeed try that, but there's no way to tell since the manager couldn't connect to your server to download anything.

**Comment by gghhkm** [comment]
It's Vancedapp.com now for 1.

And to you have to wait for the server in your location to recover.

**Comment by hackel** [comment]
This also happened to me.  I got an upgrade notification, but when I clicked on it, nothing happened.  Then when I opened Vanced Manager, it behaved as you described.

I had to explicitly allow mirror.codebucket.de:443 in my firewall.  This appears to be where the version information is stored, which is redirected to from https://vancedapp.com/api/v1/latest.json

**Comment by Darkness4** [comment]
@TiberiumFusion. When I upgraded from 1.3.1 to 2.0.0, I had the same problem.

I fixed simply by deleting the data and the cache of the application. You can probably also manually uninstall and reinstall the app.

**Comment by LordMrcS** [comment]
> @TiberiumFusion. When I upgraded from 1.3.1 to 2.0.0, I had the same problem.
> 
> I fixed simply by deleting the data and the cache of the application. You can probably also manually uninstall and reinstall the app.
> 
> As @hackel said, it seems that the information is stored somewhere in the application data.

Thanks. This fixed for me.
