### ISSUE TITLE
Not working since new launcher

### ISSUE THREAD

**Issue by knightofdemons** [YTVanced/VancedManager#248]
Installed the new vanced launcher yesterday

Today
> Youtube Vanced got uninstalled (yes auto updates disabled etc)
> Took 4 installations until the Vanced version got installed (everytime before just the original Youtube app got installed, no signs of vanced under settings
> on the 4th i at least get the usual vanced changelog on the first startup but it still plays ads anyways

> cant go back to the version from yesterday

nice!

**Comment by gghhkm** [comment]
Have you tried this?
![Screenshot_20201114-093619](https://user-images.githubusercontent.com/72711094/99149578-f8ec1400-265c-11eb-999c-3925c1423409.jpg)
![Screenshot_20201114-093648](https://user-images.githubusercontent.com/72711094/99149581-fc7f9b00-265c-11eb-8bb2-f54769b254f3.jpg)

**Comment by knightofdemons** [comment]
Thanks, didnt notice that with all that stress this morning. Just hastley tried to reinstall it and was frustrated.
Can confirm its working with one version below but thats more of a problem with the vancedapp itself (but the version didnt update since yesterday).

The uninstalled vancedapp (overnight) was a little bit confusing, because i just installed the new version of vancedapp-manager and did nothing to the vancedapp installation.
