### ISSUE TITLE
Vanced youtube won't open links

### ISSUE THREAD

**Issue by ctgcwiqc** [YTVanced/VancedManager#249]
When a youtube link is provided in the app I am unable to clock the link to follow it.  Message says youtube can't follow this link. If I open the official youtube app the link works. Just doesn't work if attempted in vanced youtube.

**Comment by X1nto** [comment]
Not a manager related issue

**Comment by Luc45** [comment]
Same issue here. Related: https://www.google.com/url?q=https://www.reddit.com/r/Vanced/comments/d7s1oo/question_vanced_cant_open_url_links/

Even though it's not related, any tips to solve it?

**Comment by shahzad1811** [comment]
Youtube Vanced can't open URL this links (FIX) | how to fix Vanced youtube won't open links Samsung 

https://youtu.be/w7cIoVWLtrY

**Comment by shahzad1811** [comment]
> When a youtube link is provided in the app I am unable to clock the link to follow it. Message says youtube can't follow this link. If I open the official youtube app the link works. Just doesn't work if attempted in vanced youtube.

Youtube Vanced can't open URL this links (FIX) | how to fix Vanced youtube won't open links Samsung

https://youtu.be/w7cIoVWLtrY

**Comment by ctgcwiqc** [comment]
Wow I waited so long for this. The vanced app is now perfect!Thanks.

Sent from Yahoo Mail on Android 
 
  On Sun, Apr 11, 2021 at 6:54 AM, Shahzad ***@***.***> wrote:   



When a youtube link is provided in the app I am unable to clock the link to follow it. Message says youtube can't follow this link. If I open the official youtube app the link works. Just doesn't work if attempted in vanced youtube.


Youtube Vanced can't open URL this links (FIX) | how to fix Vanced youtube won't open links Samsung

https://youtu.be/w7cIoVWLtrY
