### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Ajayakkapelli** [YTVanced/VancedManager#25]
Hii, i want to use this app on my redmi note 5 pro (WHYRED) It's crashing and buggy i really like this app hope you'll fix the issues.

**Comment by X1nto** [comment]
First of all, we can't fix bug if we dont know how to reproduce it. Tell us what you did to crash the app, send a logcat and wait for response

**Comment by victor-bayas** [comment]
Mine isn't crashing but it never passes the splash screen
![Screenshot_20200701-074737_Vanced Manager](https://user-images.githubusercontent.com/49411169/86245588-4d3f9d00-bb6f-11ea-868f-80ebaeaadb6d.jpg)
Device: SM-G970F
OS: Android 10

**Comment by KevinX8** [comment]
Should be fixed in PR #40
