### ISSUE TITLE
Vanced Manger failed to launch on Android 6.0

### ISSUE THREAD

**Issue by khtan01** [YTVanced/VancedManager#255]
I have a secondary devices which is Samsung Galaxy J7 (2015) running on Android 6.0 Marshmelow, after I update to version 2.0, it can't launch anymore. It keep show "Unfortunately, Vanced Manager have stopped" message. My device isn't rooted.

**Comment by SubZero5** [comment]
Same issue happening on my secondary Samsung Galaxy Note 4 with Android 6.0.1 Marshmallow. Not rooted also.

**Comment by AnthraxBass** [comment]
Same here with android tv box Alfawise S92, android 6.0

**Comment by X1nto** [comment]
Duplicate of #244
