### ISSUE TITLE
I can't give root permission

### ISSUE THREAD

**Issue by Reaper0x1** [YTVanced/VancedManager#26]
Hi, I installed Vanced Manager app on my Pixel 2 XL, rooted with Magisk (version cd6eca1d 20415).
When I open it and I click the "root" button on top right, as soon as the prompt to grant root permission appears, it disappears immediately and the app freezes/crashes with a subsequent Android warning that it says "Vanced Manager is not responding".

Once closed and reopened, by clicking on the "root" button again the app says me "Root access not granted". So I went to see if I could grant root permission directly from Magisk Manager, but Vanced Manager doesn't appear in the list.
(I also tried to disable the Magisk Manager prompt and to grant root access to all the apps that require it, but nothing)

*plus the app stucks on boot logo for a while before I can see the gui

**Comment by X1nto** [comment]
Hi, issue is with latest magisk manager canary, stable magisk manager prompt works fine. The app load speed is optimised on every release, we will definitely adress app performance issue on some phones. Cheers
