### ISSUE TITLE
[ROOT] YT Music fails to install

### ISSUE THREAD

**Issue by DanteKG** [YTVanced/VancedManager#264]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: Samsung
- Operating System: Stock Android
- Android Version: 5.1.1
- Vanced Manager Version: 2.0.1

**Please describe the problem you are having in as much detail as possible:**
When I tap to install root variant of YT Music it downloads root.apk and the architecture apk (armeabi...) and proceeds to install it but fails almost immediately giving an unknown error. Advanced details in picture below.

**Steps to reproduce:**
Simply try to install root Music

**Further details:**
![Screenshot_2020-11-16-18-13-04](https://user-images.githubusercontent.com/688183/99286724-8f752c80-2839-11eb-81ac-f73f17ae2e5d.png)
![Screenshot_2020-11-16-18-13-10](https://user-images.githubusercontent.com/688183/99286747-98fe9480-2839-11eb-96f5-50e679dbe781.png)

**Comment by X1nto** [comment]
Are you using LineageSU by any chance?

**Comment by DanteKG** [comment]
Latest Magisk v21.1 and latest Magisk Manager v8.0.3

**Comment by X1nto** [comment]
I'll look into it

**Comment by DanteKG** [comment]
As it stands, others might also have this problem so I'll keep this open. But for me personally this isn't really a relevant issue since I cannot use root versions anyway due to reasons discussed earlier. I'll stick with the non-root version unless the signature spoofed version comes back as an option in the future

**Comment by Cee123** [comment]
I can confirm this also happens on my Amlogic QBox running Android 5.1.1. YouTube Music fails to install with the same error message. Even regular YouTube Vanced fails as it begins installing and says "please be patient" but nothing happens.

**Comment by zlight-in** [comment]
I also have this problem , 
Device: Lenovo K6 Power 
ROM : pixel experience , android 11

**Comment by X1nto** [comment]
> I can confirm this also happens on my Amlogic QBox running Android 5.1.1. YouTube Music fails to install with the same error message. Even regular YouTube Vanced fails as it begins installing and says "please be patient" but nothing happens. The only way I could fix it was by reverting back to the old version of the manager.
> 
> ![20201121_143627-20201122-084714874](https://user-images.githubusercontent.com/43462099/99890941-7e944300-2c9f-11eb-849b-d34c36bfb233.jpg)
> 
> ![20201121_143512-20201122-084714454](https://user-images.githubusercontent.com/43462099/99890942-8227ca00-2c9f-11eb-94c3-a2217959b6d6.jpg)

Only magisk is supported, whatever other root solution you're using is incompatible

**Comment by X1nto** [comment]
> I also have this problem ,
> Device: Lenovo K6 Power
> ROM : pixel experience , android 11

A logcat would be helpful

**Comment by calisamgal** [comment]
> As it stands, others might also have this problem so I'll keep this open. But for me personally this isn't really a relevant issue since I cannot use root versions anyway due to reasons discussed earlier. I'll stick with the non-root version unless the signature spoofed version comes back as an option in the future

Does anyone have the standalone for the non_root music only? Having trouble finding it.

**Comment by Cee123** [comment]
> > As it stands, others might also have this problem so I'll keep this open. But for me personally this isn't really a relevant issue since I cannot use root versions anyway due to reasons discussed earlier. I'll stick with the non-root version unless the signature spoofed version comes back as an option in the future
> 
> Does anyone have the standalone for the non_root music only? Having trouble finding it.

You mean the APK for YouTube Music? I have it. I can upload it here (if it's allowed) for other people having this issue.

**Comment by Cee123** [comment]
> Only magisk is supported, whatever other root solution you're using is incompatible

The same thing happens when i try to install the non root version through the manager.

**Comment by X1nto** [comment]
Will be fixed in the upcoming release: 56eec40dd3c07e78314300c1f3fe26287bb894c0

**Comment by X1nto** [comment]
fixed in 2.3.0

**Comment by Bradford1040** [comment]
Besides the server issue, thank you guy's so much for the new version! 16.02.35 and new 2.3 manager! There are people that remember that time is donated by many developers. It is appreciated!
