### ISSUE TITLE
Vanced Manager doesn't update

### ISSUE THREAD

**Issue by TRI99ERED** [YTVanced/VancedManager#265]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: LG Max X155
- Operating System: AOSP
- Android Version: 5.0.2
- Vanced Manager Version: 1.3.1

**Please describe the problem you are having in as much detail as possible:**
When I press update inside Vanced Manager, it doesn't do so, instead it shows message "e.e.a@...". After '@' there are random 7 characters. They change every time I press Update.

**Steps to reproduce:**
1. Open Vanced Manager 1.3.1
2. It should show, that an Update is available
3. Press Update

Alternative:
1. Open Vanced Manager 1.3.1
2. Open Settings
3. Check for Updates
4. It should show, that an Update is available
5. Press Update

**Comment by Pentaphon** [comment]
Install 2.0.1. Your issue is probably fixed now.

**Comment by TRI99ERED** [comment]
I had to manually reinstall Vanced Manager to version 2.0.1. I suspect the issue was with version 1.3.1 referencing old website (vanced.app) for download links.

**Comment by X1nto** [comment]
> I had to manually reinstall Vanced Manager to version 2.0.1. I suspect the issue was with version 1.3.1 referencing old website (vanced.app) for download links.

Manager doesn't download updates from vanced.app

**Comment by TRI99ERED** [comment]
It was solved anyway, because Manager 1.3.1 didn't download anything at that point.
