### ISSUE TITLE
[Question] License issue

### ISSUE THREAD

**Issue by mbnoimi** [YTVanced/VancedManager#266]
Hi,

I can see that Vanced Manager's has an open source license but what about YouTube Vanced's license? 
Does it open source?

**Comment by X1nto** [comment]
Vanced isn't open source as it doesn't have any source code. Vanced is made by reverse engineering original youtube apk and injecting smali code into it

**Comment by mbnoimi** [comment]
That's really sad. I'll keep with [Newpipe](https://github.com/TeamNewPipe/NewPipe) which has the same features as YouTube Vanced in addition to the safe open source code.

**Comment by Oizaro** [comment]
@mbnoimi There's a little mistake in your sentence. NewPipe doesn't have the exactly same features of Vanced:

- Doesn't have login.
- Doesn't have an advanced video searching (like stock Youtube client).
- Doesn't have nested comments.
- Doesn't have SponsorBlock.

👍👍👍

**Comment by mbnoimi** [comment]
@Oizaro I don't care about all of these features because the most important feature are already available in NewPipe.
I'll never trust YouTube Vanced because I don't know what YouTube Vanced does in my phone!
YouTube Vanced is a closed source product which means it's far from a safe app unless it will be open source one!

**Comment by Oizaro** [comment]
> @Oizaro I don't care about all of these features because the most important feature are already available in NewPipe.
> I'll never trust YouTube Vanced because I don't know what YouTube Vanced does in my phone!
> YouTube Vanced is a closed source product which means it's far from a safe app unless it will be open source one!

I'm not saying what you should use or not, you are free to do what you want, but at least don't post inaccurate informations like these:

"...has the same features as YouTube Vanced"

And don't try to defend yourself by saying you don't care of them, because something doesn't exists or not based on what interests you.

**Comment by AinzTheSupremeOne** [comment]
> I'll never trust YouTube Vanced because I don't know what YouTube Vanced does in my phone!

If you are that worried about security and privacy,why don't you just decompile the APK and look at the code?

> YouTube Vanced is a closed source product which means it's far from a safe app unless it will be open source one!

Do you even know what open source is? STOCK YOUTUBE IS FUCKING NOT OPEN SOURCE. Why do you even expect its mod to be open source LMAO. Ask Google to make YouTube open source then Vanced would also be open source. If we follow your logic then every closed source app is not safe :kek:

 And FYI, YT Vanced uses Vanced microG to login and it is open source because the original microG is open source. And of course to clear any doubts/foolishness of karens.

**Comment by mbnoimi** [comment]
> If you are that worried about security and privacy,why don't you just decompile the APK and look at the code?

Why I need to decompile the APK and look into the code if it's not originally opened?!

> Do you even know what open source is? STOCK YOUTUBE IS FUCKING NOT OPEN SOURCE.

It seems you don't know what you're talking about. I DON'T USING THE FUCKING YOUTUBE dump ass!

> Why do you even expect its mod to be open source

Because some people want to steal data yo smart one!

> Ask Google to make YouTube open source then Vanced would also be open source

What a smart logic!!!
We don't need to use any alternative app for bypassing the ads if Google opened the source of YouTube!

> And of course to clear any doubts/foolishness of karens who think that they are signing in on a shady app

Yo Karen; read my comments and learn... hheheh what a smart ass.

**Comment by X1nto** [comment]
> That's really sad. I'll keep with [Newpipe](https://github.com/TeamNewPipe/NewPipe) which has the same features as YouTube Vanced in addition to the safe open source code.

Feel free to use whatever you want

**Comment by mbnoimi** [comment]
> Feel free to use whatever you want

Thanks

**Comment by Toshiba1127** [comment]
I have been using both Vanced for watching and NewPipe for downloading and they are working fine so far, no any harm on my phone.

Open source is not safe either, as they can put additional closed codes on compile they want anytime. And I don't trust anti-virus either that probably makes you believe all modded APKs are unsafe :P

**Comment by robbyoconnor** [comment]
If you don't trust it, you can always reverse engineer and audit it. That is always an option.
