### ISSUE TITLE
Vanced manager 2.0.1 installs standard yt app (with ads)

### ISSUE THREAD

**Issue by 777shibby** [YTVanced/VancedManager#268]
manager installs standard? yt app (with ads and impossible to enter "vanced settings"-> sends me to yt start screen every time)

vanced manager 2.0.1 from vancedapp.com  (I like the new design/functionality!) 
OnePlusOne 2
Android 6.1
OxygenOS 3.6.1
root - dark - english/german - latest

**Comment by X1nto** [comment]
#197
