### ISSUE TITLE
YT Music cannot login

### ISSUE THREAD

**Issue by aidilaryanto** [YTVanced/VancedManager#269]
![Screenshot_20201117-195434754](https://user-images.githubusercontent.com/57789597/99387348-ca955f80-290e-11eb-998f-4c77300c0bdc.jpg)
My google account not appear on YT Music, so I can't login into YT Music

**Comment by AinzTheSupremeOne** [comment]
Root version or non root? If you are using non root then you would need microG

**Comment by X1nto** [comment]
Not a manager related issue
