### ISSUE TITLE
Error Downloading dark.apk

### ISSUE THREAD

**Issue by egorshulga** [YTVanced/VancedManager#270]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: Honor 4C pro
- Operating System: Viper OS 3.1.1
- Android Version: 7.1.2
- Vanced Manager Version: 2.0.1

**Please describe the problem you are having in as much detail as possible:**
When I try to install YouTube Vanced via Vanced Manager, following modal opens (note `Error Downloading dark.apk`):
![image](https://user-images.githubusercontent.com/6253488/99506075-b2672400-2992-11eb-91cd-beda263eb50e.png)

**Steps to reproduce:**
1. Open Manager
2. Tap YouTube Vanced -> Install
3. Tap Install in the Installation Preferences Modal

**Comment by X1nto** [comment]
Clear manager data and try again

**Comment by egorshulga** [comment]
Oh, yeah, didn't try this one, and it worked. Thanks!
