### ISSUE TITLE
"Reinstall" Vanced only installs one APK

### ISSUE THREAD

**Issue by Toshiba1127** [YTVanced/VancedManager#271]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: Sony
- Operating System: Android (stock firmware)
- Android Version: 9
- Vanced Manager Version: 2.0.1

**Please describe the problem you are having in as much detail as possible:**
If Vanced root is installed, semi-removed by reboot or not, Manager will not fully download and install all APKs and only install black.apk. This is really annoying because we would need to uninstall and install again in order to fully install all APKs, which clears all data. This also happened on 1.3.1

I don't mind reinstalling every reboot but reinstall should install all APKs, not one

**Steps to reproduce:**
1. Grant magisk root permission for Manager
2. Install Vanced root version
3. Reinstall Vanced root version

**Comment by X1nto** [comment]
It doesn't reinstall one apk, it checks if you already have stock yt/vanced with the same version as latest vanced and just downloads dark/black apk and then mounts it to stock apk, this is for saving data

**Comment by X1nto** [comment]
Disappearing issue is related to #212

**Comment by Toshiba1127** [comment]
Oh ok, wait... I can use Titanium backup app for backing up my data
