### ISSUE TITLE
​Problems related to Japanese localization

### ISSUE THREAD

**Issue by xyzzy-foo** [YTVanced/VancedManager#274]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: Google Pixel 3
- Operating System: Stock Android
- Android Version: 11
- Vanced Manager Version: 2.0.1

**Please describe the problem you are having in as much detail as possible:**
​The AdGuard link displays the resource "Brave をダウンロードして支援する" (Download Brave to help).

**Steps to reproduce:**
Setting the Vanced Manager to Japanese

**Further details:**
![Screenshot_20201119-170420](https://user-images.githubusercontent.com/11955198/99638340-69de6200-2a89-11eb-9158-91dfa09e3da3.png)

**Comment by AinzTheSupremeOne** [comment]
Found the issue. https://crowdin.com/translate/vanced-manager/114/en-ja?filter=basic&value=3#25028 Kevin auto translated the string using a bot and approved it I am assuming. Anyway I believe I have fixed it. Feel free to suggest a different translation. I am not a native speaker of Japanese. The change would be shown in the next update.

**Comment by X1nto** [comment]
Should be fixed in new version
