### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by haritvsmurali** [YTVanced/VancedManager#275]
Swipe to Seek feature : 
Swipe Horizontally above time bar to move video time forward or backward.

Download Videos Offline : 
Option to download videos as Video and Audio in local player formats. (Video - 480,720,1080p MP4, MKV etc., Audio - 320kbps MP3, M4A etc.,)

**Comment by gghhkm** [comment]
> Download Videos Offline :
> Option to download videos as Video and Audio in local player formats. (Video - 480,720,1080p MP4, MKV etc., Audio - 320kbps MP3, M4A etc.,)

[Denied]
You want Vanced to be closed down or something?
That in violation of the Digital Millennium Copyright Act (DMCA).

**Comment by haritvsmurali** [comment]
Unaware of it. 

Swipe to Seek feature :
Swipe Horizontally above time bar to move video time forward or backward.

**Comment by X1nto** [comment]
Not a manager related issue
