### ISSUE TITLE
Unable to login with google account

### ISSUE THREAD

**Issue by mohit7189** [YTVanced/VancedManager#276]
For Samsung Note 10plus unable to login in youtube vanced for google accounts tried changing network connection reinstalling and updating app.
![Screenshot_20201121-073945_Vanced microG](https://user-images.githubusercontent.com/13028676/99865030-03faf300-2bcd-11eb-9b10-139e2f572e1c.jpg)
![Screenshot_20201121-073935](https://user-images.githubusercontent.com/13028676/99865033-065d4d00-2bcd-11eb-9677-f896c1d08f7d.jpg)

**Comment by Antoni-Czaplicki** [comment]
I have the same problem

**Comment by X1nto** [comment]
Not a manager related issue

**Comment by nightznero** [comment]
Same issue

**Comment by gghhkm** [comment]
> Same issue for samsung s10

Pls refrain from posting and commenting on non Vanced Manager related issues in this repo.

Pls refer to https://github.com/YTVanced/Vanced
