### ISSUE TITLE
[Idea] feature analogous to chrome extension that BLOCKS RECOMMENDATIONS

### ISSUE THREAD

**Issue by ashudva** [YTVanced/VancedManager#278]
Is it possible to have a feature where you could just turn of all the recommendation that you see when you open up YouTube. A lot of the time when we open YouTube just to watch a video that we intend to and instead we end binge watching for whole night. Also those cards beneath the playing video are so alluring that I sometimes feel like clicking them has become my instinct. This feature might just make YouTube a whole lot productive rather than a time sucking technology. Please look into it and provide some feedback.

**Comment by X1nto** [comment]
Not a manager related issue
