### ISSUE TITLE
App crashes/freezes instantly

### ISSUE THREAD

**Issue by Luis-L-B** [YTVanced/VancedManager#28]
Hey,
Whenever I try to open the app it crashes or gets stuck at the logo. I hope my log file helps.
My device specs:
Xiaomi Mi 9t Pro 6/128GB
Bootloader unlocked.
Rooted using Magisk
Android 10 
Evolution X 4.3
Kernel 4.14
[vanced_manager.log](https://github.com/YTVanced/VancedManager/files/4857148/vanced_manager.log)

**Comment by X1nto** [comment]
Hi, looks like app can't get data from vanced.app, can you access the website?

**Comment by Luis-L-B** [comment]
Oh, Im so stupid... I didnt made a rule for Vanced Manager on AFWall, therefore it couldnt connect... It works now. Looks like a great app btw.

**Comment by X1nto** [comment]
Thanks for reporting, we'll try to add exception handling so the crash won't appear anymore, cheers
