### ISSUE TITLE
Unable to download: Latest version: Unavailable

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [YTVanced/VancedManager#281]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server (❌**NO**, But vancedapp.com)
- I am using the latest version (reinstalled from vancedapp.com)
- This is an issue in the Vanced Manager app (NOT Youtube Vanced) ✅
- This issue keeps re-occurring every time I try ✅
- For MIUI users: I disabled MIUI optimisation ✅
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: Poco (Xiaomi)
- Operating System: MIUI global 12.0.2
- Android Version: 10 QKQ1.190828002
- Vanced Manager Version: 2.0.1 (Android5and6suck)

**Please describe the problem you are having in as much detail as possible:**

**Steps to reproduce:**
Open the vanced manager app

**Further details:**
It says unavailable (I am not using English, so maybe translation error when telling the case) next to the latest version on all the apps available. Already reinstalled from vancedapp.com while disabling MIUI optimisation.

**Comment by X1nto** [comment]
Clear manager data

**Comment by SodaWithoutSparkles** [comment]
> Clear manager data

Still the same

**Comment by X1nto** [comment]
Do you have a firewall that may be blocking connection for manager?

**Comment by oxk4r01** [comment]
Same here. No firewall.

**Comment by BobbyWibowo** [comment]
Can confirm that force stopping the app prior to clearing its storage and cache fixed it on my end.

**Comment by AU-Linsanity** [comment]
> Can confirm that force stopping the app prior to clearing its storage and cache fixed it on my end.

This sentence is hard...

**Comment by DefiantCatgirl** [comment]
Same, Xperia 1, Android 10, no proxy, no firewalls, no adblockers. "Latest: Unavailable" and "Error Downloading microG" when trying to install it.

Logcat doesn't say much, just this:

```
12-10 22:47:50.309 31601 31601 D VMLocalisation: Failed to load data: java.lang.Throwable: Network operation failed 403
```

**Comment by HerrRuin** [comment]
Same here. Android 10. Oxygen OS. Oneplus, no proxy, no firewalls.
"Latest: Unavailable" and "Error Downloading" 
Manager get no internet connection. :(

**Comment by thepcwiz101** [comment]
in response to the logcat post it clearly states "network operation failed" which means the server is down.

**Comment by DefiantCatgirl** [comment]
It's just odd because from the code it appears that it's something to do with loading translations rather than loading the applications and their metadata. But there was nothing more, just that and some Firebase events logging.

**Comment by X1nto** [comment]
It's fixed

**Comment by kobor42** [comment]
> It's fixed

How is it fixed? I deleted everything vanced related, then downloaded latest version, and it's still bad!

**Comment by monyarm** [comment]
Same here, I force closed it, i deleted the cache and storage, and it still gives the same issue,

**Comment by Kazlehoff** [comment]
I'd like to report the same issue. Latest version of Android. Pixel 4a. force stopped app, cleared cache, issue still occurring. Latest: Unavailable for Vanced and MicroG. Manager could not even see that it had an update for its self, had to come here to download manually. after that, still unavailable for new versions of vanced.

**Comment by X1nto** [comment]
website is down, wait for it to get up

**Comment by GarnetSunset** [comment]
Thanks for your great work X1into

**Comment by d4rky-pl** [comment]
It may be a good idea to add an info that says the website is down in the app when the vancedapp.com does not respond, I guess everyone clicked on that push notification you guys sent 😛

**Comment by ToxiClay** [comment]
Having the same problem. vancedapp website is up, force-stopped Vanced Manager, deleted cache, deleted data...nothing.

Why does this happen, and why can't it be solved?

**Comment by GarnetSunset** [comment]
Imagine if 10000 people tried to walk through your front door at the same time
There you go there's your answer

**Comment by ch3mn3y** [comment]
Same problem in 2.6.0 on Note10+ with latest stock. AdBlock disabled, apps removed, cannot reinstall anything from withing Manager...
