### ISSUE TITLE
Please check the network connection! 

### ISSUE THREAD

**Issue by Volgame** [YTVanced/VancedManager#282]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation

**Phone Specifications:**
- Brand:
- Operating System: 
- Android Version:
- Vanced Manager Version:

**Please describe the problem you are having in as much detail as possible:**

**Steps to reproduce:**

**Further details:**
Meizu note 8
Android 8.1. 0
App is Last version 
I get a 'no internet' error even though I have internet

**Comment by X1nto** [comment]
Not a manager related issue
