### ISSUE TITLE
[Feature Request] Restore Miniplayer restrictions

### ISSUE THREAD

**Issue by Msouza91** [YTVanced/VancedManager#295]
Considering the whole COPPA Dumpster Fire and the childish response from Google, could you guys look into if it is feasible to restore the functionality taken from us by the way they are addresing the problem.

Here is the list of features that have been reported as borked from a quick search: 

Autoplay on home
Cards or end screens
Channel branding watermark
Channel Memberships
Channel Posts
Channel Stories
Comments
Donate button
Likes and dislikes on YouTube Music
Live chat or live chat donations
Merchandise and ticketing
Miniplayer playback
Notification bell
Personalized advertising
Super Chat or Super Stickers
Save to playlist and Save to watch later

**Comment by X1nto** [comment]
Not a manager related issue
