### ISSUE TITLE
[ROOT] YouTube Music disappearing upon system reboot

### ISSUE THREAD

**Issue by crazyuploader** [YTVanced/VancedManager#296]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation

**Phone Specifications:**
- Brand: Redmi Note 5 Pro
- Operating System: Havoc OS 3.11
- Android Version: 10
- Vanced Manager Version: 2.0.1

**Please describe the problem you are having in as much detail as possible:**

I've installed YouTube Music (by root method), and it's installed without a problem, runs well too but as soon as I reboot my phone, it's gone. And Vanced Manager shows "unavailable", have to install YouTube Music again and the process goes on.

**Steps to reproduce:**

1. Install Vanced Manager App
2. Install YouTube Music (by root method)
3. Finally, restart.

**Further details:**

Attaching an screenshot after a system reboot.

![Screenshot_20201129-083752](https://user-images.githubusercontent.com/49350241/100530949-6e8bde80-321e-11eb-9356-76d9448a21cf.jpg)

**Comment by X1nto** [comment]
#212
