### ISSUE TITLE
YouTube Vanced Story Problem

### ISSUE THREAD

**Issue by GalaxyLinus** [YTVanced/VancedManager#299]
Hi, I have a problem where stories always glitch out after a few Stories
![Screenshot_20201129_214936](https://user-images.githubusercontent.com/57060126/100553236-10e2ab00-328d-11eb-9eaa-9db7450d84ec.jpg)
![Screenshot_20201129_214934~2](https://user-images.githubusercontent.com/57060126/100553238-1213d800-328d-11eb-9290-1ae0138a21e3.jpg)

**Comment by X1nto** [comment]
Not a manager related issue

**Comment by GalaxyLinus** [comment]
Where am I allowed to report this problem?

**Comment by X1nto** [comment]
> Where am I allowed to report this problem?

https://github.com/YTVanced/Vanced
