### ISSUE TITLE
YT Music & Android Auto

### ISSUE THREAD

**Issue by ismailiabderrahim** [YTVanced/VancedManager#300]
YT Music on Android Auto media is not working 
we still can hear voice trough usb on the car speakers but without being able to control any thing from the car

**Comment by X1nto** [comment]
We don't accept yt music reports and this is not a manager related issue

**Comment by ismailiabderrahim** [comment]
sorry
I'm new in this project
I'll post this in vanced section

**Comment by X1nto** [comment]
> sorry
> I'm new in this project
> I'll post this in vanced section

Didn't I say we don't accept yt music reports?
