### ISSUE TITLE
Google Play Destroying The Installation

### ISSUE THREAD

**Issue by david-lev** [YTVanced/VancedManager#303]
I'm using the latest version of Vanced Manager And there's a bug in the installation with Root permission: Because the app is installed with the same official YouTube PackageName, you need to disable youtube's automatic updating via Google Play. Otherwise every update - the app is out of use. 

I recently noticed that even after you turn off automatic updating, if you're in a country where you speak a language (Regardless of device language) other than the language you chose when you download YouTube Vanced, After a certain time Google Play will try to download the language file (config.XX.apk) automatically, Thereby destroying the installation of the app. 

I don't know what you can do about this problem but I thought I'd let you know it exists.

Device Details:
- Samsung Galaxy S9+
- Android 10
- Rooted | Magisk
- Vanced Manager V2.0.1
- YouTube Vanced V15.43.32

**Comment by X1nto** [comment]
And how is this related to manager?

**Comment by david-lev** [comment]
> And how is this related to manager?

Perhaps google play's update to apps installed through Vanced Manager can be blocked in some way.

**Comment by X1nto** [comment]
> > And how is this related to manager?
> 
> Perhaps google play's update to apps installed through Vanced Manager can be blocked in some way. 

there is no way to do that
