### ISSUE TITLE
Vanced music sends notification even though it's disabled.

### ISSUE THREAD

**Issue by frenchiveruti** [YTVanced/VancedManager#308]
Sorry I didn't make a screen shot of the issue but I got a notified today saying there was an update for VMusic and I have the setting disabled in VancedManager.
Just reporting it as is, sorry for not following any template

**Comment by X1nto** [comment]
We'll look into the issue

**Comment by thepcwiz101** [comment]
Did you update the manager in recent weeks after disabling vanced music? If so an update may have reenabled the settings. If not this is a confirmed bug i have experienced as well.

**Comment by TheArgentinian** [comment]
I got the update notification too but there's no update.

**Comment by frenchiveruti** [comment]
> 
> 
> Did you update the manager in recent weeks after disabling vanced music notifications? If so an update may have reenabled the settings. If not this is a confirmed bug i have experienced as well.

Yes that's probably the culprit, I had it disabled, updated, the setting displayed as "off" but maybe underlying was as "on".

**Comment by X1nto** [comment]
Should be fixed in the new release, reopen issue if you still encounter it
