### ISSUE TITLE
Versionz are unavailable and cannot be downloaded

### ISSUE THREAD

**Issue by gotexis** [YTVanced/VancedManager#310]
![Screenshot_2020-12-14-23-34-03-030_com.vanced.manager.jpg](https://user-images.githubusercontent.com/38595828/102081786-e552e980-3e64-11eb-8956-5bd8cf885b88.jpg)

![Screenshot_2020-12-14-23-34-51-235_com.vanced.manager.jpg](https://user-images.githubusercontent.com/38595828/102081831-fac81380-3e64-11eb-9cd0-8316f9fbceb2.jpg)

**Comment by Switch123456789** [comment]
It wasn't working for me either, but just in this moment it is working again. I guess it was a server issue since the vanced website also was down for a few minutes.

**Comment by AloVillain** [comment]
Same thing happening with me, I'm non-root btw. Uninstalled and tried to reinstall and Im stuck with the same screen

**Comment by Switch123456789** [comment]
I just finished a complete download and install of microg and ytvanced. Seems fine again (on my end).

**Comment by AloVillain** [comment]
![Screenshot_20201214-050447_Vanced Manager](https://user-images.githubusercontent.com/75987094/102084151-95731480-3dc9-11eb-9858-534d0f8221b8.jpg)

**Comment by X1nto** [comment]
Basically google servers are down is it's really not our problem
