### ISSUE TITLE
Vanced Music failed to login

### ISSUE THREAD

**Issue by vipinkumar1710** [YTVanced/VancedManager#312]
**Phone Specifications:**
- Brand: Asus(X00TD)
- Operating System: Android(RROS 8.6.4)
- Android Version: 10
- Vanced Manager Version: 2.0.1

**Please describe the problem you are having in as much detail as possible:**
I'm on latest Youtube vanced(15.43.32) and Youtube Music(4.07.51) on root varient. After installation and login from google account, both works fine but after reboot(device) youtube music starts crashing.
I tried after clearing app data, its opened but can't sign in(also tried to add google account again but worth
![WhatsApp Image 2020-12-16 at 12 58 13 PM](https://user-images.githubusercontent.com/42378111/102351878-10415880-3f9f-11eb-9b21-31a4f6eb8f30.jpeg)
less).

**Comment by X1nto** [comment]
Not a manager related issue
