### ISSUE TITLE
Crash on MEIZU M5 note

### ISSUE THREAD

**Issue by Timperr** [YTVanced/VancedManager#313]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation

**Phone Specifications:**
- Brand: MEIZU
- Operating System: Flyme 7.1.0.0 G
- Android Version: 7
- Vanced Manager Version: 2.0.1

**Please describe the problem you are having in as much detail as possible:**
Maneger is crushing when i try to install youtube (phone is rooted). It downloads all apk packages and for a second appears icon "please wait", then app just closes... Nothing happening later (app don't installs) (all premitions that possible are given). When i try to install Music, it installs the app but not vanced, and appers "please wait", app don't closes, i can't press "deny".

**Steps to reproduce:**
Just launch app. Issue is permanent.

**Further details:**
bussybox installed, using standart root maneger builtin in flyme

**Comment by X1nto** [comment]
Use magisk, other root solutions are not supported
