### ISSUE TITLE
Progress bar flickering

### ISSUE THREAD

**Issue by 1alessandro1** [YTVanced/VancedManager#314]
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- Am I using the latest version: Yes
- This is an issue in the Vanced Manager app (NOT Youtube Vanced): Yes
- This issue keeps re-occurring every time I try: Yes
- ~~For MIUI users~~: I disabled MIUI optimisation (i do not have MIUI)

**Phone Specifications:**
- Brand: Xiaomi Redmi note 5
- Operating System: crDroid 6.12
- Android Version: 10
- Vanced Manager Version: 2.0.1

**Please describe the problem you are having in as much detail as possible:**
The progress bar (when vancedmanager downloads the apk) flickers when the screen is horizontal

**Steps to reproduce:**
Download an update when the screen is horizontal

**Further details:**
None

**Comment by X1nto** [comment]
App is now locked to portrait

**Comment by dronewizard** [comment]
I never remember experiencing this issue and it was so much better to have the horizontal layout as that's what I used 100% of the time. People with big tablets understand.

**Comment by X1nto** [comment]
> I never remember experiencing this issue and it was so much better to have the horizontal layout as that's what I used 100% of the time. People with big tablets understand, especially those who use them with attached physical keyboards.

Us locking the app to portrait is unrelated to this issue, we locked it for other reasons that are way harder to fix
