### ISSUE TITLE
Crashing when install

### ISSUE THREAD

**Issue by VuHongQuang-VN** [YTVanced/VancedManager#32]
![Screenshot_20200701-214102_Pixel Launcher](https://user-images.githubusercontent.com/67698443/86257385-a812dc00-bbe3-11ea-9d73-e2f462e8edf2.jpg)
![Screenshot_20200701-214119_Vanced Manager](https://user-images.githubusercontent.com/67698443/86257392-aa753600-bbe3-11ea-81c2-c282ba2d313a.jpg)
It's keep crashing when i try to install it
My device: SM-A205F/DS
Android: 9
Rooted: Yes
Logcat: https://drive.google.com/file/d/10FxliLZEJHALGlBPtQv4eOj6kmXA-KTZ/view?usp=drivesdk

**Comment by X1nto** [comment]
Thanks for reporting. Looks like we missed one attribute in XML. Will be fixed in next update

**Comment by KevinX8** [comment]
Fixed in PR #40
