### ISSUE TITLE
[ROOT] YouTube Vanced still disappears after rebooting the phone

### ISSUE THREAD

**Issue by soredake** [YTVanced/VancedManager#322]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation

**Phone Specifications:**
- Brand: Xiaomi Redmi Note 5 Pro
- Operating System: CrDroid 6.12
- Android Version: Android 10
- Vanced Manager Version: 2.1.0

**Please describe the problem you are having in as much detail as possible:**

1. Installed Vanced Manager
2. Granted Root Permissions to the app
3. Installed YouTube Vanced (Russian Dark version) from Vanced Manager (ROOT section)
4. Rebooted the phone

After following the above steps, YouTube Vanced app disappears and I have to reinstall it.

**Comment by zheka006** [comment]
same

**Comment by X1nto** [comment]
Typing "same" doesn't solve anything, so don't junk up this thread

**Comment by soredake** [comment]
After installing youtube vanced from manager and before rebooting i see two folders, one filled with apks (correctly installed youtube), and one folder only with base.apk
![photo_2020-12-19_20-42-01](https://user-images.githubusercontent.com/5204968/102696932-a80ea300-423a-11eb-9933-c869473c0f29.jpg)
After rebooting i see only second folder
![photo_2020-12-19_20-41-56](https://user-images.githubusercontent.com/5204968/102696962-e2784000-423a-11eb-93ab-631653d69178.jpg)

**Comment by gghhkm** [comment]
> After installing youtube vanced from manager and before rebooting i see two folders, one filled with apks (correctly installed youtube), and one folder only with base.apk
> ![photo_2020-12-19_20-42-01](https://user-images.githubusercontent.com/5204968/102696932-a80ea300-423a-11eb-9933-c869473c0f29.jpg)
> After rebooting i see only second folder
> ![photo_2020-12-19_20-41-56](https://user-images.githubusercontent.com/5204968/102696962-e2784000-423a-11eb-93ab-631653d69178.jpg)

Remove data/adb/Vanced
That'll remove that.

**Comment by Vyto-Khron** [comment]
Fixed the issue by removing the redundant folders (vanced music or yt) in /data/app.

The following steps were enough:
1. Uninstall yt or music (if not system apps)
2. Reboot
Ta-daa! No more duplicate folders

Alternatively, if you already have Vanced installed and working **and have not rebooted yet**
1. Open `/data/adb/service.d/vanced.sh` or `music.sh` (as appropriate) using a text editor
2. In the last line of code, replace the "string of characters ending with ==" with the path to the correct folder 
 E.g in the case of YT Vanced replace the string portion in the line `/data/app/com.google.android.youtube{part to be replaced}`
3. Reboot 

Otherwise, if you have rebooted and Vanced has been removed, you can also follow what u/gghhkm said above this comment.
1. Delete `/data/adb/Vanced`
2. Reboot
3. Re-install from Manager

**Comment by X1nto** [comment]
I would recommend doing following:
- uninstall current Vanced and Music apps
- go to /data/adb using a file explorer and delete following folders: Vanced (if you have it), Music (if you have it), service.d and post-fs-data.d
- reboot your device
- install apps again from manager
See if this works

**Comment by gghhkm** [comment]
> I would recommend doing following:
> 
> * uninstall current Vanced and Music apps
> * go to /data/adb using a file explorer and delete following folders: Vanced (if you have it), Music (if you have it), service.d and post-fs-data.d
> * reboot your device
> * install apps again from manager
> 
> See if this works

Yeah that's the proper method to remove all of Root Vanced for a clean install.


Although if installing it the first time caused it to disappear after rebooting... After doing the above and reinstalling Vanced with the manager (2.1.0) you can try editing the scripts to add more sleep time.
Change ```do sleep 1; done``` to ```do sleep 2; done``` or higher than reboot, that could fix the uninstall after reboot problem. It still doesn't work for everyone but it does fix it for some.

**Comment by soredake** [comment]
> I would recommend doing following:
> - uninstall current Vanced and Music apps
> - go to /data/adb using a file explorer and delete following folders: Vanced (if you have it), Music (if you have it), service.d and post-fs-data.d
> - reboot your device
> - install apps again from manager
> 
> See if this works

Done this, plus changed sleep 1 -> 10, youtube disappeared.

**Comment by twu2** [comment]
> Done this, plus changed sleep 1 -> 10, youtube disappeared.

1. reboot, and uninstall regular youtube app
2. install vanced again from vanced manager
3. move /data/adb/service.d/vanced.sh to /data/adb/vanced.sh
4. reboot
5. regular youtube not exist => maybe some other reason
6. regular youtube exist, and execute it without any issue
7. execute /data/adb/vanced.sh with root shell
8. wait for a few seconds, execute youtube again, it should launch vanced version now

if this work, maybe your device need more time before mount vanced youtube apk.
just modify vanced.sh, insert a new sleep line between 'while' and 'mount' line like:
```
#!/system/bin/sh
while [ "`getprop sys.boot_completed | tr -d '\r' `" != "1" ]; do sleep 1; done
sleep 10
mount -o bind /data/adb/Vanced/base.apk /data/app/com.google.android.youtube-....
```

**Comment by soredake** [comment]
For some reason mount command in vanced.sh does not work when I'm execute it from termux, apk is unchanged
![Screenshot_20201222-101705808](https://user-images.githubusercontent.com/5204968/102865782-effe1780-443e-11eb-8d0a-5c6cae854dc0.jpg)

**Comment by udin453** [comment]
![Uploading Screenshot_2020-12-28-19-23-28-975_com.vanced.manager.png…]()

**Comment by gghhkm** [comment]
@udin453 you messed up the screen shot lmao.

**Comment by prathamesh610** [comment]
> Fixed the issue by removing the redundant folders (vanced music or yt) in /data/app.
> 
> The following steps were enough:
> 
>     1. Uninstall yt or music (if not system apps)
> 
>     2. Reboot
>        Ta-daa! No more duplicate folders
> 
> 
> Alternatively, if you already have Vanced installed and working **and have not rebooted yet**
> 
>     1. Open `/data/adb/service.d/vanced.sh` or `music.sh` (as appropriate) using a text editor
> 
>     2. In the last line of code, replace the "string of characters ending with ==" with the path to the correct folder
>        E.g in the case of YT Vanced replace the string portion in the line `/data/app/com.google.android.youtube{part to be replaced}`
> 
>     3. Reboot
> 
> 
> Otherwise, if you have rebooted and Vanced has been removed, you can also follow what u/gghhkm said above this comment.
> 
>     1. Delete `/data/adb/Vanced`
> 
>     2. Reboot
> 
>     3. Re-install from Manager

This works. Firstly delete the app form `/data/app/[your app name com.google.android.apps youtube/youtube.music]`. Then delete script from `/data/adb/service.d/[music.sh or vanced.sh]`. Then delete the `Vanced `or `Music` folder from `/data/adb`. If you are unable to delete it from file explorer, then go in recovery and do the same(From TWRP or OrangeFox or any other). Reboot. Update Vanced Manager to latest version. And then install YouTube Vanced/Music from Vanced Manager normally.

Also thanks @Vyto-Khron for the comment.
This issue can be closed now.

**Comment by gghhkm** [comment]
> (From TWRP or OrangeFox or any other)
OrangeFox Recovery getting some deserved recognition.

**Comment by soredake** [comment]
Yes, this works, can manager have button to clean this folders?

**Comment by soredake** [comment]
And after some reboots youtube disappears again, and deleting folders does not help anymore.

**Comment by Crescendo-BLYAT** [comment]
Check #340 
There's a working solution with debug manager or you can wait for official release.

**Comment by soredake** [comment]
@Crescendo-BLYAT working for now, survived two reboots, i'll wait a few weeks after new version if released and if youtube does not disappear i'll finally close this.

**Comment by Bradford1040** [comment]
I tried pretty much everything in this thread.

I got a magisk update today which caused issues with another app, I twrp recovered my boot img to previous magisk, originally I thought my problem was fixed, then I got a vanced manager update, now vanced doesn't survive a reboot.

What am I doing wrong? I have 1+7tpro5g LOS 17.1 rooted and all was working till today! Lol

**Comment by soredake** [comment]
Anyone having problems with youtube vanced disappearing?

**Comment by X1nto** [comment]
> Anyone having problems with youtube vanced disappearing?

did you try with manager 2.2.1?

**Comment by soredake** [comment]
> > Anyone having problems with youtube vanced disappearing?
> 
> did you try with manager 2.2.1?

I personally have no problems with latest manager and magisk, so i'm asking if anyone having problems before closing this

**Comment by X1nto** [comment]
> > > Anyone having problems with youtube vanced disappearing?
> > 
> > did you try with manager 2.2.1?
> 
> I personally have no problems with latest manager and magisk, so i'm asking if anyone having problems before closing this

Oh, I see. If no one else has the problem I guess we could close the issue
