### ISSUE TITLE
Youtube Vanced always showing "connect to the internet"

### ISSUE THREAD

**Issue by rajeevvishva29** [YTVanced/VancedManager#325]
Youtube Vanced always showing "connect to the internet" you're offline check your connection... 
but i am connected with internet other apps are working fine..  

**Phone Specifications:**
- Brand: Redmi Note 7s
- Operating System: MIUI V12.0.1.0 QFGINXM Stable 2.0G
- Android Version: 9PKQ1.180904.001
- Vanced Manager Version: 2.1.0

**
Youtube Vanced always showing "connect to the internet" you're offline check your connection... 
but i am connected with internet other apps are working fine..  
:**

**Steps to reproduce:**

**Further details:**

**Comment by X1nto** [comment]
not a manager related issue
