### ISSUE TITLE
Apk download

### ISSUE THREAD

**Issue by LoreBadTime** [YTVanced/VancedManager#332]
Every time Android fails to load root version,or Google Play updates youtube,you need to redownload all the apk files, i think storing all the needed files somewhere will reduce waiting time and data consume

**Comment by X1nto** [comment]
Currently not possible for root apks

**Comment by jimbt** [comment]
Could someone add a little explanation as to why this isn't possible?

If all the apks change for each version this wouldn't provide much benefit, but when there are install issues or YV gets removed after a reboot it would be nice.

**Comment by X1nto** [comment]
> Could someone add a little explanation as to why this isn't possible?
> 
> If all the apks change for each version this wouldn't provide much benefit, but when there are install issues or YV gets removed after a reboot it would be nice.

Because there's no hash checker implemented yet and without hash checker, you won't be able to find out if files are corrupted or not. Mounting corrupted files over can cause bootloops and unexpected behavior of system, we can't risk that

**Comment by X1nto** [comment]
Also root Vanced won't get removed if you follow instructions in guide and other places
