### ISSUE TITLE
Miui problem

### ISSUE THREAD

**Issue by udin453** [YTVanced/VancedManager#334]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation

**Phone Specifications:**
- Brand:xiamoi redmi 4x
- Operating System: android
- Android Version:7
- Vanced Manager Version:latest

**Please describe the problem you are having in as much detail as possible:**
I cant install YouTube vanced because miui is actived but i was deactivated,i was repeat to active,deactivated its same.i cant instal it

**Steps to reproduce:**
I reinstall

**Further details:**
I installed it before, but after restarting the cellphone, YouTube disappeared

**Comment by X1nto** [comment]
#322
