### ISSUE TITLE
Youtube Vanced working issue

### ISSUE THREAD

**Issue by VasaviLagishetty** [YTVanced/VancedManager#337]
I'm with latest version of Youtube vanced but it is showing me connectivity issue.

![Screenshot_20201230-221524_Vanced Manager](https://user-images.githubusercontent.com/47534164/103368042-9657b600-4aec-11eb-91ca-0b8a29b67ebc.jpg)

![Screenshot_20201230-215959](https://user-images.githubusercontent.com/47534164/103367198-7f17c900-4aea-11eb-8f89-10afd3684149.jpg)
I'm with good interent connetion all the other apps are working fine. I have reinstalled the vanced manager and youtube vanced too but couldn't resolve the issue. Also tried changing with other wifi and mobile networks but it is still same.

**Comment by TooneyTurkey** [comment]
Got to settings and remove you yt microg acc then resign in this is most likely caused by a password reset

**Comment by VasaviLagishetty** [comment]
Thanks @TooneyTurkey it is the password reset issue!!
