### ISSUE TITLE
View orientation

### ISSUE THREAD

**Issue by skrzek** [YTVanced/VancedManager#338]
There's a bad view orientation on TV via Mi Box S 4k. The view is vertically on horizontal TV screen. So it's looks like:

![IMG_20201231_165755](https://user-images.githubusercontent.com/60838625/103417391-d3728580-4b8a-11eb-9c3f-18490330067c.jpg)

**Phone Specifications:**
- Brand: xiaomi
- Operating System: Android TV
- Android Version: 9
- Vanced Manager Version: 2.1.0

**Steps to reproduce:**
Just open Vanced App

**Further details:**
Same issue is on Vanced Youtube Music app.

**Comment by survivor303** [comment]
yep, we need landscape mode, especially because of tablets :)

**Comment by X1nto** [comment]
Fixed in 2.2
