### ISSUE TITLE
I use Reno 4 ,I use swipe to navigate,when I swipe to close app I see a proplem with pop up it looks not normal put when I use buttons to navigate it looks normal and YouTube always say you need to update to the latest version and thanx

### ISSUE THREAD

**Issue by moamedhagoo** [YTVanced/VancedManager#339]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation

**Phone Specifications:**
- Brand:
- Operating System:
- Android Version:
- Vanced Manager Version:

**Please describe the problem you are having in as much detail as possible:**

**Steps to reproduce:**

**Further details:**

**Comment by X1nto** [comment]
not a manager related issue

**Comment by gghhkm** [comment]
> not a manager related issue

They didn't even use the template at all. :cringe:
