### ISSUE TITLE
Installation fails without message, crash, or error dialog

### ISSUE THREAD

**Issue by edo0** [YTVanced/VancedManager#34]
Device: Xiaomi Pocophone F1
OS: LOS for MicroG, based on Android 9
Rooted: Yes
Signature spoofing: Yes
![Screenshot_20200701-224823_microG_Services_Core](https://user-images.githubusercontent.com/16632292/86292346-e2cf4100-bbf0-11ea-90f7-3b50821edf50.png)

What goes wrong: After giving the go for the installation, I can see a config file and the app itself being downloaded (progress showed in the notification area), but then upon "Installing Vanced", the Manager closes itself, and the notification can be swiped away
No update is installed

![IMG_20200701_231919](https://user-images.githubusercontent.com/16632292/86292655-6b4de180-bbf1-11ea-9682-e1c593fe5c62.jpg)
![IMG_20200701_231930](https://user-images.githubusercontent.com/16632292/86292666-70129580-bbf1-11ea-876b-ee0e64968db4.jpg)
![Screenshot_20200701-225048_Vanced_Manager](https://user-images.githubusercontent.com/16632292/86292682-756fe000-bbf1-11ea-8fc4-b22157237f60.png)

Logcat: 
[logcat_07-01-2020_23-10-15.txt](https://github.com/YTVanced/VancedManager/files/4860620/logcat_07-01-2020_23-10-15.txt)

**Comment by X1nto** [comment]
Signature spoofing != Signature verification disabling. Please read pop-up dialogs next time.

**Comment by edo0** [comment]
I am sorry about that!!
Unfortunately, I have proceeded to follow the guide provided in the dialogue, but the situation has not changed - the manager manifested the same behaviour 

Patches successfully applied
![Screenshot_20200701-233556_Lucky_tcher_](https://user-images.githubusercontent.com/16632292/86294067-224b5c80-bbf4-11ea-94da-c54e41910179.png)

Logcat
[logcat_07-01-2020_23-37-04.txt](https://github.com/YTVanced/VancedManager/files/4860710/logcat_07-01-2020_23-37-04.txt)

**Comment by X1nto** [comment]
Something is blocking shell, do you have anything that can block root access/storage access/other to apps?

**Comment by edo0** [comment]
Not as far as I am aware of. I have also disabled LOS' built-in Privacy Guard for Vanced Manager, but that did not help

**Comment by X1nto** [comment]
We'll address this issue and try out best to solve this. Thanks for reporting

**Comment by edo0** [comment]
Thanks to you. I'll make sure to report back here promptly, if any more piece of information may surface or be asked here!!

**Comment by Sarah-rathore** [comment]
Same issue on nokia 6.1 plus after their last security patch. Vanced does not install, it downloads the files and then gets stuck on 'installing'

**Comment by Mattis6666** [comment]
This seems to be related to 14.21 being installed. A warning for this has been implemented in the latest release. Closing

**Comment by edo0** [comment]
Thank you!
As per the installed version, 14.21, I added it by flashing it from my recovery. Is there a proper way to uninstall it?

**Comment by edo0** [comment]
@Mattis6666

**Comment by X1nto** [comment]
> Thank you!
> As per the installed version, 14.21, I added it by flashing it from my recovery. Is there a proper way to uninstall it?

You should download uninstall.plz from same archive where you downloaded installer.zip and vanced.apk, then you should place it in downloads folder and flash installer again. Make sure both installer and uninstall.plz files are in download directory

**Comment by edo0** [comment]
Thank you @X1nto 
Unfortunately, even after successfully removing the old YT Vanced, and updating the Manager to the latest version, the latter will not work still

[logcat_07-04-2020_21-56-40.txt](https://github.com/YTVanced/VancedManager/files/4873775/logcat_07-04-2020_21-56-40.txt)
[logcat_07-04-2020_21-57-28.txt](https://github.com/YTVanced/VancedManager/files/4873776/logcat_07-04-2020_21-57-28.txt)
[logcat_07-04-2020_21-58-01.txt](https://github.com/YTVanced/VancedManager/files/4873777/logcat_07-04-2020_21-58-01.txt)

It closes and becomes unresponsive just like before (with the only difference that now a systen pop up appears warning that the app keeps in crashing)

**Comment by X1nto** [comment]
> Thank you @X1nto 
> Unfortunately, even after successfully removing the old YT Vanced, and updating the Manager to the latest version, the latter will not work still
> 
> [logcat_07-04-2020_21-56-40.txt](https://github.com/YTVanced/VancedManager/files/4873775/logcat_07-04-2020_21-56-40.txt)
> [logcat_07-04-2020_21-57-28.txt](https://github.com/YTVanced/VancedManager/files/4873776/logcat_07-04-2020_21-57-28.txt)
> [logcat_07-04-2020_21-58-01.txt](https://github.com/YTVanced/VancedManager/files/4873777/logcat_07-04-2020_21-58-01.txt)
> 
> It closes and becomes unresponsive just like before (with the only difference that now a systen pop up appears warning that the app keeps in crashing)

Did you grant root permissions properly? Are you using magisk or SuperSU

**Comment by edo0** [comment]
Ok, that may be it. Permission have been granted properly, but I am using LOS su addon.
Should I open a ticket for implementing its support?

**Comment by KevinX8** [comment]
> Ok, that may be it. Permissions have been granted properly, but I am using LOS su addon.
> Should I open a ticket for implementing its support?

We only support magisk and any other implementation that supports libsu, LOS hasn't updated their su add-on since 2016 so I recommend you stop using it.

**Comment by X1nto** [comment]
We cant guarantee that LoS SU addon will work because we don't have it's APIs. Make sure you enabled su access to both adb and apps in developer settings, if that doesn't work there's nothing we can do. Please consider upgrading to magisk instead

**Comment by edo0** [comment]
Thank you both for the advice! I had no clue LOS addonsu had been left neglected for that long
I had experienced issues with Magisk in the past (mainly lengthened, glitchy, booting process with LOS on my device), but I will give it again a try, or consider SuperSU instead!

**Comment by X1nto** [comment]
I would highly recommend to check out magisk, it has one of the greatest community, it's open source and it has been improved a lot these years

**Comment by KevinX8** [comment]
> Thank you both for the advice! I had no clue LOS addonsu had been left neglected for that long
> I had experienced issues with Magisk in the past (mainly lengthened, glitchy, booting process with LOS on my device), but I will give it again a try, or consider SuperSU instead!

might have been a slight exageration, there have been a few quotes since 2016 but hasn't fundementally changed since then https://github.com/LineageOS/android_system_extras_su
