### ISSUE TITLE
Align Latest Version Number with Installed Version Number so they are parallel

### ISSUE THREAD

**Issue by whatinthenameofgod** [YTVanced/VancedManager#341]
**Please describe the problem you are having in as much detail as possible:**

To make the app easier to see and compare installed/available versions at a glance, please consider adding a few nbsps to force align the latest version number with the installed version number.

**Comment by X1nto** [comment]
Unfortunately, doing so ruins the look of the app, makes it look a bit weird.

**Comment by X1nto** [comment]
PS: A message from the designer:

The accessibility of app design doesn't function by comparing 2 strings
1. You can spot new version is available when the install button says "reinstall"
2. Update notification is being pushed
3. Version numbers are just addition for nerds as usual normal person won't look at them
4. Your eyes have enough strength to focus on text and then compare them
