### ISSUE TITLE
(Suggestion)

### ISSUE THREAD

**Issue by itsbarker23** [YTVanced/VancedManager#344]
Hello, I was wondering if it were possible to create themes for Vanced myself. I would love to add a dark blue style theme with the same layout / style as the dark mode. I think It would make my youtube experience even better. 

I know this was available in the older versions on vanced, wonder why it isn't done here. I'm sure youtube is always changing their layouts and what not sign the updates and it just might be a bother to reskin each app. I don't know, but I would love the option to create my own youtube theme, I'm a beginner coder for android and would feel this would be a great project for me. 

Regards, Barker.

**Comment by X1nto** [comment]
not a manager related issue
