### ISSUE TITLE
Vanced manager doesn't install YouTube after one ui 3.0 update 

### ISSUE THREAD

**Issue by Nugnovadosed** [YTVanced/VancedManager#346]
**Please only report your issue here, if all points below are true*
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation

**Phone Specifications:**
- Brand: Samsung 
- Operating System: android
- Android Version: 11
- Vanced Manager Version: 2.1.0

**Please describe the problem you are having in as much detail as possible:**
Hello. I bought the Samsung galaxy s20 plus, I installed YouTube vanced through the vanced manager and it all worked fine then the next day I got a software update that upgraded my phone to One Ui 3.0. After this update YouTube vanced was gone and now every time I time I try reinstall it I just get error messages saying "installation failed because the app conflicts with an already installed app, uninstall current version and try again" but there's no previous version to uninstall so Im not sure what to do. I attached screen shots of the error messages

**Steps to reproduce:**

Trying to install YouTube vanced through the vanced manager 
**Further details:**
![Screenshot_20210109-000325_Vanced Manager](https://user-images.githubusercontent.com/77178404/104077317-25fa1480-5211-11eb-9e14-e5572e69bbd9.jpg)
![Screenshot_20210109-000336_Vanced Manager](https://user-images.githubusercontent.com/77178404/104077321-2a263200-5211-11eb-84b7-605560fc4c4b.jpg)

**Comment by X1nto** [comment]
Youtube is already installed in your system, uninstall updates for it and then install vanced

**Comment by Nugnovadosed** [comment]
Ye Iv looked through everything I can think of and there's nothing to do with vanced YouTube anywhere so I guess I'm just stuck?

**Comment by Xi-PP** [comment]
> Ye Iv looked through everything I can think of and there's nothing to do with vanced YouTube anywhere so I guess I'm just stuck?

Install stock YT (original app) then do the root installation process again

**Comment by rvargasl58** [comment]
I have ssme issue on Samsung Android 11 One ui 3

**Comment by X1nto** [comment]
I really don't think there's anything we can do, the only thing I would recommend is doing a factory reset to see if that works

**Comment by rvargasl58** [comment]
Thanks for your answer (sorry English)

I had installed Youtube vanced before update android 11 in my phone.

When Android 11 finish instalation, YoutubeVanced was erased by Android
update.

**Comment by rvargasl58** [comment]
Good morning

Yesterday, I did a factory reset an all is working grate.

Thanks

**Comment by X1nto** [comment]
If factory reset works fine, I guess this can be closed now since it's purely a OneUI issue

**Comment by rvargasl58** [comment]
Thanks for your help

**Comment by jusperby** [comment]
1. Install Android Debug Bridge (adb) (Installs with Android Studio ).
2. Open ADB folder ( default is C:\Users\Username\AppData\Local\Android\SDK\platform-tools )
3. Unlock your phone
4. Enable Developer Mode (tap 10 times on Build number in Settings - About phone -Software information
5. Enable USB debugging in Settings - Developer options
6. Connect your phone to PC
7. Open Command Prompt (CMD) and change directory: `cd C:\Users\Username\AppData\Local\Android\SDK\platform-tools` and press Enter.
8. As your phone is connected and CMD is open, in CMD run command `adb devices`
9. There will be a propt in your phone, something like "Would you like to connect your phone to PC?" Press Yes
10. Run cmd command `adb uninstall com.vanced.android.youtube`
11. After this you may install Vanced Manager and install the latest version of YouTube Vanced

**Comment by X1nto** [comment]
> 1. Install Android Debug Bridge (adb) (Installs with Android Studio ).
> 2. Open ADB folder ( default is C:\Users\Username\AppData\Local\Android\SDK\platform-tools )
> 3. Unlock your phone
> 4. Enable Developer Mode (tap 10 times on Build number in Settings - About phone -Software information
> 5. Enable USB debugging in Settings - Developer options
> 6. Connect your phone to PC
> 7. Open Command Prompt (CMD) and change directory: `cd C:\Users\Username\AppData\Local\Android\SDK\platform-tools` and press Enter.
> 8. As your phone is connected and CMD is open, in CMD run command `adb devices`
> 9. There will be a propt in your phone, something like "Would you like to connect your phone to PC?" Press Yes
> 10. Run cmd command `adb uninstall com.vanced.android.youtube`
> 11. After this you may install Vanced Manager and install the latest version of YouTube Vanced

Thanks for the solution

**Comment by gimdh** [comment]
After upgrading to OneUI 3.0, I uninstalled and tried to reinstall youtube vanced.
I got slightly different error message "INSTALL_FAILED_VERSION_DOWNGRADE".

While `adb shell pm uninstall com.vanced.android.youtube` never finished, I have finally found a solution.

`adb shell pm list users` would return something like following.
```
        UserInfo{0:USER_NAME:c15} running
        UserInfo{150:USER_NAME:SOME_NUMBER} running
```

User 0 is the system user and the other user (In this case, it is user 150) is the actual user.
So you can run following command to specify which user to delete youtube vanced.

`adb shell pm uninstall --user 150 com.vanced.android.youtube`

Note that you should replace 150 with your user id as seen above.

**Comment by gghhkm** [comment]
> After upgrading to OneUI 3.0, I uninstalled and tried to reinstall youtube vanced.
> I got slightly different error message "INSTALL_FAILED_VERSION_DOWNGRADE".
> 
> While `adb shell pm uninstall com.vanced.android.youtube` never finished, I have finally found a solution.
> 
> `adb shell pm list users` would return something like following.
> 
> ```
>         UserInfo{0:USER_NAME:c15} running
>         UserInfo{150:USER_NAME:SOME_NUMBER} running
> ```
> 
> User 0 is the system user and the other user (In this case, it is user 150) is the actual user.
> So you can run following command to specify which user to delete youtube vanced.
> 
> `adb shell pm uninstall --user 150 com.vanced.android.youtube`
> 
> Note that you should replace 150 with your user id as seen above.

Great, I'll add this into my repo.
