### ISSUE TITLE
Version for android 4.4.2

### ISSUE THREAD

**Issue by DavidBrazSan** [YTVanced/VancedManager#347]
Hello, I have a device with android 4.4.2 and wanted to install vanced on it. could make a version of these devices. Create vanced manager only to install and update.

**Comment by KevinX8** [comment]
Vanced only supports android 5.0 and up, you can install 14.21 and use it as long as you want, however android 4.4.x and below will never receive updates.

**Comment by yalov** [comment]
it is exactly the reason, why Vanced Manager could be helpful for people with android 4.4 devices — for not googling what version of the app was the last supported by pre5.0 android - but installing the last version with the Vanced Manager

**Comment by KevinX8** [comment]
We would have to add legacy APIs to the app just for that which would increase development time and increase likely hood of crashing and other issues, there are also so few users on versions of android older than 5.0 that it's not really a major issue that they have to look it up

**Comment by X1nto** [comment]
> it is exactly the reason, why Vanced Manager could be helpful for people with android 4.4 devices — for not googling what version of the app was the last supported by pre5.0 android - but installing the last version with the Vanced Manager

youtube itself already partially dropped support for android 4, supporting KitKat would require Vanced devs to make a separate version of Vanced and would also require a huge rewrite of Vanced Manager since most of PackageManager APIs are not available in versions below 5.0

**Comment by KevinX8** [comment]
> > it is exactly the reason, why Vanced Manager could be helpful for people with android 4.4 devices — for not googling what version of the app was the last supported by pre5.0 android - but installing the last version with the Vanced Manager
> 
> youtube itself already partially dropped support for android 4, supporting KitKat would require Vanced devs to make a separate version of Vanced and would also require a huge rewrite of Vanced Manager since most of PackageManager APIs are not available in versions below 5.0

It was fully dropped not partially, the last version of YouTube for 4.4.4 was 14.49

**Comment by X1nto** [comment]
> It was fully dropped not partially, the last version of YouTube for 4.4.4 was 14.49

Then I see no reason to continue this discussion
