### ISSUE TITLE
Handle versioning issues

### ISSUE THREAD

**Issue by stdedos** [YTVanced/VancedManager#348]
I have been trying to update to latest version of VancedProducts, but I have sometimes been hitting issues, or unwanted behavior after updating. 

Before I update, I would like to have the following: 
- App data backup, so I can restore them later 
- The apk of the version I am in 

Then, after I update, if I don't like it, I would like to be able to restore such backup, and be on my way 

... and all of the above, with any degree of automation. 

Does that sound like being part of VancedManager at some time?

**Comment by X1nto** [comment]
There are other apps that can handle backups absolutely fine, such as Titanium Backup and Swift Backup. Backups won't be supported in manager because that would be a bloat. Although there's an option to install older versions

**Comment by stdedos** [comment]
> There are other apps that can handle backups absolutely fine, such as Titanium Backup and Swift Backup.

I know them, and they are (at least, they look) awesome. The problem is, root rights

> Backups won't be supported in manager because that would be a bloat.

I guess, but streamlining the backup/recovery (if possible) would be so much faster than doing it manually (or over `adb`!)

>  Although there's an option to install older versions
Yeah, but downgrading is not supported in Android 😕 

I didn't know about that for ages until recently (because of Vanced too)

**Comment by KevinX8** [comment]
It wouldn't be possible for manager to do it due to android permissions system (without root) but it would be possible for vanced itself to do it so open a feature request there not here
