### ISSUE TITLE
[ROOT] Installer process go into weird loop

### ISSUE THREAD

**Issue by chesskuo** [YTVanced/VancedManager#355]
**Phone Specifications:**
- Brand: `Pixel 5`
- Operating System: `RQ1A.210105.003` (the latest version which be released few days ago)
- Android Version: `11.0.0`
- Vanced Manager Version: `2.1.0 (CyberManager2077)`

**Please describe the problem you are having in as much detail as possible:**
- When installing Vanced YT, it is still circle in `waiting step` and won't go to next step.
- The YT version is changed and same as what I choose, but app is still original YT.

**Steps to reproduce:**
- Just installing vanced normally

**Further details:**

**Comment by X1nto** [comment]
Which version of magisk are you using?

**Comment by mooms06** [comment]
Same issue here, on an x86 tablet running Android 5.1.1, and SuperSU. Updating from Vanced 13.50.52.

**Comment by KevinX8** [comment]
> Same issue here, on an x86 tablet running Android 5.1.1, and SuperSU. Updating from Vanced 13.50.52.

SuperSU is totally unsupported, please switch to Magisk

**Comment by mooms06** [comment]
I would like, but Magisk is not working on this tablet. 
Anyway, SuperSU seems to give root access, but Vanced Manager is looping. 
After a reboot, 15.43.32 is installed, but vanilla, not Vanced.

**Comment by KevinX8** [comment]
> I would like, but Magisk is not working on this tablet.
> Anyway, SuperSU seems to give root access, but Vanced Manager is looping.
> After a reboot, 15.43.32 is installed, but vanilla, not Vanced.

that's unfortunate to hear but vanced manager is fully dependent on magisk to work so using SuperSU to install is not an option.

**Comment by mooms06** [comment]
Non-root (MicroG) version is working.

**Comment by KevinX8** [comment]
> Non-root (MicroG) version is working.

Yes because it doesn't use SU at all

**Comment by chesskuo** [comment]
> Which version of magisk are you using?

@X1nto my version is :
- Magisk : `04c53c35 (21203)`
- Manager : `04c53c35 (4818)(15)`

**Comment by mooms06** [comment]
> 
> 
> > Non-root (MicroG) version is working.
> 
> Yes because it doesn't use SU at all

I know, thanks.

**Comment by brian6932** [comment]
> * Magisk : `04c53c35 (21203)`
I updated to this version of Magisk today and I have the same issue, I switched to an older build of Vanced Root installed via SAI, is there a way to get the split APK for 15.43.32 Root? The newest version I see on the mirrors is 15.05.54

**Comment by brian6932** [comment]
Ok update, this works for me
https://forum.xda-developers.com/t/app-mod-root-nonroot-youtube-vanced-edition.3758757/page-870#post-83855303

**Comment by chesskuo** [comment]
@brian6932 
Oh, it broke again... Magisk updates frequently XD
It is still in this loop, and it crash sometimes when I restart it.

now, version is:
- magisk : `f5c2d724 (21302)`
- manager : `f5c2d724 (4829)`

**Comment by X1nto** [comment]
Magisk broke root installation

**Comment by brian6932** [comment]
Still works for me with the XDA method 🤷

**Comment by KevinX8** [comment]
Fixed in magisk 21.4
