### ISSUE TITLE
I'm not patient!! I'ts been 30 mins

### ISSUE THREAD

**Issue by giou** [YTVanced/VancedManager#357]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server YES
- I am using the latest version YES
- This is an issue in the Vanced Manager app (NOT Youtube Vanced) YES
- This issue keeps re-occurring every time I try YES
- For MIUI users: I disabled MIUI optimisation AOSP

**Phone Specifications:**
- Brand: Xiaomi Redmi Note 5 whyred
- Operating System: HavocOS 3.12 Official
- Android Version: 10
- Vanced Manager Version: 2.1

**Please describe the problem you are having in as much detail as possible:**
Stuck in "Be patient" forever when installing Youtube Vanced or Music.

**Steps to reproduce:**

**Further details:**
I'm using Magisk 21.3
I just reflashed rom
First time I tried restored VancedManager with TitaniumBackup
AGNI Kernel 12
Latest opengapps

**Comment by X1nto** [comment]
Magisk 21.3 has issues with root installer
