### ISSUE TITLE
Root installer freezes on Magisk 21.3

### ISSUE THREAD

**Issue by X1nto** [YTVanced/VancedManager#358]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation

**Phone Specifications:**
- Brand: Any
- Operating System: Any
- Android Version: Any
- Vanced Manager Version: 1.3.0+

**Please describe the problem you are having in as much detail as possible:**
Shell commands don't run on Magisk 21.3

**Steps to reproduce:**
- Install any root app
- It won't install

**Further details:**
This has to do something with Magisk, not manager

**Comment by cl-ement05** [comment]
Same issue for me just after upgrading to Magisk 21.3. Manager loops installing the apps ("Please be patient" message).

**Comment by X1nto** [comment]
> Same issue for me just after upgrading to Magisk 21.3. Manager loops installing the apps ("Please be patient" message). 

I know

**Comment by RhanCandia** [comment]
Can confirm. I was encountering the same issue and when I rolled back to 21.2, installation of YouTube Vanced was successful.

**Comment by X1nto** [comment]
Fixed in magisk 21.4
