### ISSUE TITLE
[Feature request] Choosable Icons

### ISSUE THREAD

**Issue by TonyDalov99** [YTVanced/VancedManager#367]
I think it would be great if the users can choose the icon per application. Everyone has their own preference and i think it's important to let the user choose it's own icon (from earlier versions for instance). In my personal opinion the current YT Music app icon doesn't fit in general and I would appreciate if I would be able to change it to the earlier one. 
I also don't think that implementing this will cost a lot of work ( I am a software engineer myself )

My suggestion is to consider this feature request since the user's opinion needs to be valued.

**Comment by X1nto** [comment]
Won't be possible to do it with manager, however, you can customize icons inside your app launcher

**Comment by TonyDalov99** [comment]
How is this achievable on Samsung Galaxy S20(not rooted) if I may ask ?

**Comment by X1nto** [comment]
> How is this achievable on Samsung Galaxy S20(not rooted) if I may ask ?

I don't have any OneUI devices, thus I'm not sure if OneUI launcher has the option to manually pick icons for apps. Although there are other launchers that allow such customization, for example: Lawnchair 2, but it hasn't been updated for a long time so I doubt it's even worth trying, unless you use the alpha version
