### ISSUE TITLE
[Possible Features] PocketTube-like channel categorization

### ISSUE THREAD

**Issue by BrandonKMLee** [YTVanced/VancedManager#369]
The idea of https://yousub.info/ is really useful for people who subbed to many channels of diversified themes.
Science, Technology, Engineering, Maths, Music, Art, Animation, Writing, Cooking etc.

**Comment by X1nto** [comment]
not a manager related issue

**Comment by gghhkm** [comment]
> The idea of https://yousub.info/ is really useful for people who subbed to many channels of diversified themes.
> Science, Technology, Engineering, Maths, Music, Art, Animation, Writing, Cooking etc.

https://github.com/YTVanced/Vanced
