### ISSUE TITLE
Error when trying to install YT Vanced/ MicroG for non-root on V2.2.1

### ISSUE THREAD

**Issue by aecarvalho** [YTVanced/VancedManager#370]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation

**Phone Specifications:**
- Brand: Xiaomi Poco F1
- Operating System: Pixel Experience
- Android Version: 10
- Vanced Manager Version: 2.2.1

**Please describe the problem you are having in as much detail as possible:**

Seems like the Vanced Manager is still broken because the latest version is shown as unavailable and installing microg leads to error

**Steps to reproduce:**

Try using the non root version and install microg or vanced app, both will show error.

**Further details:**

![Screenshot_20210120-191927597](https://user-images.githubusercontent.com/60945000/105184221-1b1a7a80-5b55-11eb-81f2-0908b78008b2.jpg)
![Screenshot_20210120-192201048](https://user-images.githubusercontent.com/60945000/105184234-1eae0180-5b55-11eb-9093-5e706dcb471e.jpg)

**Comment by X1nto** [comment]
website is down

**Comment by AshFL** [comment]
I can confirm non root version still can't pull either latest version number or download new version

**Comment by aecarvalho** [comment]
> website is down

Any idea when it might be functional again? Don't intend to press on but asking out of curiosity.

**Comment by dm9pZCAq** [comment]
from telegram channel:

• Vanced website is down due to heavy load of servers. Please use alternative link by updating the channel url inside developer settings of vanced manager. The developer options can be enabled using the "VANCED TEAM" section by tapping 6-7 times. Dev's option settings can be found inside settings

Just put this url there and then refresh manager

https://mirror.codebucket.de/vanced/api/v1/

• Get vanced faq from here

https://play.google.com/store/apps/details?id=com.vanced.faq

**Comment by X1nto** [comment]
> > website is down
> 
> Any idea when it might be functional again? Don't intend to press on but asking out of curiosity.

should be back up in less than 15 mins

**Comment by aecarvalho** [comment]
Thank you both for responding

**Comment by WarrenWillingham** [comment]
It's back up or I was an idiot and had vanced manager's storage permissions off.

I appreciate the immediate response from you guys. Thank you

**Comment by Oratorian** [comment]
It is still offline.

Can one of the devs contact me please. I want to contribute my server to vanced as storage or Webserver as fail over.

**Comment by BilliTheKid** [comment]
Still down with root version

**Comment by aecarvalho** [comment]
Is it possible to push YouTube Vanced app directly to GitHub? Might be helpful to solve the downloading errors due to server congestion.

**Comment by BilliTheKid** [comment]
Server down again
