### ISSUE TITLE
Youtube Music Crash

### ISSUE THREAD

**Issue by atmtea** [YTVanced/VancedManager#371]
![Screenshot_2021-01-20-21-07-41-361_com miui bugreport](https://user-images.githubusercontent.com/17396273/105186235-14dfca80-5b64-11eb-943a-2a6438c56621.jpg)

any solution?

**Comment by X1nto** [comment]
Try reinstalling using manager

**Comment by hyunki** [comment]
> 
> 
> Try reinstalling using manager

Manager is currently unavailable. "dark.apk error on downloading" message appear last 13min.

**Comment by X1nto** [comment]
> > 
> > 
> > Try reinstalling using manager
> 
> Manager is currently unavailable. "dark.apk error on downloading" message appear last 13min.

Yeah server was down, try in few minutes

**Comment by atmtea** [comment]
yeah currently unavailable, will try later if server normal

**Comment by hyunki** [comment]
I guess global FAQ notice cause this problem LOL everyone want to connect.

**Comment by hyunki** [comment]
Now it's working. try again.

**Comment by hyunki** [comment]
> 
> 
> yeah currently unavailable, will try it later if server normal

Now it's working. try again.

**Comment by atmtea** [comment]
ok, now is working after reinstall youtube music via vanced manager. thanks

![Screenshot_2021-01-20-21-42-05-775_com google android apps youtube music](https://user-images.githubusercontent.com/17396273/105190503-a5200e80-5b68-11eb-9e9c-25f7462231a5.jpg)
