### ISSUE TITLE
Error downloading APK's through manager

### ISSUE THREAD

**Issue by WarrenWillingham** [YTVanced/VancedManager#372]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server  YES
- I am using the latest version 2.2.1 YES
- This is an issue in the Vanced Manager app (NOT Youtube Vanced) YES
- This issue keeps re-occurring every time I try: Downloading a new youtube vanced app through the manager
- For MIUI users: I disabled MIUI optimisation N/A

**Phone Specifications:**
- Brand: Oneplus 6t a6013
- Operating System: OxygenOS 10.3.7
- Android Version: 10
- Vanced Manager Version: 2.2.1
- Root status: Unrooted

**Please describe the problem you are having in as much detail as possible:**
Updated to vanced manager 2.2.1
Uninstalled previous microg and youtube vanced
Tried to install MicroG and Vanced.
MicroG failed, but let me install my previous microG version
Vanced download attempt gave error message: 'Error Downloading dark.apk'
MicroG download attempt gave error message: 'Error Downloading microg.apk'

**Steps to reproduce:**
Uninstall Vanced manager, install 2.2.1, attempt to install youtube vanced or microG, read error message

**Further details:**
Maybe the download server is overwhelmed by a bunch of people trying to update at once?

If you need more information from me, please let me know, thank you!

**Comment by X1nto** [comment]
#370
