### ISSUE TITLE
[non-root] Vanced Manager 2.2.1 

### ISSUE THREAD

**Issue by morgenstern72** [YTVanced/VancedManager#373]
**Phone Specifications:**
- Brand: OnePuls 8T
- Operating System: Android 
- Android Version: 11, Security Update 2020-11-01, Google Play-Systemupdate 2020-12-1
- Vanced Manager Version: 2.2.1 (RootedFirebase) (but installed as non root, I dont have root!)

**Please describe the problem you are having in as much detail as possible:**
Manager shows installed versions of Youtube Vanced, Youtube Musiv and Vanced Microg, but latest version is empty and also cant be downloaded.

**Steps to reproduce:**
Start Manager and see what I describe

I also reinstalled Manager, emptied the cache and also deleted all data and reinstalled.

![Screenshot_20210120-154541](https://user-images.githubusercontent.com/11777765/105190843-b8b28180-5b36-11eb-8eca-6a6c4bbbcdd9.jpg)

**Comment by X1nto** [comment]
#370
