### ISSUE TITLE
VM 2.21 getting error to reinstall 

### ISSUE THREAD

**Issue by BilliTheKid** [YTVanced/VancedManager#374]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation

**Phone Specifications:**
- Brand: Google
- Operating System: Stock
- Android Version: 11
- Vanced Manager Version: 2.21

**Please describe the problem you are having in as much detail as possible:**
VM 2.21 getting error on apk to reinstall . it's showing unavailable of current version. Getting error straight away trying to reinstall.

**Steps to reproduce:**

**Further details:**

**Comment by metya** [comment]
Confirm that

**Comment by X1nto** [comment]
#370
