### ISSUE TITLE
youtube version 15.44.33

### ISSUE THREAD

**Issue by joske** [YTVanced/VancedManager#375]
Hi,

I flashed the android 11 open beta for op7t. It comes with youtube 15.44.33, so latest Vanced Manager 2.2.1 can't install over it (latest vanced is 15.43.32). 

cheers

**Comment by X1nto** [comment]
Uninstall updates for youtube and try again

**Comment by brnwlshubh** [comment]
@joske Try to disable the official Youtube app and download the vanced youtube from vanced manager.

**Comment by joske** [comment]
> @joske Try to disable the official Youtube app and download the vanced youtube from vanced manager.

Thanks for the tip but it gives the same problem.

**Comment by brnwlshubh** [comment]
Maybe it is occurring due to

**Comment by brnwlshubh** [comment]
https://github.com/YTVanced/VancedManager/issues/197#issuecomment-713219365

Refer this

**Comment by brnwlshubh** [comment]
https://github.com/YTVanced/VancedManager/issues/197#issuecomment-713219365

**Comment by joske** [comment]
No it isn't. This software for this device came out today and it ships the latest youtube version (so no updates to uninstall). Android doesn't want to downgrade it (because Vanced has an older version) so it fails.

**Comment by joske** [comment]
Which part of there are no updates to uninstall don't you understand?

**Comment by joske** [comment]
![Screenshot_20210120-232600](https://user-images.githubusercontent.com/532423/105248567-e91a1000-5b76-11eb-81b4-4d0c34f00be8.jpg)

**Comment by brnwlshubh** [comment]
Please see in App settings not on Play Store.

Phone Main Settings--> Apps--> Youtube

**Comment by joske** [comment]
![Screenshot_20210120-232959](https://user-images.githubusercontent.com/532423/105248855-752c3780-5b77-11eb-987a-12ffb2aa5388.jpg)

**Comment by brnwlshubh** [comment]
Did you tried after disabling the official youtube and install vanced version?

**Comment by technic-Angel6644** [comment]
It won't work because it appears as if the preinstalled stock version of youtube is newer than the version that is provided by the vanced manager

**Comment by Arkantick** [comment]
I have same problem for my oneplus 8t with last oxygen is update.
I tried everything, I can't completely remove youtube from oxygen, it will always fail at installing an older YouTube version (Vanced or not)

I think we just have to wait a new update from Vanced, based on a more recent youtube version

**Comment by Trilis29** [comment]
Yes, confirming on One+ 8T newest update is the same situation.

**Comment by X1nto** [comment]
It appears that youtube is installed in /system/product/, those apps can't be uninstalled via pm (which is what Manager is trying to do). the solution here would be to wait for a new Vanced update

**Comment by seba2282** [comment]
About that version youtube vanced, why i see still version 15.43.32 as newest version? Not root device huawei P8 Lite (2015)

**Comment by X1nto** [comment]
> About that version youtube vanced, why i see still version 15.43.32 as newest version? Not root device huawei P8 Lite (2015)

because that's the latest vanced version

**Comment by seba2282** [comment]
> > About that version youtube vanced, why i see still version 15.43.32 as newest version? Not root device huawei P8 Lite (2015)
> 
> because that's the latest vanced version

I thought is newer version and for me don't see any update. Thanks for informations.

**Comment by oreillygshane** [comment]
Also having the same issue on Oneplus 7 Pro Android 11 Beta 1

Can this issue please be reopened, as there is no fix yet @X1nto

**Comment by X1nto** [comment]
> Also having the same issue on Oneplus 7 Pro Android 11 Beta 1
> 
> Can this issue please be reopened, as there is no fix yet @X1nto 

I guess

**Comment by minkimac** [comment]
Same issue on OP7 A11 OOS OB1

**Comment by tiziodcaio** [comment]
Try follow [this article](https://tiziodcaio.medium.com/how-to-remove-bloatware-from-the-android-device-without-rooting-462194e5f507)

**Comment by Delphox** [comment]
From what I've seen from multiple people on the Vanced discord, you can uninstall the newer youtube with the magisk Debloater module and then install Vanced.

**Comment by Bradford1040** [comment]
I might be 100% wrong here, but with root you can uninstall YouTube with titanium backup pro or app manager (fdroid app)

https://f-droid.org/packages/io.github.muntashirakon.AppManager

Would that solve the issue of the newer YouTube? Or am I looking at this wrong?

**Comment by tiziodcaio** [comment]
You can remove YouTube without root.

**Comment by Bradford1040** [comment]
True, I've done with adb, but I think the person having the issue had root,

My wording was poor,

 and maybe my advice is a pile of dog poo (shrug shoulders), lol, but I was just trying to help is all. But you are 100% correct, it can be done without root

**Comment by Delphox** [comment]
> I might be 100% wrong here, but with root you can uninstall YouTube with titanium backup pro or app manager (fdroid app)
> 
> https://f-droid.org/packages/io.github.muntashirakon.AppManager
> 
> Would that solve the issue of the newer YouTube? Or am I looking at this wrong?

Apparently you can't do it that way if the app is in the product partition (in fact manager tries to uninstall youtube that way before installing vanced over it, but fails. But I'm seeing people on discord successfully uninstalling it with the Debloater magisk module.

> You can remove YouTube preinstalled without root.
adb doesn't actually uninstall system apps, just hides it from the current user. but that's not enough to replace it with an older version.

**Comment by Bradford1040** [comment]
> > Apparently you can't do it that way if the app is in the product partition (in fact manager tries to uninstall youtube that way before installing vanced over it, but fails. But I'm seeing people on discord successfully uninstalling it with the Debloater magisk module.
> 

I am totally out of my element here, I am basically new to the android game (and old, 50's) lol

Not sure how to tell which apps are a part or the product partition yet, but you can bet that is my next reading subject. 

In titanium backup pro, there are apps that are red, they say system, and I've uninstalled one or two, Specifically & recently "audiofx" in LOS 17.1 as it was causing issues with V4A on my 1+7tpro5g

Sorry this was long, just explaining myself, I am new, but determined (probably should be committed, lol)

**Comment by oreillygshane** [comment]
Issue is now resolved with 16.02.35

**Comment by szaboariel** [comment]
What is the problem?
In the YouTube Vanced the videos not showing on and eader the profile ![Screenshot_20210127_222356_com.vanced.android.youtube.jpg](https://user-images.githubusercontent.com/76839289/106056100-93051980-60ee-11eb-989c-646e63b31b10.jpg)


And in YouTube Music Vanced?
I cant login
![Screenshot_20210127_222405_com.vanced.android.apps.youtube.music.jpg](https://user-images.githubusercontent.com/76839289/106056172-ad3ef780-60ee-11eb-8e60-921424f08106.jpg)



Pls help 😣
