### ISSUE TITLE
[NON ROOT] No YT Music Vanced app in Vanced Manager

### ISSUE THREAD

**Issue by AveoCross** [YTVanced/VancedManager#377]
**Phone Specifications:**
- Brand: Samsung Galaxy S8+ SM-G955F
- Operating System: Android 9
- Vanced Manager Version: 2.2.1 FireBase - Non Root

YouTube Music Vanced app is not visible in Vanced Manager at all. I've tried reinstalling Vanced microG and YouTube Vanced but still nothing. Installing YT Music Vanced form APK file works and app itself works perfectly too but its still not detected in Vanced Manager. I have only YT Vanced and microG in it.
Installing stock YT Music doesn't help either so I got rid of it after installing Vanced version from APK.

**Comment by X1nto** [comment]
Settings > select your apps > tick music > save

**Comment by AveoCross** [comment]
I totally have not seen that! Sorry for troubling.
