### ISSUE TITLE
Not online

### ISSUE THREAD

**Issue by HiroOnGithub** [YTVanced/VancedManager#379]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation

**Phone Specifications:**
- Brand:realme
- Operating System: Realme UI V1.0
- Android Version:10
- Vanced Manager Version:2.2.1

**Please describe the problem you are having in as much detail as possible:**I changed my passwords and Google sign in just stopped working. YouTube Vanced keeps saying I'm not online even though I am. Cannot log into YouTube Music Vanced.

**Steps to reproduce:**
Change password and log out of not frequently used devices.

**Further details:**
I have tried restarting my phone.

**Comment by HiroOnGithub** [comment]
I did try to reinstall microG. But I used the manager to do it and I somehow end up not being able to log in.

**Comment by X1nto** [comment]
Not a manager related issue
