### ISSUE TITLE
Comment section is gone

### ISSUE THREAD

**Issue by uaibo** [YTVanced/VancedManager#384]
Since I installed the latest version 15.43.32 a few days ago, the comment section in all videos is gone. I've tried using other accounts too and the comment section is nowhere to be seen. So it's not an issue with my YouTube account or anything - also, comments do exist if I watch the video from a web browser.

Any idea what's up?

**Comment by Bradford1040** [comment]
Not sure what version of vanced you had before,

YT has moved the comments to the to the top (where they are collapsed, you have to click on it to open), there is a setting to switch it back to the bottom, in the settings 

If you already knew this sorry, just seemed to be a common question after switching to newer versions

**Comment by X1nto** [comment]
Clear data of Vanced and see if that helps. Closing this because it's not manager related
