### ISSUE TITLE
I still receive notifications about YT music update even if it is not installed and the option is unchecked

### ISSUE THREAD

**Issue by mooms06** [YTVanced/VancedManager#387]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation

**Phone Specifications:**
- Brand: S7 G930F
- Operating System: Android 8.0
- Android Version: 8.0
- Vanced Manager Version: 2.2.1

**Please describe the problem you are having in as much detail as possible:**
Everything is stated in the title. It's the third time it occurs.

**Steps to reproduce:**
Wait for a YT music update

**Further details:**
![image](https://user-images.githubusercontent.com/25405517/106035282-398ff100-60d4-11eb-977b-d62707446c81.png)

**Comment by X1nto** [comment]
Fixed in 2.4.0, you may have to manually uncheck notifications under settings but most likely it will already be unchecked
