### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by mastercraft01** [YTVanced/VancedManager#388]
when there is an update and the update also appears in the notification. when I open the advanced manager, how come the latest version is not available

--welp
![Screenshot_2021-01-28-01-28-10-46](https://user-images.githubusercontent.com/75620920/106036687-3a427a80-6108-11eb-9d59-7a874eb7dc19.png)

**Comment by dgw** [comment]
I managed to get the Manager to show the updates, but it keeps failing to download them, even after updating to 2.3.0 which supposedly fixed the mirror fallback.

**Comment by camilo1505** [comment]
seems like the server just went down

**Comment by mKay00** [comment]
Push notification seems like a bad idea. Everyone wants to download and then the server goes down.

**Comment by biradarkushal7** [comment]
![Screenshot_20210127-235957_Vanced_Manager](https://user-images.githubusercontent.com/48548830/106038524-111cec80-60fe-11eb-82ae-c1396c4e615a.png)
I can't even install them now

**Comment by camilo1505** [comment]
be patient, we need to wait that people stop to downloading it at the same time

**Comment by mastercraft01** [comment]
it seems like many are using push notifications which is what makes the server shut down because of most push notifications

**Comment by X1nto** [comment]
Servers are down, please wait for some time and make sure to use manager 2.3.0

**Comment by X1nto** [comment]
For reference: Manager 2.3.0 might use a backup URL so you won't have any errors and "Unavailable" messages

**Comment by X1nto** [comment]
I guess this is resolved now, feel free to reopen and comment if it isn't resolved for you
