### ISSUE TITLE
Manager cannot perform update.

### ISSUE THREAD

**Issue by GMHR** [YTVanced/VancedManager#389]
Manager version : 2.3.0 (MicroShitMoment)
![Screenshot_20210128_004439](https://user-images.githubusercontent.com/63160619/106039278-27797700-6103-11eb-9e28-1d610a3f5dbc.jpg)

Vanced manager cannot get version info of ytvanced or vanced , refreshing doesn't work. Also
it can't update any of them.
![Screenshot_20210128_004428](https://user-images.githubusercontent.com/63160619/106039020-d1a4cf00-6102-11eb-8f7e-fb08fd2e0521.jpg)
I have tried clearing data, reinstalling vanced manager, but the problem still exists.

**Comment by PrincessFlu** [comment]
I have the same issue, I tried un installing yt vanced & music but now I can't get either of them back properly

**Comment by supertiger1234** [comment]
![image](https://user-images.githubusercontent.com/8193841/106040033-c9806b80-60d1-11eb-82a6-79d10ef95acb.png)

**Comment by GMHR** [comment]
@supertiger1234  how do I use the backup server, I can't find any options in the app?

**Comment by supertiger1234** [comment]
@GMHR backup servers are also offline now. Just try after few hours.

**Comment by X1nto** [comment]
#388
