### ISSUE TITLE
Request to provide download links for latest .apks file in website

### ISSUE THREAD

**Issue by RavirahulPadmanabhan** [YTVanced/VancedManager#39]
Vanced Manager is a great way to install the .apks file. But I install .apks files through adb, since i do not want to disable MIUI optimizations which resets all app permissions.

So, it would be great if you also provide direct download link for files in vanced.app site.

**Comment by RavirahulPadmanabhan** [comment]
Also the download links from XDA is not working now. 
https://vanced.app/downloads/YouTube_Vanced-v15.05.54-nonroot-default-black.apks

**Comment by KevinX8** [comment]
The files are very large and require us to maintain 6 different packages with a combined size of 300mb or so, you can just get vanced from mirrors such as XDA or apkmirror which have the files seperate and the necessary bandwidth to have them like so.

**Comment by RavirahulPadmanabhan** [comment]
Yes. Totally agree with you. Reason why I asked to add links in website is, I always share the vanced.app site to my friends and family, so it will be legitimate without any second thoughts.

**ApkMirror:**
Only single file is available. Not able to identify if it is black/dark. https://www.apkmirror.com/apk/team-vanced/youtube-vanced/youtube-vanced-15-05-54-release/

**XDA:**
Download links for latest versions are not working.
https://www.xda-developers.com/youtube-vanced-apk/

**Comment by KevinX8** [comment]
https://forum.xda-developers.com/android/apps-games/app-youtube-vanced-edition-t3758757 we have decided to mirror our server APK files to our mirrors listed here (Media fire and AFH) which you can then download the splits you require and install them using adb (no packed apks files but you can make those yourself)
