### ISSUE TITLE
[NOROOT]NO INTERNET CONNECTION WHILE I CONNECTED TO THE THE WIFI NETWORK

### ISSUE THREAD

**Issue by OmarKing015** [YTVanced/VancedManager#390]

**Comment by 1r0npipe** [comment]
Same here, xiaomi mi phone, also I can't download the file via mobile network it drops the connection

**Comment by X1nto** [comment]
#388

**Comment by OmarKing015** [comment]
I'm Redmi 9 also but in youtube vanced and youtube music vanced I can't
open it and also microG tell try again later when I tried to sign in my
google acc
