### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by mastercraft01** [YTVanced/VancedManager#391]
Why don't videos and profiles appear in vanced 16 versions? 
![Screenshot_2021-01-28-04-47-12-98](https://user-images.githubusercontent.com/75620920/106058642-1e4cd200-6124-11eb-9334-fd28d4072634.png)
16?

**Comment by X1nto** [comment]
Not related with manager

**Comment by mastercraft01** [comment]
> Not related with manager

I post it here so that everyone knows
