### ISSUE TITLE
Logged into microG, but account still does not show up on vanced

### ISSUE THREAD

**Issue by JohnnyBoii189** [YTVanced/VancedManager#392]
Still says add account, whited out email for security purposes.
![Screenshot_20210127-220604](https://user-images.githubusercontent.com/75832486/106084415-56382300-60ec-11eb-9840-cc8ebc879225.jpg)
![Screenshot_20210127-220830_Vanced microG](https://user-images.githubusercontent.com/75832486/106084447-605a2180-60ec-11eb-8c50-d4f0a4999dda.jpg)

**Comment by JohnnyBoii189** [comment]
Never mind, it turns out I suck at reading instructions and notifications, sorry!

**Comment by MohamadMF** [comment]
Still unavailable to read accounts in my device
