### ISSUE TITLE
YT Music Update is not showing or Misbehaving

### ISSUE THREAD

**Issue by rickninja765** [YTVanced/VancedManager#393]
**Phone Specifications:**
- Brand: Realme
- Operating System:Android
- Android Version:10
- Vanced Manager Version:2.3.0

**YT Music Update isn't showing after**

**Steps to reproduce:**
Tap On Reinstall button on YT Music.
It will show version number. But Latest is still old 4.07.51 instead of 4.11.50

**Further details:**
    Screenshots are in chronological order to reproduce Error.
![Screenshot_2021-01-28-08-31-03-69.jpg](https://user-images.githubusercontent.com/61545131/106084317-0e2df600-6116-11eb-938e-24af80b4fc8b.jpg)
![Screenshot_2021-01-28-08-31-12-36.jpg](https://user-images.githubusercontent.com/61545131/106084422-41708500-6116-11eb-97ca-1c448ddab591.jpg)![Screenshot_2021-01-28-08-32-25-03.jpg](https://user-images.githubusercontent.com/61545131/106084432-446b7580-6116-11eb-92b9-a0d057acdb1c.jpg)

**Comment by TheFenrisLycaon** [comment]
Uninstall current version.
Clear downloaded files from settings.
Then install.
While installation, select desired version from preferences.

**Comment by X1nto** [comment]
music updates are postponed because I forgot to add the warning to manager, will be fixed with 2.3.1

**Comment by X1nto** [comment]
fixed in 2.4.0
