### ISSUE TITLE
back to the previous version

### ISSUE THREAD

**Issue by mastercraft01** [YTVanced/VancedManager#395]
yesterday I updated vanved to 16 but now how come it returns to 15 by itself? and the latest version is not available
-i am using vanced manager version 2.3.0

![IMG_20210128_184747](https://user-images.githubusercontent.com/75620920/106134811-a1f4d600-6199-11eb-8a53-b63e74ad6a92.jpg)

**Comment by X1nto** [comment]
try clearing manager data

**Comment by mastercraft01** [comment]
> try clearing manager data

I did that before you told me to. but it still can't. I also uninstalled all of them but it still doesn't work

**Comment by X1nto** [comment]
Seems like servers aren't back up for your country, I would suggest waiting for a few more hours

**Comment by mastercraft01** [comment]
> Seems like servers aren't back up for your country, I would suggest waiting for a few more hours

oh ok. thanks

**Comment by mastercraft01** [comment]
wtf how come my vanced suddenly updates itself to version 16. YouTube is normal and can log in but how come it can update itself? Does Vanced Manager 2.3.0 have an automatic update feature?

**Comment by X1nto** [comment]
> wtf how come my vanced suddenly updates itself to version 16. YouTube is normal and can log in but how come it can update itself? Does Vanced Manager 2.3.0 have an automatic update feature?
> 
> ![Screenshot_2021-01-28-19-40-25-34.png](https://user-images.githubusercontent.com/75620920/106140023-cb653000-61a0-11eb-9d2d-c25e41099a11.png)
> 
> ![Screenshot_2021-01-28-19-41-52-57.png](https://user-images.githubusercontent.com/75620920/106140122-ecc61c00-61a0-11eb-9e26-871fbcf79896.png)

automatic updates are not possible, so no, manager doesn't have auto updates

**Comment by mastercraft01** [comment]
> > wtf how come my vanced suddenly updates itself to version 16. YouTube is normal and can log in but how come it can update itself? Does Vanced Manager 2.3.0 have an automatic update feature?
> > 
> > ![Screenshot_2021-01-28-19-40-25-34.png](https://user-images.githubusercontent.com/75620920/106140023-cb653000-61a0-11eb-9d2d-c25e41099a11.png)
> > 
> > ![Screenshot_2021-01-28-19-41-52-57.png](https://user-images.githubusercontent.com/75620920/106140122-ecc61c00-61a0-11eb-9e26-871fbcf79896.png)
> 
> automatic updates are not possible, so no, manager doesn't have auto updates

well, it doesn't matter to me, the important thing is that YouTube can do it. thank you!

issue is closed
