### ISSUE TITLE
Register Google user with YouTube vanced VER 16.02.32 is fail

### ISSUE THREAD

**Issue by Emesh1** [YTVanced/VancedManager#397]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation

I use xiomi mi 10 light, this defect happened on 3 xiomi devices: my, xiomi A1, xiomi redmi note7.

**Phone Specifications:**
- Brand:xiomi
- Operating System:MIUI 11.0.10
- Android Version:10,9
- Vanced Manager Version:16.02.32

**Please describe the problem you are having in as much detail as possible:**

**Steps to reproduce:**
1.Download manager Apk file. 
2.Open the file and start install the vanced manager, 3.Verify before the instalation the the battery optimization is off. 
4.Download & Install the micro g file. 
5.Download & install the YouTube vanced file. 
6.Update the YouTube vanced from VER 15 TO 16.02.32.
7.Open YouTube vanced & Sign with your Google user to sync your liberies. 

**Actual result:**
YouTube stuck in endless sign action, screen display endless cogwheel. 

**Workarround:**
Remain with YouTube vanced VER 15.

**Further details:**
Good luck. :-)

**Comment by X1nto** [comment]
Not related to manager
