### ISSUE TITLE
Slovak translation

### ISSUE THREAD

**Issue by Gouster4** [YTVanced/VancedManager#398]
techax.sk/VancedManager_Sk_XMLs.zip

**Comment by X1nto** [comment]
Use crowdin if you want to translate

**Comment by Gouster4** [comment]
I tried to. But i didnt found any options to add language for Translation, just to modify Translation of existing iné.

**Comment by Ingrown29** [comment]
@Gouster4 If you want to help me go [ahead](https://crowdin.com/project/vanced-manager/sk#).. There is a lot of work around translating the guide..
I already translated the Vanced apps

**Comment by Ingrown29** [comment]
Nevermind.. it's all done
