### ISSUE TITLE
[NON ROOT]Can't update youtube vanced 15.43.32 to 16.x.

### ISSUE THREAD

**Issue by AGou-ops** [YTVanced/VancedManager#399]
info

- Android ver: 8.1.0
- CPU: qualcomm snapdragon 660.
- vanced manager ver: 2.3.0

![Screenshot_2021-01-30-18-05-58](https://user-images.githubusercontent.com/57939102/106353608-c205d000-6326-11eb-94f0-88185ad6171a.png)

**Comment by AGou-ops** [comment]
error:

![Screenshot_2021-01-30-18-24-30](https://user-images.githubusercontent.com/57939102/106353856-84a24200-6328-11eb-856f-8d751564beb0.png)

And I tried to reinstall the software, but it doesn't work. What should I do?

**Comment by X1nto** [comment]
> error:
> 
> ![Screenshot_2021-01-30-18-24-30](https://user-images.githubusercontent.com/57939102/106353856-84a24200-6328-11eb-856f-8d751564beb0.png)
> 
> And I tried to reinstall the software, but it doesn't work. What should I do?
> 

What the hell is that? Use Vanced manager

**Comment by AGou-ops** [comment]
> > error:
> > ![Screenshot_2021-01-30-18-24-30](https://user-images.githubusercontent.com/57939102/106353856-84a24200-6328-11eb-856f-8d751564beb0.png)
> > And I tried to reinstall the software, but it doesn't work. What should I do?
> 
> What the hell is that? Use Vanced manager

YES. When installing, it will automatically call the build-in application installer and I can't choose.

**Comment by X1nto** [comment]
> > > error:
> > > ![Screenshot_2021-01-30-18-24-30](https://user-images.githubusercontent.com/57939102/106353856-84a24200-6328-11eb-856f-8d751564beb0.png)
> > > And I tried to reinstall the software, but it doesn't work. What should I do?
> > 
> > 
> > What the hell is that? Use Vanced manager
> 
> YES. When installing, it will automatically call the build-in application installer and I can't choose.

Can you send a logcat? maybe also a video recording

**Comment by AGou-ops** [comment]
> > > > error:
> > > > ![Screenshot_2021-01-30-18-24-30](https://user-images.githubusercontent.com/57939102/106353856-84a24200-6328-11eb-856f-8d751564beb0.png)
> > > > And I tried to reinstall the software, but it doesn't work. What should I do?
> > > 
> > > 
> > > What the hell is that? Use Vanced manager
> > 
> > 
> > YES. When installing, it will automatically call the build-in application installer and I can't choose.
> 
> Can you send a logcat? maybe also a video recording

like this:
![](https://user-images.githubusercontent.com/57939102/106354262-60943000-632b-11eb-9eb0-4606b08d653f.gif)

Vanced manager stay on this interface all the time.

**Comment by X1nto** [comment]
> > > > > error:
> > > > > ![Screenshot_2021-01-30-18-24-30](https://user-images.githubusercontent.com/57939102/106353856-84a24200-6328-11eb-856f-8d751564beb0.png)
> > > > > And I tried to reinstall the software, but it doesn't work. What should I do?
> > > > 
> > > > 
> > > > What the hell is that? Use Vanced manager
> > > 
> > > 
> > > YES. When installing, it will automatically call the build-in application installer and I can't choose.
> > 
> > 
> > Can you send a logcat? maybe also a video recording
> 
> like this:
> ![](https://user-images.githubusercontent.com/57939102/106354262-60943000-632b-11eb-9eb0-4606b08d653f.gif)
> 
> Vanced manager stay on this interface all the time.

I need a logcat

**Comment by AGou-ops** [comment]
> > > > > > error:
> > > > > > ![Screenshot_2021-01-30-18-24-30](https://user-images.githubusercontent.com/57939102/106353856-84a24200-6328-11eb-856f-8d751564beb0.png)
> > > > > > And I tried to reinstall the software, but it doesn't work. What should I do?
> > > > > 
> > > > > 
> > > > > What the hell is that? Use Vanced manager
> > > > 
> > > > 
> > > > YES. When installing, it will automatically call the build-in application installer and I can't choose.
> > > 
> > > 
> > > Can you send a logcat? maybe also a video recording
> > 
> > 
> > like this:
> > ![](https://user-images.githubusercontent.com/57939102/106354262-60943000-632b-11eb-9eb0-4606b08d653f.gif)
> > Vanced manager stay on this interface all the time.
> 
> I need a logcat

Is this?

```cmd
E:\platform-tools>adb logcat -v time | find "com.vanced.manager"
01-30 19:15:32.273 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
01-30 19:15:32.893 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
01-30 19:16:33.593 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
01-30 19:16:34.519 E/VoldConnector( 1225): NDC Command {14 volume mkdirs /storage/0000-0000/Android/data/com.vanced.manager/files/} took too long (838ms)
01-30 19:16:34.875 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
01-30 19:16:37.458 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
01-30 19:16:37.597 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
01-30 19:16:39.753 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
01-30 19:16:41.275 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
01-30 19:17:22.936 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
```

Full logcat: 
[logcat.txt](https://github.com/YTVanced/VancedManager/files/5897835/logcat.txt)

I don't know if this is useful. 😢

**Comment by X1nto** [comment]
> > > > > > > error:
> > > > > > > ![Screenshot_2021-01-30-18-24-30](https://user-images.githubusercontent.com/57939102/106353856-84a24200-6328-11eb-856f-8d751564beb0.png)
> > > > > > > And I tried to reinstall the software, but it doesn't work. What should I do?
> > > > > > 
> > > > > > 
> > > > > > What the hell is that? Use Vanced manager
> > > > > 
> > > > > 
> > > > > YES. When installing, it will automatically call the build-in application installer and I can't choose.
> > > > 
> > > > 
> > > > Can you send a logcat? maybe also a video recording
> > > 
> > > 
> > > like this:
> > > ![](https://user-images.githubusercontent.com/57939102/106354262-60943000-632b-11eb-9eb0-4606b08d653f.gif)
> > > Vanced manager stay on this interface all the time.
> > 
> > 
> > I need a logcat
> 
> Is this?
> 
> ```batchfile
> E:\platform-tools>adb logcat -v time | find "com.vanced.manager"
> 01-30 19:15:32.273 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> 01-30 19:15:32.893 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> 01-30 19:16:33.593 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> 01-30 19:16:34.519 E/VoldConnector( 1225): NDC Command {14 volume mkdirs /storage/0000-0000/Android/data/com.vanced.manager/files/} took too long (838ms)
> 01-30 19:16:34.875 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> 01-30 19:16:37.458 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> 01-30 19:16:37.597 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> 01-30 19:16:39.753 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> 01-30 19:16:41.275 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> 01-30 19:17:22.936 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> 
> E:\platform-tools>adb.exe logcat -v time | find "vanced"
> 01-30 19:15:32.273 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> 01-30 19:15:32.893 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> 01-30 19:16:33.593 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> 01-30 19:16:34.519 E/VoldConnector( 1225): NDC Command {14 volume mkdirs /storage/0000-0000/Android/data/com.vanced.manager/files/} took too long (838ms)
> 01-30 19:16:34.875 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> 01-30 19:16:35.958 W/OkHttpClient( 6491): A connection to https://vancedapp.com/ was leaked. Did you forget to close a response body?
> 01-30 19:16:37.458 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> 01-30 19:16:37.597 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> 01-30 19:16:39.753 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> 01-30 19:16:41.275 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> 01-30 19:17:02.891 W/PackageInstaller.Analyz( 2509): Replacing package:com.vanced.android.youtube
> 01-30 19:17:22.936 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> 01-30 19:21:32.121 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> ```
> 
> Full logcat:
> [logcat.txt](https://github.com/YTVanced/VancedManager/files/5897835/logcat.txt)
> 
> I don't know if this is useful. 😢

I guess you should try uninstalling first and then installing again. Make sure to use manager 2.3.0

**Comment by AGou-ops** [comment]
> > > > > > > > error:
> > > > > > > > ![Screenshot_2021-01-30-18-24-30](https://user-images.githubusercontent.com/57939102/106353856-84a24200-6328-11eb-856f-8d751564beb0.png)
> > > > > > > > And I tried to reinstall the software, but it doesn't work. What should I do?
> > > > > > > 
> > > > > > > 
> > > > > > > What the hell is that? Use Vanced manager
> > > > > > 
> > > > > > 
> > > > > > YES. When installing, it will automatically call the build-in application installer and I can't choose.
> > > > > 
> > > > > 
> > > > > Can you send a logcat? maybe also a video recording
> > > > 
> > > > 
> > > > like this:
> > > > ![](https://user-images.githubusercontent.com/57939102/106354262-60943000-632b-11eb-9eb0-4606b08d653f.gif)
> > > > Vanced manager stay on this interface all the time.
> > > 
> > > 
> > > I need a logcat
> > 
> > 
> > Is this?
> > ```batchfile
> > E:\platform-tools>adb logcat -v time | find "com.vanced.manager"
> > 01-30 19:15:32.273 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > 01-30 19:15:32.893 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > 01-30 19:16:33.593 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > 01-30 19:16:34.519 E/VoldConnector( 1225): NDC Command {14 volume mkdirs /storage/0000-0000/Android/data/com.vanced.manager/files/} took too long (838ms)
> > 01-30 19:16:34.875 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > 01-30 19:16:37.458 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > 01-30 19:16:37.597 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > 01-30 19:16:39.753 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > 01-30 19:16:41.275 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > 01-30 19:17:22.936 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > 
> > E:\platform-tools>adb.exe logcat -v time | find "vanced"
> > 01-30 19:15:32.273 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > 01-30 19:15:32.893 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > 01-30 19:16:33.593 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > 01-30 19:16:34.519 E/VoldConnector( 1225): NDC Command {14 volume mkdirs /storage/0000-0000/Android/data/com.vanced.manager/files/} took too long (838ms)
> > 01-30 19:16:34.875 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > 01-30 19:16:35.958 W/OkHttpClient( 6491): A connection to https://vancedapp.com/ was leaked. Did you forget to close a response body?
> > 01-30 19:16:37.458 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > 01-30 19:16:37.597 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > 01-30 19:16:39.753 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > 01-30 19:16:41.275 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > 01-30 19:17:02.891 W/PackageInstaller.Analyz( 2509): Replacing package:com.vanced.android.youtube
> > 01-30 19:17:22.936 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > 01-30 19:21:32.121 W/FloatButtonHelper( 2509): handleStateChanged pkgName: com.vanced.manager  mSupportFloatApp: true
> > ```
> > 
> > 
> > Full logcat:
> > [logcat.txt](https://github.com/YTVanced/VancedManager/files/5897835/logcat.txt)
> > I don't know if this is useful. 😢
> 
> I guess you should try uninstalling first and then installing again. Make sure to use manager 2.3.0

I tried but it doesn't work,  version 15.43.32 is also great. THANK YOU!

**Comment by X1nto** [comment]
I guess we can close this for now

**Comment by gghhkm** [comment]
> > > > > error:
> > > > > ![Screenshot_2021-01-30-18-24-30](https://user-images.githubusercontent.com/57939102/106353856-84a24200-6328-11eb-856f-8d751564beb0.png)
> > > > > And I tried to reinstall the software, but it doesn't work. What should I do?
> > > > 
> > > > 
> > > > What the hell is that? Use Vanced manager
> > > 
> > > 
> > > YES. When installing, it will automatically call the build-in application installer and I can't choose.
> > 
> > 
> > Can you send a logcat? maybe also a video recording
> 
> like this:
> ![](https://user-images.githubusercontent.com/57939102/106354262-60943000-632b-11eb-9eb0-4606b08d653f.gif)
> 
> Vanced manager stay on this interface all the time.

What kinda device has ads on the install screen 👀
Are you using your devices native installer? Because that doesn't look like a native installer.

**Comment by Bradford1040** [comment]
I would delete cache & data for everything that manager installed (vanced & vanced microg & the manager)

Uninstall everything! And download vanced from their site

**Comment by kyelbek** [comment]
> What kinda device has ads on the install screen 👀
> Are you using your devices native installer? Because that doesn't look like a native installer.

You would be suprised :D 
Usually some cheap, barely known, China brands put such things on their phones.
Bootanims, package installers, systemUI, all of them filled with ads.
It's rather rare to see but existent for sure.

**Comment by gghhkm** [comment]
> > What kinda device has ads on the install screen 👀
> > Are you using your devices native installer? Because that doesn't look like a native installer.
> 
> You would be suprised :D
> Usually some cheap, barely known, China brands put such things on their phones.
> Bootanims, package installers, systemUI, all of them filled with ads.
> It's rather rare to see but existent for sure.

Man's gotta unlock it's bootloader and install a custom ROM 😬, but sense that company already commits the federal crime of putting ads inside of their ROM; they probably locked down the bootloader too. 😑

**Comment by Bradford1040** [comment]
> > What kinda device has ads on the install screen 👀
> > Are you using your devices native installer? Because that doesn't look like a native installer.
> 
> You would be suprised :D 
> Usually some cheap, barely known, China brands put such things on their phones.
> Bootanims, package installers, systemUI, all of them filled with ads.
> It's rather rare to see but existent for sure.

Wow, I seriously thought someone cloned & spammed your guy app with ad's, I can't believe a manufacturer would go that far for ad's, I mean that is really destroying the immersive feel.

I mean even an ad blocker can stop the windows from overlaying over your App's right?

**Comment by AGou-ops** [comment]
> > What kinda device has ads on the install screen eyes
> > Are you using your devices native installer? Because that doesn't look like a native installer.
> 
> You would be suprised :D
> Usually some cheap, barely known, China brands put such things on their phones.
> Bootanims, package installers, systemUI, all of them filled with ads.
> It's rather rare to see but existent for sure.

yeah, you are right. This is my old~ Android phone, there are many ads on my phone. I can't flash my phone to another ROM except the official version, because it has BL, I must disassemble the phone  to get root privileges and install another ROM. All in one, it's very complicated.

So, I will never buy this brand of mobile phone again!

**Comment by AGou-ops** [comment]
> doesn't look like a native installer.

 Yes, it doesn't look like a native installer, but it is. This is really a junk phone ever.

**Comment by AGou-ops** [comment]
> > > > > > error:
> > > > > > ![Screenshot_2021-01-30-18-24-30](https://user-images.githubusercontent.com/57939102/106353856-84a24200-6328-11eb-856f-8d751564beb0.png)
> > > > > > And I tried to reinstall the software, but it doesn't work. What should I do?
> > > > > 
> > > > > 
> > > > > What the hell is that? Use Vanced manager
> > > > 
> > > > 
> > > > YES. When installing, it will automatically call the build-in application installer and I can't choose.
> > > 
> > > 
> > > Can you send a logcat? maybe also a video recording
> > 
> > 
> > like this:
> > ![](https://user-images.githubusercontent.com/57939102/106354262-60943000-632b-11eb-9eb0-4606b08d653f.gif)
> > Vanced manager stay on this interface all the time.
> 
> What kinda device has ads on the install screen 
> Are you using your devices native installer? Because that doesn't look like a native installer.

Yes, it doesn't look like a native installer, but it is. This is really a junk phone ever.

**Comment by gghhkm** [comment]
> > > What kinda device has ads on the install screen eyes
> > > Are you using your devices native installer? Because that doesn't look like a native installer.
> > 
> > 
> > You would be suprised :D
> > Usually some cheap, barely known, China brands put such things on their phones.
> > Bootanims, package installers, systemUI, all of them filled with ads.
> > It's rather rare to see but existent for sure.
> 
> yeah, you are right. This is my old~ Android phone, there are many ads on my phone. I can't flash my phone to another ROM except the official version, because it has BL, I must disassemble the phone to get root privileges and install another ROM. All in one, it's very complicated.
> 
> So, I will never buy this brand of mobile phone again!

What brand is it anyway?
