### ISSUE TITLE
Can't use Cast anymore since last update

### ISSUE THREAD

**Issue by JayBee-git** [YTVanced/VancedManager#400]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation

**Phone Specifications:**
- Brand: Google pixel 3
- Operating System: android
- Android Version: 11
- Vanced Manager Version: 2.3.0

**Please describe the problem you are having in as much detail as possible:**
After the last youtube vanced update, I can't use cast anymore.
When I try to cast something to my nvidia shield, the screen goes black, the video tries to load, but then stops (with still a black screen).

**Steps to reproduce:**
Install the last update.

**Further details:**

**Comment by X1nto** [comment]
Not related to manager
