### ISSUE TITLE
YouTube Apllication Stuck in theHomepage loading screen after logging in.

### ISSUE THREAD

**Issue by ZeuzValein** [YTVanced/VancedManager#403]
Currently trying to run v16.02.35 of the Vanced YouTube application in which everything works fine up until I try to login to an account. Even though the account is successfully logged in through the Vanced microG screen. It just sits there on the YouTube loading screen with Google's Spinning circle (and I let it sit there for an hour) and with the four tabs at the bottom, in which nothing gets displayed with the YouTube logomark, the wireless streaming logo, the search and the menu icons at the top. ![photo_2021-02-04_08-20-47](https://user-images.githubusercontent.com/61707745/106922432-eadceb00-66c1-11eb-8a50-208fe8241217.jpg)

Tapping on the Search Icon does nothing other than highlight that it's been tapped on, same with the bottom bar. Whether or not I have MicroG Installed, I can view the application and run it the way it is supposed to in which the app isn't stuck in some kind of loading screen on the homepage, as long as I am not signed into an account. 

![photo_2021-02-04_08-24-22](https://user-images.githubusercontent.com/61707745/106922992-79ea0300-66c2-11eb-8877-0b35055c380b.jpg)

I don't know what is causing the issue specifically. I really hope I can get some insight into this Issue and maybe either get this conflict solved really soon.

**Comment by X1nto** [comment]
not related to manager
