### ISSUE TITLE
VancedManager Logs

### ISSUE THREAD

**Issue by threeeye** [YTVanced/VancedManager#407]
I got the update this morning, and I wanted to check it out.
I went into the Logs, but the colors are bright green and bright blue
I can't read the logs...
Can you please change the colors?
Thanks

**Comment by X1nto** [comment]
You're using light theme?

**Comment by threeeye** [comment]
Ya, I don't like dark themes...

**Comment by X1nto** [comment]
Fixed in 2.5.0
