### ISSUE TITLE
Can't install and delete after delete.

### ISSUE THREAD

**Issue by hyunki** [YTVanced/VancedManager#409]
**Phone Specifications:**
- Brand: Samsung
- Operating System: Galaxy Tab S7+ (SM-T975N)
- Android Version: 11
- Vanced Manager Version: 2.4.0

**Please describe the problem you are having in as much detail as possible:**

I've been using non-root version of vanced youtube.

I wanted to install vanced music so I deleted my microg and vanced youtube via vanced manager.

I tried to re-install micro-g, vanced music, vanced youtube.

Microg is installed without any problem.

But there is an error message when installing Vanced youtube 15.43.32 (I saw the warning that v16 cannot be logged in)
 "App installation failed. User tried to install old version of an app" (What Korean screenshot said)
V16.02 also are not available. Same downgrade error message appears.

How can I clean delete app? There is no "vanced youtube" on application list in settings.

Vanced Manager re-installed several times and I also tried to delete cahce and data. but it still not working.

![Screenshot_20210207-110129_Vanced Manager](https://user-images.githubusercontent.com/25163778/107134327-7fe71a80-6934-11eb-8f54-34d7cd27f5e1.jpg)
![Screenshot_20210207-110138_Vanced Manager](https://user-images.githubusercontent.com/25163778/107134342-a1480680-6934-11eb-9b9e-f602550534bc.jpg)

![Screenshot_20210207-110209_Vanced Manager](https://user-images.githubusercontent.com/25163778/107134329-82e20b00-6934-11eb-9289-55f4bf774632.jpg)
Korean: Can't install this app thus user tried to install old version. Please change app with initial version and retry install.
(which is not available. Neither can find app in settings-applications and filemanager nor can be install.)

![Screenshot_20210207-110212_Vanced Manager](https://user-images.githubusercontent.com/25163778/107134606-04d33380-6937-11eb-83ac-62820b59ea77.jpg)

![Screenshot_20210207-110315_Vanced Manager](https://user-images.githubusercontent.com/25163778/107134343-a311ca00-6934-11eb-81b4-dc6e3341291a.jpg)

**Steps to reproduce:**

**Further details:**

**Comment by X1nto** [comment]
Check #375, it's a bug from OneUI 3, you'll need to factory reset to solve the problem

**Comment by hyunki** [comment]
TY!
