### ISSUE TITLE
Icon alignment

### ISSUE THREAD

**Issue by Caster0696** [YTVanced/VancedManager#410]
The top notification icon left beside the search icon isn't properly aligned, the number indicator is cut off from right side
![Screenshot_20210207-220727](https://user-images.githubusercontent.com/69352167/107152952-fa458800-6990-11eb-94d4-97c45f3acc70.png)

**Comment by X1nto** [comment]
not related to manager and it's a stock youtube issue, not vanced

**Comment by Caster0696** [comment]
Oh I have to post this on vanced issue tracker

**Comment by Caster0696** [comment]
Okay I'm on a aosp rom, didn't have the stock YouTube app for a year now didn't know the stock app has this issue, just checked now.
