### ISSUE TITLE
yt vanced multiple accounts not available

### ISSUE THREAD

**Issue by w-kok** [YTVanced/VancedManager#411]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation

**Phone Specifications:**
- Brand: samsung
- Operating System: os11-R & one ui3
- Android Version: 11
- Vanced Manager Version: 2.4.0

**Please describe the problem you are having in as much detail as possible:**

**Steps to reproduce:**
(reboot between each step to be sure)
install micro G
install yt vanced
add account 1
add account 2
account 2 never shows up in yt vanced, but microG shows added.

**Further details:**
Already removed and reinstalled all steps, problem occurred after update.

**Comment by X1nto** [comment]
not related to manager

**Comment by MohamadMF** [comment]
In vanced MicroG app, it does not see or read linked accounts with our phones. I tested it in Samsung A51, Huawei 20x and Xiaomi mi 9

All of them has same problem. No read or see linked accounts in Gmail
