### ISSUE TITLE
YTM Vanced signature mismatch on 4.07.51 to 4.11.50

### ISSUE THREAD

**Issue by djechelon** [YTVanced/VancedManager#412]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server ✔
- I am using the latest version ✔
- This is an issue in the Vanced Manager app (NOT Youtube Vanced) ✔
- This issue keeps re-occurring every time I try ✔
- For MIUI users: I disabled MIUI optimisation 🚫

And also

- Cleared Vanced app data ✔

**Phone Specifications:**
- Brand: Google Pixel 5
- Operating System: AOSP 11
- Android Version: 11
- Vanced Manager Version: 16.02.35

**Please describe the problem you are having in as much detail as possible:**

I am security-concerned at the moment because I can't upgrade YT Music Vanced to the latest version because of the INSTALL_FAILED_UPGRADE_INCOMPATIBLE error. This error occurs when the upgrade package's APK signature does not match the installed one.

At the moment I am thinking that either the new or the old package could be **tampered**. Either I had installed a rogue version of YTM via Vanced, or the version Vanced is trying to download could be tampered with.

I know that uninstalling and reinstalling YTM could fix, but before going ahead I'd like to better understand why do signatures mismatch at these versions.

I had always used Vanced to install the packages. Today I re-downloaded Vanced from vancedapp.com and re-installed on the fly. Signatures match so I have been using the original Vanced app since the beginning.

This problem never happened with regular YT

**With this question** I'd like to check with the team if anything happened in the past that could affect old signatures, and I found no specific security-related email to discuss sensitive topics, so here I am. Other than getting the correct version of YTM, I'd like to make sure the team is aware of security issues (if they apply, e.g. if *that* 4.07.51 is not just an astral coincidence)

**Steps to reproduce:**

- Open Vanced App, it reposts that Youtube Music upgrade is available
- Download the non-root upgrade
- Confirm installation
- Vanced says it could not install and if the problem persists discuss it on Telegram or Discord
- Advanced button shows the error `INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.vanced.android.apps.youtube.music signature do not match previously installed version, ignoring!`

**Further details:**

Retrieved the old APK from phone and submitted to [VirusTotal](https://www.virustotal.com/gui/file/d8ba34997c2fa195f7a9e5e6173734cb40856583c4560e55cc699036674b22c6/detection), hash `d8ba34997c2fa195f7a9e5e6173734cb40856583c4560e55cc699036674b22c6`

I am available to perform steps to check the integrity of my APK with some help and `adb`-fu 🥋

**Comment by X1nto** [comment]
If we trust VirusTotal's report, it seems like either the new or old version is signed with a debug key which is weird because I don't think it's possible to resign an APK with a debug key

**Comment by KevinX8** [comment]
If you look at the filename you can clearly see it's not from us, we don't own that site it comes from. The versions available in manager are all signed with the same signature, simply reinstall 4.07 from it to confirm.

**Comment by djechelon** [comment]
@KevinX8 you deserve clarification. I didn't even notice on the first time.

This morning, after writing the 1st version of the issue, I `pull`ed the APK from my device, it is named `base.apk` as Android renames all apks into base. I uploaded that to VirusTotal for check, thinking it was first submission, and I didn't notice **VirusTotal knew already of it**. For the name, someone else had uploaded the same APK to VT with different names, don't ask me why.

I am definitely sure that I downloaded that YT Music from Vanced the first time, I never downloaded the APK from other sources. I **had** doubts about the Manager so I redownloaded it.


@X1nto I have no reports about the new version, but out of curiosity you could send VirusTotal your own copy of the latest apk just to see what they say.

**Comment by X1nto** [comment]
> @KevinX8 you deserve clarification. I didn't even notice on the first time.
> 
> This morning, after writing the 1st version of the issue, I `pull`ed the APK from my device, it is named `base.apk` as Android renames all apks into base. I uploaded that to VirusTotal for check, thinking it was first submission, and I didn't notice **VirusTotal knew already of it**. For the name, someone else had uploaded the same APK to VT with different names, don't ask me why.
> 
> I am definitely sure that I downloaded that YT Music from Vanced the first time, I never downloaded the APK from other sources. I **had** doubts about the Manager so I redownloaded it.
> 
> 
> @X1nto I have no reports about the new version, but out of curiosity you could send VirusTotal your own copy of the latest apk just to see what they say.

I'll definitely investigate the issue once I have free time, there's no way it's installer because it can't generate errors out of thin air, so it must be something else. While I myself tested updating from 4.07 to 4.11 and had no problems.

**Comment by djechelon** [comment]
Thank you. The best I can tell is that I own this phone since last November, and I don't remember about the exact installation history/sequence. Not something you pay attention to in your daily life.

New apk: https://www.virustotal.com/gui/file/adfcd9410a9cc126a1c17b40e107f7dceab8e704f07b70b6aacbe52b032a6550/details

**Comment by aa956** [comment]
I've the same error and there's a few more people over here:

https://old.reddit.com/r/Vanced/comments/ld86u0/otherlatest_youtube_music_wont_update/

Am I correct in assuming that the YTM 4.07.51 was distributed with wrong signatures for short time - short but enough for a few people to install this YTM version as their first install of the app?

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
Manager is a security nightmare?

**Comment by aa956** [comment]
I've got a few minutes near the PC, so just to check i've got the same file and it's the same.

```console
C:\temp>"C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe" shell
OnePlus6:/ $ pm list packages | grep vanced
package:com.vanced.manager
package:com.vanced.android.youtube
package:com.vanced.android.apps.youtube.music
OnePlus6:/ $ pm path com.vanced.android.youtube
package:/data/app/com.vanced.android.youtube-qsizII_AYEQ0jsz941HiaA==/base.apk
package:/data/app/com.vanced.android.youtube-qsizII_AYEQ0jsz941HiaA==/split_config.arm64_v8a.apk
package:/data/app/com.vanced.android.youtube-qsizII_AYEQ0jsz941HiaA==/split_config.en.apk
OnePlus6:/ $ pm path com.vanced.android.apps.youtube.music
package:/data/app/com.vanced.android.apps.youtube.music-ZiajZrLRlB1VYtPVm0wIPQ==/base.apk
OnePlus6:/ $ ^D

C:\temp>"C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe" pull /data/app/com.vanced.android.apps.youtube.music-ZiajZrLRlB1VYtPVm0wIPQ==/base.apk c:\temp\ytm.apk
/data/app/com.vanced.android.apps.youtube.music-ZiajZrLRlB1V...file pulled, 0 skipped. 35.5 MB/s (63780257 bytes in 1.712s)

C:\temp>sha256sum ytm.apk
d8ba34997c2fa195f7a9e5e6173734cb40856583c4560e55cc699036674b22c6 *ytm.apk

C:\temp>"C:\Program Files (x86)\Android\android-sdk\build-tools\29.0.2\apksigner.bat" verify --print-certs ytm.apk
Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
WARNING: META-INF/services/com.fasterxml.jackson.core.JsonFactory not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/services/com.google.protobuf.GeneratedExtensionRegistryLoader not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
C:\temp>

```

**Comment by X1nto** [comment]
> I've the same error and there's a few more people over here:
> 
> https://old.reddit.com/r/Vanced/comments/ld86u0/otherlatest_youtube_music_wont_update/
> 
> Am I correct in assuming that the YTM 4.07.51 was distributed with wrong signatures for short time - short but enough for a few people to install this YTM version as their first install of the app?

I believe this is the case here, so I guess this is resolved now, the only way to fix the problem is by uninstalling ytm and installing it again
