### ISSUE TITLE
Disparity between App and Homepage

### ISSUE THREAD

**Issue by ShalokShalom** [YTVanced/VancedManager#414]
[This page](https://vancedmanager.com/#Download_Vanced_Manager_APK_Latest_Version_for_Android) does claim to be an official one.

In case that is true, I suggest to include that into the app, which currently tells us that only Discord, Github and vancedapp are viable sources.

In case it is not, consider investigating the case.

Thanks

**Comment by KevinX8** [comment]
It's not official but it seems to not be malicious for now, we don't have the ability to sue them anyways.

**Comment by ShalokShalom** [comment]
Well, the people should be warned, at least.

At least, they are stealing your identity.

**Comment by X1nto** [comment]
> Well, the people should be warned, at least.
> 
> At least, they are stealing your identity.

As long as they're linking to official APKs it's fine, plus there are no ads on the website either
