### ISSUE TITLE
Can't login in YouTube Vanced since 16.02.35

### ISSUE THREAD

**Issue by Ronald-Baars** [YTVanced/VancedManager#415]
Hey! Since the latest version of YT vanced I cannot login to my Google account anymore. I see the login button, it opens a modal with a button to add an account. It doesn't do anything unfortunately

Miui optimization is off

Xiaomi mi 9t pro running Android 10 and Miui 12

Thanks! Hope this helps

**Comment by X1nto** [comment]
Not related to manager, I think the fix to that issue is described in the guide

**Comment by Ronald-Baars** [comment]
All links to guides seem to be broken.

**Comment by X1nto** [comment]
> All links to guides seem to be broken. 

3 dot menu in manager > guide
