### ISSUE TITLE
Manager is bugged if device is rotated during installation

### ISSUE THREAD

**Issue by ToothlessXD** [YTVanced/VancedManager#416]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation

**Phone Specifications:**
- Brand: Redmi Note 7 Pro
- Operating System: Resurrection Remix 8.6.7
- Android Version: 10
- Vanced Manager Version: 2.4.0

**Please describe the problem you are having in as much detail as possible:**
Vanced manager gets bugged, if device is rotated during installation of YouTube or Music.
Have video recorded here https://youtu.be/rEcIqgFH-1s

**Steps to reproduce:**
Install latest manager (2.4.0)
Turn on auto rotation in device
Opened manager in portrait, given magisk root permission
Clicked install on YouTube or Music.
During progress bar dialog, rotate device to landscape.

**Further details:**
Fresh installation after ROM installed on my device using nik gapps. Magisk root.
Bug won't happen if device not rotated in entire process, installed YouTube without bug this way.

**Comment by X1nto** [comment]
Should be fixed with dc0a66c70051a5b5aa8de808a6ad58cff4fd923e

**Comment by X1nto** [comment]
Fixed in 2.5.0
