### ISSUE TITLE
Unable to log in to YouTube Music

### ISSUE THREAD

**Issue by djechelon** [YTVanced/VancedManager#417]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server ✔
- I am using the latest version ✔
- This is an issue in the Vanced Manager app (NOT Youtube Vanced) ❌ (this is YouTube Music)
- This issue keeps re-occurring every time I try ✔
- For MIUI users: I disabled MIUI optimisation 🚫

**Phone Specifications:**
- Brand: Google Pixel 5
- Operating System: AOSP 11
- Android Version: 11
- Vanced Manager Version: latest from vanced.app

**Please describe the problem you are having in as much detail as possible:**

This is a follow up to #412 
Now that I have installed the official YouTube Music, it always asks me to log in.

**Steps to reproduce:**

1. Remove existing microG account
2. Uninstall YT Vanced
3. Try to log in using YTM Vanced
4. Log in is successful, but YTM Vanced still asks to add an account

Note that I had to unstall the 15+ version of YT Vanced before installing back the 16+ because it is documented by the app.

**Further details:**
Of course it's not a problem with this project, but since Google removed Play Music I just wanted to play my offline music stored on `sdcard`. Telling that to add a bit of a context

**Comment by X1nto** [comment]
Not related to manager
