### ISSUE TITLE
Banking app detects Vanced Manager 

### ISSUE THREAD

**Issue by LieDanG** [YTVanced/VancedManager#420]
I noticed my banking app (Citibanamex Movil, Mexico) detects Vanced Manager and prevents using it, maybe because similar name to Magisk Manager, I need to uninstall the Manager to be able to use the app again

**Comment by X1nto** [comment]
Blame your banking app, not Vanced Manager

**Comment by gghhkm** [comment]
How the hell does it detect Vanced Manager?
Is it like, "oh no, a app with the word 'Manager' ". That's dumb af. I wouldn't even use an app that can't even detect stuff properly.

**Comment by X1nto** [comment]
> How the hell does it detect Vanced Manager?
> Is it like, "oh no, a app with the word 'Manager' ". That's dumb af. I wouldn't even use an app that can't even detect stuff properly.

Totally agree, it's really not our fault your banking app detects stuff improperly. Like, what the hell are we even supposed to do to fix that garbage detection? rename Vanced Manager to Vanced DefinitelyNotManager or what?
