### ISSUE TITLE
[Feature Request] Auto install for root users

### ISSUE THREAD

**Issue by lordcyb3r** [YTVanced/VancedManager#424]
This would solve the issue of vanced uninstalling when a new youtube version is installed
blocking youtube auto updates could work as well

**Comment by raojatin** [comment]
Very excellent

**Comment by X1nto** [comment]
A) we're not gonna violate android security practices
B) if your Vanced is uninstalling in reboot go to manager settings > root script sleep timer > set to 2 > reboot and see if it works

**Comment by X1nto** [comment]
I'll consider this issue resolved
