### ISSUE TITLE
Installation failed because user blocked the installation 

### ISSUE THREAD

**Issue by AzamNawazAnsari** [YTVanced/VancedManager#428]
![Screenshot_2021-02-23-01-23-57-212_com vanced manager](https://user-images.githubusercontent.com/79480284/108765687-ec3d5d00-7575-11eb-8eaa-4763e343573e.jpg)
I was trying to install mi rog from vanced manager but shows this error I have reinstall the manager and cleared data from settings but still not working and not working for anything

**Comment by X1nto** [comment]
related to 537e76499aa4e3a1b3a2c5be790089092e29dbc8, just disable MIUI optimizations. Will be fixed in the next update
