### ISSUE TITLE
Redmi 3 havoc rom android 10

### ISSUE THREAD

**Issue by complicazio** [YTVanced/VancedManager#43]
1)  15.05.54 - build - 01.41.10
2) xda forum link
3) root method
4) xiaomi redmi 3 pro 
5) havoc 3.2 android 10
6) nothing
7) https://del.dog/lowupifugr.txt
8) the manager starts regularly but when tap on the install button the app closes.
9) only magisk with following modules: migrator, riru core and riru edexposed (gravity box beta, scoop, core patch)

Thanks in advance.

**Comment by X1nto** [comment]
Your firewall is probably blocking server for downloading

**Comment by complicazio** [comment]
I solved thanks, the problem was that the system time was incorrect.
