### ISSUE TITLE
Just so you all no my youtube vanced is v 16.04.34.  https://drive.google.com/file/d/1z6bP3Rau1Rg7Xxd7_HUYWISoP9mq6gKR/view?usp=drivesdk                       her is my copy p.s I am missing the picture on the app on phone but it works fine if you can get it just ask I think I got it now so all can copy and add

### ISSUE THREAD

**Issue by alperovitz** [YTVanced/VancedManager#430]
#**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced/Music)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisations

**Phone Specifications:**
- Brand:
- Operating System:
- Android Version:
- Vanced Manager Version:

**Please describe the problem you are having in as much detail as possible:**

**Steps to reproduce:**

**Further details:**

**Comment by X1nto** [comment]
A. For god's sake use proper formatting
B. It's not manager related
C. wat?

**Comment by alperovitz** [comment]
Ya way would I put it in such a primitive old school format that's kind of
gay when I can just send you the copy of what is already been created with
the correct format that you need to install in your phone wow why would I
run that old school crap

**Comment by alperovitz** [comment]
And once again this is version 16.04.38 for YouTube vanced so wow kind of
weird that you don't get what I was trying to be nice and give you all such
an old school  way you no
