### ISSUE TITLE
[2.5.1] "There was a problem while parsing this package."

### ISSUE THREAD

**Issue by superloach** [YTVanced/VancedManager#433]
When attempting to install `manager.apk` (latest release, 2.5.1) I get this error message:
![Screenshot_20210225-092608_Package_installer~2](https://user-images.githubusercontent.com/30514424/109167241-8dc9d780-774b-11eb-849a-e33d5f181593.png)

I'm on LineageOS 17.1 (Android 10) on a Redmi Note 8 (ginkgo).

**Comment by alperovitz** [comment]
Yeah no kidding such a permanent where you all doing I don't even want to hear it yeah I already said how you fix that so it doesn't pop up why you installing the prior version hello there's a sign that new real bad new version ain't going to work funny I'm running YouTube vanced and it's version 16.04.38 interesting that's still newer than anything you have out right now so I was trying to help I can't believe somebody closed the case even though I haven't even finished fixing so there's at least a picture on my version wow when you load it in whatever peace

**Comment by alperovitz** [comment]
You install the manager for YouTube vanced download micro g then install my version of YouTube wow how hard is that everybody

**Comment by alperovitz** [comment]
Is that still doesn't work cuz I'm running on a Google TV box but there's something wrong with that operating system you're using that's trying to run 10 Android and it's not working cuz I'm running 10 Android works fine at my end you're trying to lay the new app over older app of course it won't install you got to uninstall the prior version

**Comment by X1nto** [comment]
@KevinX8 can you ban alperovitz, he's really annoying

**Comment by X1nto** [comment]
> When attempting to install `manager.apk` (latest release, 2.5.1) I get this error message:
> ![Screenshot_20210225-092608_Package_installer~2](https://user-images.githubusercontent.com/30514424/109167241-8dc9d780-774b-11eb-849a-e33d5f181593.png)
> 
> I'm on LineageOS 17.1 (Android 10) on a Redmi Note 8 (ginkgo).

Not sure what can be a problem, are you updating from manager or from website?

**Comment by superloach** [comment]
I'm trying to install the manager itself, from the latest release on this repo.

**Comment by X1nto** [comment]
> I'm trying to install the manager itself, from the latest release on this repo.

Are you sure apk isn't corrupted? Try redownloading

**Comment by superloach** [comment]
I tried 3 times, once from the website and twice from the Releases page.

**Comment by superloach** [comment]
Same issue with 2.4.0 and 2.5.0. Should I try to get some sort of log from the Package Installer?

**Comment by X1nto** [comment]
> Same issue with 2.4.0 and 2.5.0. Should I try to get some sort of log from the Package Installer?

Would be great, you could also try installing it via SAI because it provides better errors (SAI supports regular apk too)

**Comment by superloach** [comment]
Installing the manager with SAI works fine, so maybe it's a signing issue?

**Comment by superloach** [comment]
Aha, got it! Unknown sources was still disabled for Firefox, and the error message was extremely unhelpful.

Marking this closed :)

**Comment by X1nto** [comment]
Seems like your ROM's package manager is messed up and reports incorrect error messages. Glad to see you found the cause
