### ISSUE TITLE
Enhancement : include change log when updating manager

### ISSUE THREAD

**Issue by cl-ement05** [YTVanced/VancedManager#437]
On older versions, change log for the manager was displayed and I used to like it why did you remove it ?

**Comment by X1nto** [comment]
3 dot menu > About > click version card > see changelog

**Comment by cl-ement05** [comment]
> 3 dot menu > About > click version card > see changelog

Well when I click the Verizon card nothing happened (except developer mode being enabled after multiple taps on the card)

**Comment by X1nto** [comment]
> > 3 dot menu > About > click version card > see changelog
> 
> Well when I click the Verizon card nothing happened (except developer mode being enabled after multiple taps on the card)

I meant 3 dot menu in manager lmfao

**Comment by X1nto** [comment]
If it doesn't open the menu, it means you clicked the wrong card. You should click the card that has gradient

**Comment by cl-ement05** [comment]
> > > 3 dot menu > About > click version card > see changelog
> > 
> > Well when I click the Verizon card nothing happened (except developer mode being enabled after multiple taps on the card)
> 
> I meant 3 dot menu in manager lmfao

Yeah sorry lol gboard auto correcting words it shouldn't. I am actually in the manager app and like nothing happens in the about page when I click the version card

**Comment by X1nto** [comment]
I just noticed the card doesn't respond to clicks, reopening this issue

**Comment by cl-ement05** [comment]
> If it doesn't open the menu, it means you clicked the wrong card. You should click the card that has gradient

This is exactly what I am doing. Clicking the card with version 2.5.1 shown and weed code name

**Comment by cl-ement05** [comment]
> I just noticed the card doesn't respond to clicks, reopening this issue

Oh ok thx

**Comment by X1nto** [comment]
fixed in 5583674

**Comment by X1nto** [comment]
Closed by accident
