### ISSUE TITLE
no network connection

### ISSUE THREAD

**Issue by Badboy1982** [YTVanced/VancedManager#439]
From two days it was doing good but after that it can't load but saying no internet connection . I used another network and my mobile data and nothing change at all

**Comment by EmVeddii** [comment]
Having this problem too. ever since the newest update. But it happened before I updated it too. Thought that was the issue but it persisted after update. Tried normal youtube on website and that's fine. Its the app not youtube

**Comment by X1nto** [comment]
A. Not manager related
B. No bug report template

**Comment by szaboariel** [comment]
![Screenshot_20210305_092356_com.vanced.android.youtube.jpg](https://user-images.githubusercontent.com/76839289/110088003-9eee9600-7d94-11eb-9fd8-78c9122c351f.jpg)![Screenshot_20210305_092412_com.vanced.android.apps.youtube.music.jpg](https://user-images.githubusercontent.com/76839289/110088016-a2821d00-7d94-11eb-85fa-96f19e39e884.jpg)

Pls help me. How can I fix this problem?
I have network
