### ISSUE TITLE
Poco X3 NFC - INSTALL_FAILED_INTERNAL_ERROR: Permission Denied

### ISSUE THREAD

**Issue by Blackcatz1911** [YTVanced/VancedManager#440]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced/Music)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisations

**Phone Specifications:**
- Brand: Poco X3 NFC
- Operating System: MIUI Global 10.0.8
- Android Version: 10 QKQ1.200512.002
- Vanced Manager Version: 2.5.1

**Please describe the problem you are having in as much detail as possible:**
When trying to install MicroG the following error appears: 
INSTALL_FAILED_INTERNAL_ERROR: Permission Denied

I get no permission popup. Manually granted Disk permissions and to install from unknown sources.

**Steps to reproduce:**
1. Download Vanced Manager from https://vancedapp.com.
2. Install Vanced Manager
3. Try to install MicroG
4. Error message

**Further details:**
Manually granted  the permission because no request was sent.

**Comment by X1nto** [comment]
disable miui optimizations
