### ISSUE TITLE
ViewPager in welcome screen does not work with RTL languages

### ISSUE THREAD

**Issue by aviv926** [YTVanced/VancedManager#441]
The problem: 
I installed the latest version, YouTube vanced And when you click "Start" (which Hebrew is the default language on the device) it does not go to the next installation window. 

How to solve the problem:

Only when changing the language of the phone to English it works and lets install

**Comment by X1nto** [comment]
Provide a screen record please

**Comment by masrati89** [comment]
Uploading IMG_1236.MP4…

**Comment by X1nto** [comment]
> Uploading IMG_1236.MP4…

Well, that's just a text 😄. use Google Drive or something other

**Comment by masrati89** [comment]
😆
https://drive.google.com/file/d/1Gl4Ybemi4R6QDVoHjTYqLRc84cWKznpy/view?usp=drivesdk

**Comment by X1nto** [comment]
I doubt it's language-related, just try restarting your phone

**Comment by aviv926** [comment]
> I doubt it's language-related, just try restarting your phone

It is 100% language related, the way **to solve this problem** is to switch the phone to English and install the app and then return to Hebrew.

It could be that when someone translated the app into Hebrew, he changed something in the source code of the app

**Comment by X1nto** [comment]
> > I doubt it's language-related, just try restarting your phone
> 
> It is 100% language related, the way **to solve this problem** is to switch the phone to English and install the app and then return to Hebrew.
> 
> It could be that when someone translated the app into Hebrew, he changed something in the source code of the app

You can't change source code when changing string resources, it's not how languages work. I'll try to debug this but won't really guarantee anything

**Comment by X1nto** [comment]
Found the issue, any RTL language is affected because, as always, Android is shit. I'll try something

**Comment by aviv926** [comment]
> Found the issue, any RTL language is affected because, as always, Android is shit. I'll try something

Thanks

**Comment by X1nto** [comment]
Fixed: 85e2d0c5c25ab379895d25e11dbc0afaffe17ff7

**Comment by aviv926** [comment]
> Fixed: 85e2d0c5c25ab379895d25e11dbc0afaffe17ff7

Thanks.

**Comment by snirtz** [comment]
I've got the same problem in the newest version 
https://drive.google.com/file/d/1iScD8QR4Ab5_JjOQOPdqiwsZlRRiJ8uC/view?usp=drivesdk

**Comment by X1nto** [comment]
Fixed in 2.6.0
