### ISSUE TITLE
Huawei access software is not normal

### ISSUE THREAD

**Issue by GDKVIP** [YTVanced/VancedManager#444]
Huawei Android 11, every time you open it will say the network is not connected (there is no problem with the network), no matter how to refresh it doesn't work.
The solution: clear the data or reload, and then you can enter normally
I don't know if anyone has the same problem with me, please solve it

![Screenshot_20210306_234140_com vanced android youtube](https://user-images.githubusercontent.com/59302521/110212574-fbf26500-7ed6-11eb-8f77-c83ebf20202b.png)

**Comment by X1nto** [comment]
Again, not related to vanced manager
