### ISSUE TITLE
Not able to install from a secondary account on the same device

### ISSUE THREAD

**Issue by zhimingmo** [YTVanced/VancedManager#445]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced/Music)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisations

**Phone Specifications:**
- Brand: Samsung
- Operating System: OneUI 3.1
- Android Version: 11
- Vanced Manager Version: 2.5.1 weed

**Please describe the problem you are having in as much detail as possible:**
Unknown source install and storage permission manually allowed in system settings.
Vanced Manager can be properly installed in the primary user account. But once switch to a secondary account, non-root.apk downloads fine but cannot be installed. 

Key issue from log: "...you need INTERACT_ACROSS_USER permission, etc."

See log attached for details.

**Steps to reproduce:**
![Screenshot_20210308-183625_Vanced Manager](https://user-images.githubusercontent.com/80294120/110396005-37a73f00-803d-11eb-8a56-cbf1103c3c97.jpg)

**Further details:**

**Comment by X1nto** [comment]
It needs to be an admin account if you want to install apps from manager, it's just his android works
