### ISSUE TITLE
Manager not uninstalling non-root apps when switching to root

### ISSUE THREAD

**Issue by cl-ement05** [YTVanced/VancedManager#448]
**Phone Specifications:**
- Brand: Xiaomi
- Operating System: Pixel Experience
- Android Version: R11
- Vanced Manager Version: Weed 2.5.1

**Problem**
Vanced Manager does not uninstall non-root apps before installing root apps and this makes Root apps to bug (sign-in impossible maybe because MicroG installed ...)

**Steps to reproduce:**
1. First install at least one Vanced app (non-root version) from Vanced Manager
2. Then sign in to the installed app (google account)
3. Switch to root version in Vanced Manager
4. Install the app you installed but in the root version

**Further details:**
Moreover, this is confusing for the user since it is impossible to find out which app is which version (unless you to settings and check the package name but this is time-consuming and not intuitive)

**Comment by X1nto** [comment]
uhh, what? root versions can work absolutely fine with non-root versions, Manager should NEVER EVER EVER uninstall nonroot when switching to root and vice-versa. Your bug is caused by something different, not microG.

**Comment by cl-ement05** [comment]
> uhh, what? root versions can work absolutely fine with non-root versions, Manager should NEVER EVER EVER uninstall nonroot when switching to root and vice-versa. Your bug is caused by something different, not microG. 

Well why shouldn't the Manager the already installed apps ? Like I said I believe this is hugely non-inuitive and it makes no sense to have the exact same app installed two times on your phone

**Comment by X1nto** [comment]
> > uhh, what? root versions can work absolutely fine with non-root versions, Manager should NEVER EVER EVER uninstall nonroot when switching to root and vice-versa. Your bug is caused by something different, not microG. 
> 
> Well why shouldn't the Manager the already installed apps ? Like I said I believe this is hugely non-inuitive and it makes no sense to have the exact same app installed two times on your phone

Why should it uninstall? That doesn't make any sense, uninstalling will wipe user data, what if user wants to keep nonroot versions, just in case something goes wrong with root version and vice versa?
