### ISSUE TITLE
Venced manager don't download anything

### ISSUE THREAD

**Issue by XSilverTH** [YTVanced/VancedManager#457]
This shows this when I download the program
![Screenshot_20210323-004104_Vanced Manager](https://user-images.githubusercontent.com/71408233/112052743-17b16880-8b71-11eb-8026-4ee995044062.jpg)

**Comment by X1nto** [comment]
Turn off the vpn and try again

**Comment by X1nto** [comment]
> Go to "About", tap and unlock dev options. Then click on settings and you will see a gear, click on it. Go to channel url and change "v1" to "v2"

There's no such thing as API v2 on Vanced servers

**Comment by fargotable** [comment]
> > Go to "About", tap and unlock dev options. Then click on settings and you will see a gear, click on it. Go to channel url and change "v1" to "v2"
> 
> There's no such thing as API v2 on Vanced servers

So why after such a change to V2 everything works and downloads normally, and not with V1?

**Comment by X1nto** [comment]
> > > Go to "About", tap and unlock dev options. Then click on settings and you will see a gear, click on it. Go to channel url and change "v1" to "v2"
> > 
> > 
> > There's no such thing as API v2 on Vanced servers
> 
> So why after such a change to V2 everything works and downloads normally, and not with V1?

No idea lol

**Comment by fargotable** [comment]
> > > > Go to "About", tap and unlock dev options. Then click on settings and you will see a gear, click on it. Go to channel url and change "v1" to "v2"
> > > 
> > > 
> > > There's no such thing as API v2 on Vanced servers
> > 
> > 
> > So why after such a change to V2 everything works and downloads normally, and not with V1?
> 
> No idea lol

However, after deleting "1" or "2" and leaving only "V" alone, the download suddenly starts working ¯\_(ツ)_/¯

**Comment by X1nto** [comment]
> > > > > Go to "About", tap and unlock dev options. Then click on settings and you will see a gear, click on it. Go to channel url and change "v1" to "v2"
> > > > 
> > > > 
> > > > There's no such thing as API v2 on Vanced servers
> > > 
> > > 
> > > So why after such a change to V2 everything works and downloads normally, and not with V1?
> > 
> > 
> > No idea lol
> 
> However, after deleting "1" or "2" and leaving only "V" alone, the download suddenly starts working ¯_(ツ)_/¯

that is definitely not supposed to happen, I'll talk with backend devs

**Comment by Kazeshinu** [comment]
Might wanna check the app permissions for storage.

**Comment by X1nto** [comment]
> Might wanna check the app permissions for storage. 

Manager doesn't require any permissions as of now

**Comment by Kazeshinu** [comment]
> > Might wanna check the app permissions for storage.
> 
> Manager doesn't require any permissions as of now

![Screenshot_20210325-182215_Vanced_Manager](https://user-images.githubusercontent.com/12010903/112515991-16fa1b80-8d97-11eb-8d9c-01fdd59228df.png)
I had to enable storage permissions for it to be able to download

**Comment by X1nto** [comment]
> > > Might wanna check the app permissions for storage.
> > 
> > 
> > Manager doesn't require any permissions as of now
> 
> ![Screenshot_20210325-182215_Vanced_Manager](https://user-images.githubusercontent.com/12010903/112515991-16fa1b80-8d97-11eb-8d9c-01fdd59228df.png)
> I had to enable storage permissions for it to be able to download

Only if you're on android 5

**Comment by Kazeshinu** [comment]
> > > > Might wanna check the app permissions for storage.
> > > 
> > > 
> > > Manager doesn't require any permissions as of now
> > 
> > 
> > ![Screenshot_20210325-182215_Vanced_Manager](https://user-images.githubusercontent.com/12010903/112515991-16fa1b80-8d97-11eb-8d9c-01fdd59228df.png)
> > I had to enable storage permissions for it to be able to download
> 
> Only if you're on android 5

![Screenshot_20210325-190033_Vanced_Manager](https://user-images.githubusercontent.com/12010903/112521137-7575c880-8d9c-11eb-8f8f-cfe0f79b7be0.png)

And I'm on 8

Could be with the rom I'm running. But it required me to enable storage permissions to download.

**Comment by XSilverTH** [comment]
Ok it's fixed
I was using a ported ROM and the software did not work I thought the problem was my ROM, so I installed another ROM, which was also a port ROM So I thought there was a software bug and I came here to raise it today I installed a aosp based rom and tested Vance's manager again and it's fixed
Thanks to everyone who tried to help

**Comment by XSilverTH** [comment]
Ok it's fixed
I was using a ported ROM and the software did not work I thought the problem was my ROM, so I installed another ROM, which was also a port ROM So I thought there was a software bug and I came here to raise it today I installed a aosp based rom and tested Vance's manager again and it's fixed
Thanks to everyone who tried to help
