### ISSUE TITLE
Layout bug on latest debug build

### ISSUE THREAD

**Issue by Oizaro** [YTVanced/VancedManager#458]
@X1nto There's a problem with accent color window. Reset and Save buttons aren't visible at all.

<img src="https://i.ibb.co/r7GT7qJ/Screenshot-20210322-231002-Vanced-Manager.png">

**Comment by Oizaro** [comment]
Personal idea:

Move hex color textbox to the center of colors palette selectors and move the buttons Reset and Save to the freed up space.

**Comment by X1nto** [comment]
Use the bug template and please avoid tagging me, I'll look into the issue whenever possible
