### ISSUE TITLE
Black is light and light is black

### ISSUE THREAD

**Issue by umuchique** [YTVanced/VancedManager#46]
I have a screen recorder proof. Maybe it's a translation issue but I'm 100% positive that it's present. 
I'm using non-root and the language is french.

**Comment by X1nto** [comment]
I don't understand what light and black are you talking about. Is it about themes in manager? Or what

**Comment by KevinX8** [comment]
translation issues should be pushed here http://vanced.oneskyapp.com/ , I will update the french translation for now. Please read the strings xml before blaming the manager on issues thanks

**Comment by umuchique** [comment]
[Here is the link to my video in Google drive](https://drive.google.com/file/d/1FIXi2SGxwyiqQl_Z8Lep-u-NR8TIr6Au/view?usp=drivesdk)

**Comment by umuchique** [comment]
When downloading the YouTube vanced app, the manager asks for either dark or black. It's mixed up : when clicking on dark it installs black and the other way around

**Comment by X1nto** [comment]
French translator messed up values, we'll fix that

**Comment by KevinX8** [comment]
yes we understand, french translation will be removed from next version as it's incomplete on oneskyapp
