### ISSUE TITLE
Unable to Install Youtube Vanced Signature Error

### ISSUE THREAD

**Issue by krishankit3820** [YTVanced/VancedManager#461]
I am using the latest version
This is an issue in the Vanced Manager app.
This issue keeps re-occurring every time I try install vanced on my one plus oxygen OS 11

Vanced Manager Version: 2.5.1 (Weed)
Please describe the problem you are having in as much detail as possible:

When ever I try to install Youtube Vanced I get Failure, screen shot below-

Steps to reproduce:
Youtube installed as a System App
Install Youtube Vanced from VancedManager using root method

![WhatsApp Image 2021-03-24 at 2 35 57 PM](https://user-images.githubusercontent.com/81295824/112284525-59e0c400-8caf-11eb-881c-1adcad10b21f.jpeg)

can someone help me to fix this

**Comment by krishankit3820** [comment]
@X1nto  please suggest...Thanks

**Comment by X1nto** [comment]
Follow this: https://github.com/YTVanced/VancedManager/issues/346#issuecomment-763707884

**Comment by krishankit3820** [comment]
@X1nto Thanks a ton.. solution worked for me.!
