### ISSUE TITLE
Missing languages

### ISSUE THREAD

**Issue by Ingrown29** [YTVanced/VancedManager#466]
**Phone Specifications:**
- Brand: Samsung
- Operating System: Samsung Experience 9.0
- Android Version: 8.0
- Vanced Manager Version: 2.5.1

**Please describe the problem you are having in as much detail as possible:**
When trying to download Youtube Vanced there is missing a lot of languages which are supported as I can see them listed in [here](https://www.mediafire.com/?9j7n5yisdlvyg). For example in the past I was able to select Slovak language but now there is any option to do that while installing. I also saw some other posts across the internet regarding this issue with other languages as well. When I tried to install older versions in which it worked, now it doesn't.

**Steps to reproduce:**
Try to install Youtube Vances and select for example Slovak version

**Further details:**
It seems this list of languages is web requested across all versions and something went wrong while getting the data.

**Comment by X1nto** [comment]
I'll take a look

**Comment by X1nto** [comment]
Slovak language was not translated through crowdin, hence there was no split for it. now that it was added, future versions will include Slovak too: https://crowdin.com/project/vanced/sk#
