### ISSUE TITLE
Vanced YouTube Not Working

### ISSUE THREAD

**Issue by Surya434501** [YTVanced/VancedManager#467]
Don't know why but from today morning my Youtube stopped working.I tried multiple troubleshooting steps from the guide app and tried re downloading and installing multiple times.Even after doing that i'm able to open the app and when i'm trying to sign in,the account doesnot get added and keeps showing the add account popup on the screen forever.
Below is the screenshot of the app
![Screenshot_20210326-090130](https://user-images.githubusercontent.com/81401112/112573960-56664d80-8e13-11eb-8e1b-f94d6b37eb3a.jpg)

**Comment by X1nto** [comment]
Not related to manager
