### ISSUE TITLE
[Bug] Vanced Manager autoupdates YTVanced

### ISSUE THREAD

**Issue by entitleduser88** [YTVanced/VancedManager#468]
**Phone Specifications:**
- Brand: Motorola Moto G8 Power (Root)
- Operating System: Android
- Android Version: 10
- Vanced Manager Version: 2.5.1

**Problem Description**

Vanced Manager automatically updates the YTVanced version to the newest one and that is a problem for me.

The latest version of YTVanced (16.02.35) available on the Vanced Manager does not work for me (Youtube doesn't open). 

So, using the Vanced Manager I reinstalled an older version (15.43.32) and this one works just fine. The thing is that every day the Vanced Manager autoupdates YTVanced to the newer version and YTVanced stops working again, so I have to go to the manager and reinstall the older version that works. I have to do this every day, it is very annoying. There is no way to disable this autoupdate, I have searched.

**Further details:**
My phone is rooted.
I don't know how to make a logcat and the link to the guide is broken.

**Comment by Ghe1030** [comment]
Same issue. After I update the vanced app, (vanced manager &YouTube vanced) I cannot able to sign in my Google account in YouTube vanced 
![Screenshot_20210327_131131_com mgoogle android gms](https://user-images.githubusercontent.com/81457855/112710678-01533600-8efe-11eb-98ee-cc16b2f44894.jpg)

My phone is Huawei Nova 7i

**Comment by X1nto** [comment]
Manager can't and won't auto-update, it's more likely that play store auto-updates your Vanced to stock youtube, thus breaking Vanced
