### ISSUE TITLE
Loading problem, Huawei 

### ISSUE THREAD

**Issue by Gabita2000** [YTVanced/VancedManager#473]
Hello, i have problem with my yt vanced, i connect to my google account using Huawei buton, i have Huawei P40 Lite 5G,without google services.. Now my YouTube is loading constantly.. Any fix?
Sorry for my bad english. Thx.
![Screenshot_20210326_211021_com vanced android youtube](https://user-images.githubusercontent.com/57462903/112811325-9da74500-9084-11eb-9600-04595c051030.jpg)

**Comment by X1nto** [comment]
not related to manager
