### ISSUE TITLE
Vanced cannot start

### ISSUE THREAD

**Issue by sombresu** [YTVanced/VancedManager#474]
- For MIUI users: I disabled MIUI optimisations

**Phone Specifications:**
- Brand: Xiaomi Poco X3
- Operating System: Miui 12
- Android Version: Android 10
- Vanced Manager Version: Latest

**Please describe the problem you are having in as much detail as possible:**

**Steps to reproduce:**
Start vanced

**Further details:**
Video thumbnails not loaded, only blank screen

![Screenshot_2021-03-30-11-23-47-242_com.vanced.android.youtube.jpg](https://user-images.githubusercontent.com/62043417/112934207-75364e00-914b-11eb-84a2-c9e715b2480a.jpg)

**Comment by X1nto** [comment]
Not related to manager
