### ISSUE TITLE
APK Signature Different, Can Not Upgrade Vanced Manager

### ISSUE THREAD

**Issue by SubZero5** [YTVanced/VancedManager#476]
**Please describe the problem you are having in as much detail as possible:**
Can not install Vanced Manager because the old signature was different with the new pre-release version:

The signature for Vanced Manager 2.5.1 was:
CN=YouTube Vanced, OU=eventHorizon, O=eventHorizon, L=XDA, ST=Unknown, C=Unknown
CRC32: 7d4133cb
MD5: ea7b533e1dbebbb450ce5e52948caabc
SHA1: 2ef45415813d0954e4944a2d53a38e2651cd1172
SHA256: 8b1dfe07a73975ea964192555492e1fe1c8cf4f3490063865ebe3f6bdfbe597d
SHA384: 97dcd811858073e89d75de2ef35de5bed07dc4245b0d24559bd5e09ffc66249a940e85062c49ca5fe77dfa77df555d20
SHA512: 11c44d08e28087c1a6003d98eea9e73fcd6fd0e3a5675e9414a452478fd464c37cf31f00c87a32b50b44d204e9c69bfe1910c525ae4bdfc9e1e0d421ed6eb1f6

The signature for Vanced Manager 2.6.9 is:
CN=*** ****, OU=VancedCoin, O=Vanced, L=Tbilisi, ST=Georgia, C=GE
CRC32: 1338ea11
MD5: a9b68263b74edfa64424bf8e718f878f
SHA1: 120e0902ce06b364c8bedcad5c8af1778b253e50
SHA256: 9e325d1299e1706c0a850d2d7a1049a5f4c27983777a824a947615397bb05b35
SHA384: a7eea4ef97f3e69b4566011a4d35196ec14f2138f4c95aa8c9c345259ae0cdc09ec426e514275021aed24539a778db0e
SHA512: c86e44ec887139cb20d9d0fa22f223e3359def1887db0775083e81af53203ad1662911e4ee8d08757b36e9cc52af1b070ce96f34c864ae2fe147afcc166f929a

**Steps to reproduce:**
😣

**Further details:**
Shouldn't the release keys be the same with every release?

**Comment by X1nto** [comment]
It's a beta release, it was intended to have a different signature

**Comment by X1nto** [comment]
Just uninstall previous version before installing this one

**Comment by SubZero5** [comment]
It is strange that you release an APK with a different signature. Until now, every release I saw in Android world had the exact same signing certificate even if it was a nightly. I simply do not understand why on earth you have released an APK with a different signature.

**Comment by X1nto** [comment]
> It is strange that you release an APK with a different signature. Until now, every release I saw in Android world had the exact same signing certificate even if it was a nightly. I simply do not understand why on earth you have released an APK with a different signature.

For god's sake, it has a different signature because it's an April fools joke. It was never meant to be released as a direct update but rather as a separate app
