### ISSUE TITLE
Can't use Vanced Manager if storage access are not permitted 

### ISSUE THREAD

**Issue by Cris--** [YTVanced/VancedManager#477]
Hi,

installed Vanced Manager 2.6.9 today with the new YT videos download option but didn't need it so i want to permitted the media access . But can't use VM then, VM is blocks the gui without this permission.

**Comment by KevinX8** [comment]
Why wouldn't you want to use the amazing new revolutionary feature? ~~check the date~~

**Comment by X1nto** [comment]
> Hi,
> 
> installed Vanced Manager 2.6.9 today with the new YT videos download option but didn't need it so i want to permitted the media access . But can't use VM then, VM is blocks the gui without this permission.

Storage access is not only for video downloading, APK and logfiles are also stored in the internal storage because of file explorer limitations on android 11.

**Comment by Cris--** [comment]
mmh, previous VM version works normal on LOS18.1 A11!

**Comment by X1nto** [comment]
> mmh, previous VM version works normal on LOS18.1 A11 for me!

Well, now it got changed to give users more access over downloaded APKs. Storage permission is only needed to store files, no personal data is being read anyways. Either way that version was an April fools version so it doesn't even matter
