### ISSUE TITLE
No recent translations in 2.6.9

### ISSUE THREAD

**Issue by foreveryoungforty** [YTVanced/VancedManager#478]
I made and corrected a lot of Dutch translations via Crowdin on 19 march, but i see that they are not in the newly released 2.6.9 version of today 1 april.
The new string Uninstall Vanced Manager is not on Crowdin.
Thanks.

**Comment by KevinX8** [comment]
Google what happens on April first

**Comment by foreveryoungforty** [comment]
😀😛

**Comment by X1nto** [comment]
2.6.9 base is grabbed from the master branch, which does not have recent translations
