### ISSUE TITLE
New age verification process for european users

### ISSUE THREAD

**Issue by kineci** [YTVanced/VancedManager#479]
Apparently, there is a new process European users (EU) need to do to watch videos with an age restriction. You have to either make a copy of your ID-Card or type in your credit card information. I'm not even thinking about giving Google this sensitive information. Can or have you implemented a feature on YouTube Vanced to bypass this.

PS: Strangely only happens on the original YouTube App and the Vanced App. On Browsers it's working with the same Account logged in. Maybe got something to do with AdBlock? 🤔

Thanks
![Screenshot_20210401-023046~2](https://user-images.githubusercontent.com/78767752/113436106-63bba300-93e4-11eb-83f5-c70886ee4bb4.jpg)

Source: 
https://support.google.com/youtube/answer/10070779?hl=en#zippy=%2Cif-youre-in-the-european-union-eu-european-economic-area-eea-switzerland-or-united-kingdom

**Comment by X1nto** [comment]
not related to manager
