### ISSUE TITLE
Vanced Manager crashes on opening app

### ISSUE THREAD

**Issue by emmapaige111** [YTVanced/VancedManager#48]
Title. The Vanced logo appears and then it immediately closes.

Edit: I'm on Manager hotfix v1.0.2 using Android 10 on a Samsung Galaxy A50.

**Comment by X1nto** [comment]
Send a logcat please

**Comment by KevinX8** [comment]
did you try clearing data

**Comment by emmapaige111** [comment]
> did you try clearing data

This worked. Thank you.
