### ISSUE TITLE
YouTube Music Needs Update

### ISSUE THREAD

**Issue by Mike808James** [YTVanced/VancedManager#481]
In Vanced manager (latest version) it says that the latest version of YouTube Music is version 4.18.50, however in Google Play Store YouTube Music is on version 4.21.50 as of March 18, 2021. Please update this in Vanced manager. Thank you.

**Comment by KevinX8** [comment]
It doesn't _need_ an update, Google changes almost nothing each update and they make one every week, I'm not sure what benefit there is to bumping up the version number for bumping sake but to each their own I guess.

**Comment by Mike808James** [comment]
Hi, Kevin. The reason it needs an update is because it breaks one of my
favorite features when it's not up to date, and that is the feature that
allows you to select a youtube music song as an alarm tone on an Android
smartphone.

**Comment by KevinX8** [comment]
No that's because it has a different package name from stock music, the only fix is to uninstall stock music and repackage vanced music with the same package id

**Comment by X1nto** [comment]
Or just use the root version of Music Vanced
