### ISSUE TITLE
Older version install for MicroG login

### ISSUE THREAD

**Issue by rogama25** [YTVanced/VancedManager#484]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server: Yes
- I am using the latest version: Yes
- This is an issue in the Vanced Manager app (NOT Youtube Vanced/Music): Yes
- This issue keeps re-occurring every time I try: Yes. It only behaves in a different way if you already have installed Vanced and then uninstalled it.
- For MIUI users: I disabled MIUI optimisations: Don't have MIUI

**Phone Specifications:**
- Brand: Xiaomi A2 Lite
- Operating System: SyberiaOS v4.4 (Android)
- Android Version: 11
- Vanced Manager Version: 2.5.1 (Weed)

**Please describe the problem you are having in as much detail as possible:**
A few versions ago, you started installing an older version of YT and YT Music to be able to log in with MicroG before allowing you to install the latest version, but Google fixed that and this is no longer needed

**Steps to reproduce:**
* Install Vanced Manager.
* Install MicroG.
* Try to install Youtube or Music
* Popup appears asking you to install an older version. There is no way to force-install latest without installing previously this older version.
* Without logging in, update the app to latest and it still works.

**Further details:**
https://t.me/Vanced/139

**Comment by X1nto** [comment]
It is still needed because vanced hasn't been updated to include the fix from stock youtube

**Comment by rogama25** [comment]
Well, it actually was fixed because I just logged in directly into the latest version without even opening that older version, as it was said on the official Telegram message I linked in the issue

**Comment by X1nto** [comment]
> Well, it actually was fixed because I just logged in directly into the latest version without even opening that older version, as it was said on the official Telegram message I linked in the issue

Only Music is fixed, YT is not, thus, we are keeping the warning
