### ISSUE TITLE
Can't install youtube vanced.

### ISSUE THREAD

**Issue by AGou-ops** [YTVanced/VancedManager#486]
Can't install youtube vanced on my phone.

- Android version: 11（CPU: snapdrogan 870）
- vanced manager version: 2.5.1
- microg version: 0.2.18.210390

The error log is as follows:

![Screenshot_20210407_204555](https://user-images.githubusercontent.com/57939102/113869133-f2fcf800-97e2-11eb-90a9-0269ce1bed6d.jpg)

How should I solve it?

**Comment by X1nto** [comment]
Sounds like a problem with your ROM rather than Manager, I doubt it's possible to fix that. Are you the guy from Telegram by with OriginOS any chance?

**Comment by AGou-ops** [comment]
> Sounds like a problem with your ROM rather than Manager, I doubt it's possible to fix that. Are you the guy from Telegram with OriginOS by any chance?

Not me. 
Yes, my ROM is OriginOS. And I found an interesting question, I cannot give full storage permission to vanced manager, just media only access, it is very odd.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/57939102/113873420-6274e680-97e7-11eb-9a8f-3c6d400c0660.gif)

**Comment by X1nto** [comment]
> > Sounds like a problem with your ROM rather than Manager, I doubt it's possible to fix that. Are you the guy from Telegram with OriginOS by any chance?
> 
> Not me.
> Yes, my ROM is OriginOS. And I found an interesting question, I cannot give full storage permission to vanced manager, just media only access, it is very odd.
> ![ezgif com-gif-maker](https://user-images.githubusercontent.com/57939102/113873420-6274e680-97e7-11eb-9a8f-3c6d400c0660.gif)

As of now, it doesn't need any storage permissions anyways, but the fact that your ROM doesn't even properly emulate Android Q stuff makes me think that OriginOS is a piece of crap

**Comment by AGou-ops** [comment]
> > > Sounds like a problem with your ROM rather than Manager, I doubt it's possible to fix that. Are you the guy from Telegram with OriginOS by any chance?
> > 
> > 
> > Not me.
> > Yes, my ROM is OriginOS. And I found an interesting question, I cannot give full storage permission to vanced manager, just media only access, it is very odd.
> > ![ezgif com-gif-maker](https://user-images.githubusercontent.com/57939102/113873420-6274e680-97e7-11eb-9a8f-3c6d400c0660.gif)
> 
> As of now, it doesn't need any storage permissions anyways, but the fact that your ROM doesn't even properly emulate Android Q stuff makes me think that OriginOS is a piece of crap

I just joined telegram group, and I found that I have the same problem as him. I have no idea to solve it.

Thank you anyway.

**Comment by X1nto** [comment]
> 
> I just joined telegram group, and I found that I have the same problem as him. I have no idea to solve it.
> 
> Thank you anyway.

Sorry for not being able to solve this, I don't really have a device to test/debug this on and I'm not even sure what could be wrong

**Comment by AGou-ops** [comment]
> > I just joined telegram group, and I found that I have the same problem as him. I have no idea to solve it.
> > Thank you anyway.
> 
> Sorry for not being able to solve this, I don't really have a device to test/debug this on and I'm not even sure what could be wrong

I know your feeling. EXCELLENT project. Thanks again.

**Comment by Delphox** [comment]
Has you/or the Telegram guy tried to install via SAI? Think it's worth a shot, in case they solved this issue themselves.

(get the apks for SAI [here](https://mirror.codebucket.de/vanced/api/v1/apks/v15.43.32/nonroot/)).

**Comment by X1nto** [comment]
> Has you/or the Telegram guy tried to install via SAI? Think it's worth a shot, in case they solved this issue themselves.
> 
> (get the apks for SAI [here](https://mirror.codebucket.de/vanced/api/v1/apks/v15.43.32/nonroot/)).

Might be worth trying

**Comment by AGou-ops** [comment]
> Has you/or the Telegram guy tried to install via SAI? Think it's worth a shot, in case they solved this issue themselves.
> 
> (get the apks for SAI [here](https://mirror.codebucket.de/vanced/api/v1/apks/v15.43.32/nonroot/)).

Ah... It doesn't work. Same error as Vanced manager.
![Screenshot_2021_0408_194750](https://user-images.githubusercontent.com/57939102/114021954-d96fb500-98a3-11eb-8c51-7565d65c10e6.gif)

The error as follows:

```
INSTALL_FAILED_ABORTED: User rejected permissions
INSTALL_PARSE_FAILED_NOT_APK: Failed parse during installPackageLI: Failed to parse /data/app/vmdl840090973.tmp: Failed to load asset path /data/app/vmdl840090973.tmp
```

**Comment by AGou-ops** [comment]
> > Has you/or the Telegram guy tried to install via SAI? Think it's worth a shot, in case they solved this issue themselves.
> > (get the apks for SAI [here](https://mirror.codebucket.de/vanced/api/v1/apks/v15.43.32/nonroot/)).
> 
> Might be worth trying

oh... I can install `youtube blue`（YouTube_14.21.54_API19） from http://bit.ly/mfdownload .

![Screenshot_20210408_201537](https://user-images.githubusercontent.com/57939102/114025463-b7783180-98a7-11eb-8b9d-77bee6ab7593.jpg)

**Comment by Delphox** [comment]
Hmm, I guess as last resort you could try installing the split APK via adb. It's a long shot but we don't really have anything else. [I found this guide online that looks straightforward enough](https://raccoon.onyxbits.de/blog/install-split-apk-adb/).

As for 14.21, it's probably not worth bothering with it anyway since it's almost a year old now so Google is on the verge of blocking it.

**Comment by AGou-ops** [comment]
> Hmm, I guess as last resort you could try installing the split APK via adb. It's a long shot but we don't really have anything else. [I found this guide online that looks straightforward enough](https://raccoon.onyxbits.de/blog/install-split-apk-adb/).
> 
> As for 14.21, it's probably not worth bothering with it anyway since it's almost a year old now so Google is on the verge of blocking it.

Installed, but it does not work.
![Uploading Screenshot_2021_0410_172400.gif…]()

**Comment by Delphox** [comment]
> > Hmm, I guess as last resort you could try installing the split APK via adb. It's a long shot but we don't really have anything else. [I found this guide online that looks straightforward enough](https://raccoon.onyxbits.de/blog/install-split-apk-adb/).
> > As for 14.21, it's probably not worth bothering with it anyway since it's almost a year old now so Google is on the verge of blocking it.
> 
> Installed, but it does not work.
> ![Screenshot_2021_0410_172400](https://user-images.githubusercontent.com/57939102/114265180-ff22c880-9a21-11eb-9a4f-241c94d61157.gif)

Hey that's progress!! My guess is that maybe one of the parts didn't install.

You can check what parts installed using the adb command `adb shell pm path com.vanced.android.youtube` which will outputs the apks installed.

**Comment by X1nto** [comment]
> > Hmm, I guess as last resort you could try installing the split APK via adb. It's a long shot but we don't really have anything else. [I found this guide online that looks straightforward enough](https://raccoon.onyxbits.de/blog/install-split-apk-adb/).
> > As for 14.21, it's probably not worth bothering with it anyway since it's almost a year old now so Google is on the verge of blocking it.
> 
> Installed, but it does not work.
> ![Screenshot_2021_0410_172400](https://user-images.githubusercontent.com/57939102/114265180-ff22c880-9a21-11eb-9a4f-241c94d61157.gif)

it crashes because there's probably no microG installed

**Comment by AGou-ops** [comment]
> > > Hmm, I guess as last resort you could try installing the split APK via adb. It's a long shot but we don't really have anything else. [I found this guide online that looks straightforward enough](https://raccoon.onyxbits.de/blog/install-split-apk-adb/).
> > > As for 14.21, it's probably not worth bothering with it anyway since it's almost a year old now so Google is on the verge of blocking it.
> > 
> > 
> > Installed, but it does not work.
> > ![Screenshot_2021_0410_172400](https://user-images.githubusercontent.com/57939102/114265180-ff22c880-9a21-11eb-9a4f-241c94d61157.gif)
> 
> Hey that's progress!! My guess is that maybe one of the parts didn't install.
> 
> You can check what parts installed using the adb command `adb shell pm path com.vanced.android.youtube` which will outputs the apks installed.

Also installed MicroG, but it crashes too. But I find an apk package from [【hostapk】 youtube vanced](https://hostapk.com/youtube-vanced/), and I installed 15.38.35 version, it works well.
Maybe originOS is not good enough to handle multiple apk packages? I don't know.
