### ISSUE TITLE
Italian translations issues

### ISSUE THREAD

**Issue by Oizaro** [YTVanced/VancedManager#49]
<b>"Installa di nuovo" is too long, can you change it with: "Reinstalla"?</b>

<img src="https://i.ibb.co/sqtJsxX/Screenshot-20200702-224855-Vanced-Manager.png" alt="Screenshot-20200702-224855-Vanced-Manager" border="0"></a>

<b>Missing translation</b>

<img src="https://i.ibb.co/tPcPYHt/20200702-225228.png">

**Comment by KevinX8** [comment]
![Screenshot_20200702-220709](https://user-images.githubusercontent.com/17335452/86409265-69972300-bcb0-11ea-8420-fe3810ad6330.jpg)
Can you read the readme next time thanks

**Comment by Oizaro** [comment]
@KevinX8 Sorry, my bad.

In any case I managed to correct only the one already translated on the platform, the untranslated one was not present and I cannot doing anything. :-/

**Comment by KevinX8** [comment]
Moved to crowdwin for translations
