### ISSUE TITLE
Unable to click "Let's get started" on Chromecast v4

### ISSUE THREAD

**Issue by p10tr3k** [YTVanced/VancedManager#490]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced/Music)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisations

**Phone Specifications:**
- Brand: Chromecast v4
- Operating System: Android
- Android Version: latest for this device
- Vanced Manager Version: 2.5.1

**Please describe the problem you are having in as much detail as possible:**
After installing, application start, there is this button "let's get started" but when pushing button on Chromecast pilot nothing happens.

**Steps to reproduce:**

**Further details:**

**Comment by p10tr3k** [comment]
I was able to install player when paired mouse to chromecast

**Comment by X1nto** [comment]
Not related to manager

**Comment by p10tr3k** [comment]
How so?
It is before installation of YTVanced.
I think this button should be focused

**Comment by X1nto** [comment]
Oops I closed the wrong issue. I apologize. Are you using a language other than English? If yes, then it might be related to #441

**Comment by p10tr3k** [comment]
Hmmm, in my case, I connected mouse to chromecast, and I was able to click
that button.

**Comment by X1nto** [comment]
> Hmmm, in my case, I connected mouse to chromecast, and I was able to click that button.

Well, since Chromecast is not officially supported by Vanced Manager, I guess that's the only way you can use Manager for now.
