### ISSUE TITLE
Java error when installing YouTube Vanced on rooted device

### ISSUE THREAD

**Issue by miguelogin** [YTVanced/VancedManager#492]
Sorry, can't copy the error message: [https://imgur.com/a/fgP08SI](url)

**Comment by Delphox** [comment]
This error usually happens when you have a non-Magisk root solution. Only Magisk is supported.

@X1nto would it be a good idea to catch those errors and warn ppl that only Magisk is supported (or at least make it more clear when granting root that only Magisk is supported).

**Comment by X1nto** [comment]
> This error usually happens when you have a non-Magisk root solution. Only Magisk is supported.
> 
> @X1nto would it be a good idea to catch those errors and warn ppl that only Magisk is supported (or at least make it more clear when granting root that only Magisk is supported).

Should be easy enough since we just need to check if the output string includes `FileNotFoundException", I'll take a look.
