### ISSUE TITLE
Battery draining

### ISSUE THREAD

**Issue by GmoQz** [YTVanced/VancedManager#494]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced/Music)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisations

**Phone Specifications:**
- Brand: Samsung Galaxy Note 10 plus (snapdragon) 
- Operating System: Android
- Android Version: 11 one ui 3.1
- Vanced Manager Version: 2.5.1

**Please describe the problem you are having in as much detail as possible:**

The YouTube music application is draining the battery, before it did not, but since the update of said application, my battery has run out and the temperature of my device rises.
![Screenshot_20210417-093429_Device care](https://user-images.githubusercontent.com/82715771/115116761-06396180-9f61-11eb-95f0-e99b058c7f4a.jpg)

**Comment by X1nto** [comment]
not related to manager
