### ISSUE TITLE
Can't update my YT music

### ISSUE THREAD

**Issue by NROLP** [YTVanced/VancedManager#497]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced/Music)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisations

**Phone Specifications:**
- Brand: Samsung A11
- Operating System: Android 10
- Android Version: 10
- Vanced Manager Version: Latest

**Please describe the problem you are having in as much detail as possible:**
I can't update my YT music from the vance Manager itsleft. Here are some pics of the error.

![Screenshot_20210419-030040_Vanced Manager](https://user-images.githubusercontent.com/74348285/115157579-9cce6580-a0bc-11eb-9b1a-2cfcc3c4a64c.jpg)
![Screenshot_20210419-030049_Vanced Manager](https://user-images.githubusercontent.com/74348285/115157578-9b04a200-a0bc-11eb-9a8a-54ec5dfe9709.jpg)

**Steps to reproduce:**

**Further details:**

**Comment by X1nto** [comment]
uninstall and install again, it was a problem with 4.07.18 version of music
