### ISSUE TITLE
Settings – flyout overlay visible after closing

### ISSUE THREAD

**Issue by Martin5001** [YTVanced/VancedManager#498]
If you open any flyout dialog in settings (such as language selection) and then swipe down to close it instead of tapping the empty space around, you'll see the darker overlay stays visible even after the flyout is closed. See screenshots:
![Screenshot_20210420-152830_Vanced Manager](https://user-images.githubusercontent.com/35201200/115404514-b0c5b480-a1ed-11eb-880b-c14b0957c4c7.jpg)
![Screenshot_20210420-152838_Vanced Manager](https://user-images.githubusercontent.com/35201200/115404546-b8855900-a1ed-11eb-8145-6e4405893bfc.jpg)
![Screenshot_20210420-152840_Vanced Manager](https://user-images.githubusercontent.com/35201200/115404573-bf13d080-a1ed-11eb-9ba9-657f429d9956.jpg)

**Comment by X1nto** [comment]
Fixed in 2.6.0
