### ISSUE TITLE
Can't download Youtube Vanced

### ISSUE THREAD

**Issue by doclikesmusic** [YTVanced/VancedManager#499]
![Screenshot_20210422-054020](https://user-images.githubusercontent.com/82985966/115639366-d0fc8d00-a32d-11eb-84d5-f51b66678596.jpg)
I just installed Android 11 on my phone and my original YouTube Vanced was gone. tried downloading with 2.5.1, no luck. tried downgrading to 2.5.0, it didn't help. device is non rooted.

**Comment by X1nto** [comment]
Follow https://github.com/YTVanced/VancedManager/issues/346#issuecomment-763707884
