### ISSUE TITLE
YouTube Vanced disappears after a day, resets back to regular YouTube app

### ISSUE THREAD

**Issue by timvisee** [YTVanced/VancedManager#501]
**Phone Specifications:**
- Brand: OnePlus 5
- Operating System: Lineage (cheeseburger)
- Android Version: 10
- Vanced Manager Version: 2.5.1

**Please describe the problem you are having in as much detail as possible:**

After installing YouTube Vanced through the Vanced Manager, the application (YouTube Vanced) constantly disappears after about a day. It is simply reset back to the YouTube app. Automatic updates are disabled in the Play Store for YouTube.

I can't seem to find what triggers this application reset. I did not restart my phone. It simply seems to happen randomly, but almost always within a day.

I decided to post this here as it might be related to an installation failure on Vanced Manager's end.

**Steps to reproduce:**

- Install Vanced Manager.
- Install YouTube Vanced through Vanced Manager with root method.
- Use YouTube Vanced.
- Wait for about a day.
- YouTube Vanced is gone, regular YouTube is back.

**Further details:**

I did come across this, which seems somewhat related, though this explicitly notes rebooting the phone and didn't provide a solution for me: https://github.com/YTVanced/VancedManager/issues/212

**Comment by X1nto** [comment]
It's a bug in the play store which automatically updates youtube to stock even if auto-updates are disabled for it. Not Manager's fault

**Comment by timvisee** [comment]
Thanks for the prompt response. Do you know any mitigation I can use to fix this, or do I simply have to wait.

**Comment by X1nto** [comment]
> Thanks for the prompt response. Do you know any mitigation I can use to fix this, or do I simply have to wait.

I can only think of 2 solutions:
1. Fully disable auto-updates (kinda meh)
2. Use nonroot version

**Comment by gghhkm** [comment]
> Thanks for the prompt response. Do you know any mitigation I can use to fix this, or do I simply have to wait.

3 alternative options.
You can use the Detach Magisk module.

You can disable Google Play store completely and use the alternative Aurora Store.

You can manually detach it by :
Force closing the play store
Using a database editor like sqlite, navigate to the playstore's library.db file, search for youtube and remove any instances of ownership of it.

**Comment by Delphox** [comment]
The first thing you should do is uninstall any pre-installed system app version of youtube with Debloater magisk module (also needs Busybox NDK if you don't have yet). Check if that's enough to stop the forced updates.

If it still disappears after a day, use TeMeFi detach feature, which is confirmed to work but also requires the app to not have any preinstalled system versison, so the above step should be done regardless.

**Comment by milindgoel15** [comment]
Adding more alternative solutions directly here to avoid people making duplicate issues again.

[Please read how to detach root variant from play store guide here](https://telegra.ph/Troubleshooting-for-vanced-03-19#Detach)
