### ISSUE TITLE
I cannot log-in in to the YouTube Vanced

### ISSUE THREAD

**Issue by oti4500** [YTVanced/VancedManager#502]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com] (https://vancedapp.com).
- I am using the latest version
- This issue keeps re-occurring every time I try

**Phone Specifications:**
- Brand: Samsung
- Model: Galaxy S10 (SM-G973F/DS)
- Operating System: Android 
- Android Version: 11
- Vanced Manager Version: 2.5.1

**Please describe the problem you are having in as much detail as possible:**
I cannot log-in to YT Vanced app, while I can log-in YT (Vanced) Music. I have deleted my account from microG and log-in to again. Nothing have changed. I have deleted the YT Vanced and reinstalled, after the microG uninstall and reinstalled. Nothing.

Photos:

In YT Vanced app
![Screenshot_20210423-044607](https://user-images.githubusercontent.com/58808646/115821248-c102ad00-a402-11eb-9e9b-5d95be8a59e6.jpg)
![Screenshot_20210423-044611](https://user-images.githubusercontent.com/58808646/115821266-c6f88e00-a402-11eb-8c29-63c498d90530.jpg)
While in YouTube (Vanced) Music
![Screenshot_20210423-071236_YouTube Music](https://user-images.githubusercontent.com/58808646/115821386-fc04e080-a402-11eb-9952-caf7e69198c9.jpg)
![signal-2021-04-23-045025](https://user-images.githubusercontent.com/58808646/115821361-eee7f180-a402-11eb-8a49-9dc97fda754b.jpg)

**Steps to reproduce:**
Step 1: Enter to the Add Account
Step 2: Log In into microG Vanced via YT Vanced
Step 3: Nothing changed in YT vanced, but still working in YT music
Step 4: Delete the YT Vanced
Repeat.

 BTW: I want to contact directly to the developers, because I want to share my video about this problem, which contains sensitive information (my Gmail email address).

**Comment by X1nto** [comment]
Not related to manager
