### ISSUE TITLE
New update via Manager does not have the Dutch/Nederlands split apk

### ISSUE THREAD

**Issue by foreveryoungforty** [YTVanced/VancedManager#509]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server YES
- I am using the latest version YES
- This is an issue in the Vanced Manager app (NOT Youtube Vanced/Music) YES
- This issue keeps re-occurring every time I try YES (tried also on my tablet Samsung S6)
- For MIUI users: I disabled MIUI optimisations

**Phone Specifications:**
- Brand: Samsung S10
- Operating System: Android (non-root)
- Android Version: 11
- Vanced Manager Version: 2.5.1

**Please describe the problem you are having in as much detail as possible:**
I just received a push from Vanced Manager 2.5.1 to update to YouTube Vanced 16.14.34, but it lacks my default choice Nederlands (Dutch) as a choice, and therefore does not download that split nl.apk. In manager I see  "[] " next to Languages in the installation preferences, and cannot choose Dutch/Nederlands - all other European languages are there , eg. Deutsch (German), Français,....  Can you please add Dutch ?  Thanks a lot.

**Steps to reproduce:**

**Further details:**
I just visited the codebucket-mirror site, the nl-apk  is also not present in the root/non-root directories there.

**Comment by X1nto** [comment]
Its a suggestion for Vanced, not Manager
