### ISSUE TITLE
Unable to install YT Vanced Root [Segmentation fault]

### ISSUE THREAD

**Issue by VirusBurst** [YTVanced/VancedManager#510]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server => Yes
- I am using the latest version => Yes
- This is an issue in the Vanced Manager app (NOT Youtube Vanced/Music) => Maybe
- This issue keeps re-occurring every time I try => Yes
- For MIUI users: I disabled MIUI optimisations => Bruh, Don't have MIUI

**Phone Specifications:**
- Brand: BQ Aquarius X5 Plus
- Operating System: Lineage OS 14.1 
- Android Version: Android 7.1.2
- Vanced Manager Version: 2.5.1 (Weed)

**Please describe the problem you are having in as much detail as possible:**
I'm trying to install YT Vanced ROOT since my device is rooted with Magisk 22.1 from the very beginning I have it and every time I try to install, shortly after downloading the APKs it tries to do something and suddenly fails with "Segmentation fault"

**Steps to reproduce:**
1. Set Vanced to install YT Vanced ROOT 
2. Install YT Vanced ROOT in Light + Dark, Latest, German
3. Wait for fail

**Further details:**

I always bypassed this error by installing YT Vanced NON-ROOT but... at some point I ask myself what's the point of it if I have root for AdAway, ACCA, TitaniumBackup, ....

**Comment by X1nto** [comment]
Could you please dump me logs from manager

**Comment by VirusBurst** [comment]
VMNetTools: Fetching using URL: https://vancedapp.com/api/v1
VMInstall: Requesting user confirmation for uninstallation
VMpm: Successfully uninstalled com.mgoogle.android.gms
VMNetTools: Fetching using URL: https://vancedapp.com/api/v1
VMInstall: Requesting user confirmation for uninstallation
VMpm: Successfully uninstalled com.mgoogle.android.gms
VMNetTools: Fetching using URL: https://vancedapp.com/api/v1
VMInstall: Checking stock version
VMInstall: Unable to get package info
VMInstall: Installing stock
VMInstall: installing split apk files: [dark.apk, split_config.armeabi_v7a.apk, stock.apk, dpi.apk, split_config.de.apk]
VMInstall: installing APK: split_config.armeabi_v7a.apk
VMInstall: installing APK: stock.apk
VMInstall: Segmentation fault 
VMInstall: Checking stock version
VMInstall: Unable to get package info
VMInstall: Installing stock
VMInstall: installing split apk files: [dark.apk, split_config.armeabi_v7a.apk, stock.apk, dpi.apk, split_config.de.apk]
VMInstall: installing APK: split_config.armeabi_v7a.apk
VMInstall: Segmentation fault 


This one?

**Comment by X1nto** [comment]
Are you on canary Magisk by any chance?

**Comment by VirusBurst** [comment]
Stable :(

**Comment by X1nto** [comment]
> Stable :(

Could you please try canary? Report back if Canary didn't fix anything

**Comment by VirusBurst** [comment]
Switched Magisk update channel from "Stable" to "Beta"

VMNetTools: Fetching using URL: https://vancedapp.com/api/v1
VMInstall: Checking stock version
VMInstall: Unable to get package info
VMInstall: Installing stock
VMInstall: installing split apk files: [dark.apk, split_config.armeabi_v7a.apk, stock.apk, dpi.apk, split_config.de.apk]
VMInstall: installing APK: split_config.armeabi_v7a.apk
VMInstall: installing APK: stock.apk
VMInstall: installing APK: dpi.apk
VMInstall: installing APK: split_config.de.apk
VMInstall: committing...
VMInstall: Moving app
ZLog: true
VMInstall: Running chcon
VMInstall: Setting up script
VMInstall: Linking app
VMInstall: Setting installer package to com.android.vending for com.google.android.youtube
VMInstall: Installer package successfully set
VMInstall: Finished installation
VMNetTools: Fetching using URL: https://vancedapp.com/api/v1

IT WORKS!

But something I noticed... it took several tries until it fully worked...

Once it failed without any error message, other time it crashes immediately and often YT Vanced loaded indefinitely but I tried again and again and reinstalled Vanced Manager, bla bla bla and suddenly as known from the IT department
MAGIC it works!
