### ISSUE TITLE
Chromecast not detected

### ISSUE THREAD

**Issue by JDMorris81** [YTVanced/VancedManager#513]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced/Music)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisations

**Phone Specifications:**
- Brand:
- Operating System:
- Android Version:
- Vanced Manager Version:

**Please describe the problem you are having in as much detail as possible:**

**Steps to reproduce:**

**Further details:**
![Screenshot_20210426-173916](https://user-images.githubusercontent.com/72824463/116168178-b2442080-a6b6-11eb-8fca-54575102129f.jpg)
Updated to new version, pressing cast icon no longer detects my casting device

**Comment by KevinX8** [comment]
Damn when did vanced manager UI get so YouTube like?

**Comment by vaguerant** [comment]
Hahaha. Yeah, wrong place for this issue, see YTVanced/Vanced#688.
