### ISSUE TITLE
Freeze on Logo Startup

### ISSUE THREAD

**Issue by Helios0411** [YTVanced/VancedManager#52]
Phone Specifications
- Brand: Samsung
- Operating System: One UI 2.1
- Android Version: 10
- Vanced Manager Version: 1.0.2

Upon opening the app it froze at the logo of Vanced manager and the prompt "Update Available" popped up twice back-to-back.
And then just the logo for several minutes.

Steps to reproduce:

Simple installation on a non-rooted phone which has a non-rooted Youtube Vanced and MicroG installed.

Further details:
Uninstalled all traces of Vanced Manager, Youtube Vanced, and MicroG (including "Clear Data" & Package folders if any existed then)

Re-installed Vanced Manager (Fresh Download) 1.0.2
Still Froze on Logo with exemption of "Update Available" prompts

**Comment by X1nto** [comment]
Looks like you aren't using 1.0.2 at all since it won't prompt you to update, please check that you're using newest version
