### ISSUE TITLE
Video Quality Is Max

### ISSUE THREAD

**Issue by harismuntazir** [YTVanced/VancedManager#524]
YouTube Vanced is setting the video quality to max. We can change the quality on every video but the general settings does not take effect.
I tried all three options but they don't make any changes.

Auto
Higher Picture Quality
Data saver

None of them take effect.. 
Seems like the new update caused this issue..

**Comment by VancedOfficial** [comment]
Please check other issues before posting a new one (https://github.com/YTVanced/Vanced/issues/697).

Set the preferred resolution from Vanced settings to "Auto" to fix the issue while waiting for an update.
