### ISSUE TITLE
Preferred video quality for mobile data no longer works

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [YTVanced/VancedManager#525]
For the latest Vanced update, the video resolution no longer defaults to the preferred video quality for mobile data, e.g. it defaults to 1080p despite setting 480p.

**Comment by bibuborg** [comment]
I'm having the same problem despite setting the default resolution on cellular data to 360p it always plays in the maximum resolution available 1440p, 1080p, 720p

**Comment by ghost** [comment]
This isn't Vanced Manager related.
