### ISSUE TITLE
Servers are down

### ISSUE THREAD

**Issue by linuzzx** [YTVanced/VancedManager#526]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced/Music)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisations

**Phone Specifications:**
- Brand: ZTE
- Operating System: Android
- Android Version: 9
- Vanced Manager Version: Newest

**Please describe the problem you are having in as much detail as possible:**
![Screenshot_20210430_122407](https://user-images.githubusercontent.com/57060126/116682891-24667f00-a9af-11eb-97dd-df0853271fdc.jpg)

**Steps to reproduce:**
Install latest Manager Version and open it...

**Further details:**

**Comment by razvanksz** [comment]
Same problem,I use a J4+ 2019,non rooted.I tried to clear data,reinstall the manager but it doesn't works

**Comment by Caligula-z** [comment]
same problem with Samsung A series

**Comment by accik** [comment]
The server is down! Keep calm and try again later. Source: [Reddit](https://www.reddit.com/r/Vanced/comments/n1qrhn/other_youtube_vanced_is_down_yt_and_yt_music_cant/)

**Comment by X1nto** [comment]
Servers being down again, locked in order to avoid spam

**Comment by X1nto** [comment]
I'll go beat Vergil on Dante Must Die mode, close this issue when it's fixed for everyone. Also please don't spam "I have the same issue", we know you have it. Thanks in advance.

**Comment by parayeah** [comment]
Having same issues on my Galaxy S8 on Android 9. Good thing I didn't updated my Vanced Manager app on my Vivo Y69 on Android 7 yet 
![Screenshot_20210430-185235_Vanced Manager](https://user-images.githubusercontent.com/83452498/116685688-585c9700-a9e5-11eb-9170-c57c9bd43d9c.jpg)

**Comment by wartickler** [comment]
This guy gets it ^

**Comment by KevinX8** [comment]
they are no longer down it seems
