### ISSUE TITLE
Installing plain apk with MIUI optimization on

### ISSUE THREAD

**Issue by marinosGR** [YTVanced/VancedManager#529]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced/Music)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisations

**Phone Specifications:**
- Brand:
- Operating System:
- Android Version:
- Vanced Manager Version:

**Please describe the problem you are having in as much detail as possible:**
This can be a bug or an enhancement. It depends of your point of view.
YouTube Vanced uses apks format and needs the user to disable MIUI optimizations
BUT
Microg and YT Music are plain apk files. They could be installed, the same way the manager updates itself. But the manager doesn't allow you to install them and instead displays the message for the MIUI optimizations. So I have to find the apk files with a file manager to start the installation which works just fine.

So, could we just have the manager to behave differently for plain apk files and just start the installation the same way it starts its update?

**Steps to reproduce:**

**Further details:**

**Comment by X1nto** [comment]
plain apk files also require you to disable miui optimization, it's not an issue with .apks format, it's an issue with third party installers itself in miui

**Comment by fcaronte** [comment]
Not true because if I pick the apk downloaded to temp folder, then I can install normally using any file manager on Mi10 with enabled MIUI optimization. For the YouTube app I need to get the three part and install using ADB. As now disable MIUI optimization give a lot of problem and reset all app permission and so for me isn't a good option. "SAI" app installer can use the "Shizuku" app to give permission to install split apk from phone maybe can be an option for your manager too?

**Comment by FurriousFox** [comment]
> plain apk files also require you to disable miui optimization, it's not an issue with .apks format, it's an issue with third party installers itself in MIUI 

look at this https://github.com/f-droid/fdroidclient/tree/master/app/src/main/java/org/fdroid/fdroid/installer
It's possible to install plain apk files without disabling MIUI optimization, you can implement it like how F-Droid implemented it.

**Comment by X1nto** [comment]
> > plain apk files also require you to disable miui optimization, it's not an issue with .apks format, it's an issue with third party installers itself in MIUI 
> 
> look at this https://github.com/f-droid/fdroidclient/tree/master/app/src/main/java/org/fdroid/fdroid/installer
> It's possible to install plain apk files without disabling MIUI optimization, you can implement it like how F-Droid implemented it.

Except it's using Package Installer UI (the one that launches when you install apk from an explorer), manager is only using that for manager updates, for everything else it uses Package Manager API because API version allows us to listen to callbacks.

**Comment by X1nto** [comment]
We're also using API version because the native android version doesn't support split apks.

**Comment by FurriousFox** [comment]
But you could atleast use the Package Installer UI for installing MicroG & Youtube Music on Xiaomi devices with MIUI Optimization on, is much more user friendly than not being able to install the app at all

**Comment by marinosGR** [comment]
I don't know why, or how. I installed it through Shizuku first and the app now updates everything normally...

Poco F3

**Comment by FurriousFox** [comment]
> I don't know why, or how. I installed it through Shizuku first and the app now updates everything normally...
> 
> Poco F3

would be great if that also worked for me, but it doesn't, are you sure that you still have MIUI Optimization enabled?

**Comment by fcaronte** [comment]
@marinosGR how to use shizuku if isn't integrated to vanced Manager? I use SAI installer with the shizuku support but need to get split file from the temp folder of vanced manager

**Comment by marinosGR** [comment]
I really don't know how it happened. The first time I did it like you from the temp folder and the next update through the manager didn't failed... Maybe it's because I have left enabled all the programming options that Shizuku with SAI asked for.

**Comment by marinosGR** [comment]
> > I don't know why, or how. I installed it through Shizuku first and the app now updates everything normally...
> > Poco F3
> 
> would be great if that also worked for me, but it doesn't, are you sure that you still have MIUI Optimization enabled?

Yes, still enabled and double checked

**Comment by marinosGR** [comment]
https://user-images.githubusercontent.com/56827108/132206124-007a2a69-5be1-437a-8b74-de1cc30d3366.mp4

![Screenshot_2021-09-06-13-48-23-168_moe shizuku privileged api](https://user-images.githubusercontent.com/56827108/132206154-3ae1abd9-a155-4d9b-9de7-7f4b303b5ab9.jpg)

As you can see no errors (but there is no new version to fully prove it) and it doesn't use Shizuku because as you can see at the screenshot (forgot to open it in video) it wasn't running

**Comment by FurriousFox** [comment]
Ah, I see why it magically started to work for you, you got an update to MIUI 12.5.3, and since MIUI 12.5.2 they fixed this issue with custom installers, it seems really important to me, but they didn't even put it in their release notes...
