### ISSUE TITLE
Error message when attempting to update Vanced Manager

### ISSUE THREAD

**Issue by PenPinapplPen** [YTVanced/VancedManager#53]
When I select the 'Update' button, I receive a small pop-up message at the bottom of my screen and no update takes place.

Device: Huawei Y7 (2017)

![Screenshot_20200703-192553](https://user-images.githubusercontent.com/65387181/86455139-8cceda80-bd63-11ea-974d-a49a3a838112.png)

The numbers change each time, but the 'b.d.a' part is consistent.

**Comment by X1nto** [comment]
You'll have to update manually, there was a bug with auto-update system that's fixed in 1.0.2
