### ISSUE TITLE
[Feature Request] Disable Automatic Manager Updating

### ISSUE THREAD

**Issue by Codel1417** [YTVanced/VancedManager#530]
Pretty strait forward. I want the ability to not prompt me to update the manager at launch.

also there is no feature request template.

**Comment by cl-ement05** [comment]
@X1nto Maybe the TAG_FORCE_UPDATE in the ManagerUpdateDialog is a bad idea ? May I rework this part of the manager and add smth like "An update has been found do you want to install it ?" ? (sorry for the ping)

**Comment by X1nto** [comment]
> @X1nto Maybe the TAG_FORCE_UPDATE in the ManagerUpdateDialog is a bad idea ? May I rework this part of the manager and add smth like "An update has been found do you want to install it ?" ? (sorry for the ping)

force update is for Dev Settings menu, it's not related to this issue.

**Comment by KevinX8** [comment]
> Pretty strait forward. I want the ability to not prompt me to update the manager at launch.
> 
> also there is no feature request template.

considering the manager is completely reliant on the vanced backend it does not make any sense to support old versions of it, it is literally a client for a server.
