### ISSUE TITLE
An easy way to queue videos

### ISSUE THREAD

**Issue by reinaldofox** [YTVanced/VancedManager#531]
Would it be possible to implement a way to easily queue videos?
Like, when a video is playing you can select and mark others as next.
Just that would be incredible, but if there were a way to access this list to change the position of the videos and remove some, it would be magical.
I know you can create a play list and select it to play, but I’m talking about something more practical, like a session playlist.

Thanks in advance!

**Comment by X1nto** [comment]
not related to manager

**Comment by reinaldofox** [comment]
I'm sorry, I forgot to note this detail.
What a shame!

I will post in the right place.
