### ISSUE TITLE
Segmentation fault || Session ID is null error when updating YT Vanced

### ISSUE THREAD

**Issue by VirusBurst** [YTVanced/VancedManager#532]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server [Yes]
- I am using the latest version [I assume Github doesn't lie]
- This is an issue in the Vanced Manager app (NOT Youtube Vanced/Music) [Yeah]
- This issue keeps re-occurring every time I try [YES]
- For MIUI users: I disabled MIUI optimisations [LOL WHAT]

**Phone Specifications:**
- Brand: BQ Aquaris X5 Plus
- Operating System: Lineage OS 14.1
- Android Version: 7.1.2
- Vanced Manager Version: 2.6.0 (Crimson)

**Please describe the problem you are having in as much detail as possible:**
While trying to update YT Vanced through the Vanced App, it fails after downloading all the files

VMNetTools: Fetching using URL: https://api.vancedapp.com/api/v1
VMInstall: Checking stock version
VMInstall: Installing stock
VMInstall: installing split apk files: [dark.apk, split_config.armeabi_v7a.apk, stock.apk, dpi.apk, split_config.de.apk]
VMInstall: installing APK: split_config.armeabi_v7a.apk
VMInstall: installing APK: stock.apk
VMInstall: installing APK: dpi.apk
VMInstall: Segmentation fault 
VMInstall: Checking stock version
VMInstall: Installing stock
VMInstall: installing split apk files: [dark.apk, split_config.armeabi_v7a.apk, stock.apk, dpi.apk, split_config.de.apk]
VMInstall: Session ID is null
VMInstall: Checking stock version
VMInstall: Installing stock
VMInstall: installing split apk files: [dark.apk, split_config.armeabi_v7a.apk, stock.apk, dpi.apk, split_config.de.apk]
VMInstall: installing APK: split_config.armeabi_v7a.apk
VMInstall: installing APK: stock.apk
VMInstall: Segmentation fault 

VMNetTools: Fetching using URL: https://api.vancedapp.com/api/v1
VMInstall: Checking stock version
VMInstall: Installing stock
VMInstall: installing split apk files: [dark.apk, split_config.armeabi_v7a.apk, stock.apk, dpi.apk, split_config.de.apk]
VMInstall: installing APK: split_config.armeabi_v7a.apk
VMInstall: installing APK: stock.apk
VMInstall: installing APK: dpi.apk
VMInstall: installing APK: split_config.de.apk
VMInstall: Segmentation fault 
VMInstall: Checking stock version
VMInstall: Installing stock
VMInstall: installing split apk files: [dark.apk, split_config.armeabi_v7a.apk, stock.apk, dpi.apk, split_config.de.apk]
VMInstall: Session ID is null

**Steps to reproduce:**
0: Just Update YT Vanced to the latest and greatest

**Further details:**
It happens while Magisk Update Channel is set to stable AND beta (canary)

**Comment by X1nto** [comment]
Try Magisk canary. Magisk Beta != Magisk Canary

**Comment by VirusBurst** [comment]
Just install Magisk Canary apk and reboot or do I also have to install Magisk boot image from canary?

Because so far it didn't worked by installing Canary but this time, I always get "Segmentation fault"

**Comment by X1nto** [comment]
> Just install Magisk Canary apk and reboot or do I also have to install Magisk boot image from canary?
> 
> Because so far it didn't worked by installing Canary but this time, I always get "Segmentation fault"

Obviously you should also install magisk itself, not just magisk manager

**Comment by VirusBurst** [comment]
Sooo.... I installed Magisk Canary (fb80000b5) and at first after a reboot, I got "Session ID is null" but then I tried again and finally it updated YT Vanced...

But now... should I stay on Magisk Canary or can I switch back to stable or is it just temporarily a problem with Magisk stable 22.1 and therefore I had to use Canary for Vanced?

**Comment by X1nto** [comment]
> Sooo.... I installed Magisk Canary (fb80000b5) and at first after a reboot, I got "Session ID is null" but then I tried again and finally it updated YT Vanced...
> 
> But now... should I stay on Magisk Canary or can I switch back to stable or is it just temporarily a problem with Magisk stable 22.1 and therefore I had to use Canary for Vanced?

Do as you wish. I'd suggest staying with canary build as it has the bug fixed, unless you have any problems with it.
