### ISSUE TITLE
Volume Keys Beep

### ISSUE THREAD

**Issue by marceloflix** [YTVanced/VancedManager#534]
**Please check all boxes below by replacing space with** `x`
- [x] I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- [x] I am using the latest version
- [ ] This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)
- [x] This issue keeps re-occurring every time I try
- [ ] I disabled MIUI optimisations (MIUI ONLY)

**Phone Specifications:**
- Brand:Huawei
- Operating System:EMUI
- Android Version:10
- Vanced Manager Version:2.6.0

**Please describe the problem you are having in as much detail as possible:**

Everytime i press the volume keys on my Android while using Youtube Vanced i hear a beeping sound.

I disabled this behavior in Android settings and Gboard, but, Youtube Vanced seems to be the only one doing this.

**Steps to reproduce:**

Press the volume keys inside Youtube Vanced.

**Further details:**

**Comment by X1nto** [comment]
Bro you left 3rd box unchecked specifically and you still opened issue what the fuck
