### ISSUE TITLE
Vanced Manager has not Storage Permission

### ISSUE THREAD

**Issue by huseidon** [YTVanced/VancedManager#536]
**Please check all boxes below by replacing space with** `x`
- [ X] I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- [X ] I am using the latest version
- [ X] This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)
- [ X] This issue keeps re-occurring every time I try
- [ ] I disabled MIUI optimisations (MIUI ONLY)

**Phone Specifications:**
- Brand: Samsung
- Operating System: Android 
- Android Version: 9
- Vanced Manager Version: 2.6.0 (Crimson)

**Please describe the problem you are having in as much detail as possible:**

"Error downloading black.apk"

    To download and install yt vanced, manager must have storage permission for downloading process, right?  But when i want to give permission, there are no permission option appears. It shows "no permission required". Because of that I can't download Youtube vanced. 

**Steps to reproduce:**

**Further details:**
    -I am root user (Magisk latest version).
    - App using with root variant.
    -There was no problem with the previous version. I have backup of it, and i can give storage permission to it.

![Screenshot_20210502-130833_Settings](https://user-images.githubusercontent.com/12736581/116809625-940f7200-ab47-11eb-8633-a7fb4cdb4cc0.jpg)
![Screenshot_20210502-130845_Package installer](https://user-images.githubusercontent.com/12736581/116809628-9a055300-ab47-11eb-9efa-0515205981fb.jpg)

**Comment by X1nto** [comment]
Manager doesn't need storage permissions, it was there in previous versions fro backwards compatibility. Something probably broke after removing the permission for newer android versions. Currently I'd suggest clearing data for manager, if that doesn't work I'll have to re-add storage permission for all versions

**Comment by huseidon** [comment]
I've already cleared data and even tried a clean install, but same issue.

**Comment by strider15** [comment]
Same with me, Galaxy Note5 rooted.
I don't why and since when this happening. In the past, there's no problem when downloading and installing both Vanced Manager and YouTube Vanced.
Now since updating to 2.6.0, I can't download the new updates of YouTube Vanced.
I can't even save the log files. Tried downgrading to previous version, uninstalling both Manager and YouTube Vanced, still got the same issue.
The only solution right now is manually installing the YouTube Vanced with SAI. You must download both of the YouTube Vanced app and Split config apk.

![Screenshot_20210502-195700_Vanced Manager](https://user-images.githubusercontent.com/83540689/116815400-9e516080-ab87-11eb-96aa-42bc7f78c197.jpg)
![Screenshot_20210502-193531_Vanced Manager](https://user-images.githubusercontent.com/83540689/116815404-a0b3ba80-ab87-11eb-998d-2dafc81f5d09.jpg)

**Comment by X1nto** [comment]
I wonder if it's a coincidence that only Samsung users have that problem

**Comment by huseidon** [comment]
I guess as you said.

**Comment by strider15** [comment]
Welp, but I didn't got the problem from my A51 Stock OneUI 3.0, Android 11.
But I hope it just on older Samsung tho.
Btw, my Galaxy Note5 is custom ROM OneUI 1.0, Android 9.
But I just got this problem since the new updates.
By the way, I just updated my Magisk to newer version few weeks ago, and now my safetynet is broken. I hope this isn't related tho

**Comment by huseidon** [comment]
I guess, re-adding storage permission will fix the issue

**Comment by KevinX8** [comment]
it shouldn't need it as scoped storage gives it all the necessary permissions it needs

**Comment by cl-ement05** [comment]
No this is only a cosmetic issue (see [closed Magisk issue](https://github.com/topjohnwu/Magisk/issues/4231) :
> Anyone coming here and still complaining about SafetyNet check on latest stable, it's actually still passing (it's just the check that's broken), is different from this issue, and already fixed in Canary so use Canary or just wait.

**Comment by X1nto** [comment]
> it shouldn't need it as scoped storage gives it all the necessary permissions it needs

Some Android 5 ROMs had a bug which prevented apps from using app-specific folder without storage permission (even tho app-specific folders don't need any permissions starting with KitKat). In older versions, storage permissions showed up for every Android version but I limited it to Android 5 only, but it seems like some ROMs still need the permission to be there even if it's not granted

**Comment by huseidon** [comment]
> > it shouldn't need it as scoped storage gives it all the necessary permissions it needs
> 
> Some Android 5 ROMs had a bug which prevented apps from using app-specific folder without storage permission (even tho app-specific folders don't need any permissions starting with KitKat). In older versions, storage permissions showed up for every Android version but I limited it to Android 5 only, but it seems like some ROMs still need the permission to be there even if it's not granted

it means, you will give that permission to app again, right? Just we should wait next update?

**Comment by X1nto** [comment]
> > > it shouldn't need it as scoped storage gives it all the necessary permissions it needs
> > 
> > 
> > Some Android 5 ROMs had a bug which prevented apps from using app-specific folder without storage permission (even tho app-specific folders don't need any permissions starting with KitKat). In older versions, storage permissions showed up for every Android version but I limited it to Android 5 only, but it seems like some ROMs still need the permission to be there even if it's not granted
> 
> it means, you will give that permission to app again, right? Just we should wait next update?

Can't do anything without updating

**Comment by X1nto** [comment]
Spoiler alert: 3.0 will probably take more than 2 months

**Comment by huseidon** [comment]
> Spoiler alert: 3.0 will probably take more than 2 months

OMG. Is there a pack to install with "SAI" like we use to install.

**Comment by X1nto** [comment]
> > Spoiler alert: 3.0 will probably take more than 2 months
> 
> OMG. Is there a pack to install with "SAI" like we use to install.

Yep, follow this: https://github.com/YTVanced/VancedManager/issues/342#issuecomment-830837523

**Comment by missiah** [comment]
Please re-add storage permission for all versions

**Comment by huseidon** [comment]
> > > Spoiler alert: 3.0 will probably take more than 2 months
> > 
> > 
> > OMG. Is there a pack to install with "SAI" like we use to install.
> 
> Yep, follow this: [#342 (comment)](https://github.com/YTVanced/VancedManager/issues/342#issuecomment-830837523)

Thank you for all help.

**Comment by Minnona** [comment]
Got the same on LOS 14 (Android 7.1).
