### ISSUE TITLE
Torjan Malware Detected in the package

### ISSUE THREAD

**Issue by YashejShah** [YTVanced/VancedManager#542]
![Screenshot_20210507-235746956](https://user-images.githubusercontent.com/65942398/117496743-1a3b1680-af95-11eb-8d72-2b9b5746256a.jpg)
(Android.Android.WIN32.SpyNote.e)

**Comment by KevinX8** [comment]
have you heard of a thing called false positives? you'd think if there really was one that more than 1 out of 68 providers detected something?

**Comment by KevinX8** [comment]
also feel free to audit the code yourself, it's all here

**Comment by X1nto** [comment]
> ![Screenshot_20210507-235746956](https://user-images.githubusercontent.com/65942398/117496743-1a3b1680-af95-11eb-8d72-2b9b5746256a.jpg)
> (Android.Android.WIN32.SpyNote.e)
> Fix this dev or give a statement

1. Source code is publicly available, it would be dumb as fuck to put a virus in an open-source app. You can compile the code yourself to check that compiled output may trip some shitty antivirus
2. Trusting some no-name antivirus is not the best idea

**Comment by X1nto** [comment]
Just checked it myself, nothing detected at all
![image](https://user-images.githubusercontent.com/48173186/117500492-c547d200-af8d-11eb-9f4a-d3bceeea6e3e.png)

**Comment by YashejShah** [comment]
Just to be fair i really didn't knew what i was doing and it was not the vanced manager but the YouTube vanced package. If I could know to edit the codes i would definitely do it so . Sorry

**Comment by X1nto** [comment]
> Just to be fair i really didn't knew what i was doing and it was not the vanced manager but the YouTube vanced package. If I could know to edit the codes i would definitely do it so . Sorry

if it's not Vanced Manager related, it should not be posted here

**Comment by YashejShah** [comment]
I thought vanced YouTube package should be reported here .
