### ISSUE TITLE
Integrate with ytmdesktop

### ISSUE THREAD

**Issue by shahrd97** [YTVanced/VancedManager#548]
I know that vanced is supposed to be an Android mobile app. But I've been loving it on my phone especially for background ad-less music, and I've always sought to have something similar on my computer. Now designing something from ground-up for desktop would be a real pain. But this is where [ytmdesktop's](https://github.com/ytmdesktop) [ytmdesktop](https://github.com/ytmdesktop/ytmdesktop) repository, could help you guys.

**Comment by X1nto** [comment]
Not related to manager
