### ISSUE TITLE
State minimum android version required for Vanced Manager.

### ISSUE THREAD

**Issue by frenchiveruti** [YTVanced/VancedManager#549]
**Please check all boxes below by replacing space with** `x`
- [ ] I am using the latest version
- [x] This is a suggestion for in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Suggestion:**
It would be nice to have at hand when one downloads the APK, to know the minimum android version needed in order to make it work.
**Why is this suggestion relevant?**
As of now, when one downloads the APK, thinks there was an error in the download, or that the apk is not compatible for some other reason, whereas it could just be the android version.
**Further details:**
Samsung Galaxy Tab E (A 4.4.4)
![183377959_2569587896678201_2487879034217911609_n](https://user-images.githubusercontent.com/1095997/117978185-fd417300-b307-11eb-949c-a5bf6b5f0d5c.png)
![183444745_165321952185666_2985818281264897897_n](https://user-images.githubusercontent.com/1095997/117978194-ff0b3680-b307-11eb-9d7a-172540c82797.png)

**Comment by X1nto** [comment]
You need Android 5 and later to open Manager, KitKat and older won't work

**Comment by frenchiveruti** [comment]
Thanks @X1nto,
Side question, can I install Vanced Somehow on Android 4.4.4?

**Comment by X1nto** [comment]
> Thanks @X1nto,
> Side question, can I install Vanced Somehow on Android 4.4.4?

I think the only supported version for 4.4.4 is Vanced 14.21.54
