### ISSUE TITLE
App crashes immediately upon opening

### ISSUE THREAD

**Issue by jzzunl** [YTVanced/VancedManager#55]
- Brand: Amazon
- Operating System: Fire OS 7.3.1.2
- Android Version: Android 9.0
- Vanced Manager Version: 1.0.2

- Problem: vanced manager crashes immediately upon opening

- Steps to reproduce: open on android 9 (or fire os 7.3.1.2 unsure as to which it is)

- Further details: i am using a fire hd 10 9th gen

**Comment by X1nto** [comment]
Do you have some kind of firewall set up? You're probably blocking connection to servers

**Comment by jzzunl** [comment]
Not that i know of

**Comment by jzzunl** [comment]
I've also tried clearing the apps data

**Comment by X1nto** [comment]
Can you send logs?

**Comment by jzzunl** [comment]
I cant find the logs for the manager

**Comment by X1nto** [comment]
I'm about logcat, use ADB, run following commands
`adb logcat -c`
`adb logcat *:W > logcat.txt`
Then go crash manager and after it crashes, on your PC hit Ctrl+c
Then send that logcat.txt here

**Comment by jzzunl** [comment]
here it is
[logcat.txt](https://github.com/YTVanced/VancedManager/files/4870425/logcat.txt)

**Comment by X1nto** [comment]
Logcat says that issue is with themes, I don't see any reasons for themes to crash the app. Did you change anything in manager settings? And are you sure you're using latest version?

**Comment by jzzunl** [comment]
i haven't been able to open the app to change the setting and this screenshot says i'm on 1.0.2
![Screenshot_20200703-114133](https://user-images.githubusercontent.com/12969653/86483710-9edc5900-bd22-11ea-9a85-0c5008d5509a.png)

**Comment by X1nto** [comment]
I would blame this to FireOS, since all my devices run the app normally, even my fire hd 8 (I have lineage installed on it). I won't close the issue but I don't think that it'll be fixed either

**Comment by slaszt** [comment]
I'm having the same issue with my Fire HD 8 8th gen. Sucks you're not gonna fix it, the white theme is blinding me.

**Comment by X1nto** [comment]
> I'm having the same issue with my Fire HD 8 8th gen. Sucks you're not gonna fix it, the white theme is blinding me.

Wait so are you having issues on both themes or just dark

**Comment by X1nto** [comment]
We can try moving both themes to one file instead of having them separated, should fix the issue

**Comment by slaszt** [comment]
No, the app (Vanced Manager) simply won't open. I try to open it, instant crash. I can't even change the themes.

**Comment by X1nto** [comment]
@jzzunl @slaszt Can you guys try out this build? https://github.com/YTVanced/VancedManager/suites/879889593/artifacts/10332064
You'll have to uninstall current one and install this one. It's a debug build so performance of the app may be a bit bad

**Comment by slaszt** [comment]
@X1nto Just tried it, same issue. I can send logs in the afternoon when I'm back at my PC.

**Comment by ScooloV** [comment]
Having same issue with Fire HD 8 (8 Gen) with 6.3.1.5 Fire OS. 
No modification to system were done, it is almost clean install (just added Google Store via https://forum.xda-developers.com/hd8-hd10/development/official-amazon-fire-toolbox-v1-0-t3889604). 
Checked last app-debug build and it is not working too.

**Comment by X1nto** [comment]
Can you guys test this build?https://github.com/YTVanced/VancedManager/suites/881265796/artifacts/10363713
This one *should*, be working. Please send logs if crashes occur anyways

**Comment by ScooloV** [comment]
Still the same
[logcat.txt](https://github.com/YTVanced/VancedManager/files/4879644/logcat.txt)

**Comment by slaszt** [comment]
I also still have the issue. Here's my logcat. It's worth noting that I have also used the same [Amazon Fire Toolbox](https://forum.xda-developers.com/hd8-hd10/development/official-amazon-fire-toolbox-v1-0-t3889604) that @ScooloV is using, and that it disables system apps in a way that can't be re-enabled through the device; you need to re-run the Toolkit to do so - maybe this is causing an issue?

[logcat.txt](https://github.com/YTVanced/VancedManager/files/4881147/logcat.txt)

**Comment by X1nto** [comment]
Toolbox shouldn't be the issue here. I'm currently rewriting some UI code, mostly dialogs and trying to fix the bug. I'll inform you guys

**Comment by jzzunl** [comment]
@X1nto the 1.0.2 beta that you have on your repositories does work in case that helps

**Comment by X1nto** [comment]
> @X1nto the 1.0.2 beta that you have on your repositories does work in case that helps

Oh thanks for the info, I probably already fixed it on my local PC since I reconstructed some things, unfortunately I have no ETA for this but should be ready in less than a week

**Comment by mlch911** [comment]
Having same issue with OnePlus 6. 1.0.2 and 1.1 both crash.

**Comment by Mattis6666** [comment]
> Having same issue with OnePlus 6. 1.0.2 and 1.1 both crash.
@mlch911 
Please do not revive a solved issue like this, make a new issue and fill out the issue template

**Comment by X1nto** [comment]
@jzzunl @slaszt @ScooloV @mlch911 check the new 1.2.0 release. All crashes should be fixed

**Comment by slaszt** [comment]
> @slaszt check the new 1.2.0 release. All crashes should be fixed

Thanks, works perfectly. Really appreciate your help.
