### ISSUE TITLE
Problem with Vanced manager installation 

### ISSUE THREAD

**Issue by RedouaneBelakhdar** [YTVanced/VancedManager#550]
**Please check all boxes below by replacing space with** `x`
- [ x] I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- [ x] I am using the latest version
- [ x] This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)
- [x ] This issue keeps re-occurring every time I try
- [ ] I disabled MIUI optimisations (MIUI ONLY)

**Phone Specifications:**
- Brand: Samsung  Galaxy Tab S7
- Operating System: 
- Android Version: 11
- Vanced Manager Version: 2.6.0

**Please describe the problem you are having in as much detail as possible:**

I have a problem with the installation of youtube vanced with the manager I have this error message, I am trying to install the application on a second user account on the tablet I however managed to install the Vanced manager application but not vanced youtube I think the problem is in manager

**Steps to reproduce:**

Second account in samsng device and try to install mircog or youtube vanced in Vanced Manager

**Further details:**
![Screenshot_20210512-185239_Vanced Manager](https://user-images.githubusercontent.com/62985931/118016798-1e30b500-b356-11eb-91b4-d57b9c4bc87d.jpg)

**Comment by X1nto** [comment]
Manager does not work with multi user account
