### ISSUE TITLE
Feature to replace the shorts tab in new version by explore/trending tab.

### ISSUE THREAD

**Issue by TheAlphaApp** [YTVanced/VancedManager#552]
**Please check all boxes below by replacing space with** `x`
- [x] I am using the latest version
- [ ] This is a suggestion for in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Suggestion:**
There should be a feature to replace the shorts tab in the new version 16.16.38 of Youtube Vanced

**Why is this suggestion relevant?**
Many of the people doesn't like shorts like me. They watch youtube for long video.

**Further details:**
Please do it

**Comment by KevinX8** [comment]
um you somehow realised this was not vanced manager but still posted it? lol
