### ISSUE TITLE
YouTube Vance crashes at the moment you open

### ISSUE THREAD

**Issue by iakbar55** [YTVanced/VancedManager#557]
YouTube Vance crashes at the moment you open in mi9.

**Comment by cl-ement05** [comment]
Android version ? Are you using the latest version of Vanced Manager (2.6.0) ?

Including logs would be very helpful

**Comment by iakbar55** [comment]
Hi,

Actually uninstalling and reinstalling gmicro did the trick. Now it’s
normal and working.

Thank you
