### ISSUE TITLE
YouTube Vanced stops and updates auto 

### ISSUE THREAD

**Issue by aaref1234** [YTVanced/VancedManager#559]
**Please check all boxes below by replacing space with** `x`
- [x] I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- [x] I am using the latest version
- [ ] This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)
- [x] This issue keeps re-occurring every time I try
- [ ] I disabled MIUI optimisations (MIUI ONLY)

**Phone Specifications:**
- Brand: Samsung Galaxy Note 9
- Operating System: Android
- Android Version: 10
- Vanced Manager Version: 2.6.0 (Crimson)
**Please describe the problem you are having in as much detail as possible:**
The YouTube Vanced application works as a crash some times and is updated from the Google Store after restarting automatically .

**Steps to reproduce:**
Unspecified number . 

**Further details:**
The YouTube vanced application works as a crash some times, and it is also updated from the Google Store after restarting automatically , knowing that I have disabled automatic updates in the Google Store and the only solution I use is to uninstall the application and reinstall it again .

**Comment by cl-ement05** [comment]
Issues concerning YTVanced only should be reported [here](https://github.com/YTVanced/Vanced/issues)

> The YouTube vanced application works as a crash some times, and it is also updated from the Google Store after restarting automatically , knowing that I have disabled automatic updates in the Google Store and the only solution I use is to uninstall the application and reinstall it again .

For this problem see [this issue](https://github.com/YTVanced/VancedManager/issues/501#issuecomment-847016769)
