### ISSUE TITLE
[SUGGESTION] Open URLs inside browser instead of webapp

### ISSUE THREAD

**Issue by Oizaro** [YTVanced/VancedManager#56]
Or make a selector to chose between them.

**Comment by X1nto** [comment]
You can always click on 3 dot menu and open link in browser instead of custom tabs

**Comment by Oizaro** [comment]
@X1nto Yeah I know, but a direct solution could be better IMHO

**Comment by X1nto** [comment]
Well, sure. I'll work on it

**Comment by X1nto** [comment]
Added in f9e0776d9527317bd2e09f10e1413691f38e77ab
