### ISSUE TITLE
[Bug] Can't connect to chromecast 

### ISSUE THREAD

**Issue by monish009** [YTVanced/VancedManager#563]
![Screenshot_20210529-190018](https://user-images.githubusercontent.com/73144425/120075096-032da700-c0b1-11eb-80e4-44ee60acc9fb.jpg)
![Screenshot_20210529-190024_Google Play Store](https://user-images.githubusercontent.com/73144425/120075108-09238800-c0b1-11eb-9d82-503797bcb2c2.jpg)

While connecting to the chromecast it toasts a message to upgrade to Google play services. But when clicking on the message, nothing happens.

**Comment by X1nto** [comment]
not related to manager

**Comment by pieterhouwen** [comment]
@X1nto So what is this related to then? I'm also having the same problem and would like a solution.

Google Play Services doesn't show up in the Play Store anymore (AFAIK) and even with up-to-date apps it still shows this message.
