### ISSUE TITLE
YouTube Videos aren´t loading

### ISSUE THREAD

**Issue by Zeromix9** [YTVanced/VancedManager#566]
Well, the problem is pretty simple, whenever I open the Youtube Vanved App it says:
"Problem to connect, check your internet connection."

The only way to fix this, is to start the YouTube App first, let it load the Videos and change then back to the App.

Phone Specifications:

    Brand: Doogee  / Model: N30
    Operating System: Stock Andriod
    Android Version: Android 10
    Vanced Manager Version: -

**Comment by X1nto** [comment]
Not related to manager
