### ISSUE TITLE
Vanced music no local files

### ISSUE THREAD

**Issue by brogren802** [YTVanced/VancedManager#571]
**Phone Specifications:**
- Brand: pixel 5
- Operating System: latest Android 11
- Android Version: latest Android 11
- Vanced Manager Version: latest vanced

I cannot get vanced music to see local files through Android auto. Using the app alone it seems to work fine and it shows all local files but the minute it's plugged in to android auto they disappear on the headunit but are still available if I load them through the phone manually. It was working great a few months back but after an update it seemed to break this feature. I also lose any downloaded music from YouTube music when updating versions. Hopefully this can be fixed as I have been using Poweramp as a backup when I have no cell service.

**Steps to reproduce:**

**Further details:**

**Comment by X1nto** [comment]
not related to manager
