### ISSUE TITLE
Set Vanced options within Manager app?

### ISSUE THREAD

**Issue by SeaGull711** [YTVanced/VancedManager#574]
I want to suggest the possibility of choosing your Vanced options within the Manager app so that they persist through multiple reinstallations.  I'm constantly having to reinstall Vanced and then I have to go through and change  my options; it would be great if Manager could remember them for me.

Thanks so much! I really appreciate the apps and all your hard work!

**Comment by cl-ement05** [comment]
Well idk what version you are using (root or non-root) but this should not be happening : preferences should be kept. I think this would more be an issue rather than an enhancement.

> choosing your Vanced options within the Manager app

Also, about this, AFAIK you cannot change the settings of an app from another app

**Comment by X1nto** [comment]
> Well idk what version you are using (root or non-root) but this should not be happening : preferences should be kept. I think this would more be an issue rather than an enhancement.

I don't think either root or nonroot backup preferences using Android's API, so there's no way preferences would be restored on reinstall.

> Also, about this, AFAIK you cannot change the settings of an app from another app

True, the only way I see it doing is by storing preferences somewhere in the internal storage, which is a literal hell because of the scoped storage.

**Comment by cl-ement05** [comment]
> I don't think either root or nonroot backup preferences using Android's API, so there's no way preferences would be restored on reinstall.

Yeah but it's weird since reinstalling is just updating to the same version already installed : settings should not be erased.

**Comment by X1nto** [comment]
> > I don't think either root or nonroot backup preferences using Android's API, so there's no way preferences would be restored on reinstall.
> 
> Yeah but it's weird since reinstalling is just updating to the same version already installed : settings should not be erased.

I think they meant uninstalling and installing, not installing the same version over an already installed app.

**Comment by cl-ement05** [comment]
Oh well I thought they meant using the reinstall button in Vanced Manager simply. @SeaGull711 what did you mean by *reinstall* ?

**Comment by SeaGull711** [comment]
> Oh well I thought they meant using the reinstall button in Vanced Manager simply. @SeaGull711 what did you mean by _reinstall_ ?

Yeah, I meant reinstalling with the reinstall button.  Maybe I'm having to reset the options every time because YouTube keeps replacing it?  I know that the REAL solution is to decouple YouTube from the play store, but I've had nothing but problems with the 3 suggestions on doing that.

**Comment by SeaGull711** [comment]
@cl-ement05 , I'm using the root version.  Does my post above shed some light? About the factory YouTube app reinstalling?  Could that be why I'm losing my settings?
TIA!

**Comment by cl-ement05** [comment]
> @cl-ement05 , I'm using the root version. Does my post above shed some light? About the factory YouTube app reinstalling? Could that be why I'm losing my settings?
TIA!

Clearly yes. Vanced settings are overwritten by stock YTB settings when you install the stock app back. This is why you lose every preference you previously set.



> Yeah, I meant reinstalling with the reinstall button

However, when you do this (so not reinstalling stock app), no settings should be lost since the Youtube version you keep is the Vanced one
