### ISSUE TITLE
Disable "This app is in full screen" pop-up 

### ISSUE THREAD

**Issue by GreatestFool** [YTVanced/VancedManager#575]
![Screenshot_20210611-131607~(1)~(1)](https://user-images.githubusercontent.com/3003484/121679865-1d0bb880-cab9-11eb-8e62-05844eabdf21.png)

How do you disable this? I can't find a setting option for it and it is really annoying that you _must_ click ok and no other method works. Like yes, sure, _once_ is alright but I seriously don't need this for every other video. I'm aware of how swipe works.

**Device specifications:**
- Brand: Samsung S5e
- Operating System: Stock Android 
- Android Version: 11
- Vanced Manager Version: 2.6.0 (crimson)

**Comment by X1nto** [comment]
Not related to manager

**Comment by GreatestFool** [comment]
Sorry, was on mobile. Missed that I was on the manager repo.
