### ISSUE TITLE
network connection error

### ISSUE THREAD

**Issue by Aldmors** [YTVanced/VancedManager#577]
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Phone Specifications:**
- Brand: ZTE Nubia Z17 lite
- Operating System:Android
- Android Version:7.1.1
- Vanced Manager Version: 0.2.18.210500

**Please describe the problem you are having in as much detail as possible:**

After adding a google account to the application, when logging in to it, it shows an internet connection error

**Comment by cl-ement05** [comment]
This is not related to manager please report this at https://github.com/YTVanced/Vanced
