### ISSUE TITLE
[bug] Save button of versions does not appear in landscape mode. 

### ISSUE THREAD

**Issue by MiDoSaMi** [YTVanced/VancedManager#578]
Im unable to see the save button of the versions to lock into one and download it.. Forced to always download latest.. Works on portrait but not on landscape, which is the only mode available on my android car screen. 

Check below:
![Screenshot_20210613-085258_Vanced Manager](https://user-images.githubusercontent.com/48240416/121796849-c9b67900-cc24-11eb-9698-016d9a7e8108.jpg)
![Screenshot_20210613-085246_Vanced Manager](https://user-images.githubusercontent.com/48240416/121796850-cb803c80-cc24-11eb-90b1-853ca6e7bff5.jpg)

**Comment by cl-ement05** [comment]
For issues concerning yt Vanced itself report them to https://github.com/YTVanced/Vanced

**Comment by X1nto** [comment]
> For issues concerning yt Vanced itself report them to https://github.com/YTVanced/Vanced

It's a manager issue, they're talking about installation preferences bottom dialog.

**Comment by X1nto** [comment]
fixed in the new version
