### ISSUE TITLE
Can't open vanced

### ISSUE THREAD

**Issue by KeSaite** [YTVanced/VancedManager#58]
Brand: Oneplus

System: Oxygen OS

Android Version: Android 7.1.1

Vanced Manager Version: 1.0.2

Problem: vanced manager crashes immediately upon opening

Steps to reproduce: open on android 7.1.1

**Comment by X1nto** [comment]
Logcat would be helpful...

**Comment by KeSaite** [comment]
- adb logcat -v time >.\\logcat.log is here
[logcat.log](https://github.com/YTVanced/VancedManager/files/4870611/logcat.log)

- adb logcat *:W > logcat.txt is here
[logcat.txt](https://github.com/YTVanced/VancedManager/files/4870619/logcat.txt)

**Comment by X1nto** [comment]
Thanks, issue is fixed in new commits. You'll have to wait for an update
