### ISSUE TITLE
Vanced manager fails to install

### ISSUE THREAD

**Issue by mariodantas** [YTVanced/VancedManager#580]
- Brand: Ownice KT (Soc ums512)
- Operating System: Android 
- Android Version: 10
- Vanced Manager Version: latest

Failed to install modules (YT and YTM)

**Further details:**
![vanced_error](https://user-images.githubusercontent.com/1496045/121824222-d382bf80-ccaa-11eb-852b-1df3e3b4f6c5.png)

**Comment by X1nto** [comment]
You need to use Magisk in order to use Vanced Manager, other root solutions are not supported

**Comment by mariodantas** [comment]
Ok got it, I can't root my TS10 Headunit, this firmware if hard to die (hard to be rooted)

Thanks for the TIP !
