### ISSUE TITLE
Vanced microG and vanced YouTube unavailable

### ISSUE THREAD

**Issue by RaijinVPR** [YTVanced/VancedManager#582]
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Phone Specifications:**
- Brand: Xiaomin Poco M3
- Operating System: MIUI 12.0.9
- Android Version: Android 10
- Vanced Manager Version:  2.6.0

Please describe the problem you are having in as much detail as possible: When I open the manager, and try to install either microG or youtube, it won't let me. It says that it's unavailable.

Steps to reproduce: Open manager, and try to install microG or youtube.
![Screenshot_2021-06-14-20-51-06-780_com vanced manager](https://user-images.githubusercontent.com/85901473/121945185-c8379e80-cd53-11eb-8814-85d514b18e2b.jpg)

**Comment by RaijinVPR** [comment]
Nevermind, I just had to restart my phone.

**Comment by X1nto** [comment]
Servers are down, again

**Comment by Thorgalix** [comment]
It's up for me but it's impossible to download .. ![Screenshot_20210614_211743_com vanced manager](https://user-images.githubusercontent.com/85902274/121947128-fae29680-cd55-11eb-8846-93eb9c8c6798.jpg)

**Comment by mvfsullivan** [comment]
Ahh ok servers down. My luck LOL

**Comment by mvfsullivan** [comment]
Servers are back up FYI?

**Comment by cl-ement05** [comment]
> Servers are back up FYI?

Everything seems to be working now (at least for me)
