### ISSUE TITLE
Error Downloading dark.apk

### ISSUE THREAD

**Issue by woutfransis** [YTVanced/VancedManager#585]
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Phone Specifications:**
- Brand: Huawei
- Operating System:  EMUI 11.0.0
- Android Version: 10
- Vanced Manager Version: 2.6.0

**Please describe the problem you are having in as much detail as possible:**
Everythime I try to download YouTube vanced I get: Error Downloading dark.apk. Changed theme preference on install, error still exists.

**Steps to reproduce:**
Install vanced manager, install microg, install YouTube vanced

**Comment by X1nto** [comment]
Duplicate of #582
