### ISSUE TITLE
Add confirmation box for uninstall

### ISSUE THREAD

**Issue by ValleBL** [YTVanced/VancedManager#586]
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Suggestion:**
Add confirmation box on uninstall button

**Why is this suggestion relevant?**
Uninstalled by mistake a few times. Especially when you want to press update button

**Further details:**
none

**Comment by X1nto** [comment]
The feature is already added in 69e0221e8290b5ea8591cd911f6c252f2f02e46e, but I'll keep this issue open anyways.
