### ISSUE TITLE
Add a popup that tells you to disable automatic updates for youtube and youtube music in the playstore.

### ISSUE THREAD

**Issue by linusrg1** [YTVanced/VancedManager#588]
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Suggestion:**
Add popup telling users to disable automatic updates for youtube and youtube music.
**Why is this suggestion relevant?**
Because if you don't do this then google play will end up overwriting the vanced versions of youtube and youtube music with the stock versions.

**Comment by X1nto** [comment]
There's enough info on that in the guide app.

**Comment by linusrg1** [comment]
> There's enough info on that in the guide app.

Not everyone is gonna know that app exists. I didn't till just now. And why should we need yet another app to tell people something as simple as that. Why can't everything be done through the manager app? The experience seems a bit clunky to me.

**Comment by X1nto** [comment]
> > There's enough info on that in the guide app.
> 
> Not everyone is gonna know that app exists. I didn't till just now. And why should we need yet another app to tell people something as simple as that. Why can't everything be done through the manager app? The experience seems a bit clunky to me.

We don't want manager to be bloated. Manager's task is to help installing/updating apps, adding whole 30 pages of guide into manager will turn it into a mess.
