### ISSUE TITLE
Make a security conflict with bank app.

### ISSUE THREAD

**Issue by vieChong** [YTVanced/VancedManager#589]
After installed yt vanced on Samsung A71, one of a bank app alert of my phone being modify then factory default. Then it stop me from open bank app. Event uninstall yt vanced and restart few time and ran a security check. Then restart again, then reinstall the bank app. Still flag for modified device. Couldn't open anymore. 
Any suggestions?

**Comment by X1nto** [comment]
Duplicate of #420 and there's nothing we can do
