### ISSUE TITLE
Youtube Kids

### ISSUE THREAD

**Issue by kprsnt2** [YTVanced/VancedManager#606]
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Suggestion:** add support for Yt kids app also

**Why is this suggestion relevant?** now ads are coming in kids app also

**Further details:**

**Comment by X1nto** [comment]
nope, won't ever happen

**Comment by kprsnt2** [comment]
Why ?

In last one week they r giving ads for each 30min, due to this my kid is throwing his tab, if I gave him yt vanced he may watch other videos that's why I want kids app also

If possible kindly include this one too
