### ISSUE TITLE
Vanced gets removed on reboot if startup lock is turned on

### ISSUE THREAD

**Issue by n-ce** [YTVanced/VancedManager#607]
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Phone Specifications:**
- Brand: Asus
- Operating System: Android
- Android Version: 8.0
- Vanced Manager Version: 2.6.0

**Please describe the problem you are having in as much detail as possible:**
Vanced is removed on reboot if Device Boot Startup Lock is turned on.

**Steps to reproduce:**
1. Have Vanced Installed.
2. Set a lock screen with Device Boot Startup Lock turned on.
3. Reboot.
4. App Vanishes.

**Further details:**
App will reappear if Device Boot Startup Lock  is turned off and then rebooted.

**Comment by cl-ement05** [comment]
What is *secure boot* for you ?? Secure boot is a PC motherboard feature not a phone one. 

Also, when the app vanishes could you go to your app list in settings check if it is still installed ?

**Comment by X1nto** [comment]
Is it root version or nonroot?

**Comment by n-ce** [comment]
> Is it root version or nonroot?

Root Version, Latest Black.
And no it does not show up installed.

**Comment by n-ce** [comment]
> What is _secure boot_ for you ?? Secure boot is a PC motherboard feature not a phone one.
> 
> Also, when the app vanishes could you go to your app list in settings check if it is still installed ?

While setting lockscreen there is an option to enable "Require Pattern To Start Device" this looks like secure boot to me.

**Comment by cl-ement05** [comment]
> While setting lockscreen there is an option to enable "Require Pattern To Start Device" this looks like secure boot to me.

(aside your issue concerning Vanced Manager)

Oh no it is not. To sum up secure boot is a feature you find on all UEFI compatible motherboards. Its main goal is to make sure the OS you boot is secure and that you can trust it. It does that by checking if the UEFI key is whitelisted in a local *database* you can change. This avoids booting unknown OS or even malware.

## Concerning Vanced :
The thing you are talking about is an Android feature that will not let your phone finish booting without the password.
AFAIK, it should not have any impact on installed apps (Vanced should not vanish like that). Maybe the issue comes from something else.

Have you tried to install Vanced when it does not appear ?

**Comment by X1nto** [comment]
> > Is it root version or nonroot?
> 
> Root Version, Latest Black.
> And no it does not show up installed.

My guess is that Magisk either fails or intentionally doesn't initialize service.d and post-fs-data scripts while PIN startup lock (or what you call, secure boot) is enabled on your device.

**Comment by cl-ement05** [comment]
> 
> 
> > > Is it root version or nonroot?
> > 
> > 
> > Root Version, Latest Black.
> > And no it does not show up installed.
> 
> My guess is that Magisk either fails or intentionally doesn't initialize service.d and post-fs-data scripts while PIN startup lock (or what you call, secure boot) is enabled on your device.

Clearly it is see : [magisk issue](https://github.com/topjohnwu/Magisk/issues/4357)

**Comment by n-ce** [comment]
> > While setting lockscreen there is an option to enable "Require Pattern To Start Device" this looks like secure boot to me.
> 
> The thing you are talking about is an Android feature that will not let your phone finish booting without the password.

Ah, I see. I have renamed the issue accordingly.
> 
> Have you tried to install Vanced when it does not appear ?

No, I haven't. I did check the adb folder and found all the vanced related files still existed.
