### ISSUE TITLE
[ROOT] Vanced Manager can't install YouTube

### ISSUE THREAD

**Issue by aretekzs** [YTVanced/VancedManager#608]
**Phone Specifications:**
- Brand: OnePlus Nord
- Operating System: Oxygen OS
- Android Version: 11
- Vanced Manager Version: 2.6.0

**Please describe the problem you are having in as much detail as possible:**
Vanced Manager can't install YouTube. I am using Magisk.

**Steps to reproduce:**
1. Grant root permission
2. Install YouTube Vanced
3. Files are downloaded
4. Forever stuck in "_Please do NOT exit the app during the process!"_

**Further details:**

![image](https://user-images.githubusercontent.com/63618062/124475614-d187ba00-dd99-11eb-8cf3-08ce550df4f4.png)

**Comment by shier2nd** [comment]
I met the same issue today. However, I install the YouTube app from Play Store first, and then back to Vanced Manager to reinstall the (Vanced) YouTube app, it completed the installation successfully.

**Comment by PRinceBhai** [comment]
Did you try restarting the device after granting Root perms?

**Comment by aretekzs** [comment]
> I met the same issue today. However, I install the YouTube app from Play Store first, and then back to Vanced Manager to reinstall the (Vanced) YouTube app, it completed the installation successfully.

Thanks! This worked.
