### ISSUE TITLE
Making the screen dim when using 2 or 3 fingers gestures.

### ISSUE THREAD

**Issue by znaczki654** [YTVanced/VancedManager#609]
When I want to take a screenshot I get an issue that dims the screen and shows me option to forward or back the track on the playhead. The feature does not work and it gets annoying when using screenshots as a three finger gesture it gets activated and dims the screen.
![Screenshot_2021-07-07-05-03-14-267_com vanced android youtube](https://user-images.githubusercontent.com/27486533/124693966-abb8fd00-dee0-11eb-88b7-f644d1df1d15.jpg)

**Comment by X1nto** [comment]
Not related to manager
