### ISSUE TITLE
Brand vivo from install 

### ISSUE THREAD

**Issue by l3ugl2oono0** [YTVanced/VancedManager#615]
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Suggestion:**

**Why is this suggestion relevant?**

**Further details:**

**Comment by l3ugl2oono0** [comment]
Help me please.

**Comment by X1nto** [comment]
for god's sake would you stop opening blank issues

**Comment by l3ugl2oono0** [comment]
> for god's sake would you stop opening blank issues

What's your name?
