### ISSUE TITLE
Unable to install microG for secondary android user

### ISSUE THREAD

**Issue by elrac** [YTVanced/VancedManager#619]
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)
- As far as I can tell this is true

**Phone Specifications:**
- Brand: Galaxy Tab A7
- Operating System: Android
- Android Version: 11
- Vanced Manager Version: 2.6.0

**Please describe the problem you are having in as much detail as possible:**
My tablet has multiple users. Installing YouTube Vanced went fine on the primary user. When attempting to install Vanced microG for the secondary user I get an error.

java.lang.SecurityException: You need INTERACT_ACROSS_USERS or MANAGE_USERS permission to:
check getUserRestrictions

Screen cap of error will be at end of bug report.

**Steps to reproduce:**

1. Make a second Android user through the Android Settings
2. On the new user download and install YouTube Vanced Manager
3. Attempt to install Vanced microG

**Further details:**

![Screenshot_20210712-171239_Vanced Manager](https://user-images.githubusercontent.com/4564119/125372083-129e4200-e337-11eb-876f-510a9f7c4d30.jpg)

![Screenshot_20210712-173344_Vanced Manager](https://user-images.githubusercontent.com/4564119/125372255-7f194100-e337-11eb-89c2-aa80c2dd12c1.jpg)

**Comment by X1nto** [comment]
Please check issues before opening them, I already explained this 5 times. It's a limitation of android, if there's a workaround we can use, we'll use it.
