### ISSUE TITLE
Password Change of Google Account crashed YouTube Vanced

### ISSUE THREAD

**Issue by Tooba-Munir** [YTVanced/VancedManager#623]
Phone Specification: Realme C3
Android version: 10
Issue Details:
I updated my Google account password and after that I opened YouTube Vanced. It showed me the 'No internet connection' error. Although my internet was working fine. I crossed checked that on YouTube native app and it was working fine.
Then I removed the Vanced microG account from my device, cleared the data from YouTube Vanced app. Add account again in YouTube Vanced then it was working fine.
Expected Behavior:
Whenever password is changed for Google Account of user, Vanced microG should enforce the user to re-login so that this problem never appears again.

**Comment by X1nto** [comment]
not related to manager

**Comment by daikratu** [comment]
Xiaomi redmi 8 pro no setting vanced app

**Comment by daikratu** [comment]
I just update my phone to android 12
