### ISSUE TITLE
Can't install any updates

### ISSUE THREAD

**Issue by Ch1llb0** [YTVanced/VancedManager#625]
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Phone Specifications:**
- Brand: Samsung Galaxy Tab S6 Lite
- Operating System: Samsung Stock ROM
- Android Version: 11
- Vanced Manager Version: 2.6.0 (Crimson)

**Please describe the problem you are having in as much detail as possible:**

When trying to install updates for YouTube Vanced or Vanced microG, the Vanced Manager provides this error without installing the update:

![Screenshot_20210727-140112_Vanced Manager](https://user-images.githubusercontent.com/36623079/127150445-fa839621-c2b5-4485-a302-f703e5a9cb5b.png)

**Steps to reproduce:**

- Open Vanced Manager
- Press "update" on any of the two available packages
- Wait for some downloads to happen
- See the error message when installation should begin

**Further details:**

I'm using a multi-user setup that used to work without any issues until (I believe) the update to Android 11 - updates weren't an issue before.

**Comment by X1nto** [comment]
Manager doesn't support multi user accounts

**Comment by Ch1llb0** [comment]
Why has it worked before though? I've installed the manager and YouTube Vanced and kept it updated for quite a while. Only suddenly it stopped working.

**Comment by X1nto** [comment]
Probably something with android 11 and I don't quite want to look at it. I'll try to find some workaround for the next update

**Comment by Ch1llb0** [comment]
Would be much appreciated! 👍🏻 Love your work and would like to be able to keep using it on my multi-user tablet...

**Comment by Ch1llb0** [comment]
> Probably something with android 11 and I don't quite want to look at it. I'll try to find some workaround for the next update

I can report that a Vanced Manager update has installed successfully, but the consecutive updating of YouTube Vanced and MicroG from the new Manager didnt work. It would be great to get the functionality back that was there under Android 10 using a secondary user profile 👍🏻

**Comment by sanon** [comment]
Hi @X1nto,  
Same problem here... Galaxy Tab A7; multiuser account. To update Youtube Vanced, I've first uninstalled it via the Manager and can't install the newer version now. (Error message attached). Isn't there something I can do? Thanks.
![Screenshot_20211207-131607_Vanced Manager](https://user-images.githubusercontent.com/6686059/145020103-701bf643-38ed-4ade-8d71-155dbc78cafc.jpg)
