### ISSUE TITLE
Unable to install Youtube Vanced / Music 


### ISSUE THREAD

**Issue by viai957** [YTVanced/VancedManager#639]
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Phone Specifications:**
- Brand: Samsung A7 2018
- Operating System: Android 
- Android Version:10
- Vanced Manager Version:3

**Please describe the problem you are having in as much detail as possible:**
I am unable to download and install Youtube vanced/Music

It always shows error downloading dark.apk
**Steps to reproduce:**
![Screenshot_20210809-080831_Vanced Manager.jpg](https://user-images.githubusercontent.com/29157342/128655499-18d91f0b-c82a-44c9-b3ea-654139a4bb4f.jpg)

**Further details:**

**Comment by MinePlayersPE** [comment]
Server issue, not specifically a manager issue. Can be confirmed by using the mirror URL instead

**Comment by viai957** [comment]
> Server issue, not specifically a manager issue. Can be confirmed by using the mirror URL instead

I tried to download using a mirror URL but there's no option to download from Mirror URL in the Manager application.

**Comment by MinePlayersPE** [comment]
Then related: #641

**Comment by viai957** [comment]
Thanks got it
