### ISSUE TITLE
Manager can't find new Manager Update

### ISSUE THREAD

**Issue by ghost** [YTVanced/VancedManager#642]
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Phone Specifications:**
- Brand:Pixel 5
- Operating System:Android 12
- Android Version:12
- Vanced Manager Version:2.6.0

**Please describe the problem you are having in as much detail as possible:**

VencedManager can't find new update

**Steps to reproduce:**
VencedManager Open -) update -) Error

**Further details:**
None

**Comment by shubham399** [comment]
Happening same for  me on [OnePlus 6 LineageOS](https://download.lineageos.org/enchilada)

**Comment by KurioHonoo** [comment]
Pixel 3 running 12 as well and also cannot find updates.
