### ISSUE TITLE
Error updating

### ISSUE THREAD

**Issue by kamakshyaP** [YTVanced/VancedManager#644]
![Screenshot_20210809-113817_Vanced Manager](https://user-images.githubusercontent.com/21032122/128666056-f54035e0-ae2b-4f67-99b7-df592e768988.png)
First when i checked it's showed me the latest update but upon trying updating it said error downloading. So i reseted VM and now it won't even show me that an update is available.

Device: Samsung galaxy M31
Android 11

**Comment by PJFonseca** [comment]
Same here. 

OnePlus 6T with LineageOS

**Comment by wyueee** [comment]
Same issue, Android 11, Arrow OS Miatoll

**Comment by likkai** [comment]
Same here
Android 11 Samsung A50

**Comment by phanirithvij** [comment]
Same issue android 11. Realme 5 pro

**Comment by hamzaharoon1314** [comment]
Same issue, Samsung A20 Android 11. I even clear the dat a of manager but still same error

**Comment by BrenekH** [comment]
This is probably because too many people are trying to access the server to update. Wait a little bit (maybe a day?) and everything should even out.

**Comment by kamakshyaP** [comment]
> This is probably because too many people are trying to access the server to update. Wait a little bit (maybe a day?) and everything should even out.

But what about yesterday when I tried to update when it was showing update available and upon clicking it said error updating?

**Comment by kamakshyaP** [comment]
> This is probably because too many people are trying to access the server to update. Wait a little bit (maybe a day?) and everything should even out.

![Screenshot_20210809-121620_Vanced Manager.png](https://user-images.githubusercontent.com/21032122/128669062-3ff9e97d-876f-4eae-9fc9-94c92e3ba058.png)

This is what i am talking about. Now it's showing the update but...
