### ISSUE TITLE
No Update (Non-Root Vision)

### ISSUE THREAD

**Issue by IBimsPiepsii** [YTVanced/VancedManager#645]
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Phone Specifications:**
- Brand: Samsung Galaxy S9+
- Operating System:
![Screenshot_20210809-081524_Vanced Manager](https://user-images.githubusercontent.com/51275818/128666411-c6e2bec8-9b13-42e2-ac5b-43930c28f870.jpg)

- Android Version: Android 10
- Vanced Manager Version: 

**Please describe the problem you are having in as much detail as possible:**

**Steps to reproduce:**

**Further details:**

**Comment by eliduvid** [comment]
same, Samsung galaxy s7.

**Comment by ghost** [comment]
This, no install either

**Comment by BrenekH** [comment]
This is probably because too many people are trying to access the server to update. Wait a little bit (maybe a day?) and everything should even out.

**Comment by paweleq1994** [comment]
Same here. Vanced Manager 2.6.0 (Crimson). Xiaomi MI 10 lite
