### ISSUE TITLE
Vanced Manager push Music Vanced notification even when disabled

### ISSUE THREAD

**Issue by thanhminhmr** [YTVanced/VancedManager#647]
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

YES, it is.

**Phone Specifications:**
- Brand: Nokia 7 Plus
- Operating System: Android One
- Android Version: Android 10
- Vanced Manager Version: 2.6.0

**Please describe the problem you are having in as much detail as possible:**

I disabled Music Vanced notifications (about new updates), but I still receive notifications.

**Steps to reproduce:**

- Open *Vanced Manager*
- Open *Settings* from 3-dot top left drop down menu
- Disable *YouTube Music Vanced Push Notifications*
- Wait for a new update of Music Vanced.
- The notification shows up.

**Further details:**
![Screenshot_20210809-130550](https://user-images.githubusercontent.com/31412085/128666720-476248b9-14bb-4071-9d3c-cd8f3ee373a5.png)

**Comment by m4heshd** [comment]
Yup. Just got this notif.

**Comment by thanhminhmr** [comment]
@X1nto is this a Won't Fix? The last duplicate bug report is from March

**Comment by X1nto** [comment]
> @X1nto is this a Won't Fix? The last duplicate bug report is from March   

No, it's just a duplicate. Forgot to mention, sorry
