### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by X1nto** [YTVanced/VancedManager#650]
Yeah so basically server is down again lol

How to fix:
- you can't

Additional notes:
I beg all of you, please stop opening same issues over and over again. PLEASE

Thank you for your cooperation.

**Comment by AliTheMN** [comment]
ETA?

**Comment by nssatlantis** [comment]
Perhaps time they either worked it out or provide a 2nd download mirror within the app, simple solutions go a long way haha

**Comment by mon5termatt** [comment]
[Have some patience y'all](https://youtu.be/ErvgV4P6Fzc)

**Comment by AliTheMN** [comment]
@mon5termatt
Did...did you just link us to a YouTube video when the server to download the app is down?

**Comment by X1nto** [comment]
> Perhaps time they either worked it out or provide a 2nd download mirror within the app, simple solutions go a long way haha

There is a mirror which you can put in the app.

**Comment by mon5termatt** [comment]
> @mon5termatt
> Did...did you just link us to a YouTube video when the server to download the app is down?

Lol ya

**Comment by X1nto** [comment]
> @mon5termatt
> Did...did you just link us to a YouTube video when the server to download the app is down?

It's not like you uninstalled Vanced, right?

**Comment by nssatlantis** [comment]
> > Perhaps time they either worked it out or provide a 2nd download mirror within the app, simple solutions go a long way haha
> 
> There is a mirror which you can put in the app.

If there was, I would have downloaded them damn updates already! Haha

**Comment by X1nto** [comment]
> > > Perhaps time they either worked it out or provide a 2nd download mirror within the app, simple solutions go a long way haha
> > 
> > There is a mirror which you can put in the app.
> 
> If there was, I would have downloaded them damn updates already! Haha

??????

https://mirror.codebucket.de/vanced

**Comment by AliTheMN** [comment]
@X1nto
Funny thing about that. I didn't think it'd be a server issue. I mayy have uninstalled it 😬

**Comment by X1nto** [comment]
> @X1nto
> Funny thing about that. I didn't think it'd be a server issue. I mayy have uninstalled it 😬

I have no idea why people think that if manager can't download Vanced, it's related to installed version of  Vanced. Where did you all get that idea from?

**Comment by AliTheMN** [comment]
Im not the brightest lightbulb always, especially  after midnight lol

**Comment by 0x44454c** [comment]
> @X1nto
> Funny thing about that. I didn't think it'd be a server issue. I mayy have uninstalled it 😬

Me too! 😬😬 Thought my phone's issue!!😬😬

**Comment by tribela** [comment]
> > @mon5termatt
> > Did...did you just link us to a YouTube video when the server to download the app is down?
> 
> It's not like you uninstalled Vanced, right?

I uninstalled 😢

**Comment by hasanmohdkhan** [comment]
Older version of vacnced manager working fine.
But downloading speed is very slow 22 KBps.

**Comment by cl-ement05** [comment]
@X1nto 

The same thing happens every time an update is dropped. To avoid getting tons of notifications because of people opening new issues maybe you could add a message in the issue template like "If this issue concerns downloading and an update was just released, this may be happening because the server is down. Please wait a few hours."

What do u think ?

And if the same situation keeps happening maybe add a Dialog in the Manager itself

**Comment by X1nto** [comment]
> @X1nto 
> 
> The same thing happens every time an update is dropped. To avoid getting tons of notifications because of people opening new issues maybe you could add a message in the issue template like "If this issue concerns downloading and an update was just released, this may be happening because the server is down. Please wait a few hours."
> 
> What do u think ?
> 
> And if the same situation keeps happening maybe add a Dialog in the Manager itself

Ig it's better to improve automatic mirror switch and maybe even put json load on firebase so the only thing Vanced server does is actual downloading. This should be more performant

**Comment by tomo0611** [comment]
The server seems to be revived!!! (Rooted/DNS is cloudflare one)
But maybe in Japan only?

![Screenshot_20210809-175732_Vanced_Manager~2](https://user-images.githubusercontent.com/31959526/128682143-ac685bf1-95ae-4a52-b080-296fcb364c12.png)

**Comment by tomo0611** [comment]
The server dead again😭

![Screenshot_20210809-180829_Vanced_Manager~2](https://user-images.githubusercontent.com/31959526/128683402-8a7a3493-3bad-44bb-8cd2-2ab4f320ea26.png)

**Comment by LeeRyan9** [comment]
Ổn rồi

**Comment by Poilaucul** [comment]
Works fine on my Samsung Galaxy S20 FE, but on my Huawei Mate 9 there is a message saying the download is corrupted, although I don't think it tried downloading anything in half a second of getting the error...

**Comment by sudo-nautilus** [comment]
@X1nto it's working fine now (atleast, for me),

Close issue wen? :trollface:

**Comment by X1nto** [comment]
Closing, should be working without any issues now

**Comment by sudo-nautilus** [comment]
Hmm

**Comment by Girhi** [comment]
Omfg LEAVE ME ALONE

Em qua, 11 de ago de 2021 07:03, Nautilus ***@***.***>
escreveu:
