### ISSUE TITLE
Non touch support

### ISSUE THREAD

**Issue by wyvernmix** [YTVanced/VancedManager#652]
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Phone Specifications:**
- Brand: nvidia
- Operating System: shield tv
- Android Version:
- Vanced Manager Version:

Can get it to install but can't navigate the interface with the controller just stays on let's get start screen 
**Please describe the problem you are having in as much detail as possible:**

**Steps to reproduce:**

Install on android TV system
**Further details:**

**Comment by X1nto** [comment]
Android TVs are not supported.
