### ISSUE TITLE
Can't change selected version

### ISSUE THREAD

**Issue by Janrupf** [YTVanced/VancedManager#654]
**Phone Specifications (1):**
- Brand: Samsung Galaxy J5
- Operating System: LineageOS 17.1
- Android Version: Android 10
- Vanced Manager Version: 2.6.0

**Phone Specifications (2):**
- Brand: Huawei Y560
- Operating System: LineageOS 14
- Android Version: Android 7
- Vanced Manager Version: 2.6.0

**Please describe the problem you are having in as much detail as possible:**
When selecting the version of YouTube Music or YouTube, the selection menu pops up, but selecting any version does nothing. VancedManager always displays "latest" as installation target and also always installs the latest version.

**Steps to reproduce:**
1. Open VancedManager
2. Select YouTube or YouTube Music to install
3. Attempt to change version which should be installed

**Further details:**
Both phones have in common that they are running LineageOS, though I heavily assume that this is not the issue as they are running different versions of both.

**Comment by Girhi** [comment]
Shit up actually annoying

Em ter, 10 de ago de 2021 17:14, Janrupf ***@***.***>
escreveu:

**Comment by X1nto** [comment]
Are you clicking the save button?

**Comment by Janrupf** [comment]
Well, if there would be one in first place. 

Screenshot of menu when scrolling up:
![image](https://user-images.githubusercontent.com/25827180/129008127-73ca4811-da3c-4e1f-824b-b11ec6b4c799.png)

Screenshot of menu when scrolling down (bottom reached, can't scroll down further):
![image](https://user-images.githubusercontent.com/25827180/129008178-5c5a6446-711c-4c82-a4f1-1a3654aa9e4e.png)

And well, leaving the menu resets the version to latest

**Comment by X1nto** [comment]
> Well, if there would be one in first place.
> 
> Screenshot of menu when scrolling up:
> ![image](https://user-images.githubusercontent.com/25827180/129008127-73ca4811-da3c-4e1f-824b-b11ec6b4c799.png)
> 
> Screenshot of menu when scrolling down (bottom reached, can't scroll down further):
> ![image](https://user-images.githubusercontent.com/25827180/129008178-5c5a6446-711c-4c82-a4f1-1a3654aa9e4e.png)
> 
> And well, leaving the menu resets the version to latest

Oh boy this is a big bug

**Comment by Janrupf** [comment]
Interesting, the button shows up if layed out above the scroll view.
![image](https://user-images.githubusercontent.com/25827180/129022249-6eeee168-d8a7-4f0f-ad24-981ec983e595.png)

**Comment by Girhi** [comment]
Leave me alone.

Em qua, 11 de ago de 2021 08:37, Janrupf ***@***.***>
escreveu:

**Comment by themerfmerf** [comment]
Same problem here for me.

Phone Specifications:

    Brand: Sony Xperia XZ1 Compact
    Android Version: Android 9
    Vanced Manager Version: 2.6.0

**Comment by X1nto** [comment]
should be fixed in the latest version
