### ISSUE TITLE
let you install the apk version with root

### ISSUE THREAD

**Issue by lokzz** [YTVanced/VancedManager#656]
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Suggestion:** let you install the apk version with root

**Why is this suggestion relevant?** because if i use the root version it just auto updates to the offical youtube but i saw people having problems with microG 

**Further details:** no

**Comment by X1nto** [comment]
I have no idea what you're talking about

**Comment by Girhi** [comment]
Just shut up and stop talking to me.

Em qua, 11 de ago de 2021 07:11, Tornike Khintibidze <
***@***.***> escreveu:
