### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Anuarbek21** [YTVanced/VancedManager#660]
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Phone Specifications:**
- Brand: Meizu
- Operating System: Flyme 7.8.8.31G beta
- Android Version: 6.0
- Vanced Manager Version: 2.6.0 (Crimson)

**Please describe the problem you are having in as much detail as possible:**
When I try to download microg, I get an error.

**Steps to reproduce:**
https://user-images.githubusercontent.com/88872274/129308444-cfae6d07-f51b-48be-b70b-be07ef131a88.mp4
https://user-images.githubusercontent.com/88872274/129308602-d7825c93-4682-4b3b-b6c5-d44762addcf4.jpg
**Further details:**
-

**Comment by X1nto** [comment]
Provide logs

**Comment by Anuarbek21** [comment]
> Предоставить журналы

How to do it?

**Comment by X1nto** [comment]
Ah you're Russian

Погугли «как получить logcat?», после получения отправь файл тут

**Comment by Anuarbek21** [comment]
> Ах ты русский
> 
> Погугли «как получить logcat?», После получения отправь файл тут

[21-08-13--13-05-58.zip](https://github.com/YTVanced/VancedManager/files/6980545/21-08-13--13-05-58.zip)

**Comment by Anuarbek21** [comment]
> Ах ты русский
> 
> Погугли «как получить logcat?», После получения отправь файл тут

Почти угадал(а), я казах

**Comment by X1nto** [comment]
> > Ах ты русский
> > 
> > Погугли «как получить logcat?», После получения отправь файл тут
> 
> [21-08-13--13-05-58.zip](https://github.com/YTVanced/VancedManager/files/6980545/21-08-13--13-05-58.zip)
> 

Мда это какие то неправильные логи, надо было через ADB сделать. https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000ClYXCA0

**Comment by Anuarbek21** [comment]
> > > Ах ты русский
> > > Погугли «как получить logcat?», После получения отправь файл тут
> > 
> > 
> > [21-08-13--13-05-58.zip](https://github.com/YTVanced/VancedManager/files/6980545/21-08-13--13-05-58.zip)
> 
> Мда это какие то неправильные логи, надо было через ADB сделать. https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000ClYXCA0

[logcat.zip](https://github.com/YTVanced/VancedManager/files/6981712/logcat.zip)
Правильные логи?

**Comment by X1nto** [comment]
> [logcat.zip](https://github.com/YTVanced/VancedManager/files/6981712/logcat.zip)
> Правильные логи?

Всё обрезано. Попробуй установить microg заново и когда до ошибки дойдет, снять логи

**Comment by Anuarbek21** [comment]
> > [logcat.zip](https://github.com/YTVanced/VancedManager/files/6981712/logcat.zip) 
> > Правильные логи?
> 
> Всё обрезано. Попробуй установить microg заново и когда до ошибки дойдет, снять логи

[logcat2.zip](https://github.com/YTVanced/VancedManager/files/6982068/logcat2.zip)

**Comment by X1nto** [comment]
> 
> 
> 
> > > [logcat.zip](https://github.com/YTVanced/VancedManager/files/6981712/logcat.zip) 
> > > Правильные логи?
> > 
> > Всё обрезано. Попробуй установить microg заново и когда до ошибки дойдет, снять логи
> 
> [logcat2.zip](https://github.com/YTVanced/VancedManager/files/6982068/logcat2.zip)
> 

Тут опять нечего нет. Какой программой пользуешься?

**Comment by Anuarbek21** [comment]
> > > > [logcat.zip](https://github.com/YTVanced/VancedManager/files/6981712/logcat.zip) 
> > > > Правильные логи?
> > > 
> > > 
> > > Всё обрезано. Попробуй установить microg заново и когда до ошибки дойдет, снять логи
> > 
> > 
> > [logcat2.zip](https://github.com/YTVanced/VancedManager/files/6982068/logcat2.zip)
> 
> Тут опять нечего нет. Какой программой пользуешься?

SDK Platform Tools

**Comment by X1nto** [comment]
> > > > > [logcat.zip](https://github.com/YTVanced/VancedManager/files/6981712/logcat.zip) 
> > > > > Правильные логи?
> > > > 
> > > > 
> > > > Всё обрезано. Попробуй установить microg заново и когда до ошибки дойдет, снять логи
> > > 
> > > 
> > > [logcat2.zip](https://github.com/YTVanced/VancedManager/files/6982068/logcat2.zip)
> > 
> > Тут опять нечего нет. Какой программой пользуешься?
> 
> SDK Platform Tools

Странно, тогда попробуй это:
adb logcat -c
*начни загрузку microg, дойди до ошибки*
adb logcat > logcat.txt
Отправь полученный logcat.txt тут.

**Comment by Anuarbek21** [comment]
> > > > > > [logcat.zip](https://github.com/YTVanced/VancedManager/files/6981712/logcat.zip) 
> > > > > > Правильные логи?
> > > > > 
> > > > > 
> > > > > Всё обрезано. Попробуй установить microg заново и когда до ошибки дойдет, снять логи
> > > > 
> > > > 
> > > > [logcat2.zip](https://github.com/YTVanced/VancedManager/files/6982068/logcat2.zip)
> > > 
> > > 
> > > Тут опять нечего нет. Какой программой пользуешься?
> > 
> > 
> > Инструменты платформы SDK
> 
> Странно, тогда попробуй это:
> adb logcat -c
> _начни загрузку microg, дойди до_
> ошибок adb logcat> logcat.txt
> Отправь полученный logcat.txt тут.

[logcat3.zip](https://github.com/YTVanced/VancedManager/files/6982364/logcat3.zip)
![image](https://user-images.githubusercontent.com/88872274/129356786-47218c8e-0d05-414a-b049-ef91e3b9e225.png)

**Comment by X1nto** [comment]
> [logcat3.zip](https://github.com/YTVanced/VancedManager/files/6982364/logcat3.zip)
> ![image](https://user-images.githubusercontent.com/88872274/129356786-47218c8e-0d05-414a-b049-ef91e3b9e225.png)

Ясно, ты нажимаешь на "установить" или "скачать заново" когда нижное меню всплывает?

**Comment by Anuarbek21** [comment]
> > [logcat3.zip](https://github.com/YTVanced/VancedManager/files/6982364/logcat3.zip)
> > ![изображение](https://user-images.githubusercontent.com/88872274/129356786-47218c8e-0d05-414a-b049-ef91e3b9e225.png)
> 
> Ясно, ты нажимаешь на "установить" или "скачать заново" когда нижнее меню всплывает?

скачать заново

**Comment by X1nto** [comment]
> > > [logcat3.zip](https://github.com/YTVanced/VancedManager/files/6982364/logcat3.zip)
> > > ![изображение](https://user-images.githubusercontent.com/88872274/129356786-47218c8e-0d05-414a-b049-ef91e3b9e225.png)
> > 
> > Ясно, ты нажимаешь на "установить" или "скачать заново" когда нижнее меню всплывает?
> 
> скачать заново
> 

Мда, тогда у Flyme просто кукуха пошла, ничем помочь не могу в этом случае

**Comment by Anuarbek21** [comment]
> > > > [logcat3.zip](https://github.com/YTVanced/VancedManager/files/6982364/logcat3.zip)
> > > > ![изображение](https://user-images.githubusercontent.com/88872274/129356786-47218c8e-0d05-414a-b049-ef91e3b9e225.png)
> > > 
> > > 
> > > Ясно, ты нажимаешь на "установить" или "скачать заново" когда нижнее меню всплывает?
> > 
> > 
> > скачать заново
> 
> Мда, тогда у Flyme просто кукуха пошла, ничем помочь не могу в этом случае
Странно..
Если скачивать отдельно апк microg и vanced с пиратских сайтов, то почему-то все скачивается без проблем, только вот они с вирусняком и данные воруют 
Ладно, спасибо за помощь
