### ISSUE TITLE
Notification issues

### ISSUE THREAD

**Issue by LMarius** [YTVanced/VancedManager#663]
### Discussed in https://github.com/YTVanced/VancedManager/discussions/662

<div type='discussions-op-text'>

<sup>Originally posted by **LMarius** August 15, 2021</sup>
I have some problems. Last night,6 notifications appeared from youtube,cleared them and after 1 minute they appeared back. This happens all the time,in every minute. I disabled the notifications and now i don t have problems,but i miss to get notifications from yt :/
![Screenshot_20210814-224743_Reddit](https://user-images.githubusercontent.com/85368976/129470940-7258af33-ed92-4202-bff3-0d751e235eec.jpg)
![Screenshot_20210814-224749_Reddit](https://user-images.githubusercontent.com/85368976/129470941-2791df70-faad-4d0d-9955-791eccd03fc2.jpg)
![Screenshot_20210814-224816_Reddit](https://user-images.githubusercontent.com/85368976/129470942-4982d0d9-59d3-4c9b-8a27-66c1305f75f4.jpg)
</div>

**Comment by X1nto** [comment]
Not related to manager
