### ISSUE TITLE
Android 5.0.1 cannot install Youtube Vanced and Vanced microG.

### ISSUE THREAD

**Issue by Tommy881719** [YTVanced/VancedManager#666]
**Phone Specifications:**
- Brand:Samsung
- Operating System:Android 
- Android Version:5.0.1
- Vanced Manager Version:2.6.0

**Please describe the problem you are having in as much detail as possible:**

*The installation process is endless, and the installation of Youtube Vanced and Vanced microG cannot be completed, so there will be no logs.

At present, it can only be installed manually, but Youtube Vanced can only install the old version, because the new version is an APK bundle.

**Steps to reproduce:**

I have taken the actual video and screenshots, I hope to let you know more about the bug.

**Further details:**

![Screenshot_2021-08-21-21-57-53](https://user-images.githubusercontent.com/85065903/130324448-c020de6f-e3e9-4b3a-bbc2-71f8363bafc6.png)
![Screenshot_2021-08-21-21-58-07](https://user-images.githubusercontent.com/85065903/130324450-4c666c0f-c804-47f6-9dd2-2e9d212de277.png)
![Screenshot_2021-08-21-21-58-15](https://user-images.githubusercontent.com/85065903/130324451-9be2b739-34b7-423a-ae94-c4ac28bac83d.png)

https://user-images.githubusercontent.com/85065903/130324433-f3145367-1503-4cc8-b496-25a40e22af58.mp4

**Comment by X1nto** [comment]
It should be requesting installation prompt but it's not, probably something wrong with your system

**Comment by Tommy881719** [comment]
> 應該是要求安裝提示，但不是，可能是你的系統有問題

I use the original system, and other phones of the same model have the same bug.

So is there really no solution to this bug?

**Comment by X1nto** [comment]
> I use the original system, and other phones of the same model have the same bug.
> 
> So is there really no solution to this bug?

I'll see what I can do

**Comment by Tommy881719** [comment]
> > 我用的是原系統，其他同型號手機也有同樣的bug。
> > 那麼這個bug真的沒有辦法解決嗎？
> 
> 我會看看我能做什麼

Ok thank you

**Comment by SimplyMika** [comment]
I have the exact same issue on my Redmi 10X 5G (model M2004J7AC) on MIUI 12.5.4 (Android 11).
Not sure why this issue is closed, is it resolved yet? If so, what's the solution? I would love to know.
I'm on Vanced Manager 2.6.0.

**Comment by SimplyMika** [comment]
Nevermind, in my case the issue was MIUI optimization (as always...), sorry to bother!

**Comment by Tommy881719** [comment]
> 沒關係，就我而言，問題是 MIUI 優化（一如既往......），抱歉打擾！

This problem has not been resolved.

**Comment by Tommy881719** [comment]
I seem to press to close the comment, sorry.

**Comment by X1nto** [comment]
I just noticed this is the same as #564
