### ISSUE TITLE
Freezes The phone Completely 

### ISSUE THREAD

**Issue by Professor-1** [YTVanced/VancedManager#667]
1》I am using j7 Oreo 8.1. Oftentimes YouTube Vanced Freezes The phone Entirely. You cannot go to settings, Home button becomes useless.
But official YOUTUBE has Never did that.
And then you have to restart the phone.

2》When vanced is in Picture in picture mode Sometimes Vanced freezes the entire YouTube in that Small box of Picture in Picture.
Then you can either go to settings to FORCE STOP Or Restart the  phone.

3》Refreshing Home page becomes MYTH in YOUTUBE VANCED.

**Comment by X1nto** [comment]
Not related to manager
