### ISSUE TITLE
YT Music disappear after reboot or OS update

### ISSUE THREAD

**Issue by dickta** [YTVanced/VancedManager#668]
YT music disappearing after reboot or os update in root mode.

Device: Xiaomi Redmi Note 5 (whyred)
OS: LineageOS 18.1 official nighly 2021.08.23 built in kernel, rooted by Magisk 23 official stable Magisk Hide enabled.

No other changes were made.

**Comment by X1nto** [comment]
Use issue search feature of GitHub
