### ISSUE TITLE
[Improvement] Requesting a custom color picker

### ISSUE THREAD

**Issue by TacoTheDank** [YTVanced/VancedManager#67]
I think it would be super cash money if, instead of five predetermined colors, we could choose a custom color using a color picker.

I have gathered some colorpicker libraries as examples.

Kotlin-based:
- https://github.com/Madrapps/Pikolo
- https://github.com/side-codes/andColorPicker
- https://github.com/Dhaval2404/ColorPicker
- https://github.com/ohmae/color-chooser
- https://github.com/msasikanth/ColorSheet
- https://github.com/ItsPriyesh/chroma

Java-based:
- https://github.com/fennifith/ColorPickerDialog
- https://github.com/QuadFlask/colorpicker
- https://github.com/jaredrummler/ColorPicker
- https://github.com/Pes8/android-material-color-picker-dialog

(I think the Kotlin ones look a bit nicer, imo.)
Of course, you can also choose your own if you want.

(Also, instead of "we decided to make an installer for Vanced", I think it would be funnier if it said "we decided to make an app for installing Vanced", to match better with the MeME ScrIPt.)

https://github.com/YTVanced/VancedManager/blob/master/READMEME.md#problems-with-apks-format

Also Laura's pretty cute ngl 😳

**Comment by X1nto** [comment]
Adding theming using hex colors is not as easy as it seems. This doesn't mean that we won't try to implement it, but we can't guarantee either, so we'll see how this goes. Thanks for being interested in project

**Comment by X1nto** [comment]
Btw do we still need this? I'm kinda lazy ngl

**Comment by X1nto** [comment]
Actually nevermind I might add this in an upcoming release of i have enough time

**Comment by X1nto** [comment]
This is epic isn't it cc72b1c7d12f3e6bdc2a3c3bae5cc20662b1a13c

**Comment by X1nto** [comment]
Added™

**Comment by TacoTheDank** [comment]
:prayer_with_no_shoe:
