### ISSUE TITLE
Swipe to refresh yt feed unreliable

### ISSUE THREAD

**Issue by ceejey** [YTVanced/VancedManager#673]
Hello everybody,

the swipe down action on the personal feed of yt does work a few times when opening the app and then just don't show the loading circle anymore while swiping down but still the "swipe shadow". I have to switch the screen and go back to the feed to be able to refresh again a few times until it happens again.

BR

**Comment by X1nto** [comment]
not related to manager

**Comment by ceejey** [comment]
Oh sorry, will post it in the right place
