### ISSUE TITLE
Download stuck at 0%

### ISSUE THREAD

**Issue by astrolemonade** [YTVanced/VancedManager#677]
**Phone Specifications:**
- Brand: Huawei P40 E
- Operating System: EMUI 11
- Vanced Manager Version: 2.6.0

**Please describe the problem you are having in as much detail as possible:**
Every download is stuck at 0%, storage permissions have been granted

**Comment by X1nto** [comment]
Are you sure it's not your internet?

**Comment by astrolemonade** [comment]
Very sure

**Comment by X1nto** [comment]
there's a high chance it's your ISP blocking the domain, try using a different DNS from either google or cloudflare. If you already have an active DNS try disabling that first

**Comment by astrolemonade** [comment]
Yes, you were right

**Comment by X1nto** [comment]
if the issue got resolved I'll close this, feel free to reopen if you want to

**Comment by pronoob249** [comment]
Same issue
