### ISSUE TITLE
Installation fails on BlueStacks Emulator

### ISSUE THREAD

**Issue by p3rd1x** [YTVanced/VancedManager#678]
**Phone Specifications:**
- Brand:
Bluestacks 4.280.0.4206 Hyper-V on Windows 10
emulates a Samsung Galaxy S8+ SM-G955F

- Android Version:
Android 7.1.2 Rooted

- Vanced Manager Version:
2.6.0 (Crimson)

**Please describe the problem you are having in as much detail as possible:**
Installation Process for both Youtube Vanced and Youtube Music Vanced fails.
"Installation failed for unknown reasons" see Screenshot for Details

**Steps to reproduce:**
- Install Vanced Manager
- Start Manager
- Grant Root Permissions
- Install Youtube Vanced / Youtube Music Vanced

**Further details:**
![image](https://user-images.githubusercontent.com/73039942/133357843-28ca6297-9e68-4559-979a-fa516b9b12fb.png)

**Comment by X1nto** [comment]
emulators are not supported since they don't have Magisk
