### ISSUE TITLE
Download Stuck at 0% inside manager app

### ISSUE THREAD

**Issue by pronoob249** [YTVanced/VancedManager#680]
**Please only open the issue if the following is true**
- This is an issue in the Vanced Manager and ONLY Vanced Manager (NOT Youtube Vanced/Music/microG)

**Phone Specifications:**
- Brand: Redmi
- Operating System: Android
- Android Version: 9
- Vanced Manager Version: 2.6

**Please describe the problem you are having in as much detail as possible:**

**Steps to reproduce:**

**Further details:**

**Comment by X1nto** [comment]
Again, duplicate of #677
