### ISSUE TITLE
Vanced needs it's own YouTube comment section outside of YouTube's official comment sections. 

### ISSUE THREAD

**Issue by cheperth** [YTVanced/VancedManager#682]
(Suggestion) I think it would be awesome if YouTube Vanced had a separate comment section for commenting on YouTube videos that is outside of YouTube and cannot be monitored or moderated by the YouTube corporation. Youtube is using word filters and algorithms that instantly block and erase comments from appearing using specific keywords without human moderators looking at them or there being a review process or an appeal process. It would be nice to be able to comment on and have discussions on videos with disabled comment sections. It would essentially be the same as posting videos on social media and commenting on them, the difference that all Vanced users would see each others comments.

**Comment by X1nto** [comment]
No it doesn't and wrong repo

**Comment by cheperth** [comment]
My apologies. I was in the Youtube Vanced Discord server and it pointed to this page as the place to leave suggestions. What I left was a suggestion. The app is great, always has been great. I meant to leave a suggestion. I am not an entitled person. While Youtube Vanced app is a free and great app I am not complaining or making demands. I can't find a proprietary or paid app/service that does what i am describing. I am willing to pay a monthly fee to use such an app but I can't find it. An Alt Tech company made a browser plugin that does what I am describing for all websites, not just Youtube, and the plugin was banned/prevented from working on Chrome, Firefox and all other browsers, They made their own browser with the plug in based on Brave Browser but I can't get it to work. 

I am a 90s kid. Born in the 80s. Over the course of several years I got used to comment sections working in the way where people can say what they want to say without an algorithm erasing their comments without a human moderator or owner making the decision. This is how most websites worked until recent years. I fully support human moderators enforcing whatever guidelines they want to enforce. It's pretty ridiculous at this point. For me there is no point in using any Youtube app if the comment sections are unusable and block comments based on no clear guidelines and don't adhere to any known common sense Community Guidelines or Terms of Service. 

If you don't believe in the Legal Definition of the American First Amendment or you can't differentiate "hate speech" from "disagreeable speech" or "mean speech" or you don't agree corporations being held to the standards of section 230 immunity which provides them protections from lawsuits for content posted on their websites because they are "Neutral Public Forums" and actually requiring them to act like "Neutral Public Forums". I won't waste any more of either more of our time.

**Comment by fembyfox** [comment]
> My apologies. I was in the Youtube Vanced Discord server and it pointed to this page as the place to leave suggestions. What I left was a suggestion. The app is great, always has been great. I meant to leave a suggestion. I am not an entitled person. While Youtube Vanced app is a free and great app I am not complaining or making demands. I can't find a proprietary or paid app/service that does what i am describing. I am willing to pay a monthly fee to use such an app but I can't find it. An Alt Tech company made a browser plugin that does what I am describing for all websites, not just Youtube, and the plugin was banned/prevented from working on Chrome, Firefox and all other browsers, They made their own browser with the plug in based on Brave Browser but I can't get it to work.
> 
> I am a 90s kid. Born in the 80s. Over the course of several years I got used to comment sections working in the way where people can say what they want to say without an algorithm erasing their comments without a human moderator or owner making the decision. This is how most websites worked until recent years. I fully support human moderators enforcing whatever guidelines they want to enforce. It's pretty ridiculous at this point. For me there is no point in using any Youtube app if the comment sections are unusable and block comments based on no clear guidelines and don't adhere to any known common sense Community Guidelines or Terms of Service.
> 
> If you don't believe in the Legal Definition of the American First Amendment or you can't differentiate "hate speech" from "disagreeable speech" or "mean speech" or you don't agree corporations being held to the standards of section 230 immunity which provides them protections from lawsuits for content posted on their websites because they are "Neutral Public Forums" and actually requiring them to act like "Neutral Public Forums". I won't waste any more of either more of our time.

The first amendment doesn't apply to private businesses you absolute conservative idiot

**Comment by ghost** [comment]
The matter of the fact is that on any reasonably large website, especially on popular videos, it's simply impossible to rely on human moderators alone. I don't know how exactly Google's current system works, ideally there should be an appeal process for falsely flagged comments, but knowing Google I bet the majority of them are just ignored or rejected, even though they're a massive company that would definitely have the resources to handle them.
