### ISSUE TITLE
[Bug] not letting me choose a youtube venced version

### ISSUE THREAD

**Issue by Amiru4481** [YTVanced/VancedManager#684]
**Bug description**
When i want to download youtube venced, it doesnt let me choose the specific version, it gets stuck with only the latest version.

**Variant**
Non-Root

**Vanced version**
Venced Manager 2.6.0

**Android version**
5.0.2

**Device**
HTC One E9PLUS Dual Sim

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'Youtubr Venced Installation Preference'
3. Click on Versions: (select any) and the options just stay and dont apply

**Expected behavior**
Ive used Youtube Venced before, it was supposed to download me a choosen version and not the latest

![Screenshot_2021-09-19-06-46-44](https://user-images.githubusercontent.com/90996789/133914541-6ab41b97-e4a2-42f4-8d88-15959aa8dd9c.jpg)

**Comment by Amiru4481** [comment]
> Okay, I am transferring this issue to the vanced manager repo.

Alright thanks, if anything it just has to do with my old shit phone 😂

**Comment by X1nto** [comment]
Duplicate of #654
