### ISSUE TITLE
Someone is renaming your app.

### ISSUE THREAD

**Issue by Battler624** [YTVanced/VancedManager#690]
So random is renaming your app and calling it his own, "Youtube Gold", more like an arabic edition of your vanced but renamed.

Obviously there are no credits else i would've not made this post.

Youtube Gold = يوتيوب الذهبي

Using the arabic terms gives straight results.

Here is the "creator" https://www.3ssem.com/2021/05/youtube-gold.html

**Comment by KevinX8** [comment]
There are thousands of clones of vanced with the name changed to "YouTube premium crack" or similar, not much we can do about it
