### ISSUE TITLE
Read notifications keep re-appearing

### ISSUE THREAD

**Issue by MrAppAndCrap** [YTVanced/VancedManager#703]
Hey. I'm using a real me 8 phone. It is running "vanced" 16.29.39. When I click the notifications to say I have read it, it pops back up again with another notification of the same comment. I have tried swiping the notifications away. Turning them on and off and re installing vanced but they keep popping back up again.

Love the app, thank you vanced team.

Vanced version: 16.29.39

Phone details: 

Build number

RMX3085CPW 11 A.20

Baseband version

M_V3 P10,M_V3 P10

Kernel version

4.14.186+

ColorOS version

V11

Hardware version

RMX3085-11 .

**Comment by X1nto** [comment]
not related to vanced manager

**Comment by MrAppAndCrap** [comment]
It's the Youtube Vanced app that's doing it
