### ISSUE TITLE
Youtube vanced is not installing after updating to android 11

### ISSUE THREAD

**Issue by shinpie** [YTVanced/VancedManager#706]
![IMG-20211010-WA0002.jpg](https://user-images.githubusercontent.com/85542851/136693630-f9023b9c-a68f-41b9-9883-0d9ab6ae7ffc.jpg)

It's shows this error,

Methods to reproduce error:-

Install youtube vanced through vanced manager.

Current device:-

Device name: OPPO A9
Rom: Color OS 11.1
Android version:  11

Previous rom:-

Rom: Color OS 7
Android version: 10

**Comment by X1nto** [comment]
Duplicate of #346
