### ISSUE TITLE
Constant notifications from ended livestreams

### ISSUE THREAD

**Issue by ghost** [YTVanced/VancedManager#712]
## Full story
I activate notifications bell button for the minecraft live before it started. After a while i get notified for the event and watched part of the stream. Later after it ended i still constantly keep getting notified about the event even when it ended long ago. (Me writing this issue got the notification once again.)

## Summary
Pressing notification bell before the mincraft live stream started, now it wont stop.

![824eb1a1-c329-4330-9cb2-1e285a1f3ebe.jpg](https://user-images.githubusercontent.com/16048625/137631803-77489c84-f8ae-498d-9731-5573e6dcf3db.jpg)

**Comment by ghost** [comment]
Seem the issue has stopped, no clue how.

**Comment by milindgoel15** [comment]
Unrelated to vanced manager, closing this issue.
