### ISSUE TITLE
[Bug]: refresh in YTvanced homepage

### ISSUE THREAD

**Issue by pragyantpradab** [YTVanced/VancedManager#716]
### Device

Device: OnePlus 7t
Operating System: oxygen os beta 5
Android Version:11

### Version

2.6.2

### Bug Description

YouTube from YouTube vaned manager is showing a bug.
When i drag my finger down in homepage , it should refresh the page in YouTube Home page . But sometime this feature is working and sometimes it is not working.

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [ ] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment]
it's not a manager bug yet you still opened an issue
