### ISSUE TITLE
[Bug]: History doesn't work?

### ISSUE THREAD

**Issue by shinebayar-g** [YTVanced/VancedManager#720]
### Device

Device: Nokia 3.4
Operating System: Android
Android Version: 11

### Version

2.6.2

### Bug Description

My youtube watch history doesn't save. Is this a bug or missing feature?

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by shinebayar-g** [comment]
@X1nto What's the answer?

**Comment by X1nto** [comment]
It's not related to vanced manager
