### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CozaMcCoza** [YTVanced/VancedManager#725]
### Device

Device: OnePlus Nord
Operating System: Oxygen OS 11.1.6.6.AC01BA
Android Version: 11

### Version

2.6.2 (Crimson)

### Bug Description

Stock YouTube version that comes with Oxygen OS 11.1.6.6.AC01BA is version 16.30.34.  It is not possible to downgrade this version any lower.  I have tried installing and uninstalling YouTube updates to try and clear the issue but it will not go any lower than this.

Vanced Manager will not install Vanced YouTube to 16.29.39 as the version number is higher than the stock/factory version of YouTube.  The installation process fails, stating that I need to uninstall updates to YouTube first.  It's not possible to uninstall any further.

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by CozaMcCoza** [comment]
Found the solution on Discord:

Solution for ROOT-only [INSTALL_FAILED_ALREADY_EXISTS]/[INSTALL_FAILED_VERSION_DOWNGRADE], or Vanced crashing/disappearing after reboot and increasing sleep timer not resolving it
1️⃣ Uninstall all instances of Youtube you have installed. If a stock version is installed to the system, use Magisk's Debloater module to uninstall it. Here's a tutorial to set up Debloater: https://youtu.be/mwC4ZswBZiM (keep in mind Youtube could be on Priv-System or Product instead of System, depending on the ROM).
2️⃣ Get a root explorer (if you don't have any, I recommend Material Files https://f-droid.org/packages/me.zhanghai.android.files/) and delete (if they exist) /data/adb/Vanced, /data/adb/service.d/vanced.sh and /data/adb/post-fs-data.d/vanced.sh. If they existed, reboot your phone after deleting them.
3️⃣ Go to /data/app, search for all instances of com.google.android.youtube-(gibberish), delete all of those, then reboot again.
4️⃣ Now reinstall Youtube Vanced Root from Vanced Manager. If you get a [INSTALL_FAILED_INCOMPATIBLE] error, get a terminal emulator and use the command: su -c "pm uninstall com.google.android.youtube", and try to install Root Vanced again.
5️⃣ If successful, navigate to Youtube's page on the playstore (https://play.google.com/store/apps/details?id=com.google.android.youtube), click the triple dot and uncheck Enable Auto-Update. If the option is not there, then click Update then immediately cancel, until the option appears, and uncheck it.

**Comment by zyf0330** [comment]
I just follow step 1 and 4, and succeed.
