### ISSUE TITLE
[Feature]: "Pop-up" Floating Windows

### ISSUE THREAD

**Issue by ZeroA22** [YTVanced/VancedManager#730]
### Suggestion

floating video windows

### Additional Information

It is a more modern means of use allowing the app to be used in various situations. Example: Having Instagram open, but also watching a video in the app.

### Additional checks

- [X] I have checked other feature requests and this is not a duplicate.
- [X] This is a suggestion for Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment]
Vanced already has it and it's supported from android 8 and up. Also not related to manager
