### ISSUE TITLE
in actions it says the latest version is infected

### ISSUE THREAD

**Issue by mesflit** [YTVanced/VancedManager#733]
### Device

Device:
Operating System:
Android Version:9

### Version

new

### Bug Description

in actions it says the latest version is infected

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment]
Where does it say that?

**Comment by omerfarukpro** [comment]
when downloading

**Comment by mesflit** [comment]
when downloading

**Comment by X1nto** [comment]
I don't get any of the warnings on Chrome, what browser are you using?

**Comment by mesflit** [comment]
google services says infected

**Comment by mesflit** [comment]
kevinx8 latest version

**Comment by X1nto** [comment]
I'm sorry, are you downloading manager from releases or GitHub actions? If from releases, then it should have no problems, but if from GitHub actions, then play store is flagging APK as malware because its signature is fairly new

**Comment by mesflit** [comment]
github actions

**Comment by mesflit** [comment]
No problem, right?

**Comment by mesflit** [comment]
So if I download it, it's okay

**Comment by X1nto** [comment]
It's okay but that version is highly unstable, I'd recommend getting it from the releases tab.
