### ISSUE TITLE
[Bug]: Vanced Manager cant install downloaded packages

### ISSUE THREAD

**Issue by Ubrorgh** [YTVanced/VancedManager#735]
### Device

Device: Alcatel5x
Operating System: Android
Android Version: 10

### Version

2.6.0 Crimson

### Bug Description

When i try to update Vanced Manager package downloads correctly, but the pop up notification for installing the packages appears just for a fraction of a second making it unselectable.
I laready checked the app permissions, and such, also deleted user data and reinstalling the app didn't work. 
I don't know what could be causing this problem.

https://user-images.githubusercontent.com/93928957/140762508-1085b2e8-f28c-4030-951d-91a15ead8ef9.mp4

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment]
update manually from github releases
