### ISSUE TITLE
[Bug]: YouTube Vance closes everytime i try to use it

### ISSUE THREAD

**Issue by Usernamewhatever** [YTVanced/VancedManager#736]
### Device

Device: Android
Operating System: Android?
Android Version: Galaxy A51

### Version

2.6.2

### Bug Description

I try to open YouTube Vanced and it closes. I CAN'T POST THIS UNLESS I CLICK THE BOX SAYING IT'S FOR MANAGER BUT I CAN'T FIND ANY PLACE THAT HELPS WITH YOUR PRODUCT. The app doesn't completely exit, it just immediately "minimizes" or whatever the mobile equivalent of that is. I've tried every fix I can think of including deleting and reinstalling everything, deleting my Vanced account from settings. 

It's been this way for the better part of a year. Why is there not a good way to get in touch with you people?

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [ ] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment]
> I CAN'T POST THIS UNLESS I CLICK THE BOX SAYING IT'S FOR MANAGER BUT I CAN'T FIND ANY PLACE THAT HELPS WITH YOUR PRODUCT. 

It's really not hard to find the correct repo: https://github.com/YTVanced/Vanced
