### ISSUE TITLE
[Bug]: install error

### ISSUE THREAD

**Issue by wanghai-king** [YTVanced/VancedManager#739]
### Device

Device: meizu16
Operating System: flyme9
Android Version: 10

### Version

2.6.2

### Bug Description

INSTALL_FAILED_ABORTED:User rejected permissions

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment]
grant package installation permissions to manager
