### ISSUE TITLE
YouTube vanced is showing ads in YouTube shorts

### ISSUE THREAD

**Issue by virenhooda27** [YTVanced/VancedManager#740]
### Device

Device: Nokia 8.3
Operating System: Android one
Android Version: 11

### Version

16.29.39

### Bug Description

Shorts shows  ads in between videos. 

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment]
not related to manager
