### ISSUE TITLE
[Feature]: Can you add dislikes based on API and user estimations after December 13th

### ISSUE THREAD

**Issue by adamlahbib** [YTVanced/VancedManager#743]
### Suggestion

To be exact, can you implement something like this browser extension, for Vanced?

### Additional Information

I assume a lot of users will be happy to have it on Vanced, right?

### Additional checks

- [X] I have checked other feature requests and this is not a duplicate.
- [X] This is a suggestion for Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment]
Not related to manager

**Comment by InnerCato** [comment]
Related to YouTube vanced not manager
