### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by Bobydysyf** [YTVanced/VancedManager#746]
### Suggestion

Is it possible to re-add the dislike counter?

### Additional Information

It would be awesome

### Additional checks

- [X] I have checked other feature requests and this is not a duplicate.
- [X] This is a suggestion for Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by NotTsunami** [comment]
Good job reading the checkboxes!

**Comment by X1nto** [comment]
Not related to manager

**Comment by InnerCato** [comment]
It's related to YouTube vanced not manager
