### ISSUE TITLE
[Bug]: Since yesterday it is not working 

### ISSUE THREAD

**Issue by aljailane** [YTVanced/VancedManager#749]
### Device

Device: Honor 9x SA
Operating System: emui 10
Android Version: 10

Since yesterday, when I log in, I can't connect to the Internet

### Version

16.29.39

### Bug Description

Sir, the application cannot be made. It was working fine until yesterday. When entering it, it is not possible to connect to the Internet. For the information, the original application can be accessed without problems.

 The problem is only in vanced

### Additional checks

- [x] I have checked other bug reports and this is not a duplicate.
- [ ] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment]
Not related to manager
