### ISSUE TITLE
Big Sur bugs/suggestions

### ISSUE THREAD

**Issue by Oizaro** [YTVanced/VancedManager#75]
- [NEW] Add button retry during network missing.

- Add button to stop downloading (inside notification or app).

- "Open link on browser" feature is not working.
https://s7.gifyu.com/images/ezgif-5-01016bcadb16.gif

- "Manual update" window layout should be adjusted.
<img src="https://i.ibb.co/C5qzYbx/Screenshot-20200704-220518-Vanced-Manager.png">

- "Website and contribution" windows layout should be adjusted.
<img src="https://i.ibb.co/PFgKJMw/Screenshot-20200705-095525-Vanced-Manager.png">

**Comment by X1nto** [comment]
1. We tried to add button, didn't work well
2. Open link in browser feature works perfectly for me
3. We'll adjust layouts, thanks for feedback

**Comment by Oizaro** [comment]
@X1nto Can you try with Samsung Internet?

**Comment by X1nto** [comment]
I myself use chrome but sure

**Comment by Oizaro** [comment]
I will try with Chrome, to ensure that working well.

**Comment by X1nto** [comment]
Just tried with Samsung browser, again, everything is working well

**Comment by Oizaro** [comment]
Thanks, at this point I think there is a strange setting of my system.

**Comment by X1nto** [comment]
Can you try altering settings with default apps and etc?

**Comment by Oizaro** [comment]
Yes, I changed the default browser with Chrome, but unfortunately the same behaviour happen also in this case (with a Chrome webapp I assure).

**Comment by X1nto** [comment]
Might be issue with code not working properly with some ROMs, I'll see what's the issue there

**Comment by Oizaro** [comment]
Thanks. My device is a Galaxy with OneUI Rom.

**Comment by X1nto** [comment]
Fixed url opening in 87964d1fd7a6f3b1d9dd471d1dc17d384c6c33a6 and adjusted update center layout in 3ca82359644e46a51977e003c61767504d46aa4a

**Comment by Oizaro** [comment]
@X1nto Thanks, i've added another suggestion, much useful during network absence.

**Comment by X1nto** [comment]
> @X1nto Thanks, i've added another suggestion, that could be much useful during network absence.

I pointed out that too, swipe to refresh is useful for that situations

**Comment by Oizaro** [comment]
Also on the app splashscreen?

**Comment by X1nto** [comment]
> Also on the app splashscreen? Without network it was shown infinitely.

App works fine for me without internet connection. I'm not sure what you're talking about

**Comment by Oizaro** [comment]
Oh...sorry, as I said in the absence of the network the app was stuck on the splash screen. Now it's back to work in this situation.

Ok, if I have other problems I will open another report.

Thanks again.

**Comment by X1nto** [comment]
I guess I can close this issue now
