### ISSUE TITLE
offline yt vid download when [Feature]: 

### ISSUE THREAD

**Issue by ghost** [YTVanced/VancedManager#759]
### Suggestion

video downloader just like new pipe this will make this project move love

### Additional Information

this will help to make yt vanced close to yt premium or even better bcz yt dont have this till now to save vids in internal storage

### Additional checks

- [X] I have checked other feature requests and this is not a duplicate.
- [X] This is a suggestion for Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment]
no
