### ISSUE TITLE
[Bug]: ads still visible on YouTube Vanced

### ISSUE THREAD

**Issue by asorel1942** [YTVanced/VancedManager#761]
### Device

Device: Oneplus 9 Pro
Operating System: CRDroid 7.13
Android Version: 11

### Version

16.29.39

### Bug Description

As shown in the screencap ads continue to appear within YouTube even with the latest Vanced plugin installed. 
![Screenshot_20211231-173803_YouTube](https://user-images.githubusercontent.com/33983895/147841134-73b4e9e4-75ac-4ae6-9dbe-0a02af19c985.png)

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment]
Not related to manager
