### ISSUE TITLE
[Feature]: Add VancedManager to F-droid

### ISSUE THREAD

**Issue by ghost** [YTVanced/VancedManager#764]
### Suggestion

Add VancedManager to F-droid to easily share the app with more users.
https://f-droid.org/docs/Inclusion_Policy/?title=Inclusion_Policy
https://gitlab.com/groups/fdroid/-/issues

### Additional Information

F-droid is for open-source apps, it is a great place to find open-source apps and make sure they're updated. VancedManager would be easily discoverable by more users and everyone who uses it would be able to make sure it is updated.

### Additional checks

- [X] I have checked other feature requests and this is not a duplicate.
- [X] This is a suggestion for Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment]
Duplicate of #124
