### ISSUE TITLE
[Bug]: Cannot uninstall Vanced (root)

### ISSUE THREAD

**Issue by x011** [YTVanced/VancedManager#766]
### Device

Device:
Operating System: Android
Android Version: 11

### Version

Latest

### Bug Description

Cannot uninstall Vanced (root) after clicking the uninstall button nothing happens and the app/mod is still installed.

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by n-ce** [comment]
Same as #711 
[Solution for now](https://www.reddit.com/r/Vanced/comments/q7vhsz/question_vanced_related_files_still_remain_in/)

**Comment by X1nto** [comment]
Duplicate of #711
