### ISSUE TITLE
[Bug]: README.md FAQ link not available

### ISSUE THREAD

**Issue by mridun-gupta** [YTVanced/VancedManager#767]
### Device

Windows 10

### Version

latest build

### Bug Description

check title

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by AnujSsStw** [comment]
The Playstore link?

**Comment by RealKasumi** [comment]
The Vanced FAQ app on the playstore is no longer available because Google took it down for unknown reasons. You can still access the FAQ and other troubleshooting information through Discord/Telegram.

**Comment by mridun-gupta** [comment]
Okay! @TheAmazingBen100

**Comment by mridun-gupta** [comment]
issue resolved! closing issue @X1nto!
