### ISSUE TITLE
[Bug]: youtube music does not allow Download

### ISSUE THREAD

**Issue by batata004** [YTVanced/VancedManager#768]
### Device

Device: Samsung A51, A52 and Xiaomi mi a3
Operating System: Android 11

### Version

Latest

### Bug Description

I Installed Youtube Music using Vanced Manager however the Download Playlist option does not work. The button shows up but when I click it nothing happens. The Vanced version of YT Music does not allow download? Is that right? So what is the point of using the vanced version since this is the only thing it would matter using it?

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [ ] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by RealKasumi** [comment]
1: not related to manager
2: Who told you that Vanced is the same as premium? Vanced will NEVER offer free video downloading, or any other premium service (eg: yt originals).

**Comment by batata004** [comment]
@TheAmazingBen100 so what is the point using YT music vanced if you cant have offline playback? I see no point in having another bloat on my phone that does nothing more than the default app.

**Comment by X1nto** [comment]
> @TheAmazingBen100 so what is the point using YT music vanced if you cant have offline playback? I see no point in having another bloat on my phone that does nothing more than the default app.

Vanced Music unlocks background playback, if you don't want it then go use the stock app.

**Comment by batata004** [comment]
@X1nto I already have background playback on Youtube vanced. Sorry but I still see no point using Youtube music vanced, everything YT music does, YT vanced already does and much much more. The only reason I could see is offline playback but clearly YT music vanced does not allow that.

**Comment by X1nto** [comment]
Use whatever you want
