### ISSUE TITLE
[QUESTION] failing to install YouTube Vanced

### ISSUE THREAD

**Issue by pedrosill** [YTVanced/VancedManager#77]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand:
- Operating System:
- Android Version:
- Vanced Manager Version:

**Please describe the problem you are having in as much detail as possible:**

**Steps to reproduce:**

**Further details:**

My app has failed to install the YouTube Vanced three times now. Whenever I try it just seems to be "installing" forever. 

What should I do?

**Comment by X1nto** [comment]
I'm closing issue because you didn't provide any details about your phone, ROM, Android and vanced manager versions.
