### ISSUE TITLE
[Feature]: YouTube Vanced - option to remove shorts tab 

### ISSUE THREAD

**Issue by EducatedEduard** [YTVanced/VancedManager#772]
### Suggestion

Create a option in the layout settings to hide the shorts tab :
![image](https://user-images.githubusercontent.com/37374799/149630152-8d48df2e-2abc-4d92-b200-166476985485.png)

could look like this:
![WhatsApp Image 2022-01-15 at 17 53 41](https://user-images.githubusercontent.com/37374799/149630425-69fb99e1-a570-4918-a16c-7c45941d8fce.jpeg)

Just like the removal of the creation button

### Additional Information

This 'newly' added function is running along the tiktok trend and is highly addictive - removing this tab will reduce the urge to watch them

### Additional checks

- [X] I have checked other feature requests and this is not a duplicate.
- [X] This is a suggestion for Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by RealKasumi** [comment]
1: not related to vanced manager
2: it's your problem if you're addicted to them
