### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Profesoruturbat** [YTVanced/VancedManager#773]
### Device

Device:Samsung galaxy s20fe
Operating System:android
Android Version:11

### Version

16.29.39

### Bug Description

Just say me check your internet connection but i have strong internet and very good what is the problem i try to reinstall but nothing help me plz

### Additional checks

- [x] I have checked other bug reports and this is not a duplicate.
- [ ] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by ghost** [comment]
https://github.com/YTVanced/Vanced/issues/786
