### ISSUE TITLE
[Bug]: Google Account Deactivated

### ISSUE THREAD

**Issue by fdciabdul** [YTVanced/VancedManager#778]
### Device

Device: Nokia 6.1
Operating System: Android
Android Version: 11

### Version

Latest

### Bug Description

I think this happen because google was detected Micro OG for google account 

and then , the youtube vanced will be offline or can't connect to internet 

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by merouanezouaid** [comment]
#786

**Comment by merouanezouaid** [comment]
Vanced#786

**Comment by D3VR4J** [comment]
Open OG Youtube from your google account(if its running properly it means your account is not banned. Now just remove your google account from MicroG and relogin with your same account. Worked from me

**Comment by damacc** [comment]
I logged into this app I'm order to get the music too play in the background.. Number one I didn't think I'd have to do that.. Okay whatever then I kept getting strange Google verification code.. Okay didn't think it was because of this.. More time passes then I was having issues with it not playing in the background with screen off do I logged out.. Then all hell broke loose my account gets a flag.. So I can't even access like my must important emails addresses.. This is crazy..I still don't t think it's because of this app... So I really like to listen with screen off..I sign in using another account.. At this point I'm losing more attention.. YO your fuccin app again was sending codes to my damn number as if someone remotely wanted to login but could not because of the number I had in place.. So now the email my transcript.. My work.. My damn never everything is LOCKED THE FUCC DOWN 👎👎👎👎👎 what the hell gives..

**Comment by ghost** [comment]
> I logged into this app I'm order to get the music too play in the background.. Number one I didn't think I'd have to do that.. Okay whatever then I kept getting strange Google verification code.. Okay didn't think it was because of this.. More time passes then I was having issues with it not playing in the background with screen off do I logged out.. Then all hell broke loose my account gets a flag.. So I can't even access like my must important emails addresses.. This is crazy..I still don't t think it's because of this app... So I really like to listen with screen off..I sign in using another account.. At this point I'm losing more attention.. YO your fuccin app again was sending codes to my damn number as if someone remotely wanted to login but could not because of the number I had in place.. So now the email my transcript.. My work.. My damn never everything is LOCKED THE FUCC DOWN 👎👎👎👎👎 what the hell gives..

Where the FUCK did you download Vanced from?
Sur, are you aware that [Vanced MicroG](https://github.com/YTVanced/VancedMicroG)  is [FOSS](https://itsfoss.com/what-is-foss/), yes?

**Comment by ghost** [comment]
> ### Device
> Device: Nokia 6.1 Operating System: Android Android Version: 11
> 
> ### Version
> Latest
> 
> ### Bug Description
> I think this happen because google was detected Micro OG for google account
> 
> and then , the youtube vanced will be offline or can't connect to internet
> 
> ### Additional checks
> * [x]  I have checked other bug reports and this is not a duplicate.
> * [x]  This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

System settings > Accounts > remove the one for Vanced microG , then re-login Yt Vanced and disable [battery optimization](https://dontkillmyapp.com/nokia) for Vanced microG

**Comment by keegannhat** [comment]
Where did you download Vanced from?

**Comment by keegannhat** [comment]
> > ### Device
> > Device: Nokia 6.1 Operating System: Android Android Version: 11
> > ### Version
> > Latest
> > ### Bug Description
> > I think this happen because google was detected Micro OG for google account
> > and then , the youtube vanced will be offline or can't connect to internet
> > ### Additional checks
> > 
> > * [x]   I have checked other bug reports and this is not a duplicate.
> > * [x]   This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.
> 
> System settings > Accounts > remove the one for Vanced microG , then re-login Yt Vanced and disable [battery optimization](https://dontkillmyapp.com/nokia) for Vanced microG

Did you change your Google account password? If so, you will need to sign out and log back in through MicroG

**Comment by merouanezouaid** [comment]
This bug often happens when you change your Google account password ..

To fix it you need to remove your account from Youtube Vanced and sign in again and it should work perfectly fine.
