### ISSUE TITLE
[Bug]: Vanced Manager crashes when pressing Download / Install button

### ISSUE THREAD

**Issue by enveeed** [YTVanced/VancedManager#779]
### Device

Android Version: 6.0.1

### Version

2.6.2

### Bug Description

I installed Vanced Manager and with it YouTube Vanced before with no issues. It started when I uninstalled Youtube Vanced and then later decided to install it again. Whenever pressing the "Install" button in the popup where you can define theme and language, the app just crashes with a "Vanced Manager has stopped" message. The same thing happens when trying to press the button to upgrade Micro G, in this case, because there is no popup, it just crashes instantly.
The app works completely fine other than that and I have not had any other crashes when doing anything else. The settings seem to not affect it at all, it happens in root and nonroot modes.

Things I've tried:
- deleting Vanced Manager data
- deleting Vanced Manager itself and reinstalling it
- installing an old version, but that just upgrades itself to the latest one on install.

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment]
I need the full device specs, not just Android version. Also, please take a logcat of the crash. Guide on how to take logs can be found on the web.

**Comment by enveeed** [comment]
This should be it i think:

```
01-26 21:20:03.648  5892  5892 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x3753f994 in tid 5892 (.vanced.manager)
01-26 21:20:03.770   668   668 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-26 21:20:03.770   668   668 F DEBUG   : Build fingerprint: 'motorola/athene_f/athene_f:6.0.1/MPJ24.139-63/64:user/release-keys'
01-26 21:20:03.770   668   668 F DEBUG   : Revision: 'p2a0'
01-26 21:20:03.770   668   668 F DEBUG   : ABI: 'arm'
01-26 21:20:03.770   668   668 F DEBUG   : pid: 5892, tid: 5892, name: .vanced.manager  >>> com.vanced.manager <<<
01-26 21:20:03.771   668   668 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3753f994
01-26 21:20:03.804   668   668 F DEBUG   :     r0 6f7637d4  r1 134e3de0  r2 00269c7b  r3 b1f77070
01-26 21:20:03.805   668   668 F DEBUG   :     r4 00269c7b  r5 6f762e20  r6 134e3de0  r7 6fcb05f0
01-26 21:20:03.805   668   668 F DEBUG   :     r8 12d9a650  r9 b887fd90  sl 6ff57ea0  fp bef5b554
01-26 21:20:03.805   668   668 F DEBUG   :     ip b1f77070  sp bef5b4d0  lr 72198df7  pc b49dcc98  cpsr 000b0030
01-26 21:20:03.822   668   668 F DEBUG   : 
01-26 21:20:03.822   668   668 F DEBUG   : backtrace:
01-26 21:20:03.822   668   668 F DEBUG   :     #00 pc 000eac98  /system/lib/libart.so (art_quick_imt_conflict_trampoline+7)
01-26 21:20:03.823   668   668 F DEBUG   :     #01 pc 72198df5  /data/dalvik-cache/arm/system@framework@boot.oat (offset 0x1fcd000)
01-26 21:20:05.260   668   668 F DEBUG   : 
01-26 21:20:05.260   668   668 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_03
```

**Comment by enveeed** [comment]
The device is a Moto G4, i'll see if I can find the full specs.

**Comment by X1nto** [comment]
> ```
> 01-26 21:20:03.648  5892  5892 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x3753f994 in tid 5892 (.vanced.manager)
> 01-26 21:20:03.770   668   668 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> 01-26 21:20:03.770   668   668 F DEBUG   : Build fingerprint: 'motorola/athene_f/athene_f:6.0.1/MPJ24.139-63/64:user/release-keys'
> 01-26 21:20:03.770   668   668 F DEBUG   : Revision: 'p2a0'
> 01-26 21:20:03.770   668   668 F DEBUG   : ABI: 'arm'
> 01-26 21:20:03.770   668   668 F DEBUG   : pid: 5892, tid: 5892, name: .vanced.manager  >>> com.vanced.manager <<<
> 01-26 21:20:03.771   668   668 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3753f994
> 01-26 21:20:03.804   668   668 F DEBUG   :     r0 6f7637d4  r1 134e3de0  r2 00269c7b  r3 b1f77070
> 01-26 21:20:03.805   668   668 F DEBUG   :     r4 00269c7b  r5 6f762e20  r6 134e3de0  r7 6fcb05f0
> 01-26 21:20:03.805   668   668 F DEBUG   :     r8 12d9a650  r9 b887fd90  sl 6ff57ea0  fp bef5b554
> 01-26 21:20:03.805   668   668 F DEBUG   :     ip b1f77070  sp bef5b4d0  lr 72198df7  pc b49dcc98  cpsr 000b0030
> 01-26 21:20:03.822   668   668 F DEBUG   : 
> 01-26 21:20:03.822   668   668 F DEBUG   : backtrace:
> 01-26 21:20:03.822   668   668 F DEBUG   :     #00 pc 000eac98  /system/lib/libart.so (art_quick_imt_conflict_trampoline+7)
> 01-26 21:20:03.823   668   668 F DEBUG   :     #01 pc 72198df5  /data/dalvik-cache/arm/system@framework@boot.oat (offset 0x1fcd000)
> 01-26 21:20:05.260   668   668 F DEBUG   : 
> 01-26 21:20:05.260   668   668 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_03
> ```

A native crash huh? Interesting. I don't think it's something fixable but we'll how how 3.0 will perform.

**Comment by X1nto** [comment]
> The device is a Moto G4, i'll see if I can find the full specs.

No need, name is enough right now

**Comment by enveeed** [comment]
It was an Xposed issue. Not sure what triggered it but when Xposed is deactivated things started working again.

**Comment by lukeimyafada** [comment]
hi. i seem to be also having this issue on my android 8.1 go in my cars head unit

it used to work without a problem, then suddenly i couldnt use the main menu within youtube music, instead i had to go to the playlists area and select a prelisted song, which was fine

i tried uninstalling and reinstalling, factory reset, AND firmware update

the manager installs fine, but when i try and download microg it just crashes the app entirely, and im unable to install it again

**Comment by lukeimyafada** [comment]
![274322706_659930901814833_6136723733846597648_n](https://user-images.githubusercontent.com/5057385/156093418-55915e0a-a4b5-415b-b87c-e3f78e30d904.jpg)

**Comment by lukeimyafada** [comment]
> ![274322706_659930901814833_6136723733846597648_n](https://user-images.githubusercontent.com/5057385/156093418-55915e0a-a4b5-415b-b87c-e3f78e30d904.jpg)

sorry for the poor quality, but this is all the information i could find prior to the updated firmware
