### ISSUE TITLE
App crashes when opening

### ISSUE THREAD

**Issue by vishnu012** [YTVanced/VancedManager#78]
vanced manager crashes when opening 

**Phone Specifications:**
-Xiaomi Redmi note 4
- Pixel experience Plus edition
- Android 10
- Vanced Manager Version: 1.1.0

 Log file - https://paste.ee/p/Plt34

**Comment by X1nto** [comment]
You are blocking connection to server

**Comment by vishnu012** [comment]
How I solve this issue ?

**Comment by X1nto** [comment]
Don't use VPN

**Comment by vishnu012** [comment]
No , iam not using  vpn .
It opened ones or two times after I installed

**Comment by onrdrsy** [comment]
I have the same problem. I am not using vpn. 
The application does not open, but shortcuts are working. About and settings are entered, but pressing the back button closes the application again.

General Mobile GM 9 Pro - Single
- Android One 
- Android version 9.0
- Rooted
- App version: 1.1.0

**Comment by X1nto** [comment]
Ffs learn to send logs
