### ISSUE TITLE
[Feature]: Inline Links for some Links and texts

### ISSUE THREAD

**Issue by AlphaVS-76** [YTVanced/VancedManager#780]
### Suggestion

I would like to switch some links and texts with inline texts so that it becomes easy to traverse the said link without any hassle

### Additional Information

This feature will make the appearance more user-friendly and straightforward

### Additional checks

- [X] I have checked other feature requests and this is not a duplicate.
- [X] This is a suggestion for Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by AlphaVS-76** [comment]
Also, I would like to be assigned this issue

**Comment by X1nto** [comment]
I'm not sure I fully understand this suggestion. Where exactly can this be used?

**Comment by AlphaVS-76** [comment]
I would like to implement this in the [CONTRIBUTION](https://github.com/YTVanced/VancedManager#contributions) section of the README.md file.
 There are many other place which when implemented with the inline links, becomes more easy-to-traverse.

**Comment by X1nto** [comment]
Sure, why not
