### ISSUE TITLE
[Bug]: Post audio FX bugs

### ISSUE THREAD

**Issue by Throtlight** [YTVanced/VancedManager#784]
### Device

Device: Oppo A53
Operating System: ColorOS 11
Android Version: 11

### Version

2.6.2

### Bug Description

We will not walk around until about, and immediately tell you what's the matter. My smartphone has built-in audio post-processing from the company Dirac but due to the fact that the vanced may have some flaws, then the post processing for some reason does not affect the vanced. I could ignore this, but I'm afraid for people who, for example, have Dolby Atmos After all, this is also a kind of post-processing sound. I'm basically hinting that it would be better for you to add support Dirac thank you for attention.

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [ ] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment]
> ### Device
> Device: Oppo A53 Operating System: ColorOS 11 Android Version: 11
> 
> ### Version
> 2.6.2
> 
> ### Bug Description
> We will not walk around until about, and immediately tell you what's the matter. My smartphone has built-in audio post-processing from the company Dirac but due to the fact that the vanced may have some flaws, then the post processing for some reason does not affect the vanced. I could ignore this, but I'm afraid for people who, for example, have Dolby Atmos After all, this is also a kind of post-processing sound. I'm basically hinting that it would be better for you to add support Dirac thank you for attention.
> 
> ### Additional checks
> * [x]  I have checked other bug reports and this is not a duplicate.
> * [ ]  This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

Not related to manager but I can answer why post-processing doesn't work for Vanced. Basically, post-processing in your audio manager probably has a set of packages it can enhance, youtube's package being one of them. non-root version of Vanced has different package name from the stock version, which is why post-processing doesn't work. The only solution to that problem is to install root version of vanced, which will work as expected.
