### ISSUE TITLE
Cannot Install MicroG frlm Vanced Manager.

### ISSUE THREAD

**Issue by arpitr20** [YTVanced/VancedManager#79]
Hello!
So I installed Vanced Manager, and promptly used it to uninstall vanced and microg from my phone. Afterwards, however, when I click to install MicroG, the app just freezes and I am unable to click anything.
Any idea how I can troubleshoot this? I already gave Vanced Manager permission to install from unknown sources, and I deleted all previously installed APK files from my phone.

Thanks!

**Comment by X1nto** [comment]
App version? Also send logcat
