### ISSUE TITLE
[Bug]: App window stuck after maximizing

### ISSUE THREAD

**Issue by nv-ua** [YTVanced/VancedManager#793]
### Device

Device: Google Pixel 3 XL
Operating System: Android 
Android Version: 12

### Version

Vanced manager 2.6.2

### Bug Description

After reopening Youtube Vanced I got it opened on upper half screen but in a fullscreen size, like it's meant to be opened fullscreen but something broken in a process. After that happened I can't press any button on the screen for example: I opening the app manager by dragging a line from the low middle of the screen but I can't swipe because Youtube Vanced covers the screen with it's broken window preventing me from any input.
I'm opening the settings from fast buttons menu but I can't operate with anything because it opens under broken Youtube Vanced window.
The only thing which solves the problem is a device reboot.
That trouble arrived after official update to android 12.
Sorry I didn't checked if anyone wrote about the same bug and it's not a right place for bug report on Vanced product??

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by nv-ua** [comment]
![Uploading Screenshot_20220216-084435.png…]()

**Comment by X1nto** [comment]
not related to manager. use [this](https://github.com/YTVanced/Vanced) to report vanced issues
