### ISSUE TITLE
[Bug]: Update Manager not finding new updates

### ISSUE THREAD

**Issue by ghost** [YTVanced/VancedManager#798]
### Device

Device: Samsung Galaxy S9
Operating System: Android
Android Version: Android 10

### Version

2.6.2 (Crimson)

### Bug Description

There's an update available for YT Music Vanced, but it doesn't show up in the Update Manager. Same for YT Vanced and microG.

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment]
Please post screenshots

**Comment by xDevoidx** [comment]
![20220218_144849](https://user-images.githubusercontent.com/75128351/154694775-36efe58b-c9a7-4614-88a8-a9183170a6ca.jpg)
![20220218_144832](https://user-images.githubusercontent.com/75128351/154694783-2d91e2a5-1ea4-43b5-8835-bb0d9df2a4ce.jpg)

**Comment by xDevoidx** [comment]
For me it doesn't work too

**Comment by RealKasumi** [comment]
![Screenshot_2022-02-17-10-59-36-18_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/49617028/154695252-6690c55a-783e-41cc-a73e-9de6d7fd41c9.jpg)
Yes it does.
Click that button to update.

**Comment by ghost** [comment]
Thanks everyone!
