### ISSUE TITLE
YouTube Vanced - skip verification age

### ISSUE THREAD

**Issue by seba2282** [YTVanced/VancedManager#800]
### Suggestion

YouTube Vanced - skip verification age

### Additional Information

It is frustrating how see verification ages when have google account much years and is putted date born and they put asks about documents for verification or some credit cards. 

### Additional checks

- [X] I have checked other feature requests and this is not a duplicate.

**Comment by RealKasumi** [comment]
not an issue related to manager

**Comment by seba2282** [comment]
So where can put that suggest?
