### ISSUE TITLE
Skip segments

### ISSUE THREAD

**Issue by pingvinh** [YTVanced/VancedManager#801]
### Suggestion

Make if I voted against, then it itself is no longer skipped

### Additional Information

Because there is a new feature

### Additional checks

- [X] I have checked other feature requests and this is not a duplicate.
- [X] This is a suggestion for Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment]
not related to manager
