### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Shylent1** [YTVanced/VancedManager#805]
### Device

Device: Xiaomi Mi A2 lite
Operating System: snapdragon 625
Android Version: android 10

### Version

 2.6.2 crimson vance manager
using
  Youtube Vanced version 17.03.38

### Bug Description

 im using Youtube Vanced version 17.03.38
 its automatic rotate i open the video after that i cant back video  .
and if i open YouTube vanced its bso slow to show the recommended video its take log time to show up. 

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment]
not related to manager
