### ISSUE TITLE
[Bug]:  after landscaping view can't back to portrait the video

### ISSUE THREAD

**Issue by Shylent1** [YTVanced/VancedManager#807]
### Device

Device: redmi 6pro
Operating System: snapdragon 625
Android Version: android 10

### Version

2.6.2

### Bug Description

why my YouTube vanced after i view full screen landscape why it cant rotate back to portrait mode and back to videos recommended? even clicking back cant back to portrait why ? pls fix thix issue

 
![Screenshot_20220225-205657](https://user-images.githubusercontent.com/81928402/155718989-4ec86d42-fa73-4c21-8d1a-b668f24dd797.jpg)

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by X1nto** [comment]
not related to manager
