### ISSUE TITLE
Advanced Protection prevents Manager from installing despite being unenrolled

### ISSUE THREAD

**Issue by tcyeric** [YTVanced/VancedManager#81]

**Comment by KevinX8** [comment]
Excuse me but what does this have to do with the manager? Ask Google why they're still blocking you from installing APK files.

**Comment by Mattis6666** [comment]
Please follow the issue template and provide more Details. We can't do anything with this

**Comment by X1nto** [comment]
Can you explain what advanced protection is?

**Comment by Toshiba1127** [comment]
Maybe he talk about this? https://landing.google.com/advancedprotection/

**Comment by X1nto** [comment]
Again, by enabling advanced protection, you're blocking apk installation, do you really think manager will work with advanced protection on?
