### ISSUE TITLE
[Bug]: Crash YouTube Vanced

### ISSUE THREAD

**Issue by Kartikey2938** [YTVanced/VancedManager#810]
### Device

Device:Moto g 9power 
Operating System: Android
Android Version:11(Stock Android)

### Version

17.03.38

### Bug Description

![Screenshot_20220306-083402](https://user-images.githubusercontent.com/91013951/156907430-598e32b9-e21b-46d9-b1f3-ffcdd1820062.png)
Whenever I try to open YouTube Vanced then it shows You're offline.Check your connection

### Additional checks

- [X] I have checked other bug reports and this is not a duplicate.
- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by RealKasumi** [comment]
not related to manager

**Comment by JohnnyKarango** [comment]
Same problem with my pixel 6
