### ISSUE TITLE
Unable to install Vanced

### ISSUE THREAD

**Issue by Jimmycaesar** [YTVanced/VancedManager#85]
**Phone Specifications:**
- Brand: Samsung
- Operating System: Android
- Android Version: 9
- Vanced Manager Version: 11

**Please describe the problem you are having in as much detail as possible:**

Upon attempting to install Vanced through the manager app, I get an error stating "operation failed because the app conflicts with an already installed app"

**Steps to reproduce:**

Attempting to install vanced 

**Further details:**

**Comment by X1nto** [comment]
Are you trying to install root version or nonroot

**Comment by Jimmycaesar** [comment]
Nonroot

**Comment by X1nto** [comment]
Uninstall previous vanced version

**Comment by Jimmycaesar** [comment]
As far as I can tell, I have. I've had Vanced installed in the past, then
installed the manager today. Tried to update the vanced app, and it gave me
the same error.

I then uninstalled vanced through the manager app. Upon attempting to
reinstall vanced, I still receive the error.

**Comment by X1nto** [comment]
Try restarting your device

**Comment by Jimmycaesar** [comment]
Hi,

Sorry, was being an idiot. Micro G was still installed, which was causing
the issue.  Sorted it now. Cheers for the assistance.

**Comment by Vozf** [comment]
I've got the same issue with updating samsung s20 to android 11. Since the update I can't find youtube vanced on my phone(it's not present in the list of apps) and can't install it with manager or apk, the error from issue appears
