### ISSUE TITLE
Stucks at manager splash for some users

### ISSUE THREAD

**Issue by milindgoel15** [YTVanced/VancedManager#86]
Many users been facing this issue when splash gets stuck on its logo. 

temp solution:
Clear data
Turn internet off
Open manager 
Turn internet on

Only This fixes up.

**Comment by Oizaro** [comment]
@milindgoel15 In truth:

https://github.com/YTVanced/VancedManager/issues/62#issuecomment-653916728

**Comment by X1nto** [comment]
This commit should fix the issue: e9c3e7aad5f0f485162eb9fccb97250541d69cee

**Comment by X1nto** [comment]
10 days later, no one reported issues with splash screen getting stuck, I guess we can close this now

**Comment by milindgoel15** [comment]
🌝
