### ISSUE TITLE
Microg source code

### ISSUE THREAD

**Issue by MarcoCount** [YTVanced/VancedManager#87]
It would be great if users were able to build the microg that this app downloads ( https://vanced.app/api/v1/microg.json ) themself, for security reasons.
Alternatively it would be great to have the microg source public and a continuous integration that builds it, so that users can verify that the apk is built from source without dangerous modifications.
Thanks for VancedManager!

**Comment by X1nto** [comment]
For our own safety, we can't release source code for vanced MicroG, because YouTube would figure out how we use microg for nonroot log in, thus we don't want vanced to become root only

**Comment by KevinX8** [comment]
> It would be great if users were able to build the microg that this app downloads ( https://vanced.app/api/v1/microg.json ) themself, for security reasons.
> Alternatively it would be great to have the microg source public and a continuous integration that builds it, so that users can verify that the apk is built from source without dangerous modifications.
> Thanks for VancedManager!

The microg we use isn't actually built from custom sources, it's standard microg modded to work for vanced the same way YouTube is modded. We couldn't get the edits to build if we changed the source directly but if you are interested in getting it working from source then make a working source and open a PR onhttps://github.com/YTVanced/android_packages_apps_GmsCore

**Comment by TacoTheDank** [comment]
Sorry for hijacking this issue, but will you guys eventually update your MicroG to 0.2.10? https://github.com/microg/android_packages_apps_GmsCore/releases

**Comment by X1nto** [comment]
> Sorry for hijacking this issue, but will you guys eventually update your MicroG to 0.2.10? https://github.com/microg/android_packages_apps_GmsCore/releases

We don't have an answer for this question

**Comment by TacoTheDank** [comment]
Oh, ok

**Comment by KevinX8** [comment]
https://github.com/YTVanced/VancedMicroG vanced microg made to work from source thanks to @Oizaro
