### ISSUE TITLE
App freeze

### ISSUE THREAD

**Issue by AN0NYM0USop** [YTVanced/VancedManager#90]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand:mi 6
- Operating System:Android
- Android Version:pie
- Vanced Manager Version:1.1.0(big sur) 

**Please describe the problem you are having in as much detail as possible:**
So, when ever I try to open app with internet on it just stuck on opening. If I open it with out internet then is open immediately. Then I turn on data to install micro g and when I click on install button it freeze s

**Steps to reproduce:**

**Further details:**

**Comment by Mattis6666** [comment]
#86
