### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ImAgoodGirlSumtimz** [YTVanced/VancedManager#94]
First of all; thank you Vanced team so very much for being so incredibly wonderful! 💓

I absolutely love and appreciate the app, but was wondering if it could be made to run based upon a built-in scheduler, rather than having it run resident all the time? Specifically, I'm referring to the microG app constantly running in the background... Many of us users are always trying to maximize our battery life, and I was wondering if the app could be scheduled to run only at certain times and then turn itself off? That way, updated versions could be checked on a daily, weekly or monthly basis depending on the options the application might offer. I'm not by any means an Android guru, so please forgive me if I'm short-sighted in what I'm asking you. I hope I'm making sense though. Again thank you so much for your time, effort and hard work. Very sincerely... J. P.

**Comment by X1nto** [comment]
Microg is constantly running for Android to not kill it, of Android kills microg then you'll have problems with vanced loading home page. 
Solution 1:
Disable battery optimisations for microg in device settings and reboot
Solution 2 (not recommended):
Long press notification and just deny notifications

**Comment by Mattis6666** [comment]
To elaborate further, microG is what powers the connection to Google. Without microG, it is not possible to log into your google account or retrieve notifications for video uploads. It has to be running or else Vanced will not function. It is just a replacement for Google Play Services.
