### ISSUE TITLE
Root won't verify

### ISSUE THREAD

**Issue by MrGoatsy** [YTVanced/VancedManager#95]
**Phone Specifications:**
- Brand: Samsung Galaxy S9
- Operating System: Android 9
- Android Version: Android 9
- Vanced Manager Version: Latest

**Please describe the problem you are having in as much detail as possible:**
When clicking root it says "Root access not granted" even though I never got a prompt asking me to grant access.

**Comment by X1nto** [comment]
Are you using Magisk or SuperSU?

**Comment by MrGoatsy** [comment]
Magisk, but I rebooted and it has been fixed.
