### ISSUE TITLE
"Sorry... There was a problem communicating with Google servers.. Try again later." Upon trying to log into Google account 

### ISSUE THREAD

**Issue by mariadmatei** [YTVanced/VancedManager#96]
**Phone Specifications:**
- Brand:Huawei
- Operating System:Android
- Android Version:10
- Vanced Manager Version:1.1.0

**Please describe the problem you are having in as much detail as possible:**
When I go to add a Google account from the Youtube Vanced app or from the MicroG settings in the manager, once I type in my password and tap sign in it gives me the error message in the title

**Steps to reproduce:**
Open Vanced app or MicroG settings from manager>add account>type in login details

**Further details:**
I am on a Huawei P40 Lite. Managed to sign in once a few days ago but now it won't work

**Comment by X1nto** [comment]
Report only Manager related issues here

**Comment by mariadmatei** [comment]
I can't find where to submit MicroG related issues sorry
