### ISSUE TITLE
Videos freezing after a couple of minutes

### ISSUE THREAD

**Issue by rossiotti** [YTVanced/VancedManager#97]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand: LG Q60
- Operating System: Android
- Android Version: 10
- Vanced Manager Version: 1.1.0

**Please describe the problem you are having in as much detail as possible:**

When I open a video everything is ok. But after a couple of minutes starts freezing and I have to reset the app to stop it. This didn't happened before until the vanced manager update. Also why you can't select the non-root in the menu or is it non-root by default unless you select the root option ?

**Steps to reproduce:**

**Further details:**

**Comment by X1nto** [comment]
ARE YOU FUCKING KIDDING ME?. You filled a form that asks to only report manager related bugs here and you still report a Vanced bug?
