### ISSUE TITLE
Phone power cycles when I don't have the latest version of MicroG

### ISSUE THREAD

**Issue by inconsequentialCat** [YTVanced/VancedManager#98]
-Switched to new phone (LG V20, andoid 8)

-Used LG backup to transfer apps

-For whatever reason vanced no longer worked

-uninstalled it

-went to vanced.app, downloaded manager

-installed vanced but not MicroG since I already had it > phone immediately starts power cycling in 60 second 'on' intervals

-uninstalled both vanced and micro g > then reinstalled both

-phone is fine

-this morning my phone started doing the same cycling again

-went to go uninstall both again and noticed there's a newer version of MicroG

-uninstalled MicroG and reinstalled, got the new version

-phone is fine again

I have very few apps on the phone so I don't imagine anything else is conflicting or causing the issue. All I know is it seems that if I don't have the latest MicroG that my phone flips out.

Not a huge deal personally since now I know how to fix it if it happens again, but someone recommended I post the issue here.

**Comment by Mattis6666** [comment]
Not sure why that person recommended to post it here, as this place is solely for VancedManager related issues.

**Comment by inconsequentialCat** [comment]
It 100% is caused by MicroG. I can even probably load the backup and replicate the issue if need be.

And they didn't specifically link here, they just said "the GitHub" I just imagined this is the place to post this. Is there a specific category for MicroG?

I'm completely new to GitHub.

@Mattis6666

**Comment by Mattis6666** [comment]
[MicroG repo](https://github.com/YTVanced/VancedMicrog)

Attach a logcat showing that this is indeed caused by microG or there's no point reporting.

**Comment by inconsequentialCat** [comment]
@Mattis6666 

I don't even know what a logcat is. 
And i'm just trying to help out. No clue why you're being rude as fuck. 

But forget it, conversation over.

**Comment by Mattis6666** [comment]
Hmm.... I'm not being rude, I'm just stating facts.

**Comment by incIined** [comment]
> Not sure why that person recommended to post it here, as this place is solely for VancedManager related issues.
> 
> Join one of our communites for help investigating this, but I highly doubt that this is caused by any Vanced app.

Because the way they stated the problem, I was under the impression that this issue only happened when installing MicroG from Vanced Manager. They stated it doesn’t happen when installing it from a mirror.

**Comment by inconsequentialCat** [comment]
That's exactly right.

Maybe I wasn't as clear as I could have been. But literally as soon as I installed Vanced **from the vanced manager app** (with the older version of MicroG still installed) the phone started powercycling.

So I uninstalled the old version of MicroG > then installed the new one and it was perfectly fine.

BUT, then this morning it started powercycling again. So I went to the **Vanced Manager App** and noticed there's a newer version of MicroG (apparently there was update over night/early morning?) 

So again I uninstalled the old version of MicroG > then installed the new one and it was perfectly fine again.

Conclusion: Not exaggerating at all, literally within 60 seconds of me having Vanced with outdated micro G the phone started powercycling again.

And then it happened again, only to be resolved by installing the lastest MicroG.

I'm not the most tech savvy person, but without a doubt: Not having the latest version of MicroG is 100% the cause of the issue - clarified by the fact that having the latest version immediately fixed the issue.

Honestly was just trying to help. And I'm not trying to stir the pot - just further clarifying the best I can.

@Mattis6666 
@incIined

**Comment by incIined** [comment]
> That's exactly right.
> 
> Maybe I wasn't as clear as I could have been. But literally within 60 seconds of installing Vanced **from the vanced manager app** (with the older version of MicroG still installed) the phone started powercycling.
> 
> So I uninstalled the old version of MicroG > then installed the new one and it was perfectly fine.
> 
> BUT, then this morning it started powercycling again. So I went to the **Vanced Manager App** and noticed there's a newer version of MicroG (apparently there was update over night/early morning?)
> 
> So again I uninstalled the old version of MicroG > then installed the new one and it was perfectly fine again.
> 
> Conclusion: I'm not the most tech savvy person, but without a doubt: Not having the latest version of MicroG is 100% the cause of the issue - clarified by the fact that downloading the latest version of MicroG **from the vanced manager** immediately fixed the issue.
> 
> Honestly was just trying to help. And I'm not trying to stir the pot - just further clarifying the best I can.
> 
> @Mattis6666
> @incIined
> 
> Edit: for clairty

Here's a guide to grab a logcat, in case you still need it. 
https://www.xda-developers.com/guide-sending-a-logcat-to-help-debug-your-favorite-app/

But grabbing one when the device crashes should give more insight to the issue, and help the devs sees if it's Manager issue at all.
