### ISSUE TITLE
Vanced Manager v1.1.0 Big Sur automatically exit after opening

### ISSUE THREAD

**Issue by free4537** [YTVanced/VancedManager#99]
**Please only report your issue here, if all points below are true**
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications: HUAWEI P30
- Brand: HUAWEI
- Operating System: EMUI 10.1.0.160
- Android Version: 10
- Vanced Manager Version: v1.1.0 Big Sur

**Please describe the problem you are having in as much detail as possible: After starting the application, the window will flash and exit automatically.

**Steps to reproduce: Every time the application is started, it will reappear

**Further details: The v1.0 version is available

**Comment by X1nto** [comment]
Send a logcat
